### ISSUE TITLE
JedisConnectionException on Transaction.exec() but commands still being executed

### ISSUE THREAD

**Issue by rushabhnagda11** [xetorthio/jedis#1006]
I'm creating a transaction object and adding a few commands to it. There are around 5 hmset commands being added, with the map size being at 500k mappings per hmset.

I'm also resetting the timeout using

 jedis.getClient().setTimeout(500000);

When I execute the scripts, I'm seeing very peculiar behavior, all the commands added to the transaction object get executed properly and the data is also present in the cache.

However it also throws a timeout exception exception

redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out

Here's the stack trace of the exception I'm seeing 

redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
    at redis.clients.jedis.Protocol.process(Protocol.java:144) ~[jedis-2.5.1.jar:na]
    at redis.clients.jedis.Protocol.read(Protocol.java:200) ~[jedis-2.5.1.jar:na]
    at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:285) ~[jedis-2.5.1.jar:na]
    at redis.clients.jedis.Connection.getAll(Connection.java:255) ~[jedis-2.5.1.jar:na]
    at redis.clients.jedis.Transaction.exec(Transaction.java:36) ~[jedis-2.5.1.jar:na]

There is no timeout on redis side. get config timeout returns "0".

Could you let me know why this is happening?

**Comment by HeartSaVioR** [comment]
Redis side timeout is for dropping idle connection, so it doesn't matter for you.
Jedis stores commands count which Jedis doesn't read response from Redis yet.
It's just for pipeline, and transaction is actually with pipelined.

We have observed some case that commands count is not accuracy, which makes getAll() tries to read more responses than Redis actually responded, finally leading timeout.

Most cases of these are not discarding invalid Jedis instance, which threw JedisConnectionException, so you may want to check it.
There's unknown reason about commands count inaccuracy, so we decided to change count variable to actual queue length, but it's planned to next major release, 3.0.0.
https://github.com/xetorthio/jedis/pull/511

Hope this helps.

One more, sharing your codes help us finding actual issue. Thanks!

**Comment by arvindnr** [comment]
Thank You HeartSaVior.

I was able to resolve it. pubsub was unsubscribed in one thread and released the jedis on different thread causing a deadlock waiting for response from redis. This happened 2/10 times. In those 2 times, the timeout became 0 waiting infinitely. As you mentioned, in 3.0.0 we might have a resolution as per your explanation.

Thanks
Arvind

**Comment by rushabhnagda11** [comment]
Here's the code.

```
        JedisPool jedisPool = RedisJedisPool.getPool(hostName, port);
        try {
            jedis = jedisPool.getResource();
            //setting this to a high enough number, so that timeouts dont happen on large hashmaps
            jedis.getClient().setTimeout(50000);
            int count = 0;
            List<Object> result = null;
            Boolean cacheTimeStampLess = false;
            do {
                String cacheTimeStamp = jedis.get("{" + advId + "}_ts");
                /* If no element in cache or we are adding newer value update data */
                if (cacheTimeStamp == null || Integer.parseInt(cacheTimeStamp) < timeStamp ) {
                    jedis.watch(advId, "{" + advId + "}" + "_ts");
                    Transaction t = jedis.multi();
                    t.del(advId);
                    t.hmset(hashToBidValue)
                    t.set("{" + advId + "}" + "_ts", timeStamp.toString());                    
                    /* t.exec will return null incase of failed check */
                    result = t.exec();
                    cacheTimeStampLess = true;
                }
                count++;
            } while (result == null && count <= 3 && cacheTimeStampLess);
        } catch (JedisConnectionException e) {
            if (jedis != null) {
                jedisPool.returnBrokenResource(jedis);
                jedis = null;
            }
            logger.error("Exception in update data using Jedis Pool in LRECache: {}", e);
            processSuccessful = false;
        } finally {
            if (jedis != null) {
                jedisPool.returnResource(jedis);
                jedis.getClient().setTimeout(Protocol.DEFAULT_TIMEOUT);
            }
        }
```

**Comment by Animaleante** [comment]
@arvindnr I seem to be having the same problem, but how do I unsubscribe and have a clean exit, if the subscriber thread is blocking?

Here is my code:
```java
public void init(){
    JedisPoolConfig poolConfig = new JedisPoolConfig();
    JedisPool jedisPool = new JedisPool(poolConfig, redisPath, 6379, 0);
    setupSubscriber();
}

public void setupSubscriber()
{
	try{
		subscriberJedis = jedisPool.getResource();
		subscriber = new JedisSubscriber();
		
		new Thread(new Runnable(){
			@Override
			public void run() {
				try{
					subscriberJedis.subscribe(subscriber, CHANNEL_NAME);
				}
				catch(Exception e){
					log("Subscribe failed. " + e.getMessage());
				}
			}
		}).start();
	}
	catch(Exception e)
	{
		e.printStackTrace();
	}
}
	
public void publishMessage(final String channel, final String message)
{
	new Thread(new Runnable(){
		@Override
		public void run() {
			try{
				Jedis jedis = jedisPool.getResource();
				jedis.publish(channel, message);
				jedis.close();
			}
			catch(JedisConnectionException e){
				e.printStackTrace();
			}
			catch (Exception e) {
				log("Publish failed. " + e.getMessage());
			}
		}
	}).start();
}

public void close() 
{
	try{
		subscriber.unsubscribe();
		subscriberJedis.close();
		jedisPool.destroy();
	}
	catch(JedisConnectionException e)
	{
		e.printStackTrace();
	}
	catch(Exception e)
	{
		e.printStackTrace();
	}
}
```

My application freezes after calling `subscriberJedis.close();`
I am using Jedis 2.7.2.
And I never used Maven before, so when I built the jar file, I had to skip the tests cause they always failed.
