### ISSUE TITLE
jedis.clusterNodes() return contain "127.0.0.1" host ,lead to connect faild

### ISSUE THREAD

**Issue by xsjie** [xetorthio/jedis#1016]
JedisClusterInfoCache.java have a method discoverClusterNodesAndSlots() have bug,
in this method have line code "String localNodes = jedis.clusterNodes();" if localNodes contain "127.0.0.1" ip ,lead to slots map key is slot,but value is "127.0.0.1" ,so lead jedis.connect() to 127.0.0.1,so it's faild ，
my cluster nodes remote ip 132.121.88.81 
eg: I System.out.println(localNodes) ,the result contain 127.0.0.1 and 132.121.88.81

a21ae04a39c1058a5378994e1b7e12f55a3af595 127.0.0.1:6373 master - 0 1433313150355 3 connected 10923-16383
783f3ba13278ba9930eea76d6d4af4e2540f40c8 127.0.0.1:6374 slave 273f10299f9db0f9f7adc9b25374d3dbddb16195 0 1433313147355 8 connected
97a8f2db536aa55b1838abbf7a940489decf4823 127.0.0.1:6375 slave 02b1450ce1d0375277861d5fff9e703920fdacfd 0 1433313153355 5 connected
02b1450ce1d0375277861d5fff9e703920fdacfd 127.0.0.1:6372 master - 0 1433313152355 2 connected 5461-10922
07a2f37d488e90fe06498711607c2c73f0bc6136 127.0.0.1:6376 myself,slave a21ae04a39c1058a5378994e1b7e12f55a3af595 0 0 6 connected
273f10299f9db0f9f7adc9b25374d3dbddb16195 132.121.88.81:6371 master - 0 1433313154355 8 connected 0-5460

I think should fixed ClusterNodeInformationParser.java method getHostAndPortFromNodeLine()
    return new HostAndPort(arrayHostAndPort[0].isEmpty()||arrayHostAndPort[0].equals("127.0.0.1")||arrayHostAndPort[0].equals("::1") ? current.getHost() : arrayHostAndPort[0],

**Comment by allanwax** [comment]
A related issue to this has come up before.  Since cluster information is passed around, specifying localhost within your confiuration will pass around localhost to all the instances in the cluster which is incorrect as localhost is relative to the machine its on.  Try setting the address of the machine to the actual address of the machine (i.e.`hostname -I` value) and see if the problem goes away.

**Comment by xsjie** [comment]
./redis-trib.rb create --replicas 1 132.121.88.81:6371 132.121.88.81:6372 132.121.88.81:6373 132.121.88.81:6374 132.121.88.81:6375 132.121.88.81:6376 , set actual address 132.121.88.81 instead 127.0.0.1 ，it‘s work !  ,so I think jedis-master should fixed ClusterNodeInformationParser.java method getHostAndPortFromNodeLine()
return new HostAndPort(arrayHostAndPort[0].isEmpty()||arrayHostAndPort[0].equals("127.0.0.1")||arrayHostAndPort[0].equals("::1") ? current.getHost() : arrayHostAndPort[0],

**Comment by allanwax** [comment]
SEE https://github.com/xetorthio/jedis/issues/1023

**Comment by yinrong** [comment]
+1 encounter the problem. give me a headache
