### ISSUE TITLE
blpop/brpop(String) should not be deprecated in V3

### ISSUE THREAD

**Issue by allanwax** [xetorthio/jedis#1021]
blpop/brpop with a single key has been marked as `Deprecated`.  While the multiple key versions are an issue, the single key version is not incompatible with JedisCluster.  With a single key, we can always find the master to use for the request.  I think these method should be un-marked as deprecated.

If the key moves while blocked it should be relatively simple to do something sane at the time.

**Comment by marcosnils** [comment]
@allanwax the single key has been deprecated in favor of the varargs version. You can still call blpop/brpop with a single key by using varargs. I don't quite understand your thoughts about this.

**Comment by allanwax** [comment]
In the single key version, as it relates to jedis *cluster*, getting the slot for the key will always resolve to a single slot on a single master.  Because it is enforced as a single key, not varags, there is a guarantee of a single key argument.  In the varargs version, there can be multiple keys and thus the issue of trying to do blpop in multiple masters and the coordination thereof.  I.e. blpop(k1,k2,k3) and k2 returns but k1,k3 are still blocked -- how do we cancel the blocked blpop operations; timeouts need to be coordinated somehow also, different clock speeds, network delays, etc.

So both versions may be valuable unless we are going to implement jedis handling multiple masters at the same time.  Or accept a blpop with a single varags value and reject (perhaps for now) multiple keys.

**Comment by marcosnils** [comment]
@allanwax brpop and blpop were only deprecated in `Jedis` class, not `JedisCluster`. 

If you check in 3.0 `JedisCluster` has also the single key operation you're asking about.

https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/JedisCluster.java#L1173-L1191

Is there something I'm missing?

**Comment by marcosnils** [comment]
@allanwax another comment is that in v3.0 `JedisCluster` doesn't dispatch commands which have keys assigned to one more than one slot (which can only be served by one master).

You can check that here: https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/JedisClusterCommand.java#L40-L49

So even if you use varargs with multiple keys the scenario you're describing is not possible.

**Comment by allanwax** [comment]
No, I'm just missing my head.  Remind me not to make public comments when I'm sick.

I was looking at the wrong file.  You are correct.

**Comment by marcosnils** [comment]
:+1: shit happens. Don't worry :)

**Comment by xetorthio** [comment]
Hehe this kind of comments are sometimes useful to make sure the design is
coherent :)
Anyway coding while being sick can lead to crazy things :)
