### ISSUE TITLE
redis.clients.jedis.exceptions.JedisConnectionException: no reachable node in cluster

### ISSUE THREAD

**Issue by arulanandsp** [xetorthio/jedis#1024]
Hi,

I created a ElasticCache Redis Cluster with 1 Master node. When I tried to connect I am getting 
redis.clients.jedis.exceptions.JedisConnectionException: no reachable node in cluster

Here is the code

Set<HostAndPort> jedisClusterNodes = new HashSet<HostAndPort>();
//Jedis Cluster will attempt to discover cluster nodes automatically
jedisClusterNodes.add(new HostAndPort("xxxxx.0001.use1.cache.amazonaws.com", 6379));
JedisCluster jc = new JedisCluster(jedisClusterNodes);
jc.set("foo", "bar");
String value = jc.get("foo");

Please let me know if I am missing something

**Comment by marcosnils** [comment]
@arulanandsp aws ElasticCache has it's own concept of a "Redis cluster" which is not the same as the original proposal of redis (http://redis.io/topics/cluster-tutorial).

You can't use `JedisCluster` with ElasticCache because ElasticCache doesn't support native "Redis clustering" yet.
