### ISSUE TITLE
Unexpected end of stream.

### ISSUE THREAD

**Issue by Tunaiyi** [xetorthio/jedis#1029]
package com;

import org.apache.commons.pool2.impl.GenericObjectPoolConfig;

import redis.clients.jedis.Jedis;
import redis.clients.jedis.JedisPool;
import redis.clients.jedis.JedisPoolConfig;

public class TestJedis {

	public static void main(String[] args) {
		GenericObjectPoolConfig config = new JedisPoolConfig();
		JedisPool pool = new JedisPool(config, "127.0.0.1");
		try (Jedis jedis = pool.getResource()) {
			jedis.set("test", "aaa");
			System.out.println(jedis.get("test"));
		}
		pool.close();
	}
}

i get exception :
Exception in thread "main" redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:198)
	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
	at redis.clients.jedis.Protocol.process(Protocol.java:132)
	at redis.clients.jedis.Protocol.read(Protocol.java:196)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:288)
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:187)
	at redis.clients.jedis.Jedis.set(Jedis.java:66)
	at com.TestJedis.main(TestJedis.java:15)

redis version : 3.0.2
jedis version : 2.7.2

jedis.conf :
# Redis configuration file example

daemonize yes
pidfile /var/run/redis.pid
port 6379
tcp-backlog 511
timeout 0
tcp-keepalive 60

loglevel notice
logfile /Applications/service/redis-3.0.2/log/redis_6379.log

databases 16

################################ SNAPSHOTTING  ################################

save 900 1
save 300 10
save 60 10000

stop-writes-on-bgsave-error yes

rdbcompression yes
rdbchecksum yes

dbfilename redis_6379.rdb

dir /Applications/service/redis-3.0.2/db
################################# REPLICATION #################################

slave-serve-stale-data yes

slave-read-only yes

repl-diskless-sync no

repl-diskless-sync-delay 5

repl-disable-tcp-nodelay no

slave-priority 100

################################### LIMITS ####################################

maxmemory 128mb

maxmemory-policy volatile-lru

############################## APPEND ONLY MODE ###############################

appendonly no

appendfilename "appendonly.aof"
appendfsync everysec

no-appendfsync-on-rewrite no

auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
aof-load-truncated yes

################################ LUA SCRIPTING  ###############################

lua-time-limit 5000

################################ REDIS CLUSTER  ###############################

slowlog-log-slower-than 10000
slowlog-max-len 128

################################ LATENCY MONITOR ##############################

latency-monitor-threshold 0

############################# EVENT NOTIFICATION ##############################

notify-keyspace-events ""

############################### ADVANCED CONFIG ###############################

hash-max-ziplist-entries 512
hash-max-ziplist-value 64

list-max-ziplist-entries 512
list-max-ziplist-value 64

set-max-intset-entries 512

zset-max-ziplist-entries 128
zset-max-ziplist-value 64

hll-sparse-max-bytes 3000

activerehashing yes

client-output-buffer-limit normal 0 0 0
client-output-buffer-limit slave 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60

hz 10

aof-rewrite-incremental-fsync yes

**Comment by codehehe** [comment]
i have the same exception

**Comment by amitguptagwl** [comment]
I was also getting the same issue when I was using embedded redis. This [thread](https://github.com/kstyrc/embedded-redis/issues/31) has useful information.

**Comment by PunKeel** [comment]
Same here, using `JedisSentinelPool` and Jedis 2.8.1
```
19:47:24 [SEVERE] redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
19:47:24 [SEVERE] 	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:198)
19:47:24 [SEVERE] 	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
19:47:24 [SEVERE] 	at redis.clients.jedis.Protocol.process(Protocol.java:141)
19:47:24 [SEVERE] 	at redis.clients.jedis.Protocol.read(Protocol.java:205)
19:47:24 [SEVERE] 	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:297)
19:47:24 [SEVERE] 	at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:233)
19:47:24 [SEVERE] 	at redis.clients.jedis.Jedis.hgetAll(Jedis.java:796)
19:47:24 [SEVERE] 	at myapp
```

**Comment by PunKeel** [comment]
^- Fixed, `timeout` (redis config) was improperly setup.

**Comment by AaronFeng2014** [comment]
why? and i also have this problem, and I dont know why

**Comment by marcosnils** [comment]
@AaronFeng2014 do you have an example to reproduce your issue?

**Comment by marcosnils** [comment]
@AaronFeng2014 this issue is way too old, please open a new one specifying as much info as possible to reproduce the issue.

**Comment by AaronFeng2014** [comment]
@marcosnils maybe, ihave too many data in redis?

**Comment by justein** [comment]
I have meet the same problem,can anyone help?

**Comment by amitguptagwl** [comment]
Try this

@Bean
        public JedisPool jedisPool() {
            JedisPoolConfig poolConfig = new JedisPoolConfig();
            poolConfig.setMaxTotal(threadPoolSize);
            poolConfig.setTestOnBorrow(true);
            poolConfig.setTestOnReturn(true);
            return new JedisPool(poolConfig, host, port, timeout);
        }

**Comment by songcan** [comment]
I have meet the same problem ,who can help me?

**Comment by failBoyL** [comment]
Is this problem due to the incorrect settings for timeout?

**Comment by jondoe1337** [comment]
Iam also still facing this problem while doing:
```
try (Jedis jedis = jedisPool.getResource())
{
    do
        {
            ScanResult<Entry<String, String>> scan = jedis.hscan(regionKey, cursor, new ScanParams().count(50000));
```

My redis-server timeout is set to **120** and the TCP keepalive is set to **60** (However my linux kernel settings for TCP socket opts are different).

The data I receive is about 450K Hash values - thats why I set the scan params is set to 50K count.

I cannot really reproduce this issue. But it is happening from time to time from different clients (which are not having the exception at the same time).

**Comment by jondoe1337** [comment]
The problem might be that the jedisPool or in general the connection is too long open and idle. My solution was to open a new connection each time the code is called (which was in my case only once every ten minutes).

**Comment by jagadeesh583** [comment]
Hi  i am also facing the same issue. 
here is the exception. 
[Start of Exception 
SEVERE: Lost connection to Sentinel at **sentinal server node: portno**. Sleeping 5000ms and retrying.
redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:199)
	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
	at redis.clients.jedis.Protocol.process(Protocol.java:151)
	at redis.clients.jedis.Protocol.read(Protocol.java:215)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
	at redis.clients.jedis.Connection.getRawObjectMultiBulkReply(Connection.java:285)
	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:121)
	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:115)
	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2680)
	at redis.clients.jedis.JedisSentinelPool$MasterListener.run(JedisSentinelPool.java:291)
End of exception ]

We have there server nodes one is master , slave and another one is sentinel server node. 

i am trying with following code 

      `@Value("${redis.sentinel.master}")
	private String master;

	@Value("${redis.sentinel.host}")
	private String host;
	
	@Value("${redis.sentinel.port}")
	private String port;
	
	@Value("${redis.sentinel.password}")
	private String password;

	@Value("${redis.sentinel.poolSize}")
	private String poolSize;

	@Bean
	public JedisConnectionFactory jedisConnectionFactory() {
		JedisConnectionFactory jedisConnectionFactory = new JedisConnectionFactory(this.redisSentinelConfiguration(),
				this.jedisPoolConfig());
		jedisConnectionFactory.setPassword(password);
		return jedisConnectionFactory;
	}

	@Bean
	public RedisSentinelConfiguration redisSentinelConfiguration() {
		Set<String> hostAndPorts = new HashSet<String>();
		hostAndPorts.add(host + ":" + port);
		RedisSentinelConfiguration redisSentinelConfiguration = new RedisSentinelConfiguration(master, hostAndPorts);
		return redisSentinelConfiguration;
	}

	**@Bean
	public JedisPoolConfig jedisPoolConfig() {
		JedisPoolConfig jedisPoolConfig = new JedisPoolConfig();
		jedisPoolConfig.setMaxTotal(Integer.parseInt(poolSize));
		jedisPoolConfig.setMaxIdle(15);
		jedisPoolConfig.setMinIdle(1);
		jedisPoolConfig.setMaxWaitMillis(10000);
		jedisPoolConfig.setTestOnBorrow(true);
		return jedisPoolConfig;
	}**`

**Comment by bozdag** [comment]
You can use `RedisStandaloneConfiguration` to configure JedisConnectionFactory with Spring Data Redis 2.x.

**Comment by Golden-Man-Vn** [comment]
the cause is that server setting up timeout nonzero, it means after one period connection is disposed or closed. So client takes the connection from pool, but after that time it is invalid!

Solution is:
Set timeout on server to 0
or
Do not keep pool on client -> GenericObjectPoolConfig.setMaxIdle(0)
So each time to connect server, client take a new connection.
