### ISSUE TITLE
Why 2.7 JedisPoolConfig not Compatible with 2.1 JedisPoolConfig

### ISSUE THREAD

**Issue by Paul1Q84** [xetorthio/jedis#1031]
2.7 use commons-pool2 and config like
		maxTotal="300"
		maxIdle="300"
		minIdle="200"
		maxWaitMillis="5000"
		testOnBorrow="false"
		testOnReturn="false"
		testWhileIdle="true"
in commons-pool1,maxTotal is maxActive,maxWaitMillis is maxWait;

I think it's very easy to do compatible . like
 public class JedisPoolConfig extends GenericObjectPoolConfig {
	private int maxActive;
	private long maxWait;

	public JedisPoolConfig() {
		// defaults to make your life with connection pool easier :)
		setTestWhileIdle(true);
		setMinEvictableIdleTimeMillis(60000);
		setTimeBetweenEvictionRunsMillis(30000);
		setNumTestsPerEvictionRun(-1);

	}

	public int getMaxActive() {
		return maxActive;
	}

	public void setMaxActive(int maxActive) {
		this.maxActive = maxActive;
		this.setMaxTotal(maxActive);
	}

	public long getMaxWait() {
		return maxWait;
	}

	public void setMaxWait(long maxWait) {
		this.maxWait = maxWait;
		setMaxWaitMillis(maxWait);
	}
}

**Comment by HeartSaVioR** [comment]
@Paul1Q84 
We changed JediPoolConfig's method signatures to make JedisPoolConfig compatible with commons-pool 2.
Jedis 2.1 was released at May 2012, over 3 years ago.
I hope we can forget about backward compatibilities with too old releases.
