### ISSUE TITLE
hset silently skipping inserts

### ISSUE THREAD

**Issue by cdelgadob** [xetorthio/jedis#1032]
Hi,

I'm writing a simple library to insert, retrieve and remove serialized java objects.

In my tests, I have found that not all values are beign inserted, and still the hset method returns 1.

Any ideas how to find out what's hapening?

Carlos

**Comment by marcosnils** [comment]
@cdelgadob can you please provide a snippet that reproduces the problem?. It's also useful to know the Jedis - Redis version you're using.

**Comment by marcosnils** [comment]
This channel is to report identified issues in the code / design mainly. Please move this question to the mailing list (http://groups.google.com/group/jedis_redis) so other users can also help.

**Comment by cdelgadob** [comment]
Hey, it was my fault at the end, sorry for the hussle and thanks for this great library!
