### ISSUE TITLE
Getting Invalid Bulk Length Exception on Using BinaryJedis

### ISSUE THREAD

**Issue by sparkpool** [xetorthio/jedis#1034]
Hi,

I am getting below Exception on using BinaryJedis hmget Function and i am getting around 26 KB serialized data from Redis.

I have already increased buffer size on redis side also but getting same exception.

Exception occured for jedis 
redis.clients.jedis.exceptions.JedisDataException: ERR Protocol error: invalid bulk length
        at redis.clients.jedis.Protocol.processError(Protocol.java:113)
        at redis.clients.jedis.Protocol.process(Protocol.java:138)
        at redis.clients.jedis.Protocol.read(Protocol.java:192)
        at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:282)
        at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:218)
        at redis.clients.jedis.BinaryJedis.hmget(BinaryJedis.java:740)

Any Help would be highly appreciated.

**Comment by sparkpool** [comment]
I am not getting it always, i am getting it on some cases. I am not sure if data comes in large quantity then only this error comes.

**Comment by marcosnils** [comment]
@sparkpool can you please provide a snippet of what / how you're doing?. It will also help to know the Jedis / Redis version you're using.

**Comment by sparkpool** [comment]
I am using jedis 2.6.2 and redis 2.8.0. I also have checked tcp buffer size on client side and it's pretty large. Below is the code:

public List<byte[]> getBinaryValueByKeyFromMap(byte[] key, byte[] field){
		BinaryJedis binaryJedis = null;
		try{
//Getting jedis client from the pool
		  binaryJedis = getJedis();
		  return binaryJedis.hmget(key, field);
		}catch(Exception e){
			logger.error("Exception occured for jedis " + e.getMessage());
		}finally{
			if(binaryJedis!=null){
				binaryJedis.close();
			}
		}
		return null;
	}

**Comment by HeartSaVioR** [comment]
@sparkpool Could you post Redis log if you find relevant line? It contains "Protocol error from client"

**Comment by sparkpool** [comment]
Well i have checked all redis log and i couldn't find something related to "Protocol error from client" or any kind of error.

I was going through the code where this exception was coming actually inside process method it is checking first byte of input stream and which is coming as negative. So, in which case this Minus sign comes up?

**Comment by marcosnils** [comment]
@sparkpool can you change your code to print the key and field when the exception occurs?. I'd like to see what's being sent in the `hmget` method.

**Comment by HeartSaVioR** [comment]
@sparkpool 
It is not a Jedis bug. Redis has limitation of various bulk length, and it is not documented well.

Multibulk length limitation: https://github.com/antirez/redis/blob/unstable/src/networking.c#L1023-1027

There're another length limitation - line buffer and data - which I can't find from source code but I heard from colleague Redis contributor.

So I was asking that Redis has relevant logs which may help you, and us.

**Comment by sparkpool** [comment]
@HeartSaVioR Thanks for your response. 

I think there is some problem with redis. I will see if i can increase some buffer size of RESP protocol from OS side and i have already set buffer size to 0 in redis configuration file.

I will keep you posted if i find something.

**Comment by marcosnils** [comment]
@sparkpool I'll close the issue as we can't do anything from Jedis side. Let us know if you find something that requires to re-open it.

**Comment by sparkpool** [comment]
Okay just one question as i haven't seen the source code for this yet. Are you handling NULL BULK String "$-1\r\n"

**Comment by marcosnils** [comment]
Yes we are,

Jedis will return a Java `null` value for NULL BULK responses.

**Comment by huanghuaquan** [comment]
Did you solve this problem?
