### ISSUE TITLE
Maybe add an interface for "set key value PX xxxx" is a good idea

### ISSUE THREAD

**Issue by valleylord** [xetorthio/jedis#1046]
I found that Jedis does not provide an interface for the redis command "set key value PX xxxx" or "set key value EX xxxx". Maybe add this interface is a good idea. I really need it. Thank you. ^_^

I found that all redis commands are provided in BinaryClient class. Maybe add following code in this class can do.

```
    public void set(byte[] key, byte[] value, byte[] expx, long time) {
        this.sendCommand(Command.SET, new byte[][]{key, value, expx, Protocol.toByteArray(time)});
    }

```

And ofcourse, add wrapper methods in class Client, Jedis, etc. I'm not sure this modification can do.

**Comment by HeartSaVioR** [comment]
@valleylord 
Hi!
We're having related PR, https://github.com/xetorthio/jedis/pull/878, which is great I think and it is planned to be merged at 3.0.0.
Since combinations of "set" parameters are too many, I don't want to add functionality with overloading.

**Comment by valleylord** [comment]
Aha, that's good. BTW, does 3.0.0 has planned due date?

**Comment by HeartSaVioR** [comment]
@valleylord We don't have due date now, but we will try to decide 3.0.0's features and due date.
