### ISSUE TITLE
2.7.x not find BinaryJedisCluster ?

### ISSUE THREAD

**Issue by xiaolongyuan** [xetorthio/jedis#1048]

**Comment by marcosnils** [comment]
This is correct, BinaryJedisCluster was introduced in master branch. We're planning to release 2.8 soon which will have a backported version of master branch with some features like BinaryJedisCluster. 

Please ask these types of questions in the mailing list as we're trying to use github for code - design issues mainly. 

Thx.

**Comment by xiaolongyuan** [comment]
thank you very much.
