### ISSUE TITLE
BinaryJedisCluster why not provide JedisClusterCommand interface for follow custom orders?

### ISSUE THREAD

**Issue by xiaolongyuan** [xetorthio/jedis#1050]
public class BinaryJedisCluster implements BinaryJedisClusterCommands,
    MultiKeyBinaryJedisClusterCommands, JedisClusterBinaryScriptingCommands, Closeable {

  public static final short HASHSLOTS = 16384;
  protected static final int DEFAULT_TIMEOUT = 2000;
  protected static final int DEFAULT_MAX_REDIRECTIONS = 5;

  protected int maxRedirections;

  protected JedisClusterConnectionHandler connectionHandler;

External no access.

**Comment by sazzad16** [comment]
@xiaolongyuan It's not easy to address without knowing some use-cases.
