### ISSUE TITLE
How do you differentiate between an empty multi, and a multi which was blocked due to a watch?

### ISSUE THREAD

**Issue by glade-at-gigwell** [xetorthio/jedis#1051]
Jedis 2.7.2
Server 2.8.19

How do you differentiate between an empty multi, and a multi which was blocked due to a watch?  The results from the transaction.exec() method are both null.  Is there something that can be surfaced to the caller to differentiate the two conditions? 

When using the redis-cli the two use cases appear to have a different response. 

```
127.0.0.1:6379> watch foo
OK
127.0.0.1:6379> multi
OK
127.0.0.1:6379> set foo transaction1
QUEUED
```

connection 2

```
127.0.0.1:6379> set foo nottransaction
OK
```

exec and check result on connection 1

```
127.0.0.1:6379> exec
(nil)
127.0.0.1:6379> get foo
"nottransaction"
```

However, when we execute an empty transaction, the response is slightly different: 

```
127.0.0.1:6379> watch foo
OK
127.0.0.1:6379> multi
OK
127.0.0.1:6379> exec
(empty list or set)
```

Hopefully something obvious I'm missing.

Thanks!

**Comment by PunKeel** [comment]
:+1: wondering in order to implement optimistic locking :-)

**Comment by sazzad16** [comment]
@glade-at-gigwell Tried your flow with Jedis 2.7.2 and Redis 3.2.x/4.0.x. It's giving `null` as expected. However, Jedis 2.7 is not maintained anymore. You may try 2.8.0/2.8.1.
