### ISSUE TITLE
Jedis Cluster Nodecache info update

### ISSUE THREAD

**Issue by zts1993** [xetorthio/jedis#1056]
In Jedis Cluster 

when we got JedisMovedDataException , we can call renewSlotCache()
and renewSlotCache() calls discoverClusterSlots() 

These process rebuilds cluster's slot cache but didn't update Cluster Nodes ?
What if we add a new cluster matser nodes ?
It seems that new nodes will not be added?

**Comment by HeartSaVioR** [comment]
@zts1993 
If slot is assigned from new node, it will be added to node cache.

Btw, AFAIK, Redis Cluster doesn't tell client about change of cluster nodes.
Redirection is only based on slot, so Jedis can't catch up the information of current nodes of Redis cluster.
It blocks us using slave nodes safely cause failure of slave node will not be noticed.
Safer way to use Redis Cluster is just using master node with respecting redirection. In this case we don't need to know fresh information of nodes of cluster.
