### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by ApfelUser** [xetorthio/jedis#1058]
Hello,

I have been using Jedis in my java application for the last week. I have set the maximum memory amount with **-xmx** at **6GB** which should be more than enough. The only thing I am currently doing with it is using some **Pub/Sub** channels. The Redis server itself is running on another machine than the java app. Everything works perfectly fine except for my whole root server going "offline" after about **~40-60** Minutes. The SSH connection "crashes" with a:

```sh
-bash: fork: Cannot allocate memory
```
I can't do anything after that. The server is still running but nothing works anymore.

Some details about the servers:

**Server 1 / Java App Server:**

  * Debian 7
  * 32 GB Memory
  * Intel Xeon E3 1245v2
  * 360 GB SSD ( I think that is not important, but I'll write it down anyways. You never know :smiley: )
  * Running Java 8 and the Java App

**Server 2 / Database Server:**

  * Debian 8
  * 32 GB Memory
  * Intel Xeon E3 1245v2
  * 360 GB SSD ( I think that is not important, but I'll write it down anyways. You never know :smiley: )
  * Running Redis, MongoDB and PostgreSQL

I am 100% sure that this has to do with Jedis, because the server is running perfectly for days when I remove Jedis from the maven dependency + code and only use MongoDB. The server always crashes   like a clock after **~40-60** minutes when I "re-enable" Jedis. I've checked **/var/log/auth.log** etc. it always comes down to the fact that there is not enough memory for any app on the root due to the java app using too much, which shouldn't be possible due to the **-xmx**-restriction.

Here is the Jedis part of our code:

```java
public class Database implements Listener {
 
    //-> Jedis Variables
    @Getter
    private static JedisPool pool;
    @Getter
    private static PubSubListener listener;
 
    private static void connectToRedis() {
        final String host = CONFIG.getProperty("redis_host");
        final String password = CONFIG.getProperty("redis_password");
 
        System.out.println("[Database] Connecting to Redis database..");
 
        FutureTask<JedisPool> task = new FutureTask<>(() -> {
 
            ClassLoader previous = Thread.currentThread().getContextClassLoader();
            Thread.currentThread().setContextClassLoader(Proxy.class.getClassLoader());
 
            JedisPoolConfig config = new JedisPoolConfig();
            config.setMaxTotal(8);
            config.setJmxEnabled(false);
            JedisPool pool = new JedisPool(config, host, 6379, 0, password);
 
            Thread.currentThread().setContextClassLoader(previous);
            return pool;
        });
 
        delegate(task);
 
        try {
            pool = task.get();
        } catch (InterruptedException | ExecutionException ex) {
            throw new RuntimeException("[Database] Unable to create redis pool", ex);
        }
 
        try (Jedis jedis = pool.getResource()) {
            jedis.ping();
 
            listener = new PubSubListener();
            delegate(listener);
 
            System.out.println("[Database] Done! Successfully connected to Redis database!");
        } catch (JedisConnectionException ex) {
            pool.destroy();
            pool = null;
            throw new RuntimeException("[Database] Failed to connect to Redis database!", ex);
        }
    }
    
    private static void disconnectFromRedis() {
        try {
            if (pool != null) {
                listener.poison();
                pool.destroy();
            }
        } catch (Exception ignored) {}
    }
 
    private static final class PubSubListener implements Runnable {
 
        private JedisPubSubHandler handler;
 
        @Override
        public void run() {
            try (Jedis jedis = pool.getResource()) {
                handler = new JedisPubSubHandler();
                jedis.subscribe(handler, "data", "dss");
            } catch (JedisException | ClassCastException ex) {
                ex.printStackTrace();
            }
        }
 
        public void poison() {
            handler.unsubscribe();
        }
 
        public void subscribe(String... channel) {
            handler.subscribe(channel);
        }
 
        public void unsubscribe(String... channel) {
            handler.unsubscribe(channel);
        }
    }
 
    private static final class JedisPubSubHandler extends JedisPubSub {
 
        @Override
        public void onMessage(String channel, String message) {
 
            if (message.trim().length() != 0) delegate(() -> Butler.callEvent(new PubSubMessageEvent(channel, message)));
        }
    }
 
    public static void publish(String channel, String message) {
        try (Jedis jedis = pool.getResource()) {
 
            jedis.publish(channel, message);
        } catch (JedisException | ClassCastException ex) {
            ex.printStackTrace();
        }
    }
 
    public static void publish(String message) {
        try (Jedis jedis = pool.getResource()) {
 
            jedis.publish("data", message);
        } catch (JedisException | ClassCastException ex) {
            ex.printStackTrace();
        }
    }
}
```

Has anybody an idea what could be causing this?
Feel free to ask for more details on hardware etc. if you need it :smiley: 

Help would be very appreciated.

Cheers,

ApfelUser

**Comment by ApfelUser** [comment]
Has anybody an idea?

**Comment by marcosnils** [comment]
@ApfelUser apogolize for taking too long to respond. Can you please post this in the jedis mailing list https://groups.google.com/forum/#!forum/jedis_redis ?. Issue tracker is mostly for code/design and not too many users look here. Please address your issue to the ML

**Comment by ApfelUser** [comment]
@marcosnils No problem. I posted it in the forum. Didn't see the message that it needs to get approved the first time, so I posted it twice. I am sorry for that :smile:

**Comment by ApfelUser** [comment]
-> https://groups.google.com/forum/#!topic/jedis_redis/Rx25Qq4hSy8
