### ISSUE TITLE
Jedis 2.7.2 cluster performance is one-half of single instance

### ISSUE THREAD

**Issue by dudi123456** [xetorthio/jedis#1060]
Single:
 	Jedis jedis = new Jedis("10.1.228.198", 36861);
		jedis.auth("556725");
		int i = 0;
		long start = System.currentTimeMillis();
		while (i < 10000) {
			//jedis.set("" + i, "" + i);
			jedis.get("" + i);
			i++;
		}
		System.out
				.println("total time:" + (System.currentTimeMillis() - start));
		jedis.close();

		Set<HostAndPort> jedisClusterNode = new HashSet<HostAndPort>();
		jedisClusterNode.add(new HostAndPort("10.1.228.198", 36872));
		JedisCluster jc = new JedisCluster(jedisClusterNode, 30000);
		int i = 0;
		long start = System.currentTimeMillis();
		while (i < 10000) {
			jc.set("" + i, "" + i);
			jc.get("" + i);
			i++;
		}
		System.out
				.println("total time:" + (System.currentTimeMillis() - start));
		jc.close();

**Comment by marcosnils** [comment]
@dudi123456 in your single instance code the `set` is commented?
