### ISSUE TITLE
Too many redirection issue with redis cluster [ jedis version 2.7.2 ] [ redis 3.0.2]

### ISSUE THREAD

**Issue by gargde** [xetorthio/jedis#1062]
I have 3 + 3 node dev redis cluster and when ever I try to write the keys using jedis cluster I get the below error.  Is there any particular configuration required to avoid this error ?

Redis version : 3.0.2
Jedis : 2.7.2 

code snap shot :+1: 

public static void main(String[] args) {
		Set<HostAndPort> jedisClusterNodes = new HashSet<HostAndPort>();
		jedisClusterNodes.add(new HostAndPort(
				"ec2-54-80-210-178.compute-1.amazonaws.com", 6379));
		jedisClusterNodes.add(new HostAndPort(
				"ec2-54-198-160-111.compute-1.amazonaws.com", 6379));
		jedisClusterNodes.add(new HostAndPort(
				"ec2-107-22-61-96.compute-1.amazonaws.com", 6379));
		jedisClusterNodes.add(new HostAndPort(
				"ec2-54-81-36-12.compute-1.amazonaws.com", 6379));
		jedisClusterNodes.add(new HostAndPort(
				"ec2-54-80-48-155.compute-1.amazonaws.com", 6379));
		jedisClusterNodes.add(new HostAndPort(
				"ec2-23-20-191-174.compute-1.amazonaws.com", 6379));	
		JedisCluster jc = new JedisCluster(jedisClusterNodes);
		for (int i = 1; i < 1000; i++) {
			long start = System.currentTimeMillis();            
			String key = "test" + i;
			jc.set(key, "value");			
		       System.out.print("set " + i +"th value in " + (System.currentTimeMillis() - start) + " ms");
                      start = System.currentTimeMillis();
                      jc.get(key);
                      System.out.println(", get " + i +"th value in " + (System.currentTimeMillis() - start) + " ms");			
		}
		return;
	}

Exception : 

in thread "main" redis.clients.jedis.exceptions.JedisClusterMaxRedirectionsException: Too many Cluster redirections?
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:38)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:86)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:71)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:86)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:71)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:86)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:71)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:86)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:71)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:86)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:71)
	at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:32)
	at redis.clients.jedis.JedisCluster.set(JedisCluster.java:38)
	at com.test.rediscluster.App.main(App.java:33)

Master configuration :+1: 

ubuntu@ip-10-37-200-42:~/redis-3.0.2$ cat /data/redis/redis-master1-6379.conf 
dc6c2f48cac7ccc7ae670482f04f7643aea340f7 10.169.171.53:6379 slave 58a8daae197ebac76583e74d4d614074aa0ce04f 0 1437131017086 6 connected
67773902200b27b4f6aa5ab27792dcd6c1fca73a 10.37.200.42:6379 myself,master - 0 0 1 connected 0-5460
64a298d0859593d1e817b7e998f638586574cb5e 10.167.179.49:6379 slave 4ce9a970f85e92822da0abf6d8041967caafcf72 0 1437131018891 5 connected
26ce52add09a549a11ad27e60ed7a8d6a2c45b69 10.158.128.15:6379 slave 67773902200b27b4f6aa5ab27792dcd6c1fca73a 0 1437131018590 4 connected
58a8daae197ebac76583e74d4d614074aa0ce04f 10.95.175.25:6379 master - 0 1437131018590 3 connected 10923-16383
4ce9a970f85e92822da0abf6d8041967caafcf72 10.144.247.154:6379 master - 0 1437131018088 2 connected 5461-10922
vars currentEpoch 6 lastVoteEpoch 0

**Comment by marcosnils** [comment]
@gargde try using the ip addresses instead of the hostnames to initialize Jedis cluster and let me know if that works.

**Comment by gargde** [comment]
@marcosnils tried with ec2 ip address and able to connect but still facing the similar issue. 
I also noticed a crash in redis server as well. I created a but for them as well. 
https://github.com/antirez/redis/issues/2680

**Comment by antirez** [comment]
@gargde as advised in the original issue, you ran `DEBUG SEGFAULT` yourself in the instance.

**Comment by gargde** [comment]
@antirez  but I didn't run the DEBUG SEGFAULT command my self on the redis instance. I am just running the above piece of code.

**Comment by marcosnils** [comment]
@gargde I asume that the instance where your code is running from has access to all the cluster master nodes, right?

**Comment by gargde** [comment]
@marcosnils  yes. I have access to all the node.

**Comment by marcosnils** [comment]
can you connect to your your master nodes from where the code is running and run a `cluster nodes` command to all of them?.

Thx!.

**Comment by gargde** [comment]
@marcosnils sure. Please see the response in below.

Deepaks-MacBook-Pro:redis-3.0.2 deepakgarg$ src/redis-cli -h ec2-107-22-61-96.compute-1.amazonaws.com cluster nodes
64a298d0859593d1e817b7e998f638586574cb5e 10.167.179.49:6379 slave 4ce9a970f85e92822da0abf6d8041967caafcf72 0 1437134454215 5 connected
26ce52add09a549a11ad27e60ed7a8d6a2c45b69 10.158.128.15:6379 master - 0 1437134455216 7 connected 0-5460
4ce9a970f85e92822da0abf6d8041967caafcf72 10.144.247.154:6379 master - 0 1437134455718 2 connected 5461-10922
58a8daae197ebac76583e74d4d614074aa0ce04f 10.95.175.25:6379 master - 0 1437134454716 3 connected 10923-16383
67773902200b27b4f6aa5ab27792dcd6c1fca73a 10.37.200.42:6379 myself,slave 26ce52add09a549a11ad27e60ed7a8d6a2c45b69 0 0 1 connected
dc6c2f48cac7ccc7ae670482f04f7643aea340f7 10.169.171.53:6379 slave 58a8daae197ebac76583e74d4d614074aa0ce04f 0 1437134455718 6 connected

via code :+1: 

	public static void main(String[] args) {
		Set<HostAndPort> jedisClusterNodes = new HashSet<HostAndPort>();
		jedisClusterNodes.add(new HostAndPort(
				"ec2-54-80-210-178.compute-1.amazonaws.com", 6379));
		jedisClusterNodes.add(new HostAndPort(
				"ec2-54-198-160-111.compute-1.amazonaws.com", 6379));
		jedisClusterNodes.add(new HostAndPort(
				"ec2-107-22-61-96.compute-1.amazonaws.com", 6379));
		jedisClusterNodes.add(new HostAndPort(
				"ec2-54-81-36-12.compute-1.amazonaws.com", 6379));
		jedisClusterNodes.add(new HostAndPort(
				"ec2-54-80-48-155.compute-1.amazonaws.com", 6379));
		jedisClusterNodes.add(new HostAndPort(
				"ec2-23-20-191-174.compute-1.amazonaws.com", 6379));
		JedisCluster jc = new JedisCluster(jedisClusterNodes);
		Map<String,JedisPool> clusterNodeMap = jc.getClusterNodes();
		for(String s : clusterNodeMap.keySet()){
			 System.out.println(s);
		}
		jc.close();
		return;
	}

corresponding output :+1: 

10.167.179.49:6379
10.169.171.53:6379
ec2-107-22-61-96.compute-1.amazonaws.com:6379
ec2-54-81-36-12.compute-1.amazonaws.com:6379
ec2-23-20-191-174.compute-1.amazonaws.com:6379
10.158.128.15:6379
ec2-54-80-210-178.compute-1.amazonaws.com:6379
ec2-54-198-160-111.compute-1.amazonaws.com:6379
10.37.200.42:6379
10.144.247.154:6379
10.95.175.25:6379
ec2-54-80-48-155.compute-1.amazonaws.com:6379

**Comment by marcosnils** [comment]
@gargde please run the `cluster nodes`command in ALL your Redis cluster master nodes and send the output.

**Comment by gargde** [comment]
-----------------------
ubuntu@ip-10-37-200-42:~/redis-3.0.2$ src/redis-cli -h 10.37.200.42 cluster nodes
64a298d0859593d1e817b7e998f638586574cb5e 10.167.179.49:6379 slave 4ce9a970f85e92822da0abf6d8041967caafcf72 0 1437135622922 5 connected
26ce52add09a549a11ad27e60ed7a8d6a2c45b69 10.158.128.15:6379 master - 0 1437135622420 7 connected 0-5460
4ce9a970f85e92822da0abf6d8041967caafcf72 10.144.247.154:6379 master - 0 1437135622922 2 connected 5461-10922
58a8daae197ebac76583e74d4d614074aa0ce04f 10.95.175.25:6379 master - 0 1437135623422 3 connected 10923-16383
67773902200b27b4f6aa5ab27792dcd6c1fca73a 10.37.200.42:6379 myself,slave 26ce52add09a549a11ad27e60ed7a8d6a2c45b69 0 0 1 connected
dc6c2f48cac7ccc7ae670482f04f7643aea340f7 10.169.171.53:6379 slave 58a8daae197ebac76583e74d4d614074aa0ce04f 0 1437135623924 6 connected
---------------------------------------
ubuntu@ip-10-144-247-154:~/redis-3.0.2$ src/redis-cli -h 10.144.247.154 cluster nodes
64a298d0859593d1e817b7e998f638586574cb5e 10.167.179.49:6379 slave 4ce9a970f85e92822da0abf6d8041967caafcf72 0 1437135682610 5 connected
4ce9a970f85e92822da0abf6d8041967caafcf72 10.144.247.154:6379 myself,master - 0 0 2 connected 5461-10922
58a8daae197ebac76583e74d4d614074aa0ce04f 10.95.175.25:6379 master - 0 1437135682110 3 connected 10923-16383
dc6c2f48cac7ccc7ae670482f04f7643aea340f7 10.169.171.53:6379 slave 58a8daae197ebac76583e74d4d614074aa0ce04f 0 1437135681610 6 connected
67773902200b27b4f6aa5ab27792dcd6c1fca73a 10.37.200.42:6379 slave 26ce52add09a549a11ad27e60ed7a8d6a2c45b69 0 1437135681610 7 connected
26ce52add09a549a11ad27e60ed7a8d6a2c45b69 10.158.128.15:6379 master - 0 1437135681610 7 connected 0-5460
-------------------
ubuntu@ip-10-95-175-25:~/redis-3.0.2$ src/redis-cli -h 10.95.175.25 cluster nodes
58a8daae197ebac76583e74d4d614074aa0ce04f 10.95.175.25:6379 myself,master - 0 0 3 connected 10923-16383
26ce52add09a549a11ad27e60ed7a8d6a2c45b69 10.158.128.15:6379 master - 0 1437135672446 7 connected 0-5460
64a298d0859593d1e817b7e998f638586574cb5e 10.167.179.49:6379 slave 4ce9a970f85e92822da0abf6d8041967caafcf72 0 1437135673448 5 connected
dc6c2f48cac7ccc7ae670482f04f7643aea340f7 10.169.171.53:6379 slave 58a8daae197ebac76583e74d4d614074aa0ce04f 0 1437135673448 6 connected
67773902200b27b4f6aa5ab27792dcd6c1fca73a 10.37.200.42:6379 slave 26ce52add09a549a11ad27e60ed7a8d6a2c45b69 0 1437135673448 7 connected
4ce9a970f85e92822da0abf6d8041967caafcf72 10.144.247.154:6379 master - 0 1437135672446 2 connected 5461-10922

**Comment by marcosnils** [comment]
@gargde looking at your commends I see that you're running the `cluster nodes` command from the local box where the node is running. If you go to the machine where your JAVA app is running, can you connect to this addresses? 10.95.175.25 > 10.144.247.154 >  10.37.200.42

**Comment by gargde** [comment]
@marcosnils from my local machine i can connect them using ec2 names ( i can't connect with local ip address. thats how amazon aws is set up. do you thin this could be a issue ? Would it help if i create the cluster with ec2 name ? ).

When I run the cluster node command from local machine .. I still get the same out put. 

Master node 1:

Deepaks-MacBook-Pro:redis-3.0.2 deepakgarg$ src/redis-cli -h ec2-107-22-61-96.compute-1.amazonaws.com cluster nodes
64a298d0859593d1e817b7e998f638586574cb5e 10.167.179.49:6379 slave 4ce9a970f85e92822da0abf6d8041967caafcf72 0 1437134454215 5 connected
26ce52add09a549a11ad27e60ed7a8d6a2c45b69 10.158.128.15:6379 master - 0 1437134455216 7 connected 0-5460
4ce9a970f85e92822da0abf6d8041967caafcf72 10.144.247.154:6379 master - 0 1437134455718 2 connected 5461-10922
58a8daae197ebac76583e74d4d614074aa0ce04f 10.95.175.25:6379 master - 0 1437134454716 3 connected 10923-16383
67773902200b27b4f6aa5ab27792dcd6c1fca73a 10.37.200.42:6379 myself,slave 26ce52add09a549a11ad27e60ed7a8d6a2c45b69 0 0 1 connected
dc6c2f48cac7ccc7ae670482f04f7643aea340f7 10.169.171.53:6379 slave 58a8daae197ebac76583e74d4d614074aa0ce04f 0 1437134455718 6 connected

Master node 2 

Deepaks-MacBook-Pro:redis-3.0.2 deepakgarg$ src/redis-cli -h ec2-54-198-160-111.compute-1.amazonaws.com cluster nodes
64a298d0859593d1e817b7e998f638586574cb5e 10.167.179.49:6379 slave 4ce9a970f85e92822da0abf6d8041967caafcf72 0 1437137643185 5 connected
4ce9a970f85e92822da0abf6d8041967caafcf72 10.144.247.154:6379 myself,master - 0 0 2 connected 5461-10922
58a8daae197ebac76583e74d4d614074aa0ce04f 10.95.175.25:6379 master - 0 1437137642683 3 connected 10923-16383
dc6c2f48cac7ccc7ae670482f04f7643aea340f7 10.169.171.53:6379 slave 58a8daae197ebac76583e74d4d614074aa0ce04f 0 1437137641682 6 connected
67773902200b27b4f6aa5ab27792dcd6c1fca73a 10.37.200.42:6379 slave 26ce52add09a549a11ad27e60ed7a8d6a2c45b69 0 1437137642183 7 connected
26ce52add09a549a11ad27e60ed7a8d6a2c45b69 10.158.128.15:6379 master - 0 1437137641181 7 connected 0-5460

Master node 3

Deepaks-MacBook-Pro:redis-3.0.2 deepakgarg$ src/redis-cli -h ec2-54-80-210-178.compute-1.amazonaws.com cluster nodes
58a8daae197ebac76583e74d4d614074aa0ce04f 10.95.175.25:6379 myself,master - 0 0 3 connected 10923-16383
26ce52add09a549a11ad27e60ed7a8d6a2c45b69 10.158.128.15:6379 master - 0 1437137665696 7 connected 0-5460
64a298d0859593d1e817b7e998f638586574cb5e 10.167.179.49:6379 slave 4ce9a970f85e92822da0abf6d8041967caafcf72 0 1437137665194 5 connected
dc6c2f48cac7ccc7ae670482f04f7643aea340f7 10.169.171.53:6379 slave 58a8daae197ebac76583e74d4d614074aa0ce04f 0 1437137664694 6 connected
67773902200b27b4f6aa5ab27792dcd6c1fca73a 10.37.200.42:6379 slave 26ce52add09a549a11ad27e60ed7a8d6a2c45b69 0 1437137664192 7 connected
4ce9a970f85e92822da0abf6d8041967caafcf72 10.144.247.154:6379 master - 0 1437137664694 2 connected 5461-10922

**Comment by marcosnils** [comment]
@gargde yes, the thing is that your JAVA app needs to be able to connect to the IP addresses that redis-cluster exposes. 

If you run your app within an instance in AWS it should work.

**Comment by marcosnils** [comment]
@gargde please let us know if this can be closed.

**Comment by gargde** [comment]
@marcosnils Thanks for your help. it works. I will create new cluster with ec2 ip address so that I can run the code from local machine.

**Comment by marcosnils** [comment]
@gargde amazing. Can you please close the issue?

**Comment by gargde** [comment]
@marcosnils Thanks,

**Comment by skdangi** [comment]
@marcosnils  I am assuming that @gargde's redis cluster nodes have bound to private ips. So if redis nodes had bound with public ips (to which dns names are mapping i.e ec2-54-80-210-178.compute-1.amazonaws.com), his setup should have worked. Am I correct here?
