### ISSUE TITLE
Wrong index and judgement in ClusterNodeInformationParser

### ISSUE THREAD

**Issue by zts1993** [xetorthio/jedis#1066]
in jedis/src/main/java/redis/clients/util/ClusterNodeInformationParser.java

    if (nodeInfoPartArray.length >= SLOT_INFORMATIONS_START_INDEX) {
      String[] slotInfoPartArray = extractSlotParts(nodeInfoPartArray);
      fillSlotInformation(slotInfoPartArray, info);
    }

as we knew SLOT_INFORMATIONS_START_INDEX is 8，and this is the example of  cluster nodes

db8fee5d0e3eb9fa9297e37b25b8410d93e9172a 192.168.233.131:30002 master - 0 1437639637947 2 connected 5461-10922
4cbe9d5b6f5ebb5618b73d3c601caaaf7cd4614f 192.168.233.131:30005 slave db8fee5d0e3eb9fa9297e37b25b8410d93e9172a 0 1437639636941 5 connected

after split by space master array length is 9 and slave is 8
nodeInfoPartArray.length >= SLOT_INFORMATIONS_START_INDEX) means every node is matser , i think it should be nodeInfoPartArray.length > SLOT_INFORMATIONS_START_INDEX , is that correct ?

**Comment by allanwax** [comment]
An index value of 8 is the 9th item.

**Comment by marcosnils** [comment]
@zts1993 there are also tests for this: https://github.com/xetorthio/jedis/blob/master/src/test/java/redis/clients/jedis/tests/JedisClusterNodeInformationParserTest.java
