### ISSUE TITLE
JedisCluster connection problem occurs after idle for a long time 

### ISSUE THREAD

**Issue by Calabor-Hoc** [xetorthio/jedis#1069]
We are using JedisCluster to connect to redis cluster, set all six nodes' IP:port in position, run the app, do some operation on my app which cause the app to query redis, all things went well. However, After for a about half a hour without any operation on my app(so the jedis in the app is stilled connected to redis, but user donot send any command for a long time ), any subsequent operation result in a "too many redirections" exception. I logged on redis with the official redis-cli, the "info clients" show there is only one client connected(IE me, redis-cli )
Seems the connection pool becomes unavailable after a long time and never revived even new query comes

**Comment by Calabor-Hoc** [comment]
PS This is my pool config:
<bean id="redisPoolConfig" class="org.apache.commons.pool2.impl.GenericObjectPoolConfig">
        <property name="maxTotal" value="1024" />
        <property name="maxIdle" value="1024" />
        <property name="minIdle" value="0" />
        <property name="maxWaitMillis" value="-1" />
 </bean>

**Comment by marcosnils** [comment]
@Calabor-Hoc which Jedis version are you using?

**Comment by Calabor-Hoc** [comment]
version 2.7.2, redis.conf file is just the default file in the redis-cluster -3.0.2 distribution, nothing special is done on it by me.
Set the apache pool's testonborrow=true solve the problem. But I don't like this solution, because testonborrow add a "ping" command before every query I execute...

Also, I can give you the way to reproduce this bug. What the code is doing is basically that using 30 threads to run a redis command in parallel to make sure the 8 connections is all used at least once, then sleep for 13 seconds, and send one last death hit command, and Bang! the excption come out! The redis server set the "timeout" to 10 seconds, which means clients idle for more than 10 seconds is closed by redis server(in production this is longer, I just shorten it to be able to reproduce this bug quickly). 
Note that all the commands involved only touch one key "testkey", this make sure the whole running only use a single jedis pool(IE the pool connected to the redis nodes holding "testkey")
Apache Pool config: the vanila way to make a jedis client using a defalut pool config`JedisCluster jc = new JedisCluster(nodes)`


```java
public void initData() {
		ExecutorService pool = Executors.newFixedThreadPool(30);
		for (int i = 0; i < 30; i++) {
			Thread run = new ThreadTest();
			pool.execute(run);
		}
		try {
			pool.awaitTermination(5, TimeUnit.SECONDS);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
		try {
			Thread.sleep(13000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
		jedisCluster.set("testkey", "hehehehe"); //exception throws here
	}
	
	class ThreadTest extends Thread{
		
		public void run(){
			String res="";
			for (int i = 0; i < 1000; i++) {
				res = jedisCluster.set("testkey", "hehehehe");
			}
			System.out.print(res);
		}
	}

```

**Comment by HeartSaVioR** [comment]
@Calabor-Hoc @marcosnils 
I think we know about this issue, and it seems not easy to fix.
Just relying to Commons Pool 2 doesn't help cause we can't force users to use validation modes.
It doesn't have a feature which validates all idle connections and clears broken.

We need to handle three scenarios, which first one is ```some idle connections in Pool are broken, and unfortunately borrowObject() gives us broken thing```, next one is ```all idle connections in Pool are broken but server is reachable```, and other one is ```server is really not reachable```.

Actually we have the issue not only JedisCluster, but also JedisPool, JedisSentinelPool, ShardedJedisPool.

Need to think more.

**Comment by torbenrebhan** [comment]
It looks like we have this problem with JedisSentinelPool, too. Any help would be appreciated.

**Comment by HeartSaVioR** [comment]
@Calabor-Hoc @marcosnils @torbenrebhan
If user sets idle timeout to Redis, setting testOnBorrow to pool config only makes sense.

- All idle objects can be broken if pool eviction interval is longer than idle timeout.
- If evictor only checks some of idle objects, not checked idle objects can be broken, too.

Or we (or user) may take an aggressive idea, which I'm not sure it's nice way.
- clears idle objects from the pool by calling pool.clear() and re-borrow when borrowed object throws JedisConnectionException
  - We may expose that method to JedisSentinelPool and JedisCluster to call internal_pool.clear()

But it doesn't ensure all other idle objects are broken. We just drop all idle objects cause there's no way to force pool to validate all idle objects.

There's evict() method, but it doesn't work as we expected when testWhileIdle is off.
```
public abstract void evict()
                    throws Exception
Perform numTests idle object eviction tests, evicting examined objects that meet the criteria for eviction. If testWhileIdle is true, examined objects are validated when visited (and removed if invalid); otherwise only objects that have been idle for more than minEvicableIdleTimeMillis are removed.

Throws:
Exception - when there is a problem evicting idle objects.
```

**Comment by marcosnils** [comment]
@Calabor-Hoc ping

**Comment by Calabor-Hoc** [comment]
pong，whats up?

**Comment by marcosnils** [comment]
@Calabor-Hoc wanted to know if we could close this, but you already did :smile:
