### ISSUE TITLE
Feature Proposal: simplify scan/hscan/zscan iteration

### ISSUE THREAD

**Issue by corydolphin** [xetorthio/jedis#1071]
Hi there,

I would like to propose a change to scan/hscan/zscan which would hide the complexity of managing cursors, and batching required to use scan.

My proposal is to add a new scan/hscan/zscan method which takes only a ScanParams object, and returns an Iterator<String>. It would internally maintain a cursor and continue to yield results. 

Is this something that you think would make sense, and would fit with the philosophy of the project? I would be happy to put a PR together if it is interesting.

Cheers,
Cory

**Comment by marcosnils** [comment]
@corydolphin thanks for your suggestion. This issue compliments with https://github.com/xetorthio/jedis/issues/968. Please take a look at that thread and leave your thoughts there so we can all share the best approach to do this.
