### ISSUE TITLE
Brpoplpush does not set Jedis client timeout to infinite

### ISSUE THREAD

**Issue by imothee** [xetorthio/jedis#108]
The blocking call brpoplpush does not call setTimeoutInfinite() and will throw a socket timeout exception after the default 2 seconds.

blpop makes the correct call to setTimeoutInfinite() and brpoplpush should replicate this behaviour.

**Comment by mkozioro** [comment]
Hi @xetorthio.
Should the timeout be really indefinite? 

In last couple of weeks we are observing that our service hangs on method:
jedis.brpoplpush(REDIS_QUEUE_NAME_BYTES, redisWorkQueueNameBytes,                            REDIS_POP_BLOCKING_TIMEOUT_IN_SECONDS). 
It can hang for minutes. 

REDIS_POP_BLOCKING_TIMEOUT_IN_SECONDS is set to 1 second. It is quite possible that our Redis server provider restarted or terminated our redis server while brpoplpush was running. At least we've got notification from provider, that in this time redis had some maintenance.
