### ISSUE TITLE
Error - Exception in thread "main" redis.clients.jedis.exceptions.JedisClusterException: No way to dispatch this command to Redis Cluster because keys have different slots.

### ISSUE THREAD

**Issue by ashishsoni** [xetorthio/jedis#1082]
Getting below error Not sure how to proceed.

package com.ericsson.metratech.idmanager;

import java.io.IOException;
import java.io.InputStream;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.concurrent.TimeUnit;

import org.apache.commons.codec.binary.Hex;
import org.apache.commons.codec.digest.DigestUtils;
import org.apache.commons.io.IOUtils;

import redis.clients.jedis.HostAndPort;
import redis.clients.jedis.JedisCluster;

import com.intenthq.icicle.exception.LuaScriptFailedToLoadException;

public class JedisClusterTest {

	 private static final String LUA_SCRIPT_RESOURCE_PATH = "/id-generation.lua";
	  private static final int DEFAULT_MAX_ATTEMPTS = 5;

	  // We specify an custom epoch that we will use to fit our timestamps within the bounds of the 41 bits we have
	  // available. This gives us a range of ~69 years within which we can generate IDs.
	  private static final long CUSTOM_EPOCH = 1401277473L;

	  private static final int LOGICAL_SHARD_ID_BITS = 10;
	  private static final int SEQUENCE_BITS = 12;

	  private static final int TIMESTAMP_SHIFT = SEQUENCE_BITS + LOGICAL_SHARD_ID_BITS;
	  private static final int LOGICAL_SHARD_ID_SHIFT = SEQUENCE_BITS;

	  // These three bitopped constants are also used as bit masks for the maximum value of the data they represent.
	  private static final long MAX_SEQUENCE = ~(-1L << SEQUENCE_BITS);
	  private static final long MAX_LOGICAL_SHARD_ID = ~(-1L << LOGICAL_SHARD_ID_BITS);
	  private static final long MIN_LOGICAL_SHARD_ID = 1L;

	  private static final long MAX_BATCH_SIZE = MAX_SEQUENCE + 1;

	  private static final long ONE_MILLI_IN_MICRO_SECS = TimeUnit.MICROSECONDS.convert(1, TimeUnit.MILLISECONDS);

	public void runScript()
	{
		Set<HostAndPort> jedisClusterNodes = new HashSet<HostAndPort>();
        //Jedis Cluster will attempt to discover cluster nodes automatically
        jedisClusterNodes.add(new HostAndPort("10.200.37.178", 6379));
        jedisClusterNodes.add(new HostAndPort("10.200.37.172", 6379));
        jedisClusterNodes.add(new HostAndPort("10.200.37.106", 6379));
        JedisCluster jc = new JedisCluster(jedisClusterNodes);
        try {
            InputStream is = this.getClass().getResourceAsStream("/id-generation.lua");
            String luaScript = IOUtils.toString(is, "UTF-8");
         

          // Lame, but we have to use the deprecated version here in order to get this running in Hadoop (which ships with
          // commons-codec 1.4 still for some ungodly reason...)
          String luaScriptSha = Hex.encodeHexString(DigestUtils.sha(luaScript));
          
          List<String> arguments = Arrays.asList(String.valueOf(MAX_SEQUENCE),
                  String.valueOf(MIN_LOGICAL_SHARD_ID),
                  String.valueOf(MAX_LOGICAL_SHARD_ID),
                  String.valueOf(20));
          String[] args = arguments.toArray(new String[arguments.size()]);
          Object results= jc.evalsha(luaScriptSha, arguments.size(), args);
          System.out.println("Cluster Size...." + jc.getClusterNodes().size());
        } catch (IOException e) {
            throw new LuaScriptFailedToLoadException("Could not load Icicle Lua script from the resources in the JAR.", e);
          }
        
        
      
	}
	public static void main(String[] args) {
		JedisClusterTest jedis = new JedisClusterTest();
		jedis.runScript();
		

	}

}

**Comment by marcosnils** [comment]
Please refer to http://redis.io/topics/cluster-spec#multiple-keys-operations
on how to perform multiple-key operations on redis cluster.

**Comment by andrew-asa** [comment]
String script = "local t1=redis.call('KEYS','*')\n" +
                    "for k,v in pairs(t1) do\n" +
                    "redis.call('del',v)\n" + "end";
jedisCluster.eval(script, 0);
any idea i can make it work?
No way to dispatch this command to Redis Cluster.
