### ISSUE TITLE
sentinel pool does not provide enough idle connections

### ISSUE THREAD

**Issue by fabiangebert** [xetorthio/jedis#1086]
We've been using JedisSentinelPool with current and recent Jedis versions for a long time now and we're constantly seeing this issue: the pool is configured to provide 128 idle connections, however, JMX reports that it stops doing so from time to time and we're seeing connect timed out issues when requesting a connection from the pool.
This could be a connection issue. However, the numActive stays at 4-5 connections and using redis CLI we may connect to the machines.
Any advice how we may debug this?

**Comment by fabiangebert** [comment]
JMX monitoring
![java monitoring management console_143](https://cloud.githubusercontent.com/assets/1464747/9163668/f1287870-3f4a-11e5-9a5b-6c91989302b6.png)

**Comment by HeartSaVioR** [comment]
@fabiangebert 
Could you share your JedisSentinelPool's config and Redis idle timeout config? Thanks in advance!

**Comment by fabiangebert** [comment]
@HeartSaVioR sure! I'm using the Grails Redis plugin and customization looks at follows:

maxTotal = 512
minIdle = 128
maxIdle = 256
maxWaitMillis = 5000

**Comment by HeartSaVioR** [comment]
@fabiangebert 
Do you use any validation modes, which are test-on-borrow, test-on-create, test-on-return, test-while-idle?
And did you post an issue from Grails Redis plugin, too?

**Comment by fabiangebert** [comment]
@HeartSaVioR 
validation modes: only the default. It also occurs with other implementation of JedisSentinelPool in other applications on our cluster, that's why I didn't post to the Grails plugin.
The config inherits from JedisPoolConfig. I understand this has the following default settings:
testWhileIdle = true
minEvictableIdleTimeMillis = 60000
timeBetweenEvictionRunsMillis = 30000
numTestsPerEvictionRun = -1

That said, I assume, by default, testing while idle is enabled.
If you want me to test a particular setting, let me know

**Comment by HeartSaVioR** [comment]
@fabiangebert Do you use idle timeout from Redis side?

**Comment by fabiangebert** [comment]
@HeartSaVioR no, should we try?

**Comment by HeartSaVioR** [comment]
@fabiangebert Hmm... No, actually I thought it will be an issue. Let me give it a try.
@marcosnils Could you give it a try, too?

**Comment by fabiangebert** [comment]
we've enabled swallowed exception logging and it shows we're frequently getting
```
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: connect timed out
	at redis.clients.jedis.Connection.connect(Connection.java:164)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:82)
	at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1641)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:85)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:861)
	at org.apache.commons.pool2.impl.GenericObjectPool.ensureIdle(GenericObjectPool.java:920)
	at org.apache.commons.pool2.impl.GenericObjectPool.ensureMinIdle(GenericObjectPool.java:899)
	at org.apache.commons.pool2.impl.BaseGenericObjectPool$Evictor.run(BaseGenericObjectPool.java:1036)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

What is the best way to proceed?

**Comment by fabiangebert** [comment]
The issue does no longer exist if we enable timeout in redis (we've set it to ten minutes, 600 secs)

**Comment by HeartSaVioR** [comment]
@fabiangebert Sorry to respond too late. 
Hmm... I think connect timed out is not Jedis issue, but server side issue. It could be Redis, OS, Network, etc.
And it may be a reason of the actual issue, since evictor would close idle connections.

**Comment by sushilsingh94** [comment]
> The issue does no longer exist if we enable timeout in redis (we've set it to ten minutes, 600 secs)

@fabiangebert I am also facing same time out issue for my redis connections. Could you please let me know what redis timeout parameter you have enabled to 10 minutes? It would help me alot.  Below are my connection snippet.  

GenericObjectPoolConfig poolConfig = new GenericObjectPoolConfig();
poolConfig.setMaxTotal(maxTotal);
poolConfig.setMaxIdle(maxIdle);
poolConfig.setMinIdle(minIdle);
poolConfig.setMaxWaitMillis(maxWaitInSeconds*1000);
JedisSentinelPool pool = new JedisSentinelPool(clusterName, sentinels, poolConfig, timeoutInMillis);

redis.with.sentinel = true
redis.pool.connection.timeout.millis=10000
redis.pool.max.total=100
redis.pool.max.idle=25
redis.pool.min.idle=10
redis.pool.max.wait.seconds=5000
