### ISSUE TITLE
jedis hset(byte[] hashname, byte[] keyname, byte[]value) returns 0 on success

### ISSUE THREAD

**Issue by rrphotosoft** [xetorthio/jedis#1092]
Hi,
When I call hset using byte forms for the hashname, keyname and value, I get 0 as a response.
Is this expected?
What kind of value would i receive if something went wrong? (-1 ??)

Regards,
RR.

**Comment by HeartSaVioR** [comment]
http://redis.io/commands/hset

```
Return value
Integer reply, specifically:
1 if field is a new field in the hash and value was set.
0 if field already exists in the hash and the value was updated.
```

Please reopen this issue if BinaryJedis.hset() returns different from document.

**Comment by rrphotosoft** [comment]
Hi,
Thanks for the reply, but you seem to have misunderstood my question.
Just try the following in a simple java program and you'll see what I mean.

    JedisPool pool = new JedisPool(new JedisPoolConfig(), "localhost");
    try(Jedis jedis = pool.getJedis()){
        byte[] hashname = ("test").getBytes();
        byte[] keyname = ("test_key").getBytes();
        byte[] keyvalue = ("test_value").getBytes();
        Long response = jedis.hset(hashname,keyname,keyvalue);
        System.out.println(response);
    }

You get 0 as the response.
Kindly reopen the issue, until this is resolved.
Best Regards,
RR.

**Comment by HeartSaVioR** [comment]
@rrphotosoft 
You're misunderstanding me. Did you see my answer?
Redis returns "0" if field already exists, or returns "1" if field is a new.

If you want to see 1, try hdel(hashname, keyname) first and call hset().

Our test case shows and validates that. Please see here.
https://github.com/xetorthio/jedis/blob/master/src/test/java/redis/clients/jedis/tests/commands/HashesCommandsTest.java#L47

If it doesn't meet, please let me know your Redis and Jedis version.

I can't see any issue from all of version lines (2.7, 2.8, 3.0). So closing this issue again.

**Comment by rrphotosoft** [comment]
Hi,
I think we could both save a lot of time if you simply copied and ran the code that I posted above. 
Redis server: 2.8.9
jedis jar version: 2.7

I am running the code on an empty redis database. It has no keys in it at all. So the question of an existing field is irrelevant.

Hope you can see what I mean,
Regards,
RR.

**Comment by HeartSaVioR** [comment]
@rrphotosoft 
I think you need to copy our unit test to validate it.
What I really want to say is, Jedis just returns the code Redis provides, and unit test shows that it returns correctly. If it is really an issue, it is not Jedis issue, it is Redis issue.

**Comment by HeartSaVioR** [comment]
Before running each test it always flushes db.
https://github.com/xetorthio/jedis/blob/master/src/test/java/redis/clients/jedis/tests/commands/JedisCommandTestBase.java#L32

**Comment by rrphotosoft** [comment]
I'll copy and run your test if you copy and run my 5 lines. Let me know if you are up for it.

**Comment by HeartSaVioR** [comment]
It prints 1 from ```current master branch & version 2.7.0``` of Jedis and ```Redis 3.1.999 (6233d210/0) 64 bit```.
It surely prints 0 when I run code twice without flushing DB.

Seems like I don't need to waste time on it. It is not an issue. Locking issue.
