### ISSUE TITLE
why JedisCluster not suport 'Set<String> keys(String pattern)' fun

### ISSUE THREAD

**Issue by benkris1** [xetorthio/jedis#1094]
i had used ShardedJedisPool before,now i am change to use JedisCluster,but is has no keys fun.

**Comment by HeartSaVioR** [comment]
We didn't provide ShardedJedis.keys(String pattern), because each node has its keyspace, which is not cluster-wide. JedisCluster is no except.
Without #989 or #990 we couldn't implement it. When we try to get there, it should be resolved.

**Comment by xujijun** [comment]
How about this way:

	@Autowired
	private JedisCluster jedisCluster;

	@Override
	public TreeSet<String> keys(String pattern){
		logger.debug("Start getting keys...");
		TreeSet<String> keys = new TreeSet<>();
		Map<String, JedisPool> clusterNodes = jedisCluster.getClusterNodes();
		for(String k : clusterNodes.keySet()){
			logger.debug("Getting keys from: {}", k);
			JedisPool jp = clusterNodes.get(k);
			Jedis connection = jp.getResource();
			try {
				keys.addAll(connection.keys(pattern));
			} catch(Exception e){
				logger.error("Getting keys error: {}", e);
			} finally{
				//logger.debug("Connection closed.");
				connection.close();
			}
		}
		logger.debug("Keys gotten!");
		return keys;
	}

**Comment by Wei-1** [comment]
The code @xujijun provided did work.
However, note that it will try to connect and get all keys no matter it is a master or a slave.
If one cluster has a lot of replicas, it will have a lot of redundancy.
