### ISSUE TITLE
Connecting Multiple servers of Redis

### ISSUE THREAD

**Issue by a1626** [xetorthio/jedis#1100]
I am using Jedis to connect to Redis. My requirement is that i need to connect to multiple servers of Redis for fail-safe and load balancing purpose. I've explored shardedJedisPool but it does not try to connect to other server if one is down and Cluster does not support authorization. I have replication on for my servers. Which is best way to do it? Should i use VIP for this purpose?

**Comment by marcosnils** [comment]
Please address this issue to the mailing list
