### ISSUE TITLE
Sending raw commands to Redis.

### ISSUE THREAD

**Issue by har777** [xetorthio/jedis#1103]
Is there a way to send raw Redis commands using Jedis ? Something akin to Python's execute_command('command string') ? I am using the new Redis unstable branch for the new geo functionality and need to quickly use the new geo commands.

**Comment by marcosnils** [comment]
@har777 at this moment there isn't because we try to keep Jedis as simple and type safe as possible. If you need Geo commands I strongly suggest to fork redis, and implement them yourself. Adding new commands is relatively easy. 

We're always looking for new contributors

**Comment by har777** [comment]
Makes sense. Got geoadd and georadius working.
