### ISSUE TITLE
Socket leak when commands failed at makeObject()

### ISSUE THREAD

**Issue by yaxing** [xetorthio/jedis#1104]
There's a potential socket leak issue at makeObject() when using JedisPool here:

https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/JedisFactory.java#L87

After establishing the connection using ```.connect()```, if commands like ```.select()``` failed and exception thrown there, then this socket would hang since there's no way to call ```returnBrokenResource``` or ```close()``` on it in higher level logics. 

If Redis is not configured to close idle connections from server side, such connections would stay idle there.

**Comment by HeartSaVioR** [comment]
@yaxing 
Great for finding missed spot! 
Could you craft a patch? If you mind I'll take care of it.
Thanks!

**Comment by yaxing** [comment]
@HeartSaVioR could you help taking care of it?

Appreciate it!

**Comment by HeartSaVioR** [comment]
@yaxing 
Great. Marcos wrote great explanation of submitting PR, please refer here https://github.com/xetorthio/jedis/issues/1023#issuecomment-126837948

**Comment by marcosnils** [comment]
@yaxing @HeartSaVioR the steps are a bit simplified, but if you get stuck somewhere, don't hesitate to ask for help! :+1:
