### ISSUE TITLE
JedisCluster keys method

### ISSUE THREAD

**Issue by Digot** [xetorthio/jedis#1112]
Hi!

Could you please add the keys method to the JedisCluster class?

Thank you!

**Comment by marcosnils** [comment]
Please look in the issues before posting something duplicated. 

https://github.com/xetorthio/jedis/issues/1094

**Comment by xujijun** [comment]
Looks like we have to write one like this:

	@Autowired
	private JedisCluster jedisCluster;

	@Override
	public TreeSet<String> keys(String pattern){
		logger.debug("Start getting keys...");
		TreeSet<String> keys = new TreeSet<>();
		Map<String, JedisPool> clusterNodes = jedisCluster.getClusterNodes();
		for(String k : clusterNodes.keySet()){
			logger.debug("Getting keys from: {}", k);
			JedisPool jp = clusterNodes.get(k);
			Jedis connection = jp.getResource();
			try {
				keys.addAll(connection.keys(pattern));
			} catch(Exception e){
				logger.error("Getting keys error: {}", e);
			} finally{
				//logger.debug("Connection closed.");
				connection.close();
			}
		}
		logger.debug("Keys gotten!");
		return keys;
	}
