### ISSUE TITLE
Make HostAndPort implement Serializable

### ISSUE THREAD

**Issue by mjtieman** [xetorthio/jedis#1126]
Currently we use a single Redis instance as the primary data store for each of our [Storm](https://github.com/apache/storm/) topologies and are making the transition to Redis cluster. We want to set a list of HostAndPort objects (one for each cluster nodes) as a property on some of the bolts, which requires them to be HostAndPort to be serializable.

**Comment by marcosnils** [comment]
@mjtieman HostAndPort should be serializable. Why do you say it is not?

**Comment by mjtieman** [comment]
HostAndPort currently does not implement Serializable. Perhaps I should rename the issue to change HostAndPort to implement Serializable.

**Comment by marcosnils** [comment]
@mjtieman why do you need it to explicitly implement serializable?. A class can be serialized even though it does not implement it.

**Comment by mjtieman** [comment]
When storm distributes it components it first serializes them, requiring all properties of the class to be either Serializable or declared as transient and later instantiated during the prepare method. Our requirements are such that setting the bolt's HostAndPort before serialization would be easier than after.

**Comment by HeartSaVioR** [comment]
@marcosnils @mjtieman 
https://github.com/apache/storm/blob/master/storm-core/src/jvm/backtype/storm/utils/Utils.java#L83

While Storm uses Kryo to serialize/deserialize Tuples, Storm still uses Java ObjectOutputStream to serialize/deserialize Spout / Bolt class.
And HostAndPort is not serializable in point of ObjectOutputStream's view.

So it makes sense to make HostAndPort Serializable.

**Comment by HeartSaVioR** [comment]
@marcosnils I also think HostAndPort should be serializable cause it only contains serializable fields, but unfortunately seems like Java doesn't support it.

**Comment by marcosnils** [comment]
Fixed in #1127
