### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by kamcio96** [xetorthio/jedis#1133]
java.lang.ClassCastException: java.lang.Long cannot be cast to [B
        at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:201)
 	at redis.clients.jedis.Connection.getBulkReply(Connection.java:190)
 	at redis.clients.jedis.Jedis.get(Jedis.java:93)

What could be a reason?

**Comment by marcosnils** [comment]
@kamcio96 this issue has been discussed several times. Search through the closed issues and mailing list before creating a new one

**Comment by kamcio96** [comment]
So why you don't catch that exception and show correct error? That's why Exceptions exists :/

**Comment by marcosnils** [comment]
@kamcio96 we're always welcome to contributions. If you think this can be improved we'll love to hear your proposition and hopefully improve Jedis.
