### ISSUE TITLE
About spring-data-redis-1.6.0.DATAREDIS-315-SNAPSHOT

### ISSUE THREAD

**Issue by zhengfc** [xetorthio/jedis#1135]
Hi,
I want to use a spring-data-redis branch 1.6.0-DATAREDIS-315-SNAPSHOT. But it depend the jedis-3.0.0-SNAPSHOT.jar. How can I get the jar.
Thanks

**Comment by marcosnils** [comment]
Clone the repo and run `make package` on the master branch.

**Comment by zhengfc** [comment]
Ths, I got it
