### ISSUE TITLE
why would jedis 2.7.3 has much worse performance compared to jedis 2.0.0

### ISSUE THREAD

**Issue by yaojuncn** [xetorthio/jedis#1139]
1. redis server, no changes during all test
   redis_version:2.6.9
2. We've been upgrading jedis client from 2.0.0 to 2.7.3,  with the same configuration parameters, 
   we saw a lot more exceptions like below

```
Exception in thread "Thread-4" redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
    at redis.clients.util.Pool.getResource(Pool.java:50)
    at redis.clients.jedis.JedisPool.getResource(JedisPool.java:99)
    at com.yaojuncn.jedis.JedisPerfTest$.onecall(JedisPerfTest.scala:94)
    at com.yaojuncn.jedis.JedisPerfTest$$anonfun$runthreadtest$1$$anon$1$$anonfun$run$1.apply$mcVI$sp(JedisPerfTest.scala:69)
    at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)
    at com.yaojuncn.jedis.JedisPerfTest$$anonfun$runthreadtest$1$$anon$1.run(JedisPerfTest.scala:68)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.NoSuchElementException: Timeout waiting for idle object
    at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:449)
    at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
    at redis.clients.util.Pool.getResource(Pool.java:48)
    ... 6 more
```
1.  after some hard time, finally reached the test code of below
   with 2.7.3 version,
   https://github.com/yaojuncn/jedis273concurrentperftest/blob/master/src/main/scala/com/yaojuncn/jedis/JedisPerfTest.scala

we saw a lot of pool.getResource invocations longer than 20ms....  (if we uncomment out line 37 of above source file we will see a lot of exceptions)
https://github.com/yaojuncn/jedis273concurrentperftest/blob/master/jedis2.7.3.sampleoutput.txt

with 2.0.0 version
https://github.com/yaojuncn/jedis200concurrentperftest/blob/master/src/main/scala/com/yaojuncn/jedis/JedisPerfTest.scala
the output is pretty clean
https://github.com/yaojuncn/jedis200concurrentperftest/blob/master/jedis2.0.0.sampleoutput.txt
1.  I guess this is related to the apache-common pool version that jedis is using
   and I do saw the FAQ https://github.com/xetorthio/jedis/wiki/FAQ 
   and  issues listed here like  
   https://github.com/xetorthio/jedis/issues/844

but by comparing with 2.7.3 and 2.0.0, I think there's something wrong now.
with 16 threads on a 8 max pool size, 
the 2.0.0 could perform very well while the 2.7.3 will see a lot of exceptions if we set the maxwait=20ms;

**Comment by marcosnils** [comment]
@yaojuncn thanks for bringing this up. We use our own benchmarks to test Jedis performance across multiple versions and I've just run it against 2.0.0. and 2.7.2 and I didn't see any performance decrease between version. Can you run the benchmark in your environment and share the results? 

https://github.com/xetorthio/jedis/blob/master/src/test/java/redis/clients/jedis/tests/benchmark/PoolBenchmark.java

It'd be nice also to discard anything that has to do with scala also. Is there a change you can run the benchmarks (both yours and ours) in plain Java?. As we're not scala users it won't be very likely that we can help in that side.

**Comment by HeartSaVioR** [comment]
@yaojuncn 
I'm getting familiar with Scala, but it should be not related on language.

I've own repository for performance test, https://github.com/HeartSaVioR/jedis-benchmark , which uses contiperf, which supports warmup duration, test duration, concurrent threads.
You can clone and modify a bit to use JedisPool, and run the test.

Warm-up is really important for JVM process since it can help JIT to kick in. You should consider that when you create benchmark.

**Comment by yaojuncn** [comment]
@HeartSaVioR  
* some quick note, I did use onecall() in line 17 of both test codes there to init the pool; 
I've ran all the above test several rounds and I got very consistent result that 2.0.0 is giving very stable output while 2.7.3 had many rounds that exceed 20ms wait time (usually about 400  out of total of 16 * 10000 rounds. )

* another note is that the overall tps or average rt does not have that that much change, (mostly i think is tps is already very high or the rt is already very short); the point here is that the average time to get the connection from pool had some cases that is larger than 2.0.0

one solution is in 2.7.3,  to configure the pool size large enough to match the potential threads no, but that's probably not a good idea. giving that 2.0.0 is working well with the same pool size. 

@marcosnils   a java version is coming after some minutes.

**Comment by yaojuncn** [comment]
@marcosnils  below is a java version, the only changes needed for 2.0.0 vs 2.7.3 is inside initPool(), the commented lines of setMaxActive(), setMaxWait() vs setMaxTotal(),
if below line is uncommented for 2.7.3, I got a lot of exceptions listed in the 1st comment of this issue. 
config.setMaxWaitMillis(20);



```
import redis.clients.jedis.Jedis;
import redis.clients.jedis.JedisPool;
import redis.clients.jedis.JedisPoolConfig;

import java.util.ArrayList;
import java.util.concurrent.CountDownLatch;

public class JedisPerfTest {

    public static ArrayList<Long> gtimeList = new ArrayList<Long>();

    public static JedisPool pool = initPool();

    public static void main(String[] args) {
        System.out.println("Running JedisPerfTest....");

        onecall();

        runthreadtest();

        for(long item: gtimeList){
            System.out.println(item);
        }
    }

    public static JedisPool initPool() {
        JedisPoolConfig config = new JedisPoolConfig();
        config.setMinIdle(2);
        config.setMaxIdle(8);

        // below are for jedis 2.0.0
         config.setMaxActive(8);
         config.setMaxWait(20);


        // below are for jedis 2.7.3
        //config.setMaxTotal(8);
        // config.setMaxWaitMillis(20)

        JedisPool pool = new JedisPool(config, "localhost", 6379, 2000);
        return pool;
    }

    public static void runthreadtest() {

        long starttime = System.currentTimeMillis();

        int tno = 16;
        final CountDownLatch start = new CountDownLatch(1);

        final int round = 10000;

        final CountDownLatch finish = new CountDownLatch(tno);
        for(int i = 0; i < tno; ++i){
            new Thread(new Runnable(){
                public void run()  {

                    try {
                        start.await();
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }

                    for(int j = 0; j < round; ++j){
                        onecall();
                    }

                    finish.countDown();

                }
            }).start();
        }

        start.countDown();

        try {
            finish.await();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }


        double avgt = ((double)(System.currentTimeMillis() - starttime))/tno/round;
        System.out.println("tno=" + tno + ", round=" + round + ", avgt(ms)=" + avgt);

    }

    public static void onecall() {

        long start = System.currentTimeMillis();
        Jedis jedis = pool.getResource();
        long t = System.currentTimeMillis() - start;
        if (t > 20) {
            gtimeList.add(t);
        }

        try {

            jedis.set("hello", "world");
            jedis.get("hello");
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (null != jedis) {
                //jedis.close()
                pool.returnResource(jedis);
            }
        }
    }
}
```

**Comment by yaojuncn** [comment]
@marcosnils  @HeartSaVioR 
I read both codes of https://github.com/xetorthio/jedis/blob/master/src/test/java/redis/clients/jedis/tests/benchmark/PoolBenchmark.java

https://github.com/HeartSaVioR/jedis-benchmark/blob/master/src/test/java/redis/clients/jedis/test/GetSetPerformanceTest.java

both tested the overall tps;  for overall tps, I did my similar test as well, the changes seems very slight that I can not say it's downgraded. 

however, in these 2 links, the time to call pool.getResource() is not tested; while this is indeed what I saw in the test that 2.7.3 got many more cases that will take much longer.

**Comment by sazzad16** [comment]
@HeartSaVioR @marcosnils Can we close this one?
