### ISSUE TITLE
Unable to get the value in Java, while URL is giving proper response

### ISSUE THREAD

**Issue by maksood1920** [xetorthio/jedis#1141]
Exception in thread "main" redis.clients.jedis.exceptions.JedisConnectionException: Unknown reply: H

**Comment by marcosnils** [comment]
@maksood1920 please provide further information about the issue like: 

- Jedis version
- Redis version
- Complete stacktrace
- Snippet to reproduce the error (if possible)

**Comment by maksood1920** [comment]
Thanks for concern @marcosnils  ! It was giving error in jedis 2.6, I changed to 2.0. Now it's working fine.
