### ISSUE TITLE
Subscribed jedis timesout 

### ISSUE THREAD

**Issue by friendOfOurs** [xetorthio/jedis#1142]
Hello!

Although a jedisPool with configured timeout is used:
` jedisPool = new JedisPool(poolConfig, REDISHOST, REDISPORT, 0);`
a jedis instance created by this pool and subscribed always times out after 2000 ms.
The funny part is that it doesn't time out if it is not subscribed.

Regards,
friendOfOurs

**Comment by marcosnils** [comment]
@friendOfOurs please provide more information to reproduce this scenario. JedisPool timeout is tested in Jedis code and it works for me.
