### ISSUE TITLE
Pipeline with 100,000 lpush batches drops data

### ISSUE THREAD

**Issue by praveenbalaji-blippar** [xetorthio/jedis#1146]
I have a redis pipeline. I do 100,000 lpush-es before calling pipeline.sync(). I noticed that a lot of my data isn't getting committed. It works fine when I set the batchsize down to 10,000.

I can investigate this, but I wanted to see if someone ran into a similar issue.

Thanks.

**Comment by marcosnils** [comment]
@praveenbalaji-blippar plz share a snippet to reproduce and the Jedis / Redis version + configurations so we can reproduce.

**Comment by praveenbalaji-blippar** [comment]
I'm closing this issue because I can't reproduce it any more.
