### ISSUE TITLE
HostAndPort not serializable in latest Maven dependency 2.7.3

### ISSUE THREAD

**Issue by mtaivalj** [xetorthio/jedis#1149]
This causes issues with Storm deployments.
I see that serializing is already implemented in GitHub.
Thus, could you please build the latest code as Maven dependency.

**Comment by marcosnils** [comment]
@mtaivalj we'll be releasing 2.8 shortly. We've been busy with other stuff in the meanwhile.

You can go ahead and build the 2.8 branch if you want as it will be the same codebase as the one that's going to be released.
