### ISSUE TITLE
why the master and slave of a slot down,the redis-cluster is unavailable?

### ISSUE THREAD

**Issue by liujg** [xetorthio/jedis#1152]
I want to know why author thinks that the master and slave of a slot down,the redis-cluster is unavailable? I think the redis-cluster can reshard at that time to keeping available,why author does not do this

**Comment by HeartSaVioR** [comment]
If master and all slaves for specific slot are down, it means datas in slot could be lost. 
It is serious issue for ops (or devs), and should be known.

**Comment by marcosnils** [comment]
This should be a question for the redis team and doesn't belongs to Jedis. Github is used for bugs and code/design improvements, please re-submit your question in the proper channel.
