### ISSUE TITLE
Jedis Cluster JedisPool getResource   throw exception :Software caused connection abort: socket write error

### ISSUE THREAD

**Issue by moonlightheng** [xetorthio/jedis#1166]
that my whole steps 
when I use JedisCluster 
the JedisSlotBasedConnectionHandler.getConnection()  throw an exception which said that " JedisConnectionException: no reachable node in cluster"
so I debug the method invoke stack
1 jedis = pool.getResource(); 
2 internalPool.borrowObject();
3 validate = factory.validateObject(p); at line 492 in class GenericObjectPool
4 jedis.ping()
5 client.getStatusCodeReply();

and I get a new exception "Software caused connection abort: socket write error"

I don't know why I get this 
I use redis-cli  -c  at the same machine and it works

**Comment by marcosnils** [comment]
@moonlightheng you're running `redis-cli -c` from the same machine where the Java code is running?.

**Comment by marcosnils** [comment]
Closed due to inactivity

**Comment by WENPIN1** [comment]
How will we disable the 'jedis.ping()' in JedisSlotBasedConnectionHandler.getConnection()?

Most of connection pools tend to have an option to set 'seconds to trust a healthy connection' in order to eliminate the connection test during ''seconds to trust" ...
