### ISSUE TITLE
Can not invoke binary scripting commands from pipeline

### ISSUE THREAD

**Issue by janssk1** [xetorthio/jedis#1169]
I'm using jedis 2.7.2

I have a script that needs a binary parameter. However, when i invoke the script in a pipeline, jedis does not allow me to pass binary parameters. (Transaction does not implement BinaryScriptingCommands)
If the script is invoked directly on Jedis,without a pipeline, binary parameters are accepted.

**Comment by marcosnils** [comment]
@janssk1 true. Seems like MultiKeyPipelinebase and PipelineBase don't implement BinaryScriptingCommands. Can you craft a PR so we can merge?

Marcos.

**Comment by marcosnils** [comment]
We need to downmarge   downmerge 3a1b3a2 to 2.7 and 2.8 respectively.

**Comment by marcosnils** [comment]
@janssk1 #1174 should fix this issue. Once another collaborator approves we can go ahead and release 2.8.1
