### ISSUE TITLE
question about  client connect redis cluster 

### ISSUE THREAD

**Issue by Songdantes** [xetorthio/jedis#1170]
HI ALL
     I am a newer about redis cluster  ,I have a question about  the redirect to slot  .if I use  redis-cli   set a key  ，then it will  tell me  connect  to 10.39.18.41.
172.21.27.46:6379> set test222 test
-> Redirected to slot [15437] located at 10.39.18.41:6379
OK  
Like that it looks like  more then once  IO request,i dont't  know  jedis  how to write to redis cluster.Is this the same as redis-cli ?

**Comment by marcosnils** [comment]
Hi @Songdantes please post this question to the Jedis group http://groups.google.com/group/jedis_redis. Github is primarily for code issues and design discussions.
