### ISSUE TITLE
    Type 'redis/clients/jedis/JedisPoolConfig' (current frame, stack[2]) is not assignable to 'org/apache/commons/pool2/impl/GenericObjectPoolConfig'

### ISSUE THREAD

**Issue by weisong-icarbonx** [xetorthio/jedis#1171]
<dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>2.7.3</version>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-pool2</artifactId>
            <version>2.3</version>
        </dependency>

Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.data.redis.core.RedisTemplate com.icarbonx.service.RedisService.redisTemplate; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'redisTemplate' defined in file [D:\java\apache-tomcat-7.0.65\webapps\main\WEB-INF\classes\spring-redis.xml]: Initialization of bean failed; nested exception is java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/springframework/data/redis/connection/jedis/JedisConnectionFactory.createRedisPool()Lredis/clients/util/Pool; @37: invokespecial
  Reason:
    Type 'redis/clients/jedis/JedisPoolConfig' (current frame, stack[2]) is not assignable to 'org/apache/commons/pool2/impl/GenericObjectPoolConfig'
  Current Frame:
    bci: @37
    flags: { }
    locals: { 'org/springframework/data/redis/connection/jedis/JedisConnectionFactory' }
    stack: { uninitialized 0, uninitialized 0, 'redis/clients/jedis/JedisPoolConfig', 'java/lang/String', integer, integer, 'java/lang/String' }
  Bytecode:
    0x0000000: bb00 2c59 2ab6 0028 2ab6 0012 b600 2d2a
    0x0000010: b600 12b6 002e 2a2a b600 12b7 0029 2ab6
    0x0000020: 0012 b600 2ab7 002f b0                 

	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:571)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 58 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'redisTemplate' defined in file [D:\java\apache-tomcat-7.0.65\webapps\main\WEB-INF\classes\spring-redis.xml]: Initialization of bean failed; nested exception is java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/springframework/data/redis/connection/jedis/JedisConnectionFactory.createRedisPool()Lredis/clients/util/Pool; @37: invokespecial
  Reason:
    Type 'redis/clients/jedis/JedisPoolConfig' (current frame, stack[2]) is not assignable to 'org/apache/commons/pool2/impl/GenericObjectPoolConfig'
  Current Frame:
    bci: @37
    flags: { }
    locals: { 'org/springframework/data/redis/connection/jedis/JedisConnectionFactory' }
    stack: { uninitialized 0, uninitialized 0, 'redis/clients/jedis/JedisPoolConfig', 'java/lang/String', integer, integer, 'java/lang/String' }
  Bytecode:
    0x0000000: bb00 2c59 2ab6 0028 2ab6 0012 b600 2d2a
    0x0000010: b600 12b6 002e 2a2a b600 12b7 0029 2ab6
    0x0000020: 0012 b600 2ab7 002f b0

**Comment by marcosnils** [comment]
@weisong-icarbonx do you have any updates about this?

Can we close?

**Comment by backkoms** [comment]
Is that fixed?

i met it again

**Comment by skyyan2000** [comment]
i met too ,the same reason i used 2.9.0 but can not handle
 
         <dependency>
                <groupId>redis.clients</groupId>
                <artifactId>jedis</artifactId>
 				<version>2.9.0</version>
          </dependency>

**Comment by xuleiorray** [comment]
i met it again,is there anyone has fixed it , i'm sure the error is occuring when initialize the JedisPoolConfig instance.
suggestions from anyone are welcome!

**Comment by luckyqiao** [comment]
Is that fixed? I met it, too!

**Comment by xffighting** [comment]
I met it too...

**Comment by caiyao199289** [comment]
org.springframework.web.util.NestedServletException: Handler processing failed; nested exception is java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    cn/hsshop/common/utils/JedisUtil.getInstance()Lredis/clients/jedis/ShardedJedis; @186: invokespecial
  Reason:
    Type 'redis/clients/jedis/JedisPoolConfig' (current frame, stack[2]) is not assignable to 'org/apache/commons/pool2/impl/GenericObjectPoolConfig'
  Current Frame:
    bci: @186
    flags: { }
    locals: { 'redis/clients/jedis/JedisPoolConfig', 'java/util/List', '[Ljava/lang/String;' }
    stack: { uninitialized 180, uninitialized 180, 'redis/clients/jedis/JedisPoolConfig', 'java/util/List' }

**Comment by caiyao199289** [comment]
Please How to resolve this problem,everyone met is?

**Comment by DevJoey** [comment]
I have the same error on my Minecraft Server. It has broke my backend. No solve i must close my server.
