### ISSUE TITLE
SetFromList in Jedis is not Serializable

### ISSUE THREAD

**Issue by HeartSaVioR** [xetorthio/jedis#1179]
Similar issue from #419 and #1126.

I've received user's question on Apache Storm which is the serialization problem, and root cause is BinaryJedis$SetFromList.
Maybe we're having more data structures to use with serialization.

**Comment by HeartSaVioR** [comment]
Narrowing issue to just concentrate SetFromList for now.

**Comment by HeartSaVioR** [comment]
Adding Serializable to SetFromList is completely no problem, but we still need to be sure that implementation of the internal List should be serializable.
Jedis uses standard implementation of Java collection package so it would be safe to conclude it should be serializable, but note that List interface doesn't force implementation of List to be implement Serializable.

We may want to consider about serialization whenever we want to introduce new data structure.

**Comment by marcosnils** [comment]
@HeartSaVioR agree. Can you craft a PR so we can include this?

**Comment by HeartSaVioR** [comment]
@marcosnils Sure, #1182 addresses it. :)
