### ISSUE TITLE
When will JedisCluster support RPOPLPUSH command

### ISSUE THREAD

**Issue by Armstrongya** [xetorthio/jedis#1187]
Hi all, 
    I want to change my single Redis instance to Redis Cluster mode. But found that JedisCluster haven't implement RPOPLPUSH command. Is there any alternative methods ? I found a related issue in Jedis Google Group  which said RPOPLPUSH already implemented in 2014/9/26, but not merged. https://groups.google.com/forum/#!topic/jedis_redis/TauDZTDbang and https://github.com/xetorthio/jedis/pull/687

   Thanks for your time.

**Comment by marcosnils** [comment]
@Armstrongya 2.8 already supports that command: 

https://github.com/xetorthio/jedis/blob/2.8/src/main/java/redis/clients/jedis/MultiKeyJedisClusterCommands.java#L25

**Comment by Armstrongya** [comment]
@marcosnils Thanks for you reply, Jedis 2.8 is released last month, I will try it. Thanks a lot
