### ISSUE TITLE
Version 2.8.0 doesn't include all changes

### ISSUE THREAD

**Issue by cpeer** [xetorthio/jedis#1191]
Version 2.8.0 claims to include pull request #1115. Although the code was merged to master on Sep 23, it is not part of the release.

Pls recreate the release

**Comment by marcosnils** [comment]
@cpeer you're corretct. Seems like I forgot to downmerge that PR to 2.8. I just did it so It'll be available in 2.8.1

**Comment by cpeer** [comment]
@marcosnils lovely, thx. When will 2.8.1 be available?

**Comment by marcosnils** [comment]
@cpeer most likely sometime this week.
