### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by anuragladdha-fk** [xetorthio/jedis#1193]
Greetings

I believe there was documentation for advanced usage section: Transactions, Pipelining, Publish/Subscribe, ShardedJedis, etc

Was this removed recently? If yes, why?

Thanks!
Anurag

**Comment by marcosnils** [comment]
WTF?. Seems like the page completely disappeared. I'll open a github issue to see what happened with it, I can't even see the page history. 

Thanks for reporting!

**Comment by marcosnils** [comment]
Page restored some funny bot / user destroyed the page intentionally. Guess we'll have to switch to collaborators edit mode only. It's a shame :disappointed:

**Comment by anuragladdha-fk** [comment]
Thanks Marcos!
