### ISSUE TITLE
returns instances connected to old master in JedisSentinelPool.getResource()

### ISSUE THREAD

**Issue by poojagarg** [xetorthio/jedis#1194]
Using JedisSentinelPool, after failover, any borrowed instances connected to old master will return to pool. Calling getResource also returns instances that are connected to old master(which is now a slave), and hence throws: JedisDataException: READONLY You can't write against a read only slave.

How to handle this situation?

**Comment by monkeymq** [comment]
i got this situation several times when master has changed
