### ISSUE TITLE
Getting junk value like "OK" for redis get command

### ISSUE THREAD

**Issue by rajasuba** [xetorthio/jedis#1200]
Problem:

I am getting junk values like "OK" for redis get call.
This issue reproduces often over a particular period of time irrespective of the keys trying to obtain through get command.

I'm Using :

Redis version 2.8
Jedis client 2.5.1 to connect Redis

**Comment by marcosnils** [comment]
@rajasuba are you sure you're not sharing your Jedis instance across threads?

In addition to that, I'd recommend if this is happening with latest Jedis 2.8.x version.

**Comment by rajasuba** [comment]
@marcosnils I am sure that i am not sharing my jedis instance across threads. And here is a sample snippet like how i am returning my instance to the pool after execution of each thread.

//Returning redis connection

JedisPool jpool = getPool(host, port, password, database);
if (jpool != null) {
     try {
          if (connection.isNotBroken())
               jpool.returnResource(connection);
else
jpool.returnBrokenResource(connection);
} catch (Exception e) {

        }
 }

**Comment by marcosnils** [comment]
@rajasuba try updating to latest Jedis version and use try-with-resources or `jedis.close()` instead of `returnXXX` methods.

**Comment by rajasuba** [comment]
@marcosnils :+1:  And between i am not aware of "try-with-resources". Can you help me to know about this?

**Comment by marcosnils** [comment]
@rajasuba https://github.com/xetorthio/jedis/wiki/Getting-started#using-jedis-in-a-multithreaded-environment

**Comment by rajasuba** [comment]
@marcosnils :+1:

**Comment by rajasuba** [comment]
Does the above issue got fixed in any of recent Jedis updates ? If yes, is there any release notes regarding this jedis issue fix? Kindly help me.

**Comment by marcosnils** [comment]
@rajasuba. Are you still experiencing this error after the proposed fixes?

**Comment by rajasuba** [comment]
@marcosnils Just curious to know about how migrating to the latest Jedis version could fix this issue :)

**Comment by marcosnils** [comment]
@rajasuba. A lot has been improved from Jedis 2.5 to 2.8. Can you please at least try to see if the problem persista by upgrading the library and using Jedis.close() as mentioned before? This is the first time that I've seen this kind of issue. So I'm positive that the problem probably comes from your code. 

It's hard to provide assistance with so little information and an irreproducible issue

**Comment by rajasuba** [comment]
@marcosnils Thank you so much for sharing your knowledge and experience with me. Sure, I'll upgrade Jedis to its latest version and try to see if the problem persists. :+1:

**Comment by marcosnils** [comment]
@rajasuba did you notice any improvements?

**Comment by HeartSaVioR** [comment]
This is normally occurred when using flawed connection (you may indicate that cause it throws JedisConnectionException). You're encouraged to discard flawed connection and recreate the connection.

This issue is idle for two months, closing.

**Comment by rajasuba** [comment]
This was never again reproducible !! 👎
