### ISSUE TITLE
New version of apache commons pool cause problems with class loader.

### ISSUE THREAD

**Issue by GotoFinal** [xetorthio/jedis#1208]
Due to this lines of code:
https://github.com/apache/commons-pool/blob/trunk/src/main/java/org/apache/commons/pool2/impl/BaseGenericObjectPool.java#L605-L606

Jedis may throw 
`java.lang.ClassNotFoundException: org.apache.commons.pool2.impl.DefaultEvictionPolicy`
error when creating JedisPool in class with other class loader than thread, like when we have master app and addons for it (and this apache library is shaded into addon), simple work around is just override context class loader:
`Thread.currentThread().setContextClassLoader(this.getClass().getClassLoader());`
but this may cause other problems depending on used software. (Other apps can change this loader etc)

Any possible fixes?

**Comment by marcosnils** [comment]
@GotoFinal any ideas if this problem has been reported to commons pools also?. What's their opinion about this?

**Comment by GotoFinal** [comment]
@marcosnils
Commit with that change: https://github.com/apache/commons-pool/commit/3a3e763c90aa6bc04a0537b4480f9e005a45ba22
https://fisheye6.atlassian.com/changelog/commons?cs=1627022

But seems that they fixed it later again:
https://issues.apache.org/jira/browse/POOL-292
it is even visible here: (I don't know why I didn't saw this)
https://github.com/apache/commons-pool/blob/trunk/src/main/java/org/apache/commons/pool2/impl/BaseGenericObjectPool.java#L608

So the only issue is outdated version of library.

**Comment by marcosnils** [comment]
@GotoFinal Jedis uses commons-pool2 2.3 which I believe includes this fix. Is this still an issue?

**Comment by GotoFinal** [comment]
@marcosnils No, fix was added in 2.4.1 as far as I see.

**Comment by marcosnils** [comment]
@GotoFinal you're correct. I guess we can upgrade commons-pool version then.

Thanks for pointing it out!. Would you mind crafting a PR?.

**Comment by marcosnils** [comment]
@varrix. You're using commons-pool2 2.4.x with Jedis correct?. Found any issues so far?

**Comment by marcosnils** [comment]
@yaojuncn @lboue thoughts?

**Comment by GotoFinal** [comment]
weird, travis test failed?, it runs just fine on my small app, but I don't have any special code here ;/

**Comment by varrix** [comment]
@marcosnils Currently running: 
```
// Java Redis client
compile group: 'redis.clients', name: 'jedis', version: '2.7.3', transitive: false, { ext { fatJarExclude = false } }
// Apache Commons-Pool2 for Jedis pooling
compile group: 'org.apache.commons', name: 'commons-pool2', version: '2.4.1', transitive: false, { ext { fatJarExclude = false } }
```

Have quelled any and all issues I've encountered so far. Although the farthest we use it right now is with the `JedisPool`. We don't make use of transactions, clusters, etc.
