### ISSUE TITLE
SSL/TLS Support for JedisCluster

### ISSUE THREAD

**Issue by damiri-ts** [xetorthio/jedis#1210]
I'm going to start working on SSL/TLS support for JedisCluster.

**Comment by damiri-ts** [comment]
@marcosnils @HeartSaVioR I've been studying the Jedis code and I'm thinking it would make sense that the JedisClusterConnectionHandler would somehow need to know how to create SSL/TLS enabled connections but I'm debating the best way to maintain the configuration.

Does it make more sense to:
* Add parameters for enabling and configuring SSL/TLS to the HostAndPort object?
* Add parameters for enabling and configuring SSL/TLS to the JedisConnectionHandler constructor?
* A combination where the connection scheme (use or don't use SSL) is set in HostAndPort while any additional SSL/TLS configuration (SSLSocketFactory, HostnameVerifier) are configured through the JedisConnectionHandler constructor?
* Some other suggestion?

Thanks

**Comment by ameenhere** [comment]
Any tentative dates on when this feature will be released?

**Comment by damiri-ts** [comment]
I've looked into this feature a while back ago and it's not that easy to implement. The main issue is that there is no way to get an HTTPS port from a cluster. Therefore, it's impossible for the client to know what port to connect to for any given node. One potential workaround would be establish a convention where the clients can assume a delta between the regular HTTP port and the HTTPS port. This would have to be configured on the client side and all nodes in a cluster would have to adhere to that. Given the assumptions necessary to make this work I opted to forgo implementation until there was sufficient interest in the community to debate the issue above.

**Comment by bhalyd** [comment]
I'd love some feedback on a potential fix for ssl support for clusters based on my fork.  Extending HostAndPort to accept the same parameters as a Jedis object appear to work against existing Azure redis clusters with ssl enabled.

**Comment by JathinSanghvi** [comment]
Any idea when it this can be part of a release/beta build

**Comment by damiri-ts** [comment]
@bhalyd I understand this is an incredibly delayed response, but I am trying to revive this thread. Regarding, your potential fix, have you tried testing with anything else other than Azure Redis clusters? Perhaps the best thing to do would be to expand the existing integration tests for connecting to clusters?

**Comment by bhalyd** [comment]
I haven't done any additional testing outside of the azure environment.  I just simply haven't had the time to do so.

**Comment by damiri-ts** [comment]
@bhalyd There's another pull request that aims to achieve the same goal. Perhaps you can have a look at it and provide some feedback. See https://github.com/xetorthio/jedis/pull/1550.

**Comment by hkousha** [comment]
:+1:

**Comment by shimshof** [comment]
Hi. 
we built a cluster in AWS with encrypted-in-transition.
when i am trying to connect and auth against a single node in the cluster (Jedis with uri)  i success. but when i am trying to connect the cluster (JedisCluster) i get empty list of nodes (No reachable node in cluster) is JedisCluster already support SSL/TLS properly?  
regards

**Comment by hradilf** [comment]
Hi,
please, is there any estimation and plan, if/when whit feature will be available in v2.10.x?

We are currently running on v2.9.0, using spring-data and we have to start to use SSL on Redis Enterprise.

Thanks for update.

**Comment by seyadali** [comment]
do we have any update this functionalities

**Comment by rohittawde1990** [comment]
Any updated on this issue

**Comment by sazzad16** [comment]
@rohittawde1990 JedisCluster supports SSL since jedis-3.1.0. Please use latest a version.

**Comment by rohittawde1990** [comment]
@sazzad16 I had dependency of 3.4.0.

```
<dependency>
    <groupId>redis.clients</groupId>
    <artifactId>jedis</artifactId>
    <version>3.4.0</version>
</dependency>
```

**Comment by sazzad16** [comment]
@rohittawde1990 You should be able to use JedisCluster with SSL with that. However there is a bugfix in `3.4.1`. Try using that version if, somehow, your code is affected by that bug.

Also, check our test codes to get more idea about how to use JedisCluster with SSL:
- https://github.com/redis/jedis/blob/master/src/test/java/redis/clients/jedis/tests/SSLJedisClusterTest.java 
- https://github.com/redis/jedis/blob/master/src/test/java/redis/clients/jedis/tests/SSLJedisClusterWithCompleteCredentialsTest.java

**Comment by sodrulamin** [comment]
Hi,
getting 404 page not found for above to ssl jedis cluster test files.

I can't connect to my redis cluster using jedis cluster class. Need some help.

**Comment by sazzad16** [comment]
@sodrulamin The test packages are restructured since then.

- [JedisCluster test with SSL](https://github.com/redis/jedis/blob/master/src/test/java/redis/clients/jedis/SSLJedisClusterTest.java)
- [JedisCluster test with SSL and ACL](https://github.com/redis/jedis/blob/master/src/test/java/redis/clients/jedis/SSLACLJedisClusterTest.java)

**Comment by sazzad16** [comment]
@sodrulamin From your stackoverflow question, you're using a Jedis version lower than 4.0. For that, you can just replace `master` by `3` in the urls to get those examples.
