### ISSUE TITLE
silently unsubscriberr

### ISSUE THREAD

**Issue by snecker** [xetorthio/jedis#1213]
When i use Jedis pub/sub, it will work for a short time,then the subscription will dies silently after 5min
,and no exception throw,the java process is still alive

```java
public static void main(String[] args) throws Exception {
    Jedis jedis = new Jedis("127.0.0.1", 6379, 0);
    jedis.auth("XXXX");
    System.out.println("ready to subscribe:" + jedis.ping());
    jedis.subscribe(new CustomizeJedisPubSub(), "client.subscriber");
}
```

CustomizeJedisPubSub.java
```java
public class CustomizeJedisPubSub extends JedisPubSub {

        @Override
        public void onMessage(String channel, String message) {
            System.out.println(LocalDateTime.now() + "received:" + message + ",");
        }

        @Override
        public void onPMessage(String pattern, String channel, String message) {

        }

        @Override
        public void onSubscribe(String channel, int subscribedChannels) {

        }

        @Override
        public void onUnsubscribe(String channel, int subscribedChannels) {

        }

        @Override
        public void onPUnsubscribe(String pattern, int subscribedChannels) {

        }

        @Override
        public void onPSubscribe(String pattern, int subscribedChannels) {

        }
    }
```

and in server reids-cli,run
```shell
 127.0.0.1:6379> publish client.subscriber "hahah"
(integer) 1
```

after 5min,run publish again ,the console will not print any message

jedis client version:2.8.0
redis sever vesion: 3.0.1

**Comment by marcosnils** [comment]
@snecker do you have a `timeout` configured on redis side?

**Comment by snecker** [comment]
@marcosnils, i've checked that config in redis.conf
>  # Close the connection after a client is idle for N seconds (0 to disable)
>  timeout 0

**Comment by marcosnils** [comment]
@snecker maybe something is killing the connection without you realizing. Can you check after 5 mins if Jedis is still connected to your redis server using `client list`? http://redis.io/commands/client-list

**Comment by snecker** [comment]
@marcosnils 

i didnt change anything,it seems ok now,and  the subscribed connection is still connected after 5mins

> id=12533 addr=112.94.153.9:61509 fd=302 name=test age=337 idle=336 flags=N db=0 sub=1 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=subscribe

i'll check that tomorrow,it seems strange
