### ISSUE TITLE
JedisCluster.psubscribe() calling wrong subscribe command instead of psubscribe

### ISSUE THREAD

**Issue by tuutep01** [xetorthio/jedis#1214]
JedisCluster.psubscribe() should call connection.psubscribe() instead of connection.subscribe().

This is just one character fix so I didn't want to create a pull request.

**Comment by marcosnils** [comment]
@tuutep01 nice catch!. Please Go ahead and craft a PR.

**Comment by tuutep01** [comment]
#1218 crafted.

**Comment by HeartSaVioR** [comment]
Closed via #1218
