### ISSUE TITLE
Jedis should use SLF4J instead of Java logging

### ISSUE THREAD

**Issue by PatrickSauts** [xetorthio/jedis#1219]
Java Logging in not the industry standard anymore. User should be able to use the logging implementation he wants in order not to end up with several logging configuration files to maintain.

SLF4J provide a facade to the most commons logging formats: log4j, java logging and LogBack.

It also improve performances by having string build when needed
Example:
**java logging** 
```
log.fine("Sentinel " + host + ":" + port + " published: " + message + ".");
```
will always build the string

**slf4j**
```
LOG.debug("Sentinel {}:{} published: {}.",host,port,message);
```
will build the string only if logging level is set to debug.

**Comment by marcosnils** [comment]
@PatrickSauts we try to keep Jedis as plain as possible regarding external dependencies. If you check the code you'll realize that Jedis doesn't have any logging at all, and we decided that we'll try to keep logging as minimal as possible as pretty much everything can be debugged from the redis logs / monitor commands. 

If you check the code you'll realize that there's no logging at all, so unless we **really** have the need to support logging, I don't think we'll be addressing this soon.

**Comment by PatrickSauts** [comment]
Thank you for your answer.

Still the strings are built. This could be improved. But I guess that's minor.

**Comment by PatrickSauts** [comment]
Actually JedisSentinelPool uses   
protected Logger log = Logger.getLogger(getClass().getName());
That's why I was talking about logging.

By the way I'm writing a JedisElasticachePool to use Elasticache Redis.
The difference with a regular redis master slave configuration is that Amazon prevent from writing to a slave an they have implemented a way to promote a new master. it's based on https://github.com/mrniko/redisson/pull/244

So my question is should I use Java logging ?

**Comment by marcosnils** [comment]
@PatrickSauts standard redis master / slave also prevents writing to slaves by default. It can be configured however with the slave-read-only configuration parameter.

Regarding adding ElastiCache failover mechanism I'd check if it's possible to do it as a separate library instead of bundling it into Jedis directly. The main reasons for this are:

- Why try to keep jedis as close to the redis spec as possible (basically a Redis driver). Adding third party providers functionalities is something that we usually avoid unless it's entirely necessary. 

- We're currently a few active contributors to the project. Adding another module means that it's necessary to keep it up to date which will take away time for the core features

- Having a thirt party library implementing this functionality means that this library can grow organically without depending what happens to Jedis. Basically the library can have it's own release cycle and shouldn't wait for Jedis for new features. 

Hope this helps to understand our reasons.

**Comment by HeartSaVioR** [comment]
@PatrickSauts 
Adding a dependency is what we try to avoid since Jedis claims itself as a lightweight library.

Jedis itself barely leaves log message, so I think you can just add jul-to-slf4j as your dependency and choose underlying logging framework to non jdk14.
http://www.slf4j.org/legacy.html#jul-to-slf4j

Please give it a try and share the result. Thanks!

**Comment by PatrickSauts** [comment]
Thank you !

@HeartSaVioR Just once again the strings are always built.

@marcosnils If you have a third party library for that kind of things I'll gladly give them the code.

**Comment by HeartSaVioR** [comment]
@PatrickSauts 
I'm sorry but I know how logging frameworks work. I'm also a user to slf4j with logback / log4j2.
I'm saying that logging at Jedis is minimized so it shouldn't affect the performance.

**Comment by HeartSaVioR** [comment]
@PatrickSauts 
If we agree to add slf4j as a dependency, then what underlying logging framework should we choose?
If we choose one as a underlying framework, users should exclude selected framework if users already use slf4j and want to depend on other underlying framework.
If we don't choose underlying framework, and if users don't add underlying framework as a dependency, slf4j doesn't work properly.

I don't think Jedis should participate exclusion hell...

**Comment by PatrickSauts** [comment]
@HeartSaVioR  
since SLF4J 1.6 

If no binding is found on the class path, then SLF4J will default to a no-operation implementation.

so if no binding no logging.

**Comment by HeartSaVioR** [comment]
@PatrickSauts 
No, no logging is not we want. 
Scenario, users don't use slf4j and add Jedis as a dependency then it stopped logging whole log in process.

**Comment by PatrickSauts** [comment]
@HeartSaVioR 
I understand.

Jedis would perform better it's a pitty. 
Some documentation could help.
SLF4J is the most popular logging framework nowadays. One who uses Redis must know about SLF4J.
But that's probably just me who think like that.

**Comment by HeartSaVioR** [comment]
@PatrickSauts 
Please say that thing to Java.
I believe Java should address logging when releasing language at the first time.
And I also think SLF4J is nearly de facto, but it's not for putting someone down.

Btw, Redis is not related on SLF4J, it's just a C language server. ;)

**Comment by marcosnils** [comment]
> Jedis would perform better it's a pitty.

We currently have __almost no logging at all__ in Jedis. So how could it perform better?

**Comment by PatrickSauts** [comment]
@marcosnils my bad I had JedisSentinelPool in mind. Not all the classes are like this one.

**Comment by mp911de** [comment]
How about introducing a logging factory? I fell myself over logging with [mp911de/logstash-gelf](https://github.com/mp911de/logstash-gelf). The logger tries to write a log event using Redis and the logging code causes a recursion :/

See https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/logging/InternalLoggerFactory.java#L51


This approach allows to declare slf4j, log4j, ... as optional dependencies which do not pollute the class path of a user.

**Comment by HeartSaVioR** [comment]
@mp911de 
While InternalLoggerFactory can help us to add logging framework dependencies as 'provided', I don't think Jedis needs logger framework as dependency at all. Please refer comment from @marcosnils.

**Comment by mp911de** [comment]
The great advantage would be to be able to replace a particular logger to disable logging at all. That would be my use case. There's a difference between almost no logging and no logging at all.

**Comment by pejip** [comment]
Hi,

I have following log that are output by redis
Jun 03, 2016 10:17:09 AM redis.clients.jedis.JedisSentinelPool initSentinels
INFO: Trying to find master from available Sentinels...
Jun 03, 2016 10:17:09 AM redis.clients.jedis.JedisSentinelPool initSentinels
INFO: Redis master running at xxx.xxx.xxx.xxx:6379, starting Sentinel listeners...
Jun 03, 2016 10:17:09 AM redis.clients.jedis.JedisSentinelPool initPool
INFO: Created JedisPool to master at xxx.xxx.xxx.xxx:6379

Is there any way to disable the logging completely?

**Comment by marcosnils** [comment]
Mailing list please
