### ISSUE TITLE
HSCAN, SSCAN and ZSCAN not available on BinaryCluster

### ISSUE THREAD

**Issue by mp911de** [xetorthio/jedis#1225]
### Expected behavior

`HSCAN`, `SSCAN` and `ZSCAN` should be available on `BinaryCluster` 

### Actual behavior

`HSCAN`, `SSCAN` and `ZSCAN` are only available with `String` signatures which breaks the key (and also the slot hash calculation) if keys are binary (`byte[]`).

We noticed the difference in signatures while testing the jedis Cluster integration in [Spring Data Redis](https://github.com/spring-projects/spring-data-redis/blob/master/src/main/java/org/springframework/data/redis/connection/jedis/JedisClusterConnection.java#L1553).

#### Jedis version:

2.8.0

**Comment by marcosnils** [comment]
@mp911de thanks for noticing. I've already submitted a PR that fixes, can you PTAL?
