### ISSUE TITLE
spring-data-redis 315 brach

### ISSUE THREAD

**Issue by moonandstar08** [xetorthio/jedis#1228]
Hi,
   Server months ago, i can see there was a spring-data-redis 315 brach, but now i cannot find. who can tell me which brach spring-data-redis 315 becomes to ?

**Comment by moonandstar08** [comment]
Hi,
  I want to use the multi and pipeline in the redis cluster, but from the code i only see the method but no implements, when these features i can uses? 
 Thanks!

**Comment by marcosnils** [comment]
@moonandstar08 please read https://github.com/xetorthio/jedis/issues/990

Regarding spring-data-redis, that's a total separate project from pivotal, it uses Jedis but we don't maintain it.

**Comment by moonandstar08** [comment]
Do you mean in the spring-data-redis it don't support the multi and pipeline?
