### ISSUE TITLE
jedis connection breaks during failover

### ISSUE THREAD

**Issue by PriyankaRanjan** [xetorthio/jedis#1241]
### Expected behavior
i have increased the jedis conneciton timeout so expect the jedis apis to wait and keep retrying till the failover completes ...

### Actual behavior

jedis APIs are timing out without waiting. how to make jedis APIs to keep retrying internally till the failover finishes?

**Comment by HeartSaVioR** [comment]
Connection timeout is used for one trial of connecting (just as Java Socket option), and Jedis doesn't support connection retry.

If you construct H/A with Redis Sentinel, you can use JedisSentinelPool so pool can borrow appropriate instance for current master, and keep retrying from your application logic.
