### ISSUE TITLE
redis cluster require password，how to auth password when use JedisCluster API 

### ISSUE THREAD

**Issue by xsjie** [xetorthio/jedis#1242]
### Expected behavior

jedisCluster should provride auth(String password) method 

### Actual behavior

jedisCluster can not auth password 

### Steps to reproduce:

1、redis cluster set requrepass
2、user JedisCluster don't know how to auth password ! have not auth() method provrided?

**Comment by marcosnils** [comment]
dupe https://github.com/xetorthio/jedis/issues/1165
