### ISSUE TITLE
2.8.0 JedisCluster cluster send puts and get to the correct master node ?

### ISSUE THREAD

**Issue by sock-puppet-2** [xetorthio/jedis#1243]
I have read this  http://redis.io/topics/cluster-spec

```
Since cluster nodes are not able to proxy requests, clients may be redirected to other nodes using redirection errors -MOVED and -ASK. The client is in theory free to send requests to all the nodes in the cluster, getting redirected if needed, so the client is not required to hold the state of the cluster. However clients that are able to cache the map between keys and nodes can improve the performance in a sensible way.
```

hows is this relate to   redis.clients.jedis.JedisCluster  ?  
will  JedisCluster cluster send puts and get to the correct master node ?

also 

will JedisCluster auto discover and connect all the other Redis Master nodes in the cluster ? 
even if I just set the IP of just 1 Master node  ?

Thanks.

**Comment by marcosnils** [comment]
> hows is this relate to redis.clients.jedis.JedisCluster ?

JedisCluster does exactly this

> will JedisCluster cluster send puts and get to the correct master node ?

Yes.


> will JedisCluster auto discover and connect all the other Redis Master nodes in the cluster ? 
> even if I just set the IP of just 1 Master node ?

yes
