### ISSUE TITLE
2.8.0 JedisCluster GenericObjectPoolConfig for performance.

### ISSUE THREAD

**Issue by sock-puppet-2** [xetorthio/jedis#1244]
How should I configure JedisCluster client for best performance.

I have 1 instance of JedisCluster shared between a fixed number of threads,

The threads are performing set and get operations.

How to configure JedisCluster, using GenericObjectPoolConfig 
to maximize the throughput of operations. 

Thanks

**Comment by marcosnils** [comment]
Post this in the Jedis mailing list please. Github is used for code / design issues.
