### ISSUE TITLE
About pexpireAt,Is this a bug

### ISSUE THREAD

**Issue by starmarine** [xetorthio/jedis#1254]
### Expected behavior

redisTemplate.expireAt(key, new Date(System.currentTimeMillis() + 5 * 60 * 1000));
expected the key to expire after 5 minutes

### Actual behavior

My key is not expire

### Steps to reproduce:

In the redis.clients.jedis.BinaryJedisCluster.java
I've noticed that in the method pexpire(final byte[] key, final long milliseconds),it invoke the connection.pexpire(key, milliseconds);
but in the method pexpireAt(final byte[] key, final long millisecondsTimestamp),i also invoke the connection.pexpire(key, milliseconds);

Should it invoke the connection.pexpireAt() method?

#### Jedis version:
current master
#### Redis version:
3.0.7
#### Java version:
1.7

**Comment by marcosnils** [comment]
@starmarine this works as expected. Check out how we test it here: https://github.com/xetorthio/jedis/blob/master/src/test/java/redis/clients/jedis/tests/commands/AllKindOfValuesCommandsTest.java#L505-L516

**Comment by marcosnils** [comment]
You need to make sure that the key exists before running `pexpireAt`. You can verify which timeout was set with the `pttl` command after calling pexpireAt.
