### ISSUE TITLE
Really confusing lua interface in Cluster

### ISSUE THREAD

**Issue by TimothyZhang023** [xetorthio/jedis#1257]
I found interface  public Object eval(final String script, final String key) in JedisCluster really confusing.

Code is like below 
`
public Object eval(final String script, final String key) {  
    return new JedisClusterCommand<Object>(connectionHandler, maxRedirections) {  
      @Override  
      public Object execute(Jedis connection) {  
        return connection.eval(script);  
      }  
    }.run(key);  
  }  
`
i think that key is used to dispatch this command to Redis Nodes.

it is equal to `eval(String script)` in  Jedis . 

we give the key to call lua script , but we cannot use it in script ! 
#### Example:

`String script = "local v = redis.call('zrange', KEYS[1], '0', '0' ); " +  
                "if v == nil then return nil ; else  redis.call('zrem', KEYS[1], v[1]); return v end" +  
                " return v";  
`
i  call this by 
`jedisCluster.eval(script,"hello")`

so, i got exception.

correct way is 
`jedisCluster.eval(script,1,"hello")`

so, it confused me , so i think
`Object eval(final String script, final String key)`
should be implements like below
`
  public Object eval(final String script, final String key) {
    return new JedisClusterCommand<Object>(connectionHandler, maxRedirections) {
      @Override
      public Object execute(Jedis connection) {
        return connection.eval(script, 1, key);
      }
    }.run(key);
  }
`

it is more convenience and no ambiguous 
#### Jedis version:

master branch
#### Redis version:

all

**Comment by marcosnils** [comment]
@zts1993 to do what you want you have the `eval(final String script, final int keyCount, final String... params)` method in JedisCluster where you can send both keys and args to the script. 

As you said, the reason for the ` eval(final String script, final String key)` method is so we know which cluster node to dispatch the command to. If we do what you propose then there's no way to execute a lua script without sending any argument in JedisCluster. 

I believe the best approach here would be to rename the `key` argument to `nodeKey` when it's used for this purpose and to add specific JavaDocs so users understand what this parameter is doing.

**Comment by sazzad16** [comment]
Resolved by #1756
