### ISSUE TITLE
auto start of shards

### ISSUE THREAD

**Issue by PriyankaRanjan** [xetorthio/jedis#1260]
### Expected behavior

I am using Redis Enterprise cluster. I have three nodes and 4 shards where 2 shards are running on node1 and 2 shards are running on node2 , no shard is running on node3. Node 1 is master. when node1 goes down the node2 becomes master but the shards of Node1 dont failover to Node2 or Node 3. I do not understand why the shard failover is not happening automatically. I have followed RLEC documentation for the installation . Am i missing something?

### Actual behavior

shards do not failover automatically. I start them manually

### Steps to reproduce:

1) reboot/fail the master node
2) shards do not failover

**Comment by marcosnils** [comment]
Jedis doesn't perform failover. RLEC should take care of fail over, and Jedis should continue working as expected.
