### ISSUE TITLE
conversion of score from double to byte array should consider both "-inf" and "+inf"

### ISSUE THREAD

**Issue by HeartSaVioR** [xetorthio/jedis#1264]
Below logic is what Jedis converts scores typed double to byte arrays. 

```
    byte[] byteArrayMin = (min == Double.NEGATIVE_INFINITY) ? "-inf".getBytes() : toByteArray(min);
    byte[] byteArrayMax = (max == Double.POSITIVE_INFINITY) ? "+inf".getBytes() : toByteArray(max);
```

I think this kind of conversion is bad cause giving "-inf" "-inf" as score range is still valid. 
Conversion of score should check both Double.NEGATIVE_INFINITY and Double.POSITIVE_INFINITY for each score, not handling by context.

**Comment by id-ilych** [comment]
https://github.com/xetorthio/jedis/pull/1271

**Comment by marcosnils** [comment]
Plz check #1273
