### ISSUE TITLE
Getting JedisClusterException  CLUSTERDOWN The cluster is down

### ISSUE THREAD

**Issue by Annapoornar** [xetorthio/jedis#1267]
Hi,

We have redis cluster setup, 3 master-3 slaves .

We are storing/getting the data to/from the cache. The processing for happening overnight. In the logs I see below exception while get/set is happening for around 30 secs. later it started working fine. If it was a network issue during that time, it should have thrown JedisConnectionException. 

! redis.clients.jedis.exceptions.JedisClusterException: CLUSTERDOWN The cluster is down
! at redis.clients.jedis.Protocol.processError(Protocol.java:115) ~[jedis-2.8.0.jar:na]
! at redis.clients.jedis.Protocol.process(Protocol.java:151) ~[jedis-2.8.0.jar:na]
! at redis.clients.jedis.Protocol.read(Protocol.java:205) ~[jedis-2.8.0.jar:na]
! at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:297) ~[jedis-2.8.0.jar:na]
! at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:196) ~[jedis-2.8.0.jar:na]
! at redis.clients.jedis.BinaryJedis.set(BinaryJedis.java:120) ~[jedis-2.8.0.jar:na]
! at redis.clients.jedis.BinaryJedisCluster$1.execute(BinaryJedisCluster.java:75) ~[jedis-2.8.0.jar:na]
! at redis.clients.jedis.BinaryJedisCluster$1.execute(BinaryJedisCluster.java:72) ~[jedis-2.8.0.jar:na]
! at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:119) ~[jedis-2.8.0.jar:na]
! at redis.clients.jedis.JedisClusterCommand.runBinary(JedisClusterCommand.java:59) ~[jedis-2.8.0.jar:na]
! at redis.clients.jedis.BinaryJedisCluster.set(BinaryJedisCluster.java:77) ~[jedis-2.8.0.jar:na]
! at com.altisource.realdoc.capture.common.service.RedisClusterClient.store(RedisClusterClient.java:39) ~[armoury-3.0.1.13.jar:3.0.1.13]

Please help why this behaviour could be?

**Comment by marcosnils** [comment]
Please put your cluster logs into debug check your redis logs and provide more info about the incident. We provide feedback with only a stacktrace. Also please inform Jedis and Redis versions.

**Comment by TracyJian** [comment]
@Annapoornar have the problem solved now?

**Comment by vipsql** [comment]
same problem with me, it the hava any solution?

**Comment by TracyJian** [comment]
https://github.com/xetorthio/jedis/issues/1461#issuecomment-344038224

**Comment by TracyJian** [comment]
@vipsql hope this could help you
https://github.com/xetorthio/jedis/issues/1461#issuecomment-344038224

**Comment by TracyJian** [comment]
@vipsql hope this could help you https://github.com/xetorthio/jedis/issues/1461

**Comment by vipsql** [comment]
@TracyJian  Thanks
