### ISSUE TITLE
Does Jedis support Azure Redis Cluster

### ISSUE THREAD

**Issue by xingzhougmu** [xetorthio/jedis#1268]
### Expected behavior

Microsoft Azure supports Redis Cluster. But it seems there is no support for this in Jedis at this moment.

I used ShardJedis, but get intermittent redis.clients.jedis.exceptions.JedisMovedDataException: MOVED.
**Example Usage:**
/* In this line, replace <name> with your cache name: */
	    JedisShardInfo shardInfo = new JedisShardInfo("testpremium.redis.cache.windows.net", 6379); //testpremium/rediscachexing.redis.cache.windows.net
	    shardInfo.setPassword("password key") ;
	   	    Jedis jedis = new Jedis(shardInfo);
	    jedis.set("foo", "bar");
	    String value = jedis.get("foo");
	    jedis.close();
	    System.out.println(value);

when checking Jedis Cluster, there is no way to set access key however.
**Example Usage for Jedis Cluster:**
Set<HostAndPort> jedisClusterNodes = new HashSet<HostAndPort>();
//Jedis Cluster will attempt to discover cluster nodes automatically
jedisClusterNodes.add(new HostAndPort("127.0.0.1", 7379));
JedisCluster jc = new JedisCluster(jedisClusterNodes);
jc.set("foo", "bar");
String value = jc.get("foo");

### Redis / Jedis Configuration
default configuration
#### Jedis version:
2.8.0

**Comment by marcosnils** [comment]
ShardedJedis is not intended to be used with Redis Cluster. You need to use `JedisCluster` instead.

**Comment by xingzhougmu** [comment]
But how to use JedisCluster for Azure Cache?
What I have is a redis DNS name and access key, we don't have host IP and port for each shard.

**Comment by xingzhougmu** [comment]
Actually this is my question.
https://github.com/xetorthio/jedis/issues/1242

Looks like JedisCluster does not support password auth. Any plan to add this in the future?

**Comment by marcosnils** [comment]
@xingzhougmu even though clustering password strategy hasn't been defined in the redis cluster spec seems like users need it quite a lot. I'll try to see if It's straightforward to implement so it doesn't represent a roadblock to Jedis users.

**Comment by marcosnils** [comment]
@xingzhougmu just implemented it in #1269

**Comment by xingzhougmu** [comment]
@marcosnils thanks for the information. Besides the password strategy, not sure if the JedisCluster can work with Azure Redis Cluster by feeding the DNS name. For example: rediscluster.redis.cache.windows.net.
Right now, I can only see the JedisCluster clinet is initilated with a ServerNode hashset.

Thanks,
Xing

**Comment by marcosnils** [comment]
@xingzhougmu it should. If you connect to he redis-instance listening on that DNS and you issue a `cluster slots` what do you get in the response?

That's the mechanism that Jedis uses to automatically discover cluster nodes.

**Comment by xingzhougmu** [comment]
@marcosnils I use redis-cli to test, and the resoponse is as below.
**PS C:\Program Files\Redis>** .\redis-cli.exe -h testpremium.redis.cache.windows.net -p 6379 -a CxDZ1/oUEBoE86iQQaGwMtEmJ5K08V4vHuL3iCga/Pk=
**testpremium.redis.cache.windows.net:6379>** cluster slots
1) 1) (integer) 8192
   2) (integer) 16383
   3) 1) "100.76.6.3"
      2) (integer) 10226
   4) 1) "100.76.2.15"
      2) (integer) 10226
2) 1) (integer) 0
   2) (integer) 8191
   3) 1) "100.75.112.63"
      2) (integer) 10226
   4) 1) "100.76.56.94"
      2) (integer) 10226
**testpremium.redis.cache.windows.net:6379>** cluster nodes
7bcc3b5ed05803612fe5d10dafae1f36265d1c8a 13.92.131.54:13002 myself,master - 0 0 3 connected 8192-16383
f2025f4598129657080ce20c5245e5f32826a82f 13.92.131.54:13003 slave 7bcc3b5ed05803612fe5d10dafae1f36265d1c8a 0 1461650178246 3 connected
296c22cc2e43eae9d77a4af231248cfb7b19ec55 13.92.131.54:13001 slave 03d403829551ba90709ac055ee31d8abb9019317 0 1461650178669 2 connected
03d403829551ba90709ac055ee31d8abb9019317 13.92.131.54:13000 master - 0 1461650177153 1 connected 0-8191
**testpremium.redis.cache.windows.net:6379>**

**Comment by marcosnils** [comment]
@xingzhougmu in that case current Jedis version should work correctly if you can connect to the server without a password. 

Take into account that Jedis **needs** to be able to connect to the ip's that you see in the `cluster slots` outputs, so the machine that is running your Java code should be able to connect to the Redis instances in those ip's.

**Comment by xingzhougmu** [comment]
@marcosnils No. If I connect without password key, the "cluster slots" commands will fail.

PS C:\Program Files\Redis> .\redis-cli.exe -h testpremium.redis.cache.windows.net -p 6379
testpremium.redis.cache.windows.net:6379> cluster slots
(**error) NOAUTH Authentication required.**
testpremium.redis.cache.windows.net:6379>

**Comment by marcosnils** [comment]
@xingzhougmu what I was saying is that you need to disable authentication in your Redis cluster because JedisCluster still doesn't have support for auth. I've included in #1269 as I said before. 

If you disable password, it should work.

**Comment by xingzhougmu** [comment]
@marcosnils okay. Got you now! I will wait for the next release as Microsoft does not allow me to disable authentication in Azure Redis Cluster.

Really appreciate your help.

**Comment by HeartSaVioR** [comment]
About inconsistency IPs between `cluster slots` and `cluster nodes` should be corrected with setting up announce IP via Redis side.
https://github.com/antirez/redis/issues/2527

It's planned to be introduced on Redis 3.2.

**Comment by marcosnils** [comment]
@xingzhougmu if you need to play around with it you can merge my PR manually until it gets release (it might take some time)

**Comment by xingzhougmu** [comment]
@marcosnils sure. I will take a try from my side, and report back how it works for me.
where can I pull your PR?

**Comment by marcosnils** [comment]
@xingzhougmu you can use this branch https://github.com/xetorthio/jedis/tree/cluster_password, and run `mvn package -DskipTests` from the project root.

**Comment by marcosnils** [comment]
It will probably fail because of javadocs. Try instead: `mvn package -DskipTests -Dmaven.javadoc.skip=true`

**Comment by xingzhougmu** [comment]
@marcosnils compile result.

Tests run: 473, Failures: 1, Errors: 426, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:07 min
[INFO] Finished at: 2016-04-26T15:39:39+08:00
[INFO] Final Memory: 27M/441M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.
19.1:test (default-test) on project jedis: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\xingzhou\Downloads\jedis-cluster_password\targe
t\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption

**Comment by marcosnils** [comment]
@xingzhougmu use the command I've sent you before to skip tests.

**Comment by xingzhougmu** [comment]
@marcosnils did you mean this command line "  mvn package -DskipTests -Dmaven.javadoc.skip=true "?
It failed as well.

**Comment by marcosnils** [comment]
Can you paste the error please?

**Comment by xingzhougmu** [comment]
@marcosnils looks like I got the same error message for both.

**mvn package -DskipTests -Dmaven.javadoc.skip=true **
Tests run: 473, Failures: 1, Errors: 426, Skipped: 0

[INFO] ------------------------------------------------------------------------
 [INFO] BUILD FAILURE
 [INFO] ------------------------------------------------------------------------
 [INFO] Total time: 04:07 min
 [INFO] Finished at: 2016-04-26T15:39:39+08:00
 [INFO] Final Memory: 27M/441M
 [INFO] ------------------------------------------------------------------------
 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.
 19.1:test (default-test) on project jedis: There are test failures.
 [ERROR]
 [ERROR] Please refer to C:\Users\xingzhou\Downloads\jedis-cluster_password\targe
 t\surefire-reports for the individual test results.
 [ERROR] -> [Help 1]
 [ERROR]
 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
 ch.
 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
 [ERROR]
 [ERROR] For more information about the errors and possible solutions, please rea
 d the following articles:
 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
 eption

**mvn package -DskipTests **
Tests run: 473, Failures: 1, Errors: 426, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:19 min
[INFO] Finished at: 2016-04-27T10:19:26+08:00
[INFO] Final Memory: 19M/474M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.
19.1:test (default-test) on project jedis: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\xingzhou\Downloads\jedis-cluster_password\targe
t\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption

**Comment by marcosnils** [comment]
@xingzhougmu seems like tests are running anyway. Can you try with the flag -Dmaven.test.skip=true ?

**Comment by xingzhougmu** [comment]
@marcosnils yes, by skip the tests I can compile successfully.
Could you please provide an example on how to use it?

You can test with my test redis account.
DNS name: testpremium.redis.cache.windows.net
Non-SSL Port: 6379
Password: CxDZ1/oUEBoE86iQQaGwMtEmJ5K08V4vHuL3iCga/Pk=

Cheers,
Xing

**Comment by marcosnils** [comment]
Here's an example about how to initialize JedisCluster with a password https://github.com/xetorthio/jedis/blob/cluster_password/src/test/java/redis/clients/jedis/tests/JedisClusterTest.java#L132

**Comment by ultracap** [comment]
Does Jedis also support Azure Redis Cluster with SSL connection?

**Comment by marcosnils** [comment]
@xingzhougmu I totally forgout about this. What's the status?

**Comment by yogeshbelur** [comment]
@marcosnils I still didn't get how to resolve this. #1274 

cluster-announce-ip - is supported in latest version?
If so can u tell me how to use?
 
https://github.com/antirez/redis/issues/2527

**Comment by jamespedwards42** [comment]
@yogeshbelur I don't see 'cluster-announce-ip' in the [3.2 branch conf] (https://github.com/antirez/redis/tree/3.2/redis.conf) of Redis but maybe he will merge it from [unstable](https://github.com/antirez/redis/blob/unstable/redis.conf#L838) before it is released within the next week before redis conference.

You can reference this docker file [jamespedwards42/alpine-redis-testing:unstable](https://github.com/jamespedwards42/alpine-redis-testing/blob/master/integ/unstable/Dockerfile) if you want to go ahead and test it out.  Other than that, it should be independent of Jedis. 

Here is an example of how I use that docker image to spin up a cluster for integration testing:
[startRedis.sh](https://github.com/jamespedwards42/jedipus/blob/master/scripts/startRedis.sh)
