### ISSUE TITLE
JedisPubSub doesn't support ping/pong exchanges

### ISSUE THREAD

**Issue by Anisotrop** [xetorthio/jedis#1279]
### Expected behavior

When having a pubsub subscribed to a channel it is useful to have the connection also exchange ping/pong messages. A discussion can be seen in the redis [repository](https://github.com/antirez/redis/issues/420). It would be expected that pong responses are not rejected with "Unknown message type: " exception.

### Actual behavior

An exception is thrown:
```Java
redis.clients.jedis.exceptions.JedisException: Unknown message type: [B@125b163
    at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:149)
    at redis.clients.jedis.JedisPubSub.proceedWithPatterns(JedisPubSub.java:95)
    at redis.clients.jedis.Jedis.psubscribe(Jedis.java:2608)
    [...]
```

### Steps to reproduce:

1. Create a JedisPubSub with any necessary overrides (jedisPubSub)
2. Create a Jedis instance (jedisClient)
3. On thread 1 call jedisClient.psubscribe(jedisPubSub, patterns);
4. On thread 2 call jedisClient.ping();

#### Jedis version:
2.7+
#### Redis version:
2.8.19
#### Java version:
openjdk version "1.8.0_91"

Will add a pull-request that should fix this issue by allowing pong to be received and calling a new onPong abstract method.

**Comment by Anisotrop** [comment]
Adding the [PR](https://github.com/xetorthio/jedis/pull/1280)

**Comment by Anisotrop** [comment]
@marcosnils I have added the new [PR](https://github.com/xetorthio/jedis/pull/1281) for master branch. Nevertheless it would be useful to have it backported to older branches since we currently use 2.7 (upgrading to 2.8) and there seem to be some breaking changes between those versions and 3.x. I am trying to prepare pull requests for these branches, is this ok with you ?

**Comment by Anisotrop** [comment]
Adding also [PR for 2.8](https://github.com/xetorthio/jedis/pull/1282) and [PR for 2.9](https://github.com/xetorthio/jedis/pull/1283)

**Comment by Anisotrop** [comment]
marcosnils @HeartSaVioR  Thanks for merging, I think the issue can be closed. Are you waiting for the release of commons pool 2.4.3 that fixes the issue related to:  https://github.com/xetorthio/jedis/pull/1158 before releasing 2.8.2 ? Do you have any other release planned in the near future ?

**Comment by HeartSaVioR** [comment]
Oh my I actually forgot [POOL-303](https://issues.apache.org/jira/browse/POOL-303).
Seems like it's resolved, so while I'd like to take a look to see further work on #1158, I also would like to wait for releasing Commons Pool 2.4.3 before releasing any minor/major versions.
@marcosnils What do you think?

**Comment by marcosnils** [comment]
@HeartSaVioR definitely. Let's wait on 2.4.3 before releasing!.

**Comment by HeartSaVioR** [comment]
@marcosnils FYI: I left a mail to request new release for Commons Pool 2.4.3.

**Comment by marcosnils** [comment]
@HeartSaVioR you're da man!

**Comment by mehar** [comment]
As Jedis is not threadsafe, would the ping/pong work with two threads? Would it case any issues with req/resp?
