### ISSUE TITLE
Jedis doesn't support the BITFIELD command

### ISSUE THREAD

**Issue by fabiopedrosa** [xetorthio/jedis#1284]
This is a very useful command that has not yet made its way into jedis. Could someone add it please?

**Comment by marcosnils** [comment]
@fabiopedrosa what about crafting a PR to add this command into Jedis?

**Comment by smadasu** [comment]
@marcosnils I am working on a PR to add this command. I will submit it soon.

**Comment by biagionicp** [comment]
With the BITFIELD command you can essentially create an array of n-byte integers, where n is a constant.  Is there a Jedis command in the works that would retrieve that array as an integer array/list?

**Comment by marcosnils** [comment]
@biagionicp https://github.com/xetorthio/jedis/pull/1297

**Comment by HeartSaVioR** [comment]
It's resolved from #1297
