### ISSUE TITLE
hgetAll return hashMap muddled

### ISSUE THREAD

**Issue by qw2283345** [xetorthio/jedis#1286]
what to return data by order

**Comment by marcosnils** [comment]
Since when hashes preserve order?

**Comment by qw2283345** [comment]
redis's original command—hgetAll would return ordered data,  but jedis returned a unordered hashMap, I hope that jedis hgetAll command would return an ordered map. I think it's very necessary. My English is poor, please don't mind. Thx.

> public static final Builder<Map<String, String>> STRING_MAP = new Builder<Map<String, String>>() {
    @SuppressWarnings("unchecked")
    public Map<String, String> build(Object data) {
      final List<byte[]> flatHash = (List<byte[]>) data;
      final Map<String, String> hash = new HashMap<String, String>();// this is return hashMap ,hope update ordered map
      final Iterator<byte[]> iterator = flatHash.iterator();
      while (iterator.hasNext()) {
        hash.put(SafeEncoder.encode(iterator.next()), SafeEncoder.encode(iterator.next()));
      }

      return hash;
    }

**Comment by HeartSaVioR** [comment]
@qw2283345 
Do you have any pointers or clues that hgetall returns pairs ordered? Because hash is naturally unordered, and by definition, making result unordered once again also doesn't hurt.

**Comment by marcosnils** [comment]
I've searched through the redis documentation and it doesn't say anything about hashes being ordered by any criteria at all. By nature, hashes as a data structure doesn't have an order. @qw2283345 if you want to have an ordered hash you'll have to wrap it around a SortedSet or something.

**Comment by qw2283345** [comment]
yep, thanks for your answer @marcosnils @HeartSaVioR . Using a SortedSet or others can order the data. But I am wondering if we can make the data ordered BEFORE I retrieve them.

**Comment by marcosnils** [comment]
@qw2283345 there's no "native" way of getting ordered results. However you have two ways of doing this before retrieving the results if this is a MUST.

1 - Subclass Jedis and override the `hgetall method`
2 - You can do it yourself by using the client directly as follows:


```java
  Jedis j = new Jedis();
    j.getClient().hgetAll("key");
    Map<String, String> ordered = getOrderedMap(j.getClient().getBinaryMultiBulkReply());


  }

  private static Map<String,String> getOrderedMap(List<byte[]> reply) {
    final List<byte[]> flatHash = (List<byte[]>) reply;
    final Map<String, String> hash = new TreeMap<String, String>();
    final Iterator<byte[]> iterator = flatHash.iterator();
    while (iterator.hasNext()) {
      hash.put(SafeEncoder.encode(iterator.next()), SafeEncoder.encode(iterator.next()));
    }

    return hash;
  }
```

**Comment by qw2283345** [comment]
thanks a lot, it helped! @marcosnils love you
