### ISSUE TITLE
Jedis client version to use for JDK 1.6, ibm webpshere runtime

### ISSUE THREAD

**Issue by lavinahum** [xetorthio/jedis#1291]
### Expected behavior
IBM Websphere 7 java code using jedis client in order to set and get cached values

### Actual behavior
Garbage Collector is working non stop!

### Redis / Jedis Configuration
Default JedisPool values
Using ibm com.ibm.ws.jpa.jar instead of commons-pool-1.6.jar

### Questions
What is the lowest version to use in order to avoid performence issues as this?
Or
What are the preffered JedisPool configuration values for high performence and scalibilty?

#### Jedis version:
2.1.0
#### Java version:
1.6

**Comment by HeartSaVioR** [comment]
Hi @lavinahum,
We surely recommend users to update Jedis as latest release. Latest release is 2.8.1, and 2.1.0 is released at May, 2012, 4 years ago. We also no longer use commons-pool 1.6, we use 2.x now.

**Comment by lavinahum** [comment]
Thanks for the reply!

Since i must use JDK 1.6,  should'nt be a problem using jedis 2.8.1?

I tried using the 2.6.x version with commons-pool 2.4.2, but catched a NoClassDefError runtime exception of 
"org.apache.common.pool.impl.GenericObjectPool".
 is that class still in indirect use?

**Comment by HeartSaVioR** [comment]
No we're still building Jedis with JDK 1.6. We plan to bump the JDK version to 7 starting at 3.0.0.

Maybe other place still use commons-pool 1.x and it's hidden from commons-pool 2.x what Jedis provides. Please check your dependency tree and see what libraries/frameworks depend on commons-pool.

**Comment by HeartSaVioR** [comment]
I guess it can be closed.

**Comment by lavinahum** [comment]
thanks!

2016-08-19 2:29 GMT+03:00 Jungtaek Lim <notifications@github.com>:
