### ISSUE TITLE
Pool not open at assertOpen(BaseGenericObjectPool.java:662)

### ISSUE THREAD

**Issue by DongAaron** [xetorthio/jedis#1294]
Hi,
My application use Zset as a delay queue implementation.
I catch the exception:
java.lang.IllegalStateException: Pool not open at assertOpen(BaseGenericObjectPool.java:662)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:412)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
        at redis.clients.util.Pool.getResource(Pool.java:48)

But my application can zadd data and that redis Zset had the data.
I was puzzled.
I used version 2.8.0.
Please help me.

**Comment by marcosnils** [comment]
@DongAaron how are you using `JedisPool`?.

**Comment by marcosnils** [comment]
Have you checked https://github.com/xetorthio/jedis/issues/1159?

**Comment by DongAaron** [comment]
@marcosnils  
I used JedisPoll the following:
@Component
public class RedisUtil {
	
	private static final Logger LOG = LoggerFactory.getLogger(RedisUtil.class);
	
	@Autowired
	private JedisPool jedisPool;
    
    private Jedis getJedis() {
        try {
            if (jedisPool != null) {
                Jedis resource = jedisPool.getResource();
                return resource;
            } 
        } catch (RuntimeException e) {
            e.printStackTrace();
            throw e;
        }
		return null;
    }

    private void returnResource(final Jedis jedis) {
        if (jedis != null) {
        	jedis.close();
        }
    }

    public void destroyPool() {
        synchronized (jedisPool) {
            if (jedisPool != null) {
            	jedisPool.destroy();
            }
        }
    }

But the destroyPool() no calls

**Comment by marcosnils** [comment]
@DongAaron clearly someone is trying to retrieve stuff from the pool after `destroyPool` has been closed. I'd suggest debugging the code to see where that might be happening.

**Comment by marcosnils** [comment]
I'll close this issue for now. Please reopen if you have more info or a way to reproduce it.

**Comment by likaiqing** [comment]
I also have the case when I reused a cleared pipeline by accident with redis server version 2.8.19, but with redis server version 2.8.22 it is sucessful

**Comment by anujpradhaan** [comment]
> @DongAaron clearly someone is trying to retrieve stuff from the pool after `destroyPool` has been closed. I'd suggest debugging the code to see where that might be happening.

Saved me a lot of time :)
