### ISSUE TITLE
About AUTH problem in latest Redis version 3.2

### ISSUE THREAD

**Issue by lekko1988** [xetorthio/jedis#1295]
### Expected behavior
bar

### Actual behavior
ERROR MSG:

Write here what happens instead ...
My code as bellow:
		Set<HostAndPort> jedisClusterNodes = new HashSet<HostAndPort>();
		jedisClusterNodes.add(new HostAndPort("120.55.91.36", 7001));
		JedisCluster jc = new JedisCluster(jedisClusterNodes);
		jc.auth("****");
		jc.set("foo", "bar");
		String value = jc.get("foo");
		System.out.println(jc.get("key"));
		System.out.println(value);

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random

I think jc.auth  is not supported by Jedis in cluser enviornment.
Will be supported in Jedis 3.0 or above?

#### Jedis version:
2.8.0
#### Redis version:
3.2
#### Java version:
1.8.0

**Comment by marcosnils** [comment]
This is waiting  for #1269
