### ISSUE TITLE
Removing X objects from redis server with jedis client using the same prefix key as pattern

### ISSUE THREAD

**Issue by lavinahum** [xetorthio/jedis#1298]
Hello!

What is the best practice of deleting\removing many object\values from the redis server using jedis client?

I have a fix prefix for my keys, is there a pattern usage for del command?

Thanks in advance,
Lavi

#### Jedis version:
2.6.3

#### Redis version:
3.0.6

#### Java version:
1.6

**Comment by marcosnils** [comment]
Please address this to the mailing list http://groups.google.com/group/jedis_redis
