### ISSUE TITLE
ModuleTest make redis crash in some platforms and travis.

### ISSUE THREAD

**Issue by marcosnils** [xetorthio/jedis#1315]
Tests are not passing in CI

More info here: https://github.com/xetorthio/jedis/pull/1297#issuecomment-224745290

**Comment by marcosnils** [comment]
@HeartSaVioR seems like ModuleTest was breaking the build as you discovered. I'll omit those tests in travis for the moment until we investigate. I'll try to reproduce the issue in my local env maybe changing the alloc library or something.

**Comment by marcosnils** [comment]
https://travis-ci.org/xetorthio/jedis/jobs/136287842

**Comment by jamespedwards42** [comment]
I've been having the same issue with tests failing following my module test. I just removed MODULE UNLOAD and everything works again.... I don't think anything is wrong with your module test either, just module unload corrupting the Redis server.

Posting here to try to help with getting closer to the root cause and I figure you guys will be more likely to capture the attention of antirez with this issue.

**Comment by HeartSaVioR** [comment]
Recently one contributor of Redis submitted related fix and antirez merged it. Maybe we can experiment resurrection of module test and see latest unstable branch doesn't have this issue.

**Comment by jamespedwards42** [comment]
@HeartSaVioR I checked with a build against the redis unstable branch [as of today](https://hub.docker.com/r/jamespedwards42/alpine-redis-testing/builds/bkr9f5qm7jlwlcojiadxf/), but still seeing the same issue.

**Comment by marcosnils** [comment]
I can't reproduce the problem in my machine. Not sure what the issue might
be.

@jamespedwards42 are you running in Mac?

sent from mobile

**Comment by jamespedwards42** [comment]
@marcosnils Yes, I am running Mac, but I'm using docker for mac and therefore my Redis instances are running in Alpine linux, so it appears to be a linux issue, considering it is failing on travis as well.

**Comment by marcosnils** [comment]
@jamespedwards42 I could reproduce with docker. Awesome!.

**Comment by marcosnils** [comment]
@jamespedwards42 false alarm I mapping ports propertly :angry:

**Comment by marcosnils** [comment]
@jamespedwards42 willing to run some steps to help me reproduce?

**Comment by marcosnils** [comment]
Fixed by: a911ff6cc87fa430dac4cbe0017633796907b839

Thx everyone for your support.
