### ISSUE TITLE
Not extend Junit Assert classes in Tests.

### ISSUE THREAD

**Issue by smadasu** [xetorthio/jedis#1316]
### Expected behavior

Asserts from Junit must be used statically
### Actual behavior

All the tests extend from Assert but do not override anything. This leads to tight coupling and fragile code. Moreover Jedis resources are not closed properly in tests, which could have been the reason for recent Travis failures. But for these changes I will create a new issue.
### Steps to reproduce:

This is a test enhancement

**Comment by sazzad16** [comment]
Resolved by #1331
