### ISSUE TITLE
 Regarding JedisPool timeout

### ISSUE THREAD

**Issue by PriyankaRanjan** [xetorthio/jedis#1317]
Hi Experts
We are using jedis 2.8.1 If i understand correctly the Jedispool connection object should wait for "timeout" period before throwing  JedisConnection exception . Is my understanding correct? if yes then what is your recommendation for choosing the right timeout value.

Thanks in advance.

**Comment by marcosnils** [comment]
Please redirect this issue to the mailing list: http://groups.google.com/group/jedis_redis
