### ISSUE TITLE
jedis.close() is not closing connection

### ISSUE THREAD

**Issue by laxmi-narayan-nitdgp** [xetorthio/jedis#1321]
### Expected behavior

Write here what you're expecting ...

### After using jedis.close() I was expecting jedis connection object to be null.

Write here what happens instead ...
It was available and i was able to connect to redis-server again with same connection object.
### Steps to reproduce:
Below code can be used to reproduce steps :-

 Jedis jedis = new Jedis("localhost");
 
       System.out.println("Connection to server sucessfully");
        
        jedis.lpush("tutorial-list", "Redis");
        jedis.lpush("tutorial-list", "Mongodb");
        jedis.lpush("tutorial-list", "Mysql");
        
        List<String> list = jedis.lrange("tutorial-list", 0, 5);
        
        for (int i = 0; i < list.size(); i++) {
        
            System.out.println("Stored string in redis:: " + list.get(i));
        }
// i closed connection here
        jedis.close();
        
// trying to get list again
        List<String> list1 = jedis.lrange("tutorial-list", 0, 5);
        
        for (int i = 0; i < list1.size(); i++) {
        // this is printing valid values
            System.out.println("Stored string in redis1:: " + list1.get(i));
        }

**Comment by marcosnils** [comment]
`close` closes the connection when using jedis in single instance mode. The thing is that if object is re-used, it will establish a new connection redis. This is how it works, you can use the `isConnected` method to check if a specified Jedis instance is connected to the server.
