### ISSUE TITLE
Tomcat thread leak,because I use jedis blpop,timeout not work 

### ISSUE THREAD

**Issue by terry19850829** [xetorthio/jedis#1324]
### Expected behavior

use tomcat shutdown.bat gracefully shutdown my webapp which use spring-data-redis and jedis client  

### Actual behavior

all threads in spring TheadPoolTaskExecutor use blpop() block forever,tomcat can not shutdown.

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. boot daemon thread which submit task implements runnable use brpop() when spring contextRefreshedEvent happen
2. shutdown tomcat
3.use jVisualVm or other tool, will see threads blocked 

### Redis / Jedis Configuration
        <bean id="poolConfig" class="redis.clients.jedis.JedisPoolConfig">
		<property name="maxIdle" value="${redis.maxIdle}" />
		<property name="maxTotal" value="${redis.maxTotal}" />
		<property name="maxWaitMillis" value="${redis.maxWaitMillis}" />
		<property name="testOnBorrow" value="${redis.testOnBorrow}" />
		<property name="jmxEnabled" value="${redis.jmx.enable}"></property>
	</bean>

	<bean id="connectionFactory"
		class="org.springframework.data.redis.connection.jedis.JedisConnectionFactory"
		p:host-name="${redis.host}" p:port="${redis.port}" p:password="${redis.pass}"
		p:pool-config-ref="poolConfig" />

#### Jedis version:
2.6.1

#### Redis version:
Redis-x64-3.0.501

#### Java version: 
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

### my thread dump

      "receivemsgdb-1" prio=6 tid=0x00000000169c7800 nid=0x2c60 runnable    [0x000000001abbe000]
      java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:152)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at java.net.SocketInputStream.read(SocketInputStream.java:108)
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:204)
	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:47)
	at redis.clients.jedis.Protocol.process(Protocol.java:131)
	at redis.clients.jedis.Protocol.read(Protocol.java:196)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:283)
	at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:219)
	at redis.clients.jedis.BinaryJedis.blpop(BinaryJedis.java:2151)
	at redis.clients.jedis.BinaryJedis.blpop(BinaryJedis.java:1998)
	at org.springframework.data.redis.connection.jedis.JedisConnection.bLPop(JedisConnection.java:1542)
	at com.raiyi.sms.service.impl.redis.RedisServiceImpl.takeFromHead(RedisServiceImpl.java:128)
	at com.raiyi.sms.service.impl.redis.RedisServiceImpl.takeFromHead(RedisServiceImpl.java:145)
	at com.raiyi.sms.util.thread.block.ReceiveMsgToCallHistory.run(ReceiveMsgToCallHistory.java:31)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

       Locked ownable synchronizers:- <0x00000007dc44f520> (a java.util.concurrent.ThreadPoolExecutor$Worker)

**Comment by terry19850829** [comment]
When I use lpop,it just work fine.

**Comment by marcosnils** [comment]
@terry19850829 makes sense because blpop blocks?. The only thing I can recommend now is to make your thread doing `blpop` timeout (http://redis.io/commands/BLPOP) so you can free your resources before shutting down the server.

**Comment by terry19850829** [comment]
@marcosnils  I do has timeout setting.But it's not work when I use tomcat shutdown.sh to stop tomcat.It just block forever. 

Here is some snippet code in jedis source code:

     public List<byte[]> blpop(byte[]... args) {
	checkIsInMulti();
	client.blpop(args);
	client.setTimeoutInfinite(); // infinite???
	try {
	    return client.getBinaryMultiBulkReply();
	} finally {
	    client.rollbackTimeout();
	}

The reason is  **client.setTimeoutInfinite()** ???

**Comment by marcosnils** [comment]
> The reason is client.setTimeoutInfinite() ???

Not really. Socket read timeout is being set to infinite because Redis will return a response after the specified timeout.

You can check this example to see how it works

```java
        final JedisPool jp = new JedisPool();
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                System.out.println("Before");
                Jedis j = jp.getResource();
                try  {
                    j.blpop(1,"lala");
                } finally {
                    j.close();
                }

                System.out.println("After");
            }
        });
        t.start();


        //Wait for BLPO
        Thread.sleep(1000);
        jp.close();

        //Wait for BLPOP
        Thread.sleep(2000);
        System.out.println("Done");
```

Q: Are you closing your pool before shutting down tomcat?. That way you make sure that new requests can't make new blpop calls.

**Comment by terry19850829** [comment]
@marcosnils I use spring-data-redis manage my jedispool,So I've not closed jedispool manually.My threads which use brpop() method is submitted to spring ThreadPoolTaskExecutor.And I set the pool use shutdownNow method when bean destroying.

Q: problem by spring-data-redis???

**Comment by terry19850829** [comment]
@marcosnils Here is some snippet code with **JedisConnectionFactory implements InitializingBean, DisposableBean, RedisConnectionFactory**

     public void destroy() {
		if (usePool && pool != null) {
			try {
				pool.destroy();
			} catch (Exception ex) {
				log.warn("Cannot properly close Jedis pool", ex);
			}
			pool = null;
		}
	}

**Comment by terry19850829** [comment]
@marcosnils  when I use Rpop() method insteadOf Brpop(),Tomcat shutdown.sh just work fine.

**Comment by marcosnils** [comment]
@terry19850829 makes sense that `rpop` works fine because it **doesn't** block` while `brpop` does. Can you show me how you're using brpop please?

**Comment by terry19850829** [comment]
@marcosnils  here is my code structure:

I has a daemon thread which submit thread to threadpool to do real business work:

      class ReceiveMsgDBThread {
      ...
      ...
      protected void run() throws Exception {
		try {
			ThreadPoolTaskExecutor executor = AppCtxUtil.getExec("receivemsgdb");
			if (executor != null) {
				executor.execute(new ReceiveMsgToCallHistory(queueName));
			}
		} catch (RejectedExecutionException e) {
			Thread.sleep(SLEEP_Millis); // sleep
		} catch (Exception e) {
			LOG.error("ReceiveMsgDBThread", e);
		}
	}

}

The **ReceiveMsgToCallHistory**  code:

public class ReceiveMsgToCallHistory implements Runnable {

	private static final Logger logger = LoggerFactory.getLogger(ReceiveMsgToCallHistory.class);

	private String queuename;

	public ReceiveMsgToCallHistory(String queuename) {
		this.queuename = queuename;
	}

	@Override
	public void run() {
		....
		try {
			//Object callStr = redisService.popFromHead(queuename);
			Object callStr = redisService.takeFromHead(1000, queuename); // block 1 second
			if (null != callStr) {
				...
			}
		} catch (Exception e) {
			logger.error("ReceiveMsgToCallHistory", e);
		}

	}
      }


The **takeFromHead(timeout,keys)** method use bLpop():

       public Object takeFromHead(int timeout, byte[]... rawKey) {
		RedisConnection connection = null;
		Object object = null;
		try {
			connection = factory.getConnection(); //RedisConnectionFactory
			List<byte[]> results = connection.bLPop(timeout, rawKey);
			if (!CollectionUtils.isEmpty(results) && results.size() > 1) {
				object = redisTemplate.getValueSerializer().deserialize(results.get(1));
			}
		} catch (Exception e) {
			logger.error("takeFromHead error.rawKKey is{}", String.valueOf(rawKey), e);
		} finally {
			if (connection != null) {
				connection.close();
			}
		}
		return object;
	}

**Comment by marcosnils** [comment]
@terry19850829 can you verify that after shutdown has been initiated the ThreadPoolExecutor is not running any more tasks?. Because you're setting a timeout to the `blpop` command so after 1 second, the response should return and the thread should finish correctly. 

I'm thinking that what might be happening is that while waiting 1 second in the `blpop` the ThreadPoolExecutor just runs a new thread and this loops forever. Maybe that's why it never finishes to shutdown.

**Comment by terry19850829** [comment]
@marcosnils  I think it's true.But when you use a theadPoolExecutor and when the shutdown method is initialted,there is always some threads running.The threadPoolExecutor can set **waitForTasksToCompleteOnShutdown=true** and wait threads to finish.But that still not work for this situation.

**Comment by marcosnils** [comment]
@terry19850829 try to check what I described in my last comment. Add some prints and make sure that the threadPoolExecutor is not running any more tasks after the shutdown has initiated

**Comment by terry19850829** [comment]
@marcosnils OK.Thanks a lot.I'll try.

**Comment by terry19850829** [comment]
@marcosnils  I have resolve this problem.My fault! The blpop() timeout unit is **second**,I just set it to 1000!!!! I have thought the timeunit is milliseconds.  Thanks a lot ,again.
