### ISSUE TITLE
Scan support for JedisClient using tagging

### ISSUE THREAD

**Issue by idans-ybrantdigital-com** [xetorthio/jedis#1325]
Though it makes sense why key scanning is not supported for jedis cluster client
Support for key scanning with tagging should work as depicted here :

http://www.paluch.biz/blog/162-iterate-over-all-keys-in-a-redis-cluster.html

Any chance it might find it's way to the JedisCluster implementation ?

10x

**Comment by marcosnils** [comment]
@idans-ybrantdigital-com patches are always welcome :)

**Comment by mp911de** [comment]
@idans-ybrantdigital-com Maybe you want to take a look [here](https://github.com/mp911de/lettuce/blob/master/src/main/java/com/lambdaworks/redis/cluster/ClusterScanSupport.java) and port it to jedis? Would be a nice addition.

**Comment by sheinbergon** [comment]
@marcosnils  , I created a minimal implementation support only TAG-prefix based scanning , it can be found in the pull request mentioned  #1327  . I interfered as little as possible with the Jedis existing code and made this exetnsion blend as naturally as possible with the rest of your code. 

I tested it and found it to be working as expected :)  Looking forward for your feedback/rejects

@mp911de  That is same great work you've done there. Once someone approves this patch , I'll find the time and port that code as well :)

**Comment by sheinbergon** [comment]
BTW , I made all of the fixes on top of 2.8 as I believe this is considered a rather minor fix . If you'd like me to apply it on some other branch , let me know

**Comment by HeartSaVioR** [comment]
@sheinbergon Hi, all of patch should be against master since all changes must be reflected to master.
Having cluster-wise command is nice, especially if it gets rid of interface difference between Jedis and JedisCluster. 
I'll have a look when I get some time. Thanks!

**Comment by idans-ybrantdigital-com** [comment]
Done by @sheinbergon  , merged by @HeartSaVioR  , will be released in 2.9

Closing
