### ISSUE TITLE
Make Jedis 2.9 available in public maven repository.

### ISSUE THREAD

**Issue by duobliu1** [xetorthio/jedis#1326]
### Expected behavior

I would like to get jedis 2.9 from public maven repository to get authentication feature. 

### Actual behavior

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

**Comment by marcosnils** [comment]
We do have some pending issues/prs before releasing 2.9. We'll release whenever it's finished.

**Comment by DonMcNamara** [comment]
@marcosnils  Any update on publishing 2.9?

**Comment by marcosnils** [comment]
Yes, it will definitely happen this week. We're just waiting for a small issue to come in.

**Comment by DonMcNamara** [comment]
Thanks!!
