### ISSUE TITLE
jedis 3.0.0-SNAPSHOT have a bug?

### ISSUE THREAD

**Issue by chengjiafeng** [xetorthio/jedis#1328]
I meet a problem where jedis gets data very slowly when server is running a period of time.
Is that because jedis version?

### Redis / Jedis Configuration
static {
    GenericObjectPoolConfig poolConfig = new GenericObjectPoolConfig();
    poolConfig.setMaxWaitMillis(3000);
    poolConfig.setMinIdle(5);
    poolConfig.setMaxIdle(200);
    poolConfig.setMaxTotal(1000);

    Integer timeout = 2000;
    Integer maxRedirections = 1;
    Set<HostAndPort> haps = parseHostAndPort();

    try {
      jedisCluster = new JedisClusterExt(haps, timeout, maxRedirections, poolConfig);
    } catch (Exception e) {
      logger.error("Redis cluster initialization error", e);
    }
  }

**Comment by marcosnils** [comment]
There's no Jedis 3.0.1 version. We can't do  a lot with this, please provide more info like thread dumps or code to reproduce the error you're seeing

**Comment by chengjiafeng** [comment]
I am very sorry . Jedis version is not 3.0.1 but 3.0.0-SNAPSHOT. I just  do a little package about jedis.auth() . 
![image](https://cloud.githubusercontent.com/assets/6769754/16444772/5244c598-3e12-11e6-899e-c6af283772b1.png)

The above is some information about  jedis geting data  slowly

**Comment by chengjiafeng** [comment]
![image](https://cloud.githubusercontent.com/assets/6769754/16444883/db668f8c-3e12-11e6-90ad-ed4eb43680d0.png)

![image](https://cloud.githubusercontent.com/assets/6769754/16444915/01c2f5f8-3e13-11e6-96b6-824823036336.png)

![image](https://cloud.githubusercontent.com/assets/6769754/16444945/1efa3a32-3e13-11e6-871d-97a792fba01c.png)

![image](https://cloud.githubusercontent.com/assets/6769754/16445210/2ad163a2-3e14-11e6-98ab-7b2b9a7f256c.png)

![image](https://cloud.githubusercontent.com/assets/6769754/16445228/3edfe526-3e14-11e6-83e1-a01685693ee3.png)


**The pictures are which I make some changes  on the basis of the original**

**Comment by HeartSaVioR** [comment]
You just removed auth which is not a solution. If you believe there're connection leak, attaching jmx and see pool metric helps us.

**Comment by marcosnils** [comment]
Or you're not returning resources to the pool correctly.

**Comment by chengjiafeng** [comment]
JedisCluster.set -----> 
![image](https://cloud.githubusercontent.com/assets/6769754/16475701/38004c9c-3eb3-11e6-874f-ede841614d12.png)
 
jedisCluster will release connection, so I do not need manager connection??
