### ISSUE TITLE
JedisSentinelPool: 'ERR max number of clients reached' kills MasterListener

### ISSUE THREAD

**Issue by werdex** [xetorthio/jedis#1329]
The issue is similar to https://github.com/xetorthio/jedis/issues/1036 
However it can happen in JedisSentinelPool.MasterListener.

Exception in thread "MasterListener-redismaster-[mysecrethost.com:26379]" redis.clients.jedis.exceptions.JedisDataException: ERR max number of clients reached
    at redis.clients.jedis.Protocol.processError(Protocol.java:117)
    at redis.clients.jedis.Protocol.process(Protocol.java:151)
    at redis.clients.jedis.Protocol.read(Protocol.java:205)
    at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:297)
    at redis.clients.jedis.Connection.getRawObjectMultiBulkReply(Connection.java:242)
    at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:108)
    at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:102)
    at redis.clients.jedis.Jedis.subscribe(Jedis.java:2591)
    at redis.clients.jedis.JedisSentinelPool$MasterListener.run(JedisSentinelPool.java:283)

JedisDataException is not catched and MasterListener thread exit.
Expected: JedisDataException must be catched and listener shall reconnect later.
#### Jedis version:

2.7.3

**Comment by sheinbergon** [comment]
I will try and inspect this 

@werdex can you please elaborate on the exact steps to reproduce ?

**Comment by werdex** [comment]
Hi,
You can try to reproduce using the following simple scenario
1) start sentinel node locally
2) create 5 pools using this sentinel node
3) stop the sentinel
4) MasterListener will try to reconnect
5) set maxclient=3 in the sentinel config, start sentinel
6) once MasterListener reconnects it will get 'max client' error and thread exit

**Comment by sheinbergon** [comment]
@werdex  Just to be sure I got it right , by 5 pools you mean 5 instances of JedisSentinelPool connecting to the same master definition , right ?

**Comment by werdex** [comment]
Yes, 5 instances of JedisSentinelPool which connects to the same sentinel instance.Each pool will create its own MasterListener to this node.

**Comment by sheinbergon** [comment]
@werdex  Created new PR , it's up to maintainers now

**Comment by idans-ybrantdigital-com** [comment]
@werdex  Though the fix is simple , I want to work on a proper test case and integrate your steps on how to reproduce the issue into it. In progress

**Comment by sheinbergon** [comment]
@werdex Though the fix is simple , I want to work on a proper test case and integrate your steps on how to reproduce the issue into it. In progress

**Comment by werdex** [comment]
Thanks.

**Comment by sheinbergon** [comment]
@marcosnils  OK , I see I can write a test that changes the max clients  in one of the sentinels to 1 via CONFIG SET , create another pool , notice the error , then set the client again , watch the issue resolve itself and change back the maxclients to the original value

I'll get  on it in the next couple of days

**Comment by marcosnils** [comment]
@sheinbergon we're about to release 2.8.2 and 2.9.0 and we'd like this issue to be included. Is there something I can help you with so we can get it in?. Thx!.

**Comment by sheinbergon** [comment]
@marcosnils the fix is easy , but if you want to include the test case , it'll take a few more days.
What's your ETA ?

**Comment by marcosnils** [comment]
We'd like to release before the weekend. Do you think you can make it?. I can help you out if you can't.

**Comment by sheinbergon** [comment]
Sorry , I've been a bit busy during the last couple of days . Maybe release this as part of the next minor ? I havn't gotten round to fixing it but will do so over the  weekend

**Comment by sheinbergon** [comment]
@marcosnils  waiting for your referrence/ideas in #1354  on how to tackle the test case

**Comment by marcosnils** [comment]
@sheinbergon I'll give it a look this week.

**Comment by edwardotis** [comment]
Any update on this bug?

**Comment by marcosnils** [comment]
@edwardotis we're waiting for @sheinbergon updates on #1354

**Comment by sheinbergon** [comment]
@marcosnils  @edwardotis  sorry for not updating on this , it's quite a hectic time for me. I'll reapply the fix during the next few days

**Comment by sheinbergon** [comment]
PR to fix has been created at #1422
