### ISSUE TITLE
Fix resource leaks and warnings in Junit tests

### ISSUE THREAD

**Issue by smadasu** [xetorthio/jedis#1332]
### Expected behavior

The Redis connections opened in unit tests should be closed properly. There are also lot of warnings in code which can be cleaned up easily
### Actual behavior

The resources are not closed properly and may cause problems in running unit tests. Unnecessary suppresswarnings etc can be cleaned up
### Steps to reproduce:

This is code enhancement
#### Jedis version:

Latest unstable
#### Redis version:

Latest unstable
#### Java version:

1.7

**Comment by smadasu** [comment]
@marcosnils , I cannot use try with resources for java7. Why is Jedis still using 1.6 version of java?

**Comment by HeartSaVioR** [comment]
We discussed about version but seems like we forgot to change. 
@marcosnils @xetorthio I guess we already discussed this - using at least JDK 7. Right?

**Comment by smadasu** [comment]
Here is part of pom.xml


		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.1</version>
				<configuration>
					<source>**1.6**</source>
					<target>**1.6**</target>
				</configuration>
			</plugin>

This uses 1.6

**Comment by smadasu** [comment]
@marcosnils @HeartSaVioR Do you think it's OK if I change as part of this pull request?

**Comment by HeartSaVioR** [comment]
Sorry I think it should be handled as another commit/issue/pull request for history.

**Comment by smadasu** [comment]
OK. I can create another PR for upgrading to 1.7. How likely is that PR merged into master? Because only   then I can fix this issue.

**Comment by marcosnils** [comment]
fixed by #1334 for master branch.

**Comment by HeartSaVioR** [comment]
Using JDK7 is just a requirement for him to use try-with-finally, and he doesn't submit pull request regarding this. @smadasu Is this correct?

**Comment by smadasu** [comment]
That is correct

**Comment by HeartSaVioR** [comment]
OK. I reopen this.

**Comment by smadasu** [comment]
Thanks

**Comment by marcosnils** [comment]
Oh, sorry I thought you meant change the jdk support only in master. Well, Oracle added an extended support for the jdk 6 until the end of 2018 so I wouldn't recommend to drop support in before that time.
http://www.oracle.com/technetwork/java/eol-135779.html

**Comment by HeartSaVioR** [comment]
Well I think we can't change JDK version even in future if we're concerning Oracle paid support. :)
For public update, even public update for **JDK 7** was end at last year (April 2015).

**Comment by sazzad16** [comment]
Closing as #1348 is closed.
