### ISSUE TITLE
Upgrade the JDK versin to 1.7

### ISSUE THREAD

**Issue by smadasu** [xetorthio/jedis#1333]
### Expected behavior

Jedis should run using JDK1.7

### Actual behavior

It still uses 1.6 accroding to pom.xml below
``
                 <plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.1</version>
				<configuration>
					<source>1.6</source>
					<target>1.6</target>
				</configuration>
			</plugin>
``
### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

#### Java version:
Upgrade to 1.7

**Comment by marcosnils** [comment]
Fixed by #1334
