### ISSUE TITLE
JedisClusterInfoCache why not use ConcurrentHashMap instead of lock

### ISSUE THREAD

**Issue by 51opensrc** [xetorthio/jedis#1337]
### Expected behavior

Why not use ConcurrentHashMap instead of Lock. When concurrency is high, performance is down quickly.

### Actual behavior

Why not use ConcurrentHashMap instead of Lock. When concurrency is high, performance is down quickly.

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.  no
2.  no
3.  no

### Redis / Jedis Configuration
redis cluster

#### Java version: jdk1.8

**Comment by marcosnils** [comment]
Because ConcurrentHashMap only locks for writing whether JedisClusterInfoCache needs to lock for both reading and writing depending on the operation.

**Comment by HeartSaVioR** [comment]
We update bunch of elements on map rather than updating one. In that case thread-safe is not achieved only use of ConcurrentHashMap.
Please raise your opinion with valid analysis. If you have fix for that it would be great.
Closing this.
