### ISSUE TITLE
Feature proposal : Integrate a more advanced logging framework

### ISSUE THREAD

**Issue by sheinbergon** [xetorthio/jedis#1340]
Though I understand the considerations of keeping Jedis lean & mean and the overall aim of not binding to specific logging frameworks in 3rd party libraries in the likes of Jedis, I find the JUL interface to be rather crude / obsolete .

Plus , it pales in comparison to other logging solutions performance wise : 

http://blog.takipi.com/the-logging-olympics-a-race-between-todays-top-5-logging-frameworks/
https://logging.apache.org/log4j/2.x/performance.html

I have very good experience with Log4J2 in other projects I use it.

@marcosnils @HeartSaVioR  was this ever discussed  ?

**Comment by xetorthio** [comment]
Never discussed before. I wonder what other big java projects are using...

**Comment by marcosnils** [comment]
It has been discussed indeed. https://github.com/xetorthio/jedis/issues/1219

**Comment by HeartSaVioR** [comment]
Yeah discussed before. Note that we're only using log to JedisSentinelPool.

**Comment by sheinbergon** [comment]
@HeartSaVioR  @marcosnils  I've gone over #1219 thoroughly , the arguments there indeed make sense ( and not surprising at all ) . 

If I were to implement an internal logger factory as @mp911de mentioned (and portrayed here  https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/logging/InternalLoggerFactory.java#L51 )   but make it a bit smartter ( like support placeholders in a unified fashion )  -

Is that something you'd be inclined to merge into jedis ? it won't effect the dependency graph and would provide  a nicer logging factory ? 

Hoping for a yes :) let me know  :)

**Comment by marcosnils** [comment]
@sheinbergon @HeartSaVioR I do agree that as Jedis / Redis is becoming more complex (with cluster and modules) it'd be nice to add logging in order to print some debug information when needed. @sheinbergon if dependency graph is kept small and adding logging doesn't require too much effort, I believe that we can include it and use it when needed.

**Comment by sheinbergon** [comment]
@marcosnils  that's great . Let's leave this issue open , I'll work on it as soon as I clear some other stuff from the table

**Comment by r0main** [comment]
Hi,

Which logging interface do you want to use ? 

I think slf4j would be the best suited for this, slf4j-api has no transitive  dependencies (https://search.maven.org/#artifactdetails|org.slf4j|slf4j-api|1.7.22|jar). Every project could then use the implementation he wants (logback, log4j2, ...).

I see there is only 3 classes using JUL it's not much work to migrate to slf4j, I would be happy to propose a pull request. Just tell me which logging interface you want to use.

**Comment by mballoni** [comment]
I agree with @r0main .
Also even if there was a lot of usage of some log library you could use the slf4j migration tool:
https://www.slf4j.org/migrator.html

**Comment by r0main** [comment]
@mballoni I didn't knew that migration tool, thanks. Anyway there are a lot of limitations with JUL that need a manual resolution. I made a pull request few days ago without the tool, feel free to review : https://github.com/xetorthio/jedis/pull/1467

**Comment by mballoni** [comment]
@r0main I saw your PR. It looks good, avoiding string concatenations and toString invocations.
 Just to see if everybody agrees with the chosen log levels.

**Comment by r0main** [comment]
@mballoni I applied this concersion table : https://www.slf4j.org/apidocs/org/slf4j/bridge/SLF4JBridgeHandler.html So people already bridging JUL with slf4j shouldn't see a difference.

**Comment by sheinbergon** [comment]
@mballoni  https://github.com/xetorthio/jedis/issues/1340#issuecomment-281170394 my point exactly

**Comment by sheinbergon** [comment]
PR is marked as merged. closing
