### ISSUE TITLE
Support IPv6

### ISSUE THREAD

**Issue by xetorthio** [xetorthio/jedis#1344]
@mp911de said:

Redis reports its host-and-port strings with `1.2.3.4:6379`
and similar for IPv6 `affe:affe:affe::1234:6379` which leaves some ambiguity to the naive reader of the string
affects `CLUSTER NODES`, `ASK` and `MOVED` redirections. Just wanted letting you know ppl starting to use Redis with IPv6-bound addresses, maybe you want to check your code for possible issues

**Comment by marcosnils** [comment]
Let's continue discussion here: https://github.com/xetorthio/jedis/pull/1342
