### ISSUE TITLE
Passing database in JedisSentinelPool Constructor

### ISSUE THREAD

**Issue by durgeshsuthar1992** [xetorthio/jedis#1345]
Passing database index as 1 in JedisSentinelPool constructor is not working.
Then I checked the code and saw  `this.database = 0;` in the constructor.

I don't understand why there is a parameter in the constructor when it will always be set to 0.

Can anyone please suggest a way we can have the pool with a different database?

I am aware of selecting database after getting resource but then we need to write again n again. Also, I am using multiple databases with diff pools corresponding to it.

Thanks

**Comment by marcosnils** [comment]
Which version are you using?

https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/JedisSentinelPool.java#L91

**Comment by sheinbergon** [comment]
@durgeshsuthar1992  I've successfully used jedis sentinel with different database indices and it works. Could you share your code and version ?

**Comment by durgeshsuthar1992** [comment]
I am using version 2.2.0.
I changed it to 2.8.1 and it is working fine now.

Thanks
