### ISSUE TITLE
Improve clusterSlots response

### ISSUE THREAD

**Issue by xetorthio** [xetorthio/jedis#1346]
### Expected behavior

Maybe `List<SlotAssignment>` where `SlotAssignment` is:
```java
class SlotAssignment {
  int start
  int end
  Node master
  List<Node> replicas
}
```

And `Node` is:
```java
class Node {
  HostAndPort net
  String key
}
```
### Actual behavior

```java
List<Object>
```

**Comment by marcosnils** [comment]
Dupe of https://github.com/xetorthio/jedis/issues/988. Let's continue on that thread.

**Comment by xetorthio** [comment]
Not sure if it is the same. The other issue is about nodes and this one
about slots.

**Comment by marcosnils** [comment]
The conversion in the thread also suggests adding slots info. I've just updated the issue title so it's more representative
