### ISSUE TITLE
Redis is taking about 4GB of RAM on startup

### ISSUE THREAD

**Issue by chinmaym7430** [xetorthio/jedis#1351]
So my Redis db has two major hashmaps. One of them contains around 1,000,000 records and the other contains 6,000,000 records. The size of the dump.rdb file is 2.395 GB.
As soon as I start the redis-server, the RAM usage by redis peaks to 4GB and remains in that state. Since my computer has 8GB RAM installed, I am not being able to insert any more records in the redis db. Every time I do that, I get a JedisConnectionException.
**Is this RAM consumption normal? Is there something I can do to reduce this?**

Here are some screenshots for your reference:
## **The RAM usage stats:-**
![image](https://cloud.githubusercontent.com/assets/18327469/16945730/e35d85b8-4dc3-11e6-9695-e24cde93c481.png)

## **The startup time for redis-db:-**
![image](https://cloud.githubusercontent.com/assets/18327469/16945750/f648cfca-4dc3-11e6-9956-149bd96936f9.png)

## **The size of the dump file:-**
![image](https://cloud.githubusercontent.com/assets/18327469/16945760/09e18252-4dc4-11e6-86fc-8fcd530412de.png)

## **This is the exception that I am getting:-**
![image](https://cloud.githubusercontent.com/assets/18327469/16946012/2cb24d88-4dc5-11e6-8127-dff58336f337.png)

## **This is the error I get when I try to insert more data:-**
![image](https://cloud.githubusercontent.com/assets/18327469/16946155/d8f03d3a-4dc5-11e6-922e-a94594dfc9d7.png)

#### Jedis version:
2.8.1
#### Redis version:
3.0.501
#### Java version:
1.7.079

**Comment by HeartSaVioR** [comment]
Please use Redis user group instead.
