### ISSUE TITLE
throw specialized exception for NOSCRIPT answer

### ISSUE THREAD

**Issue by smagellan** [xetorthio/jedis#1352]
### Expected behavior

Jedis should throw specialized exception(e.g. JedisNoscriptDataException) if evalsha answers with NOSCRIPT ('NOSCRIPT No matching script. Please use EVAL.').
Caller should retry with eval in this case

### Actual behavior
Generic JedisDataException is thrown. So the only way to catch NOSCRIPT at the client side is to use 
```java
try {
   ret = cluster.evalsha(sha1Digest, keys, args);
} catch (JedisDataException ex) {
   if (ex.getMessage().startsWith("NOSCRIPT")) {
       //retry with eval + lua script body
   }
}
```
I suppose best way to improve it is to modify redis.clients.jedis.Protocol.processError. I can prepare PR if such solution is acceptable

**Comment by HeartSaVioR** [comment]
Closed by #1353
