### ISSUE TITLE
Can't compile from source, whilst following Wiki.

### ISSUE THREAD

**Issue by camdenorrb** [xetorthio/jedis#1355]
Mvn package results - https://pastebin.com/i6FHRm9G

This was a clean clone from the repo, not sure how I should go about this issue.

**Comment by camdenorrb** [comment]
Solved, used "mvn package -DskipTests" this should be added to the Wiki.

**Comment by marcosnils** [comment]
@camdenorrb wiki is open, you can go ahead and add the change :D
