### ISSUE TITLE
Undocumented timeout units

### ISSUE THREAD

**Issue by mcandre** [xetorthio/jedis#1359]
I can't quickly identify which unit of time Jedis measures `int timeout` in. The documentation doesn't appear to clarify.

Are Jedis timeouts understood to be milliseconds (ms)? In any case, please update the javadocs to clear this up.

**Comment by marcosnils** [comment]
@mcandre Jedis is just a library around redis commands. So the command parameters **should** match the same unit the redis commands are. If you find a specific error please report it or as Jedis is an OS project, we encourge you to submit a PR to fix or clarify any documentation.

**Comment by mcandre** [comment]
Please don't leave time unit information unspecified, it's a frequent cause of bugs.

**Comment by marcosnils** [comment]
@mcandre I still don't know which `timeout` parameter you're referring to. Can you submit a PR with th proper javadoc to fix this?

**Comment by mcandre** [comment]
I respect that jedis is a pass-through API, but time units are a famously critical yet ambiguous detail. I'm referring to the undocumented unit of time used by the `timeout` parameter in several [rj]edis commands. For example:

http://javadox.com/redis.clients/jedis/2.2.0/redis/clients/jedis/Jedis.html#blpop(int, java.lang.String...)

In fact, the Redis documentation says that timeouts are in units of seconds:

http://redis.io/commands/blpop#blocking-behavior

But I had to do some digging in order to determine this specific answer, where other coders would likely just guess.

If Jedis will not clarify time units in the interest of being "pass-through", then please at least link back to the equivalent Redis command documentation pages in the javadocs, e.g.:

http://redis.io/commands/blpop#blocking-behavior

**Comment by marcosnils** [comment]
@mcandre those javadocs are extremely outdated, these are the official and latest ones: 

http://xetorthio.github.io/jedis/redis/clients/jedis/Jedis.html#blpop-int-java.lang.String...-

On the other hand, in that link that you sent that specific function **IS** documented in jedis and it clearly states that the blocking timeout is in seconds

> When blocking, if a non-zero timeout is specified, the client will unblock returning a nil special value if the specified amount of seconds passed without a push operation against at least one of the specified keys.

I'm aware that some other commands are not documented accordingly. As a rule of thumb, if you don't get the documentation from Jedis, just look into the redis doc, that shouldn't take more than a minute. 

As a last comment, as you're using the library and finding these missing spots, it'd be awesome if you could also contribute back by adding some javadocs
