### ISSUE TITLE
Running Redis commands in Jedis

### ISSUE THREAD

**Issue by darionyaphet** [xetorthio/jedis#1363]
### Expected behavior

Running redis command in jedis . such as input a string "get key" or "set key val" and I don't want to split command into tokens .

### Actual behavior

I'm not sure is there any way to support this one ?

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

**Comment by marcosnils** [comment]
You can't do this as of today. The closest that you can do is the Protocol.sendCommand function (https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/Protocol.java#L83) but that still requires that you specify a Protocol parameter.
