### ISSUE TITLE
jdeis method incyBy is an Atomic operation?

### ISSUE THREAD

**Issue by lijunyong** [xetorthio/jedis#1364]

**Comment by marcosnils** [comment]
@lijunyong Jedis instances shouldn't be shared across threads, so yes. It's an atomic opereation.

**Comment by lijunyong** [comment]
@marcosnils I have a redis id generator,take redis system time and incy key. when jedis was in distributed system, produce repeated id.

**Comment by marcosnils** [comment]
@lijunyong please post this issue in the Jedis mailing list here: http://groups.google.com/group/jedis_redis and try to provide an example that reproduces the problem

**Comment by lijunyong** [comment]
@marcosnils I send the post need to audit,the source code[https://github.com/lijunyong/redis-id-generator](url)
