### ISSUE TITLE
JedisPool getResource consumes too much time

### ISSUE THREAD

**Issue by sd4324530** [xetorthio/jedis#1373]
### Expected behavior

Write here what you're expecting ...

### Actual behavior

Write here what happens instead ...

when many thread (less than the pool config "MinIdle") run this code "Jedis jedis = pool.getResource()"
then it sometimes consumes too much time.
JedisPoolConfig's MaxWaitMillis does not work.

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

### Redis / Jedis Configuration
JedisPoolConfig config = new JedisPoolConfig();
        config.setMaxIdle(30);
        config.setMaxTotal(50);
        config.setMinIdle(20);
        config.setMaxWaitMillis(100);
        config.setTestOnBorrow(true);
#### Java version:
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

**Comment by sd4324530** [comment]
2016-08-23 10:05:11.762 [pool-1-thread-3] DEBUG c.h.platform.kredis.agent.commond.RedisCommand - numActive:1
2016-08-23 10:05:11.762 [pool-1-thread-3] DEBUG c.h.platform.kredis.agent.commond.RedisCommand - numIdle:19
2016-08-23 10:05:11.762 [pool-1-thread-3] DEBUG c.h.platform.kredis.agent.commond.RedisCommand - numWaiters:0
2016-08-23 10:05:13.956 [pool-1-thread-3] DEBUG c.h.platform.kredis.agent.commond.RedisCommand - 获取jedis连接耗时:2193ms

**Comment by sd4324530** [comment]
long getResourceStart = System.currentTimeMillis();
        try (Jedis jedis = jedisPool.getResource()) {
            long getResourceTime = System.currentTimeMillis() - getResourceStart;
            log.debug("获取jedis连接耗时:{}ms", getResourceTime);

**Comment by sd4324530** [comment]
int numActive = jedisPool.getNumActive();
        int numIdle = jedisPool.getNumIdle();
        int numWaiters = jedisPool.getNumWaiters();
        log.debug("numActive:{}", numActive);
        log.debug("numIdle:{}", numIdle);
        log.debug("numWaiters:{}", numWaiters);
        long getResourceStart = System.currentTimeMillis();
        try (Jedis jedis = jedisPool.getResource()) {
            long getResourceTime = System.currentTimeMillis() - getResourceStart;
            log.debug("获取jedis连接耗时:{}ms", getResourceTime);

**Comment by marcosnils** [comment]
@sd4324530 
have you read this?

https://commons.apache.org/proper/commons-pool/apidocs/org/apache/commons/pool2/impl/BaseGenericObjectPool.html#setMaxWaitMillis-long-

in order for setMaxWaitMillis to work setBlockWhenExhausted should be set to true as well.

**Comment by sd4324530** [comment]
but blockWhenExhausted's default value is true

**Comment by marcosnils** [comment]
@sd4324530 it works as expected

Check this example

```java
public static void main(String[] args) throws InterruptedException {

        JedisPoolConfig configJedis = new JedisPoolConfig();;
        configJedis.setMaxTotal(1);
        configJedis.setMaxWaitMillis(1);
        final JedisPool pool= new JedisPool(configJedis, "localhost");

        System.out.println(System.currentTimeMillis());

        for (int i = 0; i <5 ; i++) {
            try {
                Jedis j = pool.getResource();
            } catch (Exception e) {
                System.out.println("Timeout waiting for resource " + e.getMessage());
            }
        }

    }
```

**Comment by sd4324530** [comment]
Jedis jedis = pool.getResource()
Is this method thread safe?

**Comment by marcosnils** [comment]
Yes

**Comment by a4abhishek** [comment]
FWIW
If the pool size is zero (`setMaxTotal`) and `setMaxWaitMillis` is not set then `getResource()` will wait indefinitely.

**Comment by JanakiramanChandrasekran** [comment]
I am also experiencing similar issue. I see Redis lookup is pretty fast but i see some latency when i try to get jedisclient from pool.. Sometimes it takes ~30 ms but occasionally 220 ms..  I am testing with 52 rps with configuration of 20 idle connections & 25 max connections.. Capable to handle ~600rps.. Any idea like what causes latency?
