### ISSUE TITLE
How to know the redis server is master or slave?

### ISSUE THREAD

**Issue by ansonliao** [xetorthio/jedis#1375]
Hi, 
I am a new Jedis and Redis user, and I would like to know, I have two redis IP addresses (for example, 192.168.10.10, 192.168.10.11), one of master, and another is slave, but I no idea how to know which redis server IP address is master or slave by Jedis programming, could you kindly provide some known Jedis method to check the redis's server role?

Many thanks.

**Comment by marcosnils** [comment]
@ansonliao can u please address this concern to the mailing list? Github is for issues and design discussions mainly
