### ISSUE TITLE
Maybe serious bug in JedisCluster.subscribe

### ISSUE THREAD

**Issue by TimothyZhang023** [xetorthio/jedis#1376]
I got ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / QUIT allowed in this context when using subscribe.

As we all known a connection with CLIENT_PUBSUB flag cannot process with other command like get,set ,etc..... (server.c:2448)
Usually , we get connection subscribe and then unsub it. 

When we use subscribe in JedisCluster we call runWithAnyNode . 

```
public T runWithAnyNode() {  
        Jedis connection = null;  
        try {  
            connection = connectionHandler.getConnection();  
            return execute(connection);  
        } catch (JedisConnectionException e) {  
            throw e;  
        } finally {  
            releaseConnection(connection);  
        }  
    }  
```

we release connection (return pool or desert it ) by isBroken tag in Connection.java
### Code Example

```
@Test
    public void subscribe() {    
        JedisCluster c = cluster.getClient();
        try {
            c.subscribe(new JedisPubSub() {
                public void onMessage(String channel, String message) {
                       throw new RuntimeException("sss");
                        unsubscribe();
                }
                public void onSubscribe(String channel, int subscribedChannels) {
                    assertEquals("foo", channel);
                    assertEquals(1, subscribedChannels);

                    // now that I'm subscribed... publish
                    publishOne("foo", "exit");
                }

                public void onUnsubscribe(String channel, int subscribedChannels) {
                    assertEquals("foo", channel);
                    assertEquals(0, subscribedChannels);
                }
            }, "foo");
        } catch (Exception e) {


        }

         for (int i = 0; i < 100; i++) {
                cluster.get(RandomUtil.getRamdomString());
          }
    }

```

if any Runtime Exception in onMessage it is hard to process with this situation because there is no exceptions with jedis subpub connection and connection will be return to pool....

if we unsubscribe , but there will still contains somedata in RedisInputStream and its buf[]

```
try {
          throw new RuntimeException("sss");
 } finally {
         unsubscribe();
 }
```

we will got java.lang.ClassCastException: java.util.ArrayList cannot be cast to [B
### Expected behavior

should be no exception in Test.

it never happend in single Jedis due to we can controll how to process with used jedispool .(but now we can't right? only .close() )
### Solution

Two solution we can process with it 
1.  do not return connection to pool . mark connection as broken . (it is confusing , connection is actually not broken)
1. using   unsubscribe(); in finally but we need to clear buf in RedisInputStream . so we need some modifications in RedisInputStream and Connection
### Steps to reproduce:

see example above
### Redis / Jedis Configuration

set JedisPool maxtotal=1 for test 
#### Jedis version:

All
#### Redis version:

3.0+
#### Java version:

All

**Comment by zts1993** [comment]
@marcosnils  please review this~

**Comment by marcosnils** [comment]
@zts1993 nice finding. IMHO this should be handled in the `resetState` method of `BinaryJedis` https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/BinaryJedis.java#L1821 basically unsubscribe before returning the connection to the pool as it makes no sense for other client to use that. 

@HeartSaVioR ?

**Comment by HeartSaVioR** [comment]
@marcosnils
Would just clearing buffer of inputstream and outputstream be safe? I'm not sure, since we're reusing socket. Still the safest way is discarding that instance.

**Comment by marcosnils** [comment]
@HeartSaVioR I agree that discarding the pool instance would be the safest, but we're penalizing the user performance by forcing a new resource to be created unnecessarily. I'm trying to understand why `unsubscribe` on @zts1993 example `onUnsubscribe` is not being called. I believe the problem lies there as the `unsubscribe` response never gets read back.

**Comment by zts1993** [comment]
@marcosnils  i have working on this today . i found reason . 

we send  unsubscribe(); and not waiting for response .
usually we wait unsubscribe() response in JedisPubSub.process() . but if we throw Exception from onMessage , the do-while loop in process() do not working again . so response of  unsubscribe command remains in input buffer area. 

it necessary to discard this jedis instance and create new one , but it is a safe way.
it is not safe that we just empty the buffer area because unsubscribe command should be send then blocking and wait for response.

**Comment by sazzad16** [comment]
@marcosnils @HeartSaVioR From [OP's comment](https://github.com/xetorthio/jedis/issues/1376#issuecomment-243737943), it seems like issue is in user's implementation. Close?
