### ISSUE TITLE
Jedis Exception

### ISSUE THREAD

**Issue by xtechgamer735** [xetorthio/jedis#1377]
Hello! I am trying to connect to redis in my application but I am getting a Could not get a resource from the pool jedis exception. This is the line causing the issue `Jedis jedis = read.getResource();` and read is declared as `private JedisPool read;`

Of course, the pool gets configured as:

JedisPoolConfig jedisPoolConfig = new JedisPoolConfig();
	        jedisPoolConfig.setMaxWaitMillis(1000);
	        jedisPoolConfig.setMinIdle(5);
	        jedisPoolConfig.setTestOnBorrow(true);
	        jedisPoolConfig.setMaxTotal(20);
	        jedisPoolConfig.setBlockWhenExhausted(true);
	        pool = new JedisPool(jedisPoolConfig, <ip>, <port>);

```
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:42) ~[?:?]
Caused by: java.util.NoSuchElementException: Unable to validate object
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:502) ~[?:?]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:361) ~[?:?]
	at redis.clients.util.Pool.getResource(Pool.java:40) ~[?:?]
	... 16 more
```

**Comment by xtechgamer735** [comment]
Any thoughts, feeling or other inclinations?

**Comment by HeartSaVioR** [comment]
@xtechgamer735 
Are there any other exceptions, or symptoms? And what's the version of Jedis and Commons Pool 2 in your classpath?

**Comment by xtechgamer735** [comment]
Hey! Nothing else nope, Jedis 2.4.2 and Commons Pool 2.2

**Comment by marcosnils** [comment]
@xtechgamer735 seems like you're running a super old version of Jedis. Have you tried upgrading?

**Comment by xtechgamer735** [comment]
I can give that a go thanks! Will this cause any problems with the current Jedis code since it was built on this version?

**Comment by marcosnils** [comment]
@xtechgamer735 we try to keep backwards compatibility as much as possible, but given that you're running a super old version, I'd recommend recompiling your code to prevent any API level issues.

**Comment by xtechgamer735** [comment]
Great thanks I will give this a shot when I get the chance and report back!

**Comment by xtechgamer735** [comment]
I downgraded to Redis 2.8 which fixed my problem! Thanks.
