### ISSUE TITLE
return value of JedisCluster.publish

### ISSUE THREAD

**Issue by TimothyZhang023** [xetorthio/jedis#1378]
### Expected behavior

as we all known jedis publish return value of clients subscirbe on channel . but  in cluster mode , pub information broadcast by cluster protocol , we run sub/pub on anynode which cause incorrect return value of publish
### Actual behavior

mostly return 0
#### Jedis version:

All
#### Redis version:

3.0+
#### Java version:

All

**Comment by marcosnils** [comment]
@zts1993 thx for reporting. If you run this through the redis CLI in cluster mode, what do you get in return of the publish operation?

**Comment by sazzad16** [comment]
Close due to inactivity.
