### ISSUE TITLE
TestOnBorrow & TestOnReturn can cause performance problem when using jedis cluster

### ISSUE THREAD

**Issue by sorheart** [xetorthio/jedis#1379]
### Expected behavior

Use jedis cluster,  open 10 threads, each send set command for about 10k times.
We expect it will finish quickly.
### Actual behavior

Instead it finished slowly.
And we found there is lofs of commands in the slave nodes, which is very strange because we only send set command. Then we found that slave node receive lots of ping commands.
By reading code, we found that when JedisCluster.set is called, first it will get resource from a jedis pool. And because TestOnBorrow & TestOnReturn is set, it'll actually send 3 commands (2 ping and 1 set).
### Redis / Jedis Configuration

Redis cluster
#### Jedis version:

2.8,1
#### Redis version:

3.2.0
#### Java version:

1.7.0

**Comment by jiafu1115** [comment]
@sorheart  so why do you need to both set TestOnBorrow & TestOnReturn = true, when true, it will call ping

**Comment by jiafu1115** [comment]
```
@Override
  public boolean validateObject(PooledObject<Jedis> pooledJedis) {
    final BinaryJedis jedis = pooledJedis.getObject();
    try {
      HostAndPort hostAndPort = this.hostAndPort.get();

      String connectionHost = jedis.getClient().getHost();
      int connectionPort = jedis.getClient().getPort();

      return hostAndPort.getHost().equals(connectionHost)
          && hostAndPort.getPort() == connectionPort && jedis.isConnected()
          && jedis.ping().equals("PONG");
    } catch (final Exception e) {
      return false;
    }
  }
```

**Comment by sazzad16** [comment]
Close due to inactivity.
