### ISSUE TITLE
lpushx with string array

### ISSUE THREAD

**Issue by JBearded** [xetorthio/jedis#1380]
### Expected behavior

jedis.lpushx("key", "ok", "hello");
ERR wrong number of arguments for 'lpushx' command

**Comment by marcosnils** [comment]
:D

**Comment by JBearded** [comment]
redis supports only one parameter, but jedis client using variable length parameter

**Comment by marcosnils** [comment]
@JBearded that's not what the redis doc say http://redis.io/commands/lpush

**Comment by marcosnils** [comment]
@JBearded you're right. Mind opening a PR to fix it?
