### ISSUE TITLE
Highly Concurrent read slowly

### ISSUE THREAD

**Issue by buzzchina** [xetorthio/jedis#1389]
when read the data with highly concurrency, the once time to do "JedisPool.getResource()" over 100ms. How can I solve it? 

version: jedis 2.8.2
              redis 2.8.19
              java 1.7

**Comment by marcosnils** [comment]
@buzzchina can you please provide an example snippet that reproduces the problem?

**Comment by buzzchina** [comment]
`JedisPoolConfig poolConfig = new JedisPoolConfig();
	            poolConfig.setMaxTotal(-1);
	            poolConfig.setMaxIdle(100);
	            poolConfig.setMaxWaitMillis(1000l);
	            poolConfig.setTestOnBorrow(true);
	            poolConfig.setTestOnReturn(true);
	            poolConfig.setTestWhileIdle(true);`

Hello, this is my connection pool config. The maximum connect port is infinite. When the highly concurrency will execute read command over 200ms. But when low concurrency, the time will only spend less than 20ms.  The server load I/O and RAM just use less than 50% when highly concurrency. Maybe I need check my network bandwidth because I am working on the LAN.

**Comment by marcosnils** [comment]
@buzzchina also keep in mind that default max open sockets is usually 1024. I really doubt that this is Jedis problem, you're probably hitting a bottleneck somewhere else. Can you please provide a complete snippet (main program) that reproduces the scenario?. Otherwise it's difficult to help.

**Comment by buzzchina** [comment]
We use Distributed Service Architecture, it's all base command. So we cannot provide main program. We execute thousands command per second when busy time. In this moment, the execution time unsteady. We check the redis connection only about 200. 
![image](https://cloud.githubusercontent.com/assets/4163763/18631497/e461f3b0-7ea4-11e6-85f2-f1dd892b4245.png)

**Comment by marcosnils** [comment]
> We use Distributed Service Architecture, it's all base command. So we cannot provide main program. We execute thousands command per second when busy time

?? To make a simple main program that launches X amounts of threads to replicate the amount of ops you're getting shouldn't be difficult. You don't need distributed architecture to isolate this behavior and test it. I'm sorry @buzzchina but I'll have to close this issue if no deterministic way to replicate is provided.

As Maintainers we try to do our best to help, but we don't have time to replicate users scenarios "guessing" which might be their problem as several things might be happening here. There are thousands of Jedis users that have high concurrent environments and don't have an issue, I'll recommend investigating other areas as I doubt that Jedis is the problem

**Comment by buzzchina** [comment]
OK, thank you!
