### ISSUE TITLE
Jedis.keys should not convert returned byte array to String using UTF-8

### ISSUE THREAD

**Issue by chichuExpedia** [xetorthio/jedis#1390]
### Expected behavior
Jedis.keys(pattern) should return a list of byte arrays rather than Set<String> for that Redis keys are not restricted to only string. 

### Actual behavior
In the cases of pure byte arrays, Jedis.keys return incorrect result by convert List<byte[]> to Set<String> using UTF-8 as the charset.

### Redis / Jedis Configuration
default configuration

#### Jedis version:
2.8.1

#### Redis version:
3.2.3

#### Java version:
8

**Comment by HeartSaVioR** [comment]
You can use `keys(byte[])` to call binary version of keys() and it should return the response to binary format (I mean `byte[]`).
Passing parameter to binary vs string is how Jedis separates binary version and string version.
Closing.

**Comment by chichuExpedia** [comment]
Didn't notice that, Thanks!!
