### ISSUE TITLE
Bump the version lines: 2.9 for bugfix lines and 2.10 for minor lines

### ISSUE THREAD

**Issue by HeartSaVioR** [xetorthio/jedis#1391]
Things to do: 

- move milestone 2.8.3 to 2.9.1
- create milestone 2.10.0
- change the milestone for issues / PRs

**Comment by HeartSaVioR** [comment]
Just did it by moving milestones: 2.8.3 to 2.9.1, 2.9.1 to 2.10.0.

**Comment by HeartSaVioR** [comment]
One more: Just created and pushed 2.10 branch based on current 2.9 branch.

**Comment by marcosnils** [comment]
perfect, thx @HeartSaVioR
