### ISSUE TITLE
testInvalidStartNodeNotAdded consistently fails on my local dev.

### ISSUE THREAD

**Issue by HeartSaVioR** [xetorthio/jedis#1392]
### Expected behavior

Tests run: 26, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 25.232 sec - in redis.clients.jedis.tests.JedisClusterTest

### Actual behavior

Tests run: 26, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 24.583 sec <<< FAILURE! - in redis.clients.jedis.tests.JedisClusterTest
testInvalidStartNodeNotAdded(redis.clients.jedis.tests.JedisClusterTest)  Time elapsed: 0.606 sec  <<< ERROR!
redis.clients.jedis.exceptions.JedisConnectionException: java.net.UnknownHostException: not-a-real-host
	at redis.clients.jedis.tests.JedisClusterTest.testInvalidStartNodeNotAdded(JedisClusterTest.java:616)
Caused by: java.net.UnknownHostException: not-a-real-host
	at redis.clients.jedis.tests.JedisClusterTest.testInvalidStartNodeNotAdded(JedisClusterTest.java:616)

### Steps to reproduce:

Run `make stop; make test` to OSX & JDK 1.8 env. Not sure it's failing with Linux.

#### Jedis version:

master, 2.10, 2.9 branches

#### Redis version:

unstable

#### Java version:

Oracle JDK 1.8.0_66 (JDK 1.7 passes)

**Comment by HeartSaVioR** [comment]
```
  private void initializeSlotsCache(Set<HostAndPort> startNodes, GenericObjectPoolConfig poolConfig, String password, String clientName) {
    for (HostAndPort hostAndPort : startNodes) {
      Jedis jedis = new Jedis(hostAndPort.getHost(), hostAndPort.getPort());
      if (password != null) {
        jedis.auth(password);
      }
      if (clientName != null) {
        jedis.clientSetname(clientName);
      }
      try {
        cache.discoverClusterNodesAndSlots(jedis);
        break;
      } catch (JedisConnectionException e) {
        // try next nodes
      } finally {
        if (jedis != null) {
          jedis.close();
        }
      }
    }
  }
```

It makes sense to throw JedisConnectionException when initializing Jedis instance with unknown hostname. Auth failing or clientSetname failing also throw Exception and stop discovering. We need to suppress and try next nodes as same as inner try statement is doing.

**Comment by marcosnils** [comment]
@HeartSaVioR can you check if #1402 fixes this issue?

**Comment by HeartSaVioR** [comment]
@marcosnils I'll merge #1402 and re-run the test. It could take some time.

**Comment by marcosnils** [comment]
thx @HeartSaVioR there's no rush!.

**Comment by HeartSaVioR** [comment]
@marcosnils Build passed. Great! Closing this.
