### ISSUE TITLE
Jedis connection pool was created twice and kept in JedisClusterInfoCache

### ISSUE THREAD

**Issue by Neway6655** [xetorthio/jedis#1398]
### In the low traffic period, all redis nodes' connection num should be the same

As there is minIdle configuration item in JedisPool, for a redis-cluster, all redis nodes' connection min num should be the same.

### Several redis nodes' connection num was much higher than others.

In some env, several redis nodes' connection num was much higher than others.

### Steps to reproduce:
1. using hostname:port instead of ip:port when constructing JedisCluster's HostAndPort object.
2. then you will find the configured redis host's connection num was doubled than others.

### Redis / Jedis Configuration
default configuration.

**Comment by Neway6655** [comment]
Oh, it was duplicated with this issue: https://github.com/xetorthio/jedis/issues/1229

Close it.

**Comment by qunchenmy** [comment]
：D
