### ISSUE TITLE
JedisSentinelPool like functionality but for Slaves

### ISSUE THREAD

**Issue by kgdinesh** [xetorthio/jedis#1400]
### Expected behavior
1. I'm looking for a **JedisSentinelPool** like functionality but instead of failing-over to the master, this needs to always connect to a slave (i.e., in-case our slave becomes master, move to another slave)
2. Optionally, the pool can also **round-robin** the requests to distribute the load to all the slaves in the cluster.

Has anyone implemented such a feature in Jedis?

**Comment by HeartSaVioR** [comment]
I was on the fence with this since slave is not managed to Sentinel (only master is managed to).
But if someone comes up pull request with proper handling of slave connection failure, I'd be really appreciated. I'm not going to implement it myself since Redis now has advance feature: Redis Cluster.

**Comment by marcosnils** [comment]
@kgdinesh I don't think there's an implementation for this and it's not likely that Jedis maintainers will do it. I'll just leave the issue open in case community wants to push it forwards in which case we'll have to discuss further.

**Comment by kgdinesh** [comment]
Thanks for your comments guys.

@HeartSaVioR I agree with you philosophically but since we're talking about slaves here, I'm guessing we can be tolerant to connection failures for a limited duration since mission critical apps will anyway be serviced from the master node.

I can think of two approaches on the top of my mind,

1. Periodically query the sentinel with "**SENTINEL slaves <master name>**" & update our ConnectionPool to point to these machines. (Not optimal + polling is bad)
1. Use Pub-Sub messages to identify new slaves (topic **slave**), remove downed slaves (topics **sdown**, **odown**) & remove slave that has become master (topic **switch-master**)

Please correct me if I am missing something here.

I'll be happy to submit a PR for this.

**Comment by mp911de** [comment]
`SENTINEL SLAVES <master-name>` is required to bootstrap the pool and once in a while when Sentinel publishes topology changes. Slave/Master promotion affects not only the slave pool but should affect the master (pool) as well (maybe a different ticket).

Periodical updates are IMHO not necessary as all changes are communicated reliably via Pub/Sub. You should also consider that Pub/Sub connections might break and Sentinel topology might change (Sentinel added, Sentinel down, Sentinel recovery).

**Comment by sazzad16** [comment]
Closed due to inactivity.
