### ISSUE TITLE
Data Sharding in Redis replication mode

### ISSUE THREAD

**Issue by vishalsharma13** [xetorthio/jedis#1403]
### Expected behavior

How to achieve Data Sharding in Redis replication mode through jedis
Sharding (MD5, MurmurHash)
Key-tags for sharding
Sharding with pipelining

**Comment by marcosnils** [comment]
@vishalsharma13 please post this question in the Jedis mailing list as github is for code bugs or design discussions mainly. 

http://groups.google.com/group/jedis_redis
