### ISSUE TITLE
Whether jedis client have implement the `HSTRLEN` Command ?

### ISSUE THREAD

**Issue by darionyaphet** [xetorthio/jedis#1404]
### Expected behavior

Whether jedis client have implement the `HSTRLEN` Command ? If not add this command .

### Actual behavior

I couldn't find it at `Jedis` class .

**Comment by marcosnils** [comment]
@darionyaphet a PR would be much appreciated. Thx!.

Plz don't forget to add the same command to Binary versions and Sharded / Pipeline and JedisCluster
