### ISSUE TITLE
Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool

### ISSUE THREAD

**Issue by gowrisankar22** [xetorthio/jedis#1405]
Hi,

I am getting a below issue when i am trying to connect with redis,, any idea to resolve this issue. 
Redis version 3.2.4

Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool

BRs, Gowrisankar

**Comment by sheinbergon** [comment]
Could you please provide an excerpt of your code ?
What it is exactly that you are trying to do ? 

Please provide more elaborate details on specific use cases & scenarios

**Comment by gowrisankar22** [comment]
Hi @sheinbergon , Thanks for your response.

We have created a monitoring application that connects to a Redis Server. The application is a spring based application and we are using Spring Cofiguration classes. The details of the redis server are provided by a VCAP_SERVICES environment variable (a user variable that holds the important information like hostname, username, port, etc).

The Spring Configuration class does not throw any exception, but we have noticed that while using the RedisTemplate to perform CRUD operations, we are getting a JedisConnectionException.

I tried using the redis-cli command to check if the redis instance is up, the command is working:

Here is the code snippet below:

Spring Configuration:

@Bean
	public RedisConnectionFactory redisConnectionFactory() {
		try {

			ServiceInstance redisService = fetchServiceName(ServiceNames.redis);
                     JedisPoolConfig poolConfig = new JedisPoolConfig();
                     poolConfig.setMaxTotal(10);
                     poolConfig.setMaxIdle(5);
                     poolConfig.setMinIdle(1);
                     poolConfig.setTestOnBorrow(true);
                     poolConfig.setTestOnReturn(true);
                     poolConfig.setTestWhileIdle(true);
                     poolConfig.setMaxWaitMillis(10*1000);
                     JedisConnectionFactory cf = new JedisConnectionFactory(poolConfig);
                     cf.setHostName(redisService.getHostname());
                     //to remove
                     System.out.println("redisService.getHostname() > " + redisService.getHostname());
                     cf.setPort(Integer.valueOf(redisService.getPort()));
                     System.out.println("redisService.getPort() > " + redisService.getPort());
                     cf.setPassword(redisService.getPassword());
                     cf.setUsePool(true);
                     return cf;


		} catch (Exception e) {
			/*
			 * Usually a bad practice to catch generic exceptions, but in this
			 * case the ConnectionFactory creation could give an error for
			 * various reasons.
			 */
			LOGGER.error("Redis Factory Service is not available");
			return null;
		}
	}

	@Bean
	public RedisTemplate<String, DataBean> redisTemplate() {
		// return new StringRedisTemplate(redisConnectionFactory());
		if (null == redisConnectionFactory()) {
			LOGGER.error("Redis Template Service is not available");
			return null;
		}
		;
		RedisTemplate<String, DataBean> redisTemplate = new RedisTemplate<String, DataBean>();
		redisTemplate.setConnectionFactory(redisConnectionFactory());
		return redisTemplate;

	}

DAO/Repository Code:

public Status connect() {
		Status status = null;
		RedisConnection redisConnection = null;
		try {
			// redisTemplate.
			System.out.println("redisTemplate.getConnectionFactory() " + redisTemplate.getConnectionFactory());
			redisConnection = redisTemplate.getConnectionFactory().getConnection();
			if (redisConnection!=null && !redisConnection.isClosed()) {
				status = new Status(StatusCode.OK, "", StatusOperation.CONNECT);
			} else {
				status = new Status(StatusCode.ERROR, NOT_FOUND, StatusOperation.CONNECT);
			}

		} catch (Exception exception) {
			System.out.println("Connection Exception > " + exception.getMessage());
			status = new Status(StatusCode.ERROR, exception.getMessage(), StatusOperation.CONNECT);
		} finally{
			if(redisConnection!=null){
				redisConnection.close();
			}
		}
		return status;

	}

Redis Version on server - 3.2.4
Maven pom xml dependencies

<dependency>
			<groupId>org.springframework.data</groupId>
			<artifactId>spring-data-redis</artifactId>
			<version>${spring-data-redis.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.data</groupId>
			<artifactId>spring-data-commons</artifactId>
			<version>${spring-data-commons.version}</version>
		</dependency>
		<dependency>
			<groupId>redis.clients</groupId>
			<artifactId>jedis</artifactId>
			<version>${redis.client.version}</version>
		</dependency>
		
<properties>
	<spring-data-redis.version>1.7.4.RELEASE</spring-data-redis.version>
		<redis.client.version>2.8.1</redis.client.version>
		<spring-data-commons.version>1.12.4.RELEASE</spring-data-commons.version>
</properties>

**Comment by sheinbergon** [comment]
@gowrisankar22  I think you are calling ```redisConnectionFactory``` out of spring application context
You should inject/autowire it to the bean method the way spring java configuration is intended to work

```
@Bean
public RedisTemplate<String, DataBean> redisTemplate() {
    // return new StringRedisTemplate(redisConnectionFactory());
    if (null == redisConnectionFactory()) {
        LOGGER.error("Redis Template Service is not available");
        return null;
    }
```

**Comment by gowrisankar22** [comment]
Thanks @sheinbergon , I tried with the solution that you provided, but I am still facing the same exception.

I feel that this is probably a configuration issue at the server side, as on my development windows laptop, I was able to install redis locally and run the application successfully (it is able to connect to localhost on my laptop). I used tomcat as the servlet container for the application.

My server is a docker image running on Ubuntu (14.04), Redis version 3.2.4. Do you know if any others faced this issue with a similar environment setup as mine?

**Comment by sheinbergon** [comment]
@gowrisankar22  Please paste how your code looks now after the fix , Looking again , you're injecting ```redisConnectionFactory()``` out spring context again at 

```
    RedisTemplate<String, DataBean> redisTemplate = new RedisTemplate<String, DataBean>();
    redisTemplate.setConnectionFactory(redisConnectionFactory());
    return redisTemplate;
```

This is a wrong writing paradigm ...

**Comment by zongwu233** [comment]
I  fall into  this error too.
 I use 
```
       <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
       </dependency>
```
jedis verion is 2.8.1 . 
some code :
```
@Value("${redis.host}")
private String host;
@Value("${redis.port}")
private int port;

 @Bean
    public JedisConnectionFactory redisConnectionFactory(JedisPoolConfig config) {
        JedisConnectionFactory factory = new JedisConnectionFactory();
        factory.setHostName(host);
        factory.setPort(port);
        factory.setPoolConfig(config);
        return factory;
    }
```
And  I get exception 
```
aused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused
	at redis.clients.jedis.Connection.connect(Connection.java:164)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:80)
	at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1677)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:87)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:435)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at redis.clients.util.Pool.getResource(Pool.java:49)
	... 169 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at redis.clients.jedis.Connection.connect(Connection.java:158)
	... 176 more
```
if I replace  port with 6379   in  
```
 factory.setPort(port);
```
everything is OK. 
But I debug the App  and  confirm the value of port is 6379  when execute this line .

**Comment by wellphd** [comment]
I briefly had some trouble with the exceptions listed.  In my case, the security settings in the default installation held in the redis.confs are set to protected-mode.  This mode prevents connections from IP addresses other than the loopback (127.0.0.1).  In addition, the default installation settings also filter the same.  My configuration connects from docker based machines to the physical localhost.  To reach the localhost from the docker machines the IP Address of the localhost (redis-server i.e. 192.168.xxx.xxx) must be specified in docker-based redis-client (172.18.xxx.xxx). There are two redis.conf files, one in the install-dir and another in /etc/redis.  By disabling the protected-mode, an incompatibility between the default client and the unprotected server; there is no password set in the redis-server.  A password needs to be added to the redis.conf in the /etc/redis directory.  Don't forget to either comment the IP bind command opening all addresses or add bind addresses from which connections are required.

**Comment by sheinbergon** [comment]
@zongwu233  @wellphd  you describe different scenarios which not related to jedis itself in anyway. I've been using jedis in a multitude of installations and it works fine as expected and documented

@marcosnils  I think you can close this one

**Comment by rocspread** [comment]
I have the same problem, my redis is installed in the virtual machine inside.Redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the poolI ask: Where I made a mistake, the configuration file is written in the virtual machine ip?

**Comment by jbhardwaj12** [comment]
@rocspread  Redis by default has protected mode on. 

I am using redis as a service on a remote windows machine - I had to do following modifications in redis.windows-service.conf files : 

1. comment bind to 127.0.0.1 to allow connection from all instances 
2. Set protected mode to no.

I am assuming that you are using dockers - you may may create your own docker image with no protection mode  or refer to detailed accepted answer on stackoverflow : 

http://stackoverflow.com/questions/39424559/check-connect-to-redis-running-within-docker-from-javaspring-boot-or-node-js

**Comment by devrajjmn** [comment]
@sheinbergon [https://github.com/xetorthio/jedis/issues/1405#issuecomment-253510403](url)
What is the reason to use exact above code? Because when i did as below, My connections are not getting closed and after some time I am getting `redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool` Exception. 
```@Bean
    RedisTemplate<Object, Object> redisTemplate() throws MalformedURLException {
        RedisTemplate<Object, Object> redisTemplate = new RedisTemplate<Object, Object>();
        redisTemplate.setConnectionFactory(jedisConnectionFactory());
        redisTemplate.setEnableTransactionSupport(true);
        return redisTemplate;
    }
```

**Comment by sheinbergon** [comment]
@devrajjmn if you are creating ```redisTemplate()``` as a spring, it cannot call another method like ```jedisConnectionFactory```  intended to be used as a Spring bean directly because you're breaking Spring DI/IoC flow.

**Comment by Duolaimon** [comment]
Maybe you did not start the Redis.

**Comment by wellphd** [comment]
Happy to help, is this still open?

**Comment by mindhaq** [comment]
@sheinbergon: can you elaborate on this? I have a custom filter using redis (works fine) and on top spring security using redis as a session store, and getting that JedisConnectionException.

**Comment by sheinbergon** [comment]
@mindhaq  what I meant was  he's calling  @Bean annotated methods directly from within java code whereas he's expecting to have them instantiated as spring beans, thus he should inject/autowire their value type to the method ```redisTemplate```

**Comment by viniciusccarvalho** [comment]
I bumped into this issue while having similar problems, just to make a correction @sheinbergon calling a method from a an configuration class is totally normal and does not break spring DI. So
```java
@Bean
JedisConnectionFactory cf() {
}

@Bean 
RedisTemplate redisTemplate(){
 RedisTemplate<Object, Object> redisTemplate = new RedisTemplate<Object, Object>();
        redisTemplate.setConnectionFactory(cf());
}
```

It's completely normal, Spring will proxy configuration classes with CGLIB and those methods are cached and any invocation to them will actually respect any bean initialization (post processors and stuff)

**Comment by masterBrog** [comment]
I had a `Connection refused` because my application.yml which contains the `spring.redis.host` and `spring.redis.port` properties is not automatically picked up by Jedis like it seems to be when using application.properties, therefore defaulting the host to localhost. Fixed it by manually setting the host/port on the `JedisConnectionFactory` -

```java
@Value("${spring.redis.host}")
private String host;
@Value("${spring.redis.port}")
private Integer port;

@Bean
public RedisConnectionFactory redisConnectionFactory() {
        JedisConnectionFactory factory = new JedisConnectionFactory();
        factory.setHostName(host);
        factory.setPort(port);
        return factory;
}
```
Not sure why properties in application.yml aren't picked up like application.properties. Anyone know?

Also fyi, as of writing, the official redis docker image has `protected-mode=no` so no CONFIG SET required. Can't speak for other platforms though.

**Comment by xiongben-tongxue** [comment]
You're using an extremely old Jedis version which we don't support
      
```
 <dependency>
  		<groupId>org.springframework.boot</groupId>
  		<artifactId>spring-boot-starter-data-redis</artifactId>
  		<version>1.5.13.RELEASE</version>
  	</dependency>
```

**Comment by kiansoung** [comment]
I will not make a mistake on eclipse, and I am wrong on the Idea tool. Why?

**Comment by LucasScottik** [comment]
> 
> 
> @rocspread Redis by default has protected mode on.
> 
> I am using redis as a service on a remote windows machine - I had to do following modifications in redis.windows-service.conf files :
> 
>     1. comment bind to 127.0.0.1 to allow connection from all instances
> 
>     2. Set protected mode to no.
> 
> 
> I am assuming that you are using dockers - you may may create your own docker image with no protection mode or refer to detailed accepted answer on stackoverflow :
> 
> http://stackoverflow.com/questions/39424559/check-connect-to-redis-running-within-docker-from-javaspring-boot-or-node-js

Hi!
I'm also faced with the same issue  - I try to connect from docker container (sink connector) to redis run on WSL (windows subsystem linux)
But the following instructions above doesn't help me. 
Do u have any other suggestions why I can't connect 
Maybe I need to add some network additional configurations for docker container?
