### ISSUE TITLE
Redis Healthcheck

### ISSUE THREAD

**Issue by Annapoornar** [xetorthio/jedis#1411]
Hi, I am using JedisCluster as client to connect to Redis cluster. Need to create a HealthCheck for this. 
1. As I have set of nodes as part of JedisCluster, should I iterate over each of the node and check the connection?
2. I have to add memory utilization check as part of HealthCheck. Can you please tell is there any command available for the same?

**Comment by marcosnils** [comment]
Please ask this question in the mailing list. github is used for design discussions and bugs mainly.

http://groups.google.com/group/jedis_redis
