### ISSUE TITLE
Jedis support TOUCH Command 

### ISSUE THREAD

**Issue by darionyaphet** [xetorthio/jedis#1412]
### Expected behavior

Jedis support TOUCH Command . 
### Actual behavior

I couldn't find `touch` at Jedis class .

**Comment by marcosnils** [comment]
@darionyaphet probably because the command is not implemented. What do you think about crafting a PR if you need it?

**Comment by darionyaphet** [comment]
@marcosnils I will try to implement this command :)

**Comment by marcosnils** [comment]
@darionyaphet amazing!. Let me know if you need some help or run into any issues!.

**Comment by cobbzilla** [comment]
👍 I too would love to see the `touch` command implemented

**Comment by marcosnils** [comment]
@cobbzilla PR's are welcome!.

**Comment by cobbzilla** [comment]
@marcosnils Could you point me to a similarly-simply command already in the codebase that I could use as an example? Not promising a PR but if you can guide me just a bit I might be able to... :)

**Comment by marcosnils** [comment]
@cobbzilla if you check this project PR's you can see many commands implementations. Just look for the word "command" in the PR list.

**Comment by sazzad16** [comment]
PR #1579
