### ISSUE TITLE
How do I implement SSL into a JedisPool?

### ISSUE THREAD

**Issue by camdenorrb** [xetorthio/jedis#1417]
There is no documentation on how to implement SSL to Jedis and it's kinda confusing, maybe there should be more documentation on the topic?

**Comment by marcosnils** [comment]
@camdenorrb thx for the suggestions. We don't use SSL ourselves, we implemented it because the community was asking for that feature. Would you like to contribute to Jedis by writing some wiki docs about how to use it?. I can assist you in any technical aspects that you or concerns that you might have

**Comment by camdenorrb** [comment]
I would love to :P, but first I will need to learn how to utilize it myself.

**Comment by marcosnils** [comment]
@camdenorrb did you figure out how to do it?. Any chance you can write a wiki entry about it?

**Comment by camdenorrb** [comment]
I'm just using Stunnel client and server, not sure if it is recommended tho.

**Comment by marcosnils** [comment]
@camdenorrb you shouldn't need to use stunnel to achieve ssl.

JedisPool constructor from 2.9 onwards has the option to use SSL through a URL: https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/JedisPool.java#L33 or via constructor parameters: https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/JedisPool.java#L51

Here you have a test about how to use it:

https://github.com/xetorthio/jedis/blob/master/src/test/java/redis/clients/jedis/tests/SSLJedisTest.java#L54

Let me know if you still have issues trying to use it.

**Comment by shailesh33** [comment]
Hi
I am trying to use SSL from Dyno (github.com/Netflix/dyno) client. I pre-create a bunch of connections, however none of these connections have SSL handshake done. So later when I try to use those connections, it first starts a SSL handshake however the server has timed out by then. Is there a way to initiate SSL handshake at the time of connection establishment?
for example calling socket.startHandshake() here 
https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/Connection.java#L190

**Comment by cdhutche** [comment]
How do you implement ssl with JedisSentinelPool?  I cannot find any documentation about this anywhere.  Looking at the JedisSentinelPool code I see it is creating a JedisFactory instance but passing null for ssl.
