### ISSUE TITLE
MasterListener why not use sentinelGetMasterAddrByName to check  the master host and port 

### ISSUE THREAD

**Issue by caojingui** [xetorthio/jedis#1418]
### MasterListener thread check the master host and port why not use the sentinelGetMasterAddrByName command

I am reading the source code of jedis(3.0)。  When i see the MasterListener implements, I don't know why use the pubsub to check the master host and port。 I think it is easy to use the sentinelGetMasterAddrByName command 。

1. first the jedis to connection sentinel and sub on the message。
2. finally always to close the connection, and sub message is not use。
3. if use the sub message why close the connection.

### This is my implements

```
while (running.get()) {
    try {
        j = new Jedis(host, port);
        List<String> masterAddr = j.sentinelGetMasterAddrByName(masterName);
        if (masterAddr == null || masterAddr.size() != 2) {
            continue;
        }
        initPool(toHostAndPort(masterAddr));
    } catch (JedisConnectionException e) {
        if (running.get()) {
            log.log(Level.SEVERE, "Lost connection to Sentinel at " + host + ":" + port + ". Sleeping 5000ms and retrying.", e);
            try {
                Thread.sleep(subscribeRetryWaitTimeMillis);
            } catch (InterruptedException e1) {
                log.log(Level.SEVERE, "Sleep interrupted: ", e1);
            }
        } else {
            log.fine("Unsubscribing from Sentinel at " + host + ":" + port);
        }
    } finally {
        j.close();
    }
 }
```

### Ask
if this i do write or wrong。And why author use pusSub command not use  sentinelGetMasterAddrByName。

thank you for reading。 My english is not good, if you don't understand and you know chinese , i can express in chinese。

**Comment by vattezhang** [comment]
PubSub是阻塞式调用的，再调用端关闭前，除非服务端的哨兵down掉，否则永远阻塞在订阅消息处，不会走到close。
