### ISSUE TITLE
How to add slaves to ShardedJedis (for read operations)?

### ISSUE THREAD

**Issue by porunov** [xetorthio/jedis#1419]
### Expected behavior

Reads operation forwarded to slave nodes when we are using ShardedJedis.

### Actual behavior

Reads operation forwarded only to the master nodes when we are using ShardedJedis.

### Steps to reproduce:

1. Configure 4 redis nodes
2. Make 2 nodes to be a slaves of two masters
3. Run next code (where 192.168.0.15 and 192.168.0.14 is the IPs of master nodes):

```
List<JedisShardInfo> shards = new ArrayList<JedisShardInfo>();
JedisShardInfo si = new JedisShardInfo("192.168.0.15", 6379);
si.setPassword("bTFBx1NYYWRMTUEyNHhsCg");
shards.add(si);
JedisShardInfo si2 = new JedisShardInfo("192.168.0.16", 6379);
si2.setPassword("bTFBx1NYYWRMTUEyNHhsCg");
shards.add(si2);
JedisPoolConfig jedisPoolConfig = new JedisPoolConfig();
ShardedJedisPool pool = new ShardedJedisPool(new JedisPoolConfig(), shards);

for(int i=0;i<100;i++) {
    ShardedJedis jedis = pool.getResource();
    jedis.get("a");
    jedis.get("z");
    jedis.get("foo");
    jedis.get("hello");
    pool.returnResource(jedis);
    ShardedJedis jedis2 = pool.getResource();
    jedis2);
    jedis.get("a");
    jedis.get("z");
    jedis.get("foo");
    jedis.get("hello");
    pool.returnResource(jedis2);
}

pool.destroy();
```

### Redis / Jedis Configuration
I have 4 Redis nodes which are controlled by the Redis Sentinel:
192.168.0.15 - master 1
192.168.0.16 - master 2
192.168.0.14 - slave for master 1
192.168.0.17 - slave for master 2

**Comment by marcosnils** [comment]
dup https://github.com/xetorthio/jedis/issues/790
