### ISSUE TITLE
ERR invalid expire time in psetex

### ISSUE THREAD

**Issue by terry19850829** [xetorthio/jedis#1421]
### Expected behavior

JedisConnection 

`public void pSetEx(byte[] key, long milliseconds,byte[] value) `

set expire time with TimeUnit.MILLISECONDS right.

### Actual behavior

exception with the message as this issue title suggested

### Steps to reproduce:

call API
ValueOperations  

` void set(K key, V value, long timeout, TimeUnit unit); `

set timeout > 2^31 ,TimeUnit.MILLISECONDS  . Then the expireTime will be negative.(overflow)

```
@Override
	public void pSetEx(byte[] key, long milliseconds, byte[] value) {

		try {
			if (isPipelined()) {
				doPipelined(pipeline.psetex(key, (int) milliseconds, value));
				return;
			}
			if (isQueueing()) {
				doQueued(transaction.psetex(key, (int) milliseconds, value));
				return;
			}
			jedis.psetex(key, (int) milliseconds, value);  // why  int ?????
		} catch (Exception ex) {
			throw convertJedisAccessException(ex);
		}
	}
```

#### Jedis version:

2.6.1

#### Redis version:

2.8

#### Java version:

JDK7

**Comment by aluenkinglee** [comment]
I do think this is a bug. Any value bigger than INT_MAX will cause this error... This cast is no sense.

**Comment by marcosnils** [comment]
@terry19850829 @aluenkinglee thx for reporting. Is anyone willing to open a PR to fix it?

**Comment by terry19850829** [comment]
@marcosnils  
Days before, I'm busy with my job. I  see this '@' just now. Is it a bug or not? 
I have never open PR before. Could I open one ?

**Comment by marcosnils** [comment]
@terry19850829 where is this cast?, I can't find in Jedis code.. Can you please paste the link where this line is please?

**Comment by terry19850829** [comment]
@marcosnils  It's my fault... The code is in another project spring-data-jedis 1.5.2 version.
It's not a jedis issue. 
The cast is at org.springframework.data.redis.connection.JedisConnection line 1255 and many other positions.
I'll close this.
