### ISSUE TITLE
Jedis.migrate() don't support "replace" param

### ISSUE THREAD

**Issue by guoshun0321** [xetorthio/jedis#1423]
### API probleam
As in `redis-trib.rb`, when you got a `BUSYKEY` exception, you need to replace the node using `migrate`.
![image](https://cloud.githubusercontent.com/assets/1397148/20090236/d748d1d2-a5c6-11e6-91a0-1e55132fc605.png)

In Jedis `migrate` method don't have the `replace` param.
```
public String migrate(final String host, final int port, final String key, final int destinationDb, final int timeout)
```

#### Jedis version:
jedis-2.8

**Comment by marcosnils** [comment]
@guoshun0321 as you seem to need this feature, would you like to craft a PR to include it?

**Comment by guoshun0321** [comment]
@marcosnils Sorry for not following this problem. I will have a try.

**Comment by zts1993** [comment]
i added REPLACE support for restore command , migrate should be the next . #1447 
also jedis's migrate command does not support pipeline migrate which was introduced  3.2
(but BTW migrate contains a serious issue about ttl before 3.2.6)

**Comment by marcosnils** [comment]
@zts1993 thx for the contribution. I'll try to take a look this week.
