### ISSUE TITLE
Connection failure

### ISSUE THREAD

**Issue by Gilbert2189** [xetorthio/jedis#1425]
### Expected behavior

The connection pool should perform good even under poor network condition

### Actual behavior

many connection timeout be found in logs, all connections failed, however, not every key produce such error.

`org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool`

bellow is my pool configuration
`redis.pool.maxActive=512
redis.pool.maxIdle=200
redis.pool.maxWait=1000
redis.pool.testOnBorrow=true
`
### Steps to reproduce:

Don't know how to reproduce, restart application sometimes recover, but the pool would be broken after a while.

#### Jedis version:
redis_version:2.6.10

#### Java version:
java 1.7

**Comment by Gilbert2189** [comment]
Jedis version: 2.4.0

**Comment by marcosnils** [comment]
@Gilbert2189 is there a chance you can upgrade Jedis? You're using a super old version which we are not supporting anymore.

Lots of connections bug fixes were added since 2.4

**Comment by lkwg82** [comment]
so this can be closed?

**Comment by marcosnils** [comment]
Let's close due to inactivity
