### ISSUE TITLE
I don't see any heartbeat mechanism in the souce code!!!

### ISSUE THREAD

**Issue by derekzhuo** [xetorthio/jedis#1426]
My client need to get into subscribe mode, and there is no other way to determine if the connection is still active except for using timed ping in JedisPubSub.java, is there any plan of heartbeat mechanism???

**Comment by marcosnils** [comment]
Nope, there's no plans to implement heartbeat as it's use-case specific. Please open a proper proposal so it can be discussed accordingly. This issue doesn't help

**Comment by derekzhuo** [comment]
Thanks a lot!
