### ISSUE TITLE
jedis don't support redis 3.2

### ISSUE THREAD

**Issue by caoxinyu** [xetorthio/jedis#1427]
### Expected behavior

Write here what you're expecting ...

### Actual behavior

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

**Comment by HeartSaVioR** [comment]
Please describe which points Jedis doesn't support. Our build targets even unstable branch of Redis.

**Comment by sheinbergon** [comment]
@caoxinyu  I'm working with jedis 2.9 and redis cluster 3.2 and it's A-OK for me.

**Comment by caoxinyu** [comment]
sorry, I found my problem.
