### ISSUE TITLE
Redis cluster down 

### ISSUE THREAD

**Issue by Annapoornar** [xetorthio/jedis#1432]
### Expected behavior

Tho the machine which was taken down is not up, the other nodes of cluster should have been working without any error

### Actual behavior

processing failing with cluster down

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. I have 3 machines where each machine is having one master and one slave running. The set up looks some thing like this. Where M1 has S2 as its slave, M2-> S3 and M3->S1.

M1            M2              M3

S1             S2               S3

2. Registered all the machines (3 ips with the master port as 6379) to JedisCluster client 
3. started processing data, everything was fine. But later, I stopped one of the machine, say which has M3 and S3 running on it, The processing went fine till 20 seconds (cluster-node-timeout 20000) set in redis.conf, after that the cluster state went to failure state and furhter requests started failing with cluster down.

#### Jedis version:
jedis-2.9.0
#### Redis version:
redis is 3.2.5

#### Java version:
jdk 8

**Comment by HeartSaVioR** [comment]
When Redis Cluster is marked as cluster down, no command will be allowed from Redis side so there's nothing to do for Jedis side. You need to check Redis why failover doesn't happen.

**Comment by HeartSaVioR** [comment]
Please reopen if you think Redis Cluster worked properly and you found a symptom of misbehavior of Jedis. Closing.

**Comment by Annapoornar** [comment]
Thanks for the update. It failed from redis itself. But one clarification, in general, should I configure all the nodes of the redis cluster to JedisClusterClient or one of the nodes is fine? And any pros/cons adding all the nodes of the cluster , like in above case all masters and slaves of all the 3 machines to be added to JedisClusterClient??

**Comment by HeartSaVioR** [comment]
I recommend adding all or at least some of them since they'll be used as seeds for cluster node discovery. Suppose you're specifying just one node, and the node is down. Even though Redis Cluster handles failover and the node is got rid, Jedis can't discover Redis Cluster nodes since all seed nodes are not available.
