### ISSUE TITLE
ClassCastException when trying to do del operation

### ISSUE THREAD

**Issue by thegamblerrises** [xetorthio/jedis#1437]
We are deleting some key from redis and I noticed in my logs, it is throwing ClassCastException. 

java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.Long

I read somewhere that jedis is not thread-safe and to use it in threaded environment, one should use jedispool. So, I am using jedispool to get jedis connection. However, Jedis connection is at class level.

Class MyCacheClass {

  private Jedis jedis = null;

  public MyCacheClass(){
    // RedisFactory instance
    this.jedis = redisFactory.getJedi();
  }

  public void methodA(){
    jedi.get();
   // some other operations
  }

  public void methodB(){
    jedi.del("some_key");
   // some other operations
  }
}

Is it wrong approach? I was using it at method-level, but things were getting slow. So, I thought of using it at class level to skip getting a new connection each time I call a method from same class object.

**Comment by marcosnils** [comment]
> Is it wrong approach? I was using it at method-level, but things were getting slow. So, I thought of using it at class level to skip getting a new connection each time I call a method from same class object.

Yes, you need to retrieve an instance from the JedisPool and return it after you use it. Regarding performance, that shoudln't be a problem maybe there's something else you're using that causing the slowness.
