### ISSUE TITLE
Jedis pool is acting weird

### ISSUE THREAD

**Issue by noordawod** [xetorthio/jedis#1438]
### Expected behavior

I'm expecting the eviction thread to evict idle objects.

### Actual behavior

I'm getting `Timeout waiting for idle object` while trying to call `pool.getResource()`. I deliberately wait more than eviction time so objects are properly cleared, but seems like they aren't.

### Steps to reproduce:

I have a single function that creates the pool, here it is: 

```
public static JedisPool prepareJedisPool(String hostName, String password, int port, int database) {
    final JedisPoolConfig poolConfig = new JedisPoolConfig();
    poolConfig.setBlockWhenExhausted(true);
    poolConfig.setMaxTotal(5);
    poolConfig.setMinIdle(1);
    poolConfig.setMaxIdle(3);
    poolConfig.setMaxWaitMillis(10000);
    poolConfig.setTimeBetweenEvictionRunsMillis(5000);
    poolConfig.setSoftMinEvictableIdleTimeMillis(2500);
    return new JedisPool(poolConfig, hostName, port, 10000, password, database);
}
```

### Redis / Jedis Configuration

(Just see the code above)

#### Jedis version:

2.9.0

#### Redis version:

No idea, it's the one bundled with Jedis 2.9.0.

#### Java version:

Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
CentOS Linux 3.10.0-327.36.3.el7.x86_64

**Comment by marcosnils** [comment]
> No idea, it's the one bundled with Jedis 2.9.0.

Jedis doesn't come with a redis version

**Comment by marcosnils** [comment]
Please ask this question in the mailing list. github is used for design discussions and bugs mainly. Or submit a reproducible snippet that shows the error

http://groups.google.com/group/jedis_redis
