### ISSUE TITLE
block 3~8s when one master crash down in cluster

### ISSUE THREAD

**Issue by wenxuanguan** [xetorthio/jedis#1441]
### Expected behavior

throws `JedisClusterMaxRedirectionsException("Too many Cluster redirections?")` in `BinaryJedisCluster.DEFAULT_TIMEOUT` seconds

### Actual behavior

throw exception after 3~5 seconds, 8 seconds at max

### Steps to reproduce:

1.create **3** master redis-cluster with config `cluster-require-full-coverage no`
2.loop execute command and record cost when catch `JedisClusterMaxRedirectionsException`
```java
concurrentThreadNum = 200;
....
for (long i = begin; i < nums + begin; i++) {
            start = System.nanoTime();
            try {
                if (jedisClient.set(key, value).compareTo("OK") == 0) {
                    ops.getAndIncrement();
                }
            } catch (Exception e) {
                cost = (System.nanoTime() - start) / TimeUnit.MILLISECONDS.toNanos(1);
                logger.error("latency:{} ms.", cost, e);
            }

```
3.kill one master node
4.no resource limit(say memory, CPU)

### Redis / Jedis Configuration

- redis configuration
`appendonly no`
`#save ""`
`#save 900 1`
`#save 300 10`
`#save 60 10000`
`timeout 0`
`repl-diskless-sync no`
`cluster-node-timeout 5000`
`cluster-require-full-coverage no`

- jedis cluster configuration
```java
maxTotal=50
maxIdle=30
maxWaitMs=3000
GenericObjectPoolConfig config = new GenericObjectPoolConfig();
config.setMaxTotal(maxTotal);
config.setMaxIdle(maxIdle);
config.setMaxWaitMillis(maxWaitMs);
...
JedisCluster(Set<HostAndPort> nodes, config)
```

#### Jedis version:
2.80
#### Redis version:
3.0.3
#### Java version:
7

### additional

1. change jedis cluster config `DEFAULT_MAX_REDIRECTIONS` to 3, latency reduce to 2~3 seconds.
2. debug the program, block in
```java
redis.clients.jedis.JedisClusterCommand.runWithRetries()

connection = connectionHandler.getConnectionFromSlot(JedisClusterCRC16.getSlot(key)); 
```
and then throw ``java.net.ConnectException: Connection refused`` when try to create connection with the crashed cluster node

**Comment by sheinbergon** [comment]
@wenxuanguan your cluster is configured with ```cluster-node-timeout 5000```. That means it takes at least 5 seconds for failover to takeplace. It's more likely that your code is blocking on pool exhaustion rather than cluster node connectivity. 

I can't really piece your excerpts together. If you want  to provide a fully working example, we can take it from there.

**Comment by marcosnils** [comment]
Closed due to inactivity. @wenxuanguan plz comment if you're still having issues and you need it to be reopened.
