### ISSUE TITLE
jedisCluster : how to user the password to connect the cluster

### ISSUE THREAD

**Issue by zhang19960118** [xetorthio/jedis#1442]
### Expected behavior

Write here what you're expecting ...

### Actual behavior

Write here what you're expecting ...

### Actual behavior

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

#### Java version:1.8

Caused by: redis.clients.jedis.exceptions.JedisDataException: NOAUTH Authentication required.

**Comment by marcosnils** [comment]
This has been posted before, check https://github.com/xetorthio/jedis/pull/1269
