### ISSUE TITLE
interface of redis.clients.jedis.JedisCommands  is so much method,

### ISSUE THREAD

**Issue by qintang** [xetorthio/jedis#1444]
### Expected behavior

interface of redis.clients.jedis.JedisCommands  is so much method,it's so boring！！！

Write here what you're expecting ...

### Actual behavior

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

**Comment by marcosnils** [comment]
Please don't use this channel to rant about something you don't like. Instead, we encourage users to propose solutions so everyone can benefit from it. After all, this is an OS project and nobody is getting paid to do it.
