### ISSUE TITLE
Performance Between Direct Socket and JedisCluster

### ISSUE THREAD

**Issue by joffier** [xetorthio/jedis#1445]
### Expected behavior

Performance is same between direct socket and jedisCluster

### Actual behavior

Performance is not same between direct socket and jedisCluster

### Steps to reproduce:
1. First I make a long socket connection to redis port,and send the same command 100000 times.Then i found just one or two responses are longer than 5 milliseconds.
command as follows:
		String ctl="\r\n";		
		String command="*2"+ctl+"$3"+ctl+"GET"+ctl+"$19"+ctl+"6217002020056574552"+ctl;
                OutputStream os=socket.getOutputStream();
	        InputStream is=socket.getInputStream();
	        byte[] buf=new byte[1024];
	        long start=System.currentTimeMillis();
	        long begin=System.currentTimeMillis();
			for(int i=0;i<100000;i++){
	        	os.write(command.getBytes());
	                os.flush();
	        	start=System.currentTimeMillis();
	               int length=is.read(buf);
	               if(length!=-1){
	            	long span=System.currentTimeMillis()-start;
	            	if(span>5)
	            	System.out.println("query long time:"+span);
	            }
	        }
total time:20884ms

2. Then I use the JedisCluster with one single thread and also send the same command 100000 times.But i found about 15 responses are longer than 5 milliseconds,even longer than 10 milliseconds.
                String key="6217002020056574552";
                long start=System.currentTimeMillis();
	        long begin=System.currentTimeMillis();
			for(int i=0;i<100000;i++){
	        	start=System.currentTimeMillis();
	        	String value=JedisFactory.getCluster().get(key);
	            	long span=System.currentTimeMillis()-start;
	            	if(span>5){
	            		System.out.println("query long time:"+span);
		            	System.out.println("value:"+value);
	            	}
	            	
	            }
total time:31819ms

3. So i want to know follows:
    i.If the Redis itself have fluctuation in query a key(such as avg maybe 0.2milliseconds but some may be       2 or 3 milliseconds)?
    2.What may be the reason to cause the performance difference?

Thks!

**Comment by joffier** [comment]
@sheinbergon 
Yes,you're right, JedisFactory  is my own class not the "redis.clients.jedis.JedisFactory".Code as follows:

public class JedisFactory {
private static JedisCluster cluster;
private static List<String> hostList;
private static Set<HostAndPort> list=new HashSet<HostAndPort>();
public static void init(List<String> addresslist){
	if(JedisFactory.hostList==null){
		JedisFactory.hostList=addresslist;
		for(String host:hostList){
			list.add(new HostAndPort(host.split(":")[0],Integer.valueOf(host.split(":")[1])));
		}
		JedisFactory.cluster=new JedisCluster(list);
	}
	
	
}
public static JedisCluster getCluster() {
	return cluster;
}

public static void close(){
	try {
		if(cluster!=null)
		cluster.close();
		JedisFactory.hostList=null;
	} catch (IOException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
}
}


2.I think the 'computational load' is very small, comparing to some abnormal response time.And i  add some logs in the class 'redis.clients.jedis.Connection':

public byte[] getBinaryBulkReply() {	  
    flush();
    long start=System.currentTimeMillis();
    pipelinedCommands--;
    byte[] returnByte=(byte[]) readProtocolWithCheckingBroken();
    long span=System.currentTimeMillis()-start;
    if(span>5)
    System.out.println("________________jedis get time:"+span);
    return returnByte;
   // return (byte[]) readProtocolWithCheckingBroken();
  }

Also can find about 15 responses are longer than 5 milliseconds,even longer than 10 milliseconds,in 100000 times 'get'.

So i guess if the Redis itself have fluctuation in just query a key(such as avg maybe 0.2milliseconds but some may be 5 or 6 milliseconds)?

**Comment by avram** [comment]
You could also be encountering GC pauses -- among many other differences your hand-crafted version reuses the read buffers, while the Jedis version is allocating a new string for each read. In order for this to be helpful feedback to the Jedis project, I think you'd have to provide an example of unreasonable pauses within Jedis itself, or of unneeded GC churn.

**Comment by sheinbergon** [comment]
@joffier I believe @avram input is crucial. You can always follow a guide like this https://plumbr.eu/blog/garbage-collection/understanding-garbage-collection-logs and see the GC details behavior.

Also , when benchmarking , be sure to prestart the JVM with large enough Eden + Heap and in any case,let the JVM "warm-up" ( conduct some "unmeasured" test iterations before commencing with the measured one )

**Comment by marcosnils** [comment]
I'll close this as it leads nowhere. @joffier if you make a more comprehensive and realistic test and still think that there's need for improvement in Jedis, please open a new issue. 

@avram @sheinbergon thx a lot for your feedback.
