### ISSUE TITLE
zrangeByScoreWithScores should return a LinkedHashSet or SortedSet

### ISSUE THREAD

**Issue by DanielYWoo** [xetorthio/jedis#1450]
### Expected behavior

zrangeByScoreWithScores should return a LinkedHashSet or SortedSet. Currently it returns Set which is too generic and does not tell clients it's actually *sorted*.

**Comment by sheinbergon** [comment]
@DanielYWoo  Returned type is ```Set<Tuple>``` , tuple containing both the score & the value
The actual implementation is ```LinkedHashSet<Tuple>``` giving predictable iteration order ( which based on the response from Redis which is ordered).

So let's clarify a few things :

1. Though it's a of type ```Set<Tuple>``` , iteration is actually "magically" sorted
2. You can always create some sort of OxM/Persistence layer on top to tranform the result into a ```SortedSet``` with a premade ```Comparator<Tuple>``` comparing ```Tuple``` scores. ( That's what I do in both my Scala & Java code, using Jedis & Lettuce )
3. I actually agree with your point-of-view, but I think that fixing this would be a breaking-change. @marcosnils  what do you think ?

**Comment by DanielYWoo** [comment]
Developers know that it must be a sub class of Set, and they can easily find that it's a LinkedHashSet with a debugger or read the source code of jedis, we know it will work, but the API is too generic. You don't want to return a Collection<String> with lrange, right? :-)

Definitely this will break compatibility so if possible, if you want to fix it, maybe for the next major release.

**Comment by sheinbergon** [comment]
@marcosnils  WDYT ?

**Comment by marcosnils** [comment]
@DanielYWoo @sheinbergon I don't see any reasons to do this as LinkedHashSet shares the same methods as it's parent hierarchies. It'd totally make sense if this wasn't the case as Jedis users would have to cast to use it. But TBH, I prefer to leave it that way to avoid breaking backwards compatibility in future versions. 

@HeartSaVioR @xetorthio any thoughts?

**Comment by DanielYWoo** [comment]
@marcosnils Let's say I am writing a DAO and other people use the DAO I write, I have to expose it to LinkedHashSet<> to collaborate with other people, telling them the Set returned is actually ordered. 
```
public LinkedHashSet<String> topPlayers() {
  ...
  return new LinkedHashSet<>(returnedSetFromJedis)
}
```

I cannot cast it directly into LinkedHashSet since you are returning a more general Set, you are trying to hide the implementation details at the API level, that means there is no guarantee what the actual implementation is, or will be in the next release.

Polymorphism is good, if it we expose good abstraction level at the API level.

**Comment by marcosnils** [comment]
> I cannot cast it directly into LinkedHashSet since you are returning a more general Set

You should be able to do this. 

```java
public LinkedHashSet<Tuple> topPlayers() {
 return (LinkedHashSet<Tuple>) jedis.zrangeByScoreWithScores("foo", 0d, 2d);
}
```

Jedis tries to return the most `usable` and generic type when possible, that's why you'll see that most of the time it uses `List` , `Map`, `Map.Entry` and `Set` types.

**Comment by DanielYWoo** [comment]
No, I will never do that cast. Unless you add a guarantee to the document that the implementation will always to LinkedHashSet and will never change ;-). The return type is a guarantee and contract to client programmers in OOP, client programmer should not guess and cast to the implementation class, that's how polymorphism works. 

Actually, jedis should not return a List, jedis should return Collection which is more generic if you prefer generic types.

**Comment by DanielYWoo** [comment]
close since no response.
