### ISSUE TITLE
JavaDoc methods for obtaining Pool metrics

### ISSUE THREAD

**Issue by vdzhuvinov** [xetorthio/jedis#1452]
In particular, I wonder what kind of metric **redis.clients.util.Pool.getNumWaiters** returns.

The other methods for obtaining metrics (getNumActive, getNumIdle, getMeanBorrowWaitTimeMillis, getMaxBorrowWaitTimeMillis) seem descriptive enough, but a JavaDoc would certainly help in understanding.

**Comment by marcosnils** [comment]
@vdzhuvinov https://commons.apache.org/proper/commons-pool/apidocs/org/apache/commons/pool2/impl/GenericObjectPool.html#getNumWaiters--

**Comment by vdzhuvinov** [comment]
Cheers! Just added a few lines of JavaDocs for the Pool class based on your pointers: https://github.com/xetorthio/jedis/pull/1453
