### ISSUE TITLE
jedisCluster : how to set byte[] value

### ISSUE THREAD

**Issue by flygit** [xetorthio/jedis#1454]
### Expected behavior

Long setnx(final String key, final byte[] value)

### Actual behavior

Long setnx(final String key, final String value)

### Steps to reproduce:

why not provide byte[] type param?

#### Jedis version:
2.8

#### Redis version:
3.0

#### Java version:
8

**Comment by marcosnils** [comment]
https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/BinaryJedis.java#L596

**Comment by SnowWhitePig** [comment]
I cann't understand.Is there no this command with the client?string key byte[] values

**Comment by SnowWhitePig** [comment]
@marcosnils Thank you for your reply.I have knew that interface.But,i want some commands like "Long setnx(String key, byte[] value)".My previous comment mean that is there no command to save byte[] value with String key in the redis.

**Comment by marcosnils** [comment]
@SnowWhitePig that's not how BinaryJedis is implemented. It's either all string or all []bytes interfaces.

**Comment by SnowWhitePig** [comment]
@marcosnils I understood.Thank you very much.
