### ISSUE TITLE
IMPROVEMENT: add more prominent warning to keys() methods

### ISSUE THREAD

**Issue by kutzi** [xetorthio/jedis#1458]
On Jedis/MultiKeyCommands there's a long Javadoc describing the performance issues of KEYS.
But as obviously most devs don't really read the Javadoc - and then we end up with keys() calls in production code - could you please add a more prominent warning to it?

The only thing which I actually thing could work, would be .@Deprecated, though

**Comment by marcosnils** [comment]
@kutzi thx for the suggestion. I don't believe **@Deprecated** is an option as it doesn't reflect the reality which is that KEYS is still a valid and long standing command. 

I might be wrong, but I believe this is just a matter of understanding how redis works rather than improving documentation from the redis side. I don't think there's much we can do from our end as KEYS vs SCAN depends entirely on the use case

@HeartSaVioR ?

**Comment by kutzi** [comment]
Totally agree that it is a valid command. However no one should ever be using it IMHO.
I also find @Deprecated a perfect solution, but it's the only one I know of which would give an automated warning when using the method.

**Comment by marcosnils** [comment]
> However no one should ever be using it IMHO.

I respectfully disagree. Even the redis official doc (https://redis.io/commands/KEYS) says the it should be used with extremely precaution, for debbuging or changing keypsace layout (there's no other command that does this).

I still believe that Jedis users should understand what the base redis commands do, what are trade-offs of using them and when to do so.

**Comment by kutzi** [comment]
https://redis.io/commands/KEYS
"Don't use KEYS in your regular application code. "

Yes, there might be edge cases when you need to use it - even in Java code and not just with the CLI.

So, IMO just put a description to @deprecated saying why it is isn't actually deprecated, but should be used with extreme care and e.g. linking to official documentation.

**Comment by kutzi** [comment]
If there would be any other way than @deprecated I would perfectly agree to use that one instead

**Comment by marcosnils** [comment]
> So, IMO just put a description to @deprecated saying why it is isn't actually deprecated, but should be used with extreme care and e.g. linking to official documentation.

This will definitely not happen, deprecated has a totally different meaning from an API perspective and will bring more confusion than clarification.

> If there would be any other way than @deprecated I would perfectly agree to use that one instead

Me too, but as there's no other way I don't see there's much to be done besides adding a regular javadoc which is already there.

**Comment by kutzi** [comment]
>  deprecated has a totally different meaning from an API perspective
agree

>  and will bring more confusion than clarification.
Respectfully disagree as IMHO no one should be using this in Java application code

Okay, then please at at least make the Javadoc more alarming.
In the current form I have to read until the 3rd paragraph to see the warning. Please put a big warning on top of it and also add the warning to the  MultiKeyCommands interface

**Comment by marcosnils** [comment]
> Okay, then please at at least make the Javadoc more alarming.
> In the current form I have to read until the 3rd paragraph to see the warning. Please put a big warning on top of it and also add the warning to the MultiKeyCommands interface

Ok, I guess we can do that. Would you like to contribute and submit a patch for this?. I won't have time until a couple of days.

**Comment by kutzi** [comment]
I will try to find some time this weekend.
Thanks

**Comment by kutzi** [comment]
Hmm, maybe use something like this: https://github.com/peichhorn/lombok-pg/wiki/%40Warning

But for now, I'll just update the Javadoc

**Comment by marcosnils** [comment]
> But for now, I'll just update the Javadoc

sounds good!. Thx!

**Comment by kutzi** [comment]
FYI: there's no Contributing.md as said on https://github.com/xetorthio/jedis#i-want-to-contribute

Also I don't know how to run the unit tests as they seem to require a running Redis with a non standard password

**Comment by marcosnils** [comment]
@kutzi don't worry just submit your PR and the CI will take care of running the tests

**Comment by marcosnils** [comment]
> FYI: there's no Contributing.md as said on https://github.com/xetorthio/jedis#i-want-to-contribute

Sorry, it has been moved to the recommended github location https://github.com/xetorthio/jedis/blob/master/.github/CONTRIBUTING.md. I'll update the README

**Comment by DanielYWoo** [comment]
How about simply print a warning log whenever keys() is called? @kutzi

**Comment by kutzi** [comment]
In my experience, in real live no one is actually paying attention the neither what is written in the Javadoc nor to any log entries ...

**Comment by kutzi** [comment]
Actually, I think this can be closed, given that https://github.com/xetorthio/jedis/pull/1459 is merged.
@marcosnils
