### ISSUE TITLE
Getting high response time from Redis Server while 4-5 requests per second

### ISSUE THREAD

**Issue by vishalsharma13** [xetorthio/jedis#1462]
### Expected behavior

In normal load , i am getting response in 8-9 ms but when i am doing load testing in which 5-6k requests per second then redis response time increased upto 7-8 seconds.   

Write here what you're expecting ...

### Actual behavior

As redis is cache and i am using as pure cache all data at RAM(64 GB with 16 core processor) not in Hard Disk for those configuration this response time is not good. So please help me to tune the redis server to get high performance.

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

### Redis / Jedis Configuration

Architecture :- 

One master (only for write)
Two slaves (For read)

To Load Balancing using Twemproxy :- 

twemproxy configurations :- 

alpha:
  auto_eject_hosts: false
  client_connections: 40000
  distribution: modula
  hash: crc32a
  hash_tag: '{}'
  listen: 0.0.0.0:8511
  preconnect: false
  redis: true
  server_connections: 10000
  server_failure_limit: 2
  server_retry_timeout: 30000
  servers:
  - 0.0.0.0:6381:1
  timeout: 500
beta:
  auto_eject_hosts: false
  client_connections: 75000
  distribution: modula
  hash: crc32a
  hash_tag: '{}'
  listen: 0.0.0.0:8510
  preconnect: false
  redis: true
  server_connections: 20000
  server_failure_limit: 2
  server_retry_timeout: 30000
  servers:
  - 0.0.0.0:6380:1 slave1
  - 0.0.0.51:6382:1 slave2
  timeout: 1000

Redis Conf :- 

port 6382
bind 0.0.0.0
loglevel notice
logfile "/home/cache/redis/logs/6382.log"
maxmemory 55gb
maxmemory-policy volatile-lru
maxclients 75000
timeout 5
(Same for master and slaves)
Jedis Pool :- 
JedisPoolConfig poolConfig = new JedisPoolConfig();
poolConfig.setMaxTotal(Integer.parseInt(ResourceLoader.getProperties(60000)));
poolConfig.setTestOnBorrow(true);
poolConfig.setTestOnReturn(true);
poolConfig.setMaxIdle(10000);
poolConfig.setMinIdle(10);
poolConfig.setTestWhileIdle(true);
poolConfig.setNumTestsPerEvictionRun(10);
poolConfig.setTimeBetweenEvictionRunsMillis(30000);
pool = new JedisPool(poolConfig, host, port);

To get resource from pool :- 

public Jedis getJedis() {
    	return pool.getResource();
    }
	
To return resource :- 

	public void returnJedis(Jedis jedis) {
    	try {
			if(jedis!=null&&jedis.isConnected()){
				jedis.close();
		
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
    }
}	

Java Method Used to get data :- 

public List<String> getStringArray(String keys, String[] arrayValues, String trackerId) throws  Exception{
        logger.info(" REDIS: Request Params trackerId {} Method {} key {}  value {} ",trackerId,"getStringArray",keys,arrayValues);
        objectAsMap = new HashMap<String, String>();
          Jedis jedis=null;
          long start=0l;
          long after=0l;
          List<String> response= new ArrayList<String>();
            try {
               //get instance of jedis connection
            	start=System.currentTimeMillis();
                     jedis=RedisReadManager.getInstance().getJedis();
     		        response=jedis.hmget(keys, arrayValues);
     		        after=System.currentTimeMillis();
               } catch (Exception e) {
                     logger.error("REDIS: Exception trackerId {} Method {} Exception {}" ,trackerId,"getStringArray",e);
                     e.printStackTrace();
                     throw e;
               }finally {
                     //close jedis connection and connection back to pool 
            	   RedisReadManager.getInstance().returnJedis(jedis);
                     //for gc
                     
               }
            logger.info(" REDIS: Response trackerId {} Method {} resp{} respTime {} "  ,trackerId,"getStringArray", response, after-start);
               return response;
 }

#### Jedis version:
2.8.1
#### Redis version:
Redis3.2.6
#### Java version:
Java 8

**Comment by marcosnils** [comment]
Please ask this question in the mailing list. github is used for design discussions and bugs mainly.

http://groups.google.com/group/jedis_redis

**Comment by vishalsharma13** [comment]
You can guide me that my Architecture is able to take load of 10-15 requests per second. As i am know in Redis and i am going on production servers .

Current Architecture :- 

One Master (64 GB Ram, 16 core processor)
Two slaves (64 GB RAM, 16 core processor)

And i am using as pure cache not persist the data on disk.
