### ISSUE TITLE
IMPROVMENT: Jedis should distingusih between exhausted pool to other failures

### ISSUE THREAD

**Issue by shmulik-ubimo** [xetorthio/jedis#1463]
### Expected behavior

In continuance to issue #1236, I would expected Jedis to let me know that it failed to retrieve a connection from the inner pool, since the pool is exhausted by throwing an exception that indicates rather then a general one.   

### Actual behavior

When Jedis fails to retrieve a connection from the pool, it throws a `JedisException`, which is too general and can be thrown for a failure in the implemented `activateObject()` or `validateObject()` method.  

### Steps to reproduce:
1. Create a `GenericObjectPoolConfig` object with `setMaxTotal(1)` and `setBlockWhenExhausted(false)`.
2. Create a `JedisPool` with the configuration from step (1).
3. Try to retrieve a connection from the pool by `getResource()`.
4. Try to retrieve another connection and expect a `JedisException`. 

#### Jedis version:
3.0.0-SNAPSHOT
#### Redis version:
3.0.7
#### Java version:
1.8

**Comment by marcosnils** [comment]
Let's continue the discussion in #1464
