### ISSUE TITLE
Execute lua script From jedis on all nodes of a cluster

### ISSUE THREAD

**Issue by svsteja** [xetorthio/jedis#1465]
### Expected behavior
We have a lua script that needs to be executed on each and every node of a cluster.
In Jedis we just have eval fucntion and based on hash its executing only on particular node.

There should be provision in jedis to specify on which host and port of a cluster should this
script be executed / provide api to execute on all the nodes of a cluster

### Actual behavior
Executes script only one Node based on hash provide

There should be provision in jedis to specify on which host and port of a cluster should this
script be executed / provide api to execute on all the nodes of a cluster

Write here what happens instead ...
Executes script only one Node based on hash provide

**Comment by marcosnils** [comment]
Dup of #990
