### ISSUE TITLE
zlexcount(String key, String min, String max) , the parameter min and max are in a perversion

### ISSUE THREAD

**Issue by xinhaiCai** [xetorthio/jedis#1471]
### Expected behavior

output: 3

### Actual behavior

output: 0

while using   System.out.println(jedis.zlexcount("zset","[hello","[zset"));
I can get the right result that is 3.

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.     Jedis jedis = new Jedis();
        jedis.zadd("zset", 10.1, "hello");
        jedis.zadd("zset", 10.0, ":");
        jedis.zadd("zset", 9.0, "zset");
        jedis.zadd("zset", 11.0, "zset!");
        System.out.println(jedis.zlexcount("zset","[zset","[hello"));
2.
3.

**Comment by HeartSaVioR** [comment]
Please turn on `monitor` in redis-cli and see how command is sent from Jedis.
Proper command is `ZLEXCOUNT key min max`, and if Jedis correctly sends that, you may want to check Redis.

**Comment by xinhaiCai** [comment]
the command is sent correctly.

**Comment by marcosnils** [comment]
@xinhaiCai if the command is sent correct, then It's not a Jedis issue, right? Can we close this?

**Comment by xinhaiCai** [comment]
All right

**Comment by xinhaiCai** [comment]
Finally, by the way, I found that the version of my redis is 3.0.5 actually.
