### ISSUE TITLE
Alow Basic Authentication headers

### ISSUE THREAD

**Issue by gyscos** [xetorthio/jedis#1472]
### Expected behavior

In order to connect to a Basic Authentication-protected redis server, Jedis would allow to set some specific headers to be added to each request.

### Actual behavior

Jedis provides no such option (or I did not find any?).

**Comment by marcosnils** [comment]
https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/JedisPool.java#L91-L94

https://github.com/xetorthio/jedis/blob/1f1e23b26a4aa244ebfdbcbcdf489b630c841884/src/test/java/redis/clients/jedis/tests/utils/JedisURIHelperTest.java#L17-L20

**Comment by gyscos** [comment]
My bad! Thanks!
