### ISSUE TITLE
Jedis cluster initialization problem

### ISSUE THREAD

**Issue by wanghongenpin** [xetorthio/jedis#1474]
Expected behavior

The current jedis IP can be obtained under jidis.getClient ().GetHost () not according to cluster slots

### Actual behavior

Write here what happens instead ...
Jedis cluster initialization is based on the cluster slots to initialize but send the command of the jedis return is IP is 127.0.0.1 instead of the correct IP will not be able to connect in the operation

[
![en74nge _ fn23ae168xxr6](https://cloud.githubusercontent.com/assets/24794200/23338529/4f7ee236-fc48-11e6-8436-3b0303dbd416.png)
](url)
![99tpkp1ea 1llwudwdp nt](https://cloud.githubusercontent.com/assets/24794200/23338536/708ead80-fc48-11e6-81e6-4e4e746b4f94.png)
### Steps to reproduce:
127.0.0.1 this node is master in the set key slots is this node will be reported :Could not get a resource from the pool

**Comment by tonylau08** [comment]
I have this problem too.
Exception:
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:53)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
	at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnectionFromSlot(JedisSlotBasedConnectionHandler.java:66)

Jedis version:2.9.0
Redis version:3.2.8 (00000000/0) 64 bit
Java version:1.8

The system can be run normally when i  used Jedis but not JedisCluster
JedisPool pool1 = new JedisPool("192.168.0.11",7000);
		JedisPool pool2 = new JedisPool("192.168.0.11",7001);
		JedisPool pool3 = new JedisPool("192.168.0.11",7002);
		Jedis jedis = pool2.getResource();
		
		List<Object> nodes = jedis.clusterSlots();
		for(int i=0; i<3; i++){
			@SuppressWarnings("unchecked")
			List<Object> node = (List<Object>)nodes.get(i);
			Object start = node.get(0);
			System.out.println("SLOT_START：：			" + start);
			Object end = node.get(1);
			System.out.println("SLOT_END：：			" + end);
			ArrayList<?> master = (ArrayList<?>)node.get(2);
			Object masterHost = master.get(0);
			System.out.println("MASTER_HOST_LIST_0_BYTE[]：：	" + new String((byte[])masterHost));
			Object masterPort = master.get(1);
			System.out.println("MASTER_PORT_LIST_1_LONG：：	" + masterPort);
			Object masterIDs = master.get(2);
			System.out.println("MASTER_IDs_LIST_1_BYTE[]：：	" + new String((byte[])masterIDs));
			
			if(node.size()>3){
				ArrayList<?> slave1 = (ArrayList<?>)node.get(3);
				Object slave1Host = slave1.get(0);
				System.out.println("SLAVE_HOST_LIST_0_BYTE[]：：	" + new String((byte[])slave1Host));
				Object slave1Port = slave1.get(1);
				System.out.println("SLAVE_PORT_LIST_1_LONG：：	" + slave1Port);
				Object slave1IDs = slave1.get(2);
				System.out.println("SLAVE_IDS_LIST_1_BYTE[]：：	" + new String((byte[])slave1IDs));
			}
			System.out.println();
		}
		
		System.out.println("GET_RESULT：			"+ jedis.get("iiii"));
		
		Client cli = jedis.getClient();
		String host = cli.getHost();
		int port = cli.getPort();
		System.out.println("HOST:PORT：			"+host + ":" + port);

SLOT_START：：			10923
SLOT_END：：			16383
MASTER_HOST_LIST_0_BYTE[]：：	192.168.0.11
MASTER_PORT_LIST_1_LONG：：	7002
MASTER_IDs_LIST_1_BYTE[]：：	f8f154bc5aaf0f828077215a5a30367db56c07d1

SLOT_START：：			5461
SLOT_END：：			10922
MASTER_HOST_LIST_0_BYTE[]：：	127.0.0.1
MASTER_PORT_LIST_1_LONG：：	7001
MASTER_IDs_LIST_1_BYTE[]：：	855b05129860a888c7c15c6fd94ebfeae297c110

SLOT_START：：			0
SLOT_END：：			5460
MASTER_HOST_LIST_0_BYTE[]：：	192.168.0.11
MASTER_PORT_LIST_1_LONG：：	7000
MASTER_IDs_LIST_1_BYTE[]：：	707dcac597d2ad158dcbbc366f126b495de902b0

GET_RESULT：			1111
HOST:PORT：			192.168.0.11:7001

**Comment by allanwax** [comment]
When creating a cluster, always use the local address of the machines in the cluster.  In this way the nodes config file does not contain the localhost address of a separate machine.  trying to reference another machine using localhost will always fail but using the local ip address will succeed.
