### ISSUE TITLE
why BinaryJedisCommands.blpop deprecated since 2.7.0?

### ISSUE THREAD

**Issue by stephenfire** [xetorthio/jedis#1479]
if blpop(byte[]) and brpop(byte[]) are removed in 3.0.0, i could not able to use BinaryJedisCommands as the base interface for sharded and non-sharded binary jedis.

**Comment by marcosnils** [comment]
they're not deprecated, they're here:

https://github.com/xetorthio/jedis/blob/1f1e23b26a4aa244ebfdbcbcdf489b630c841884/src/main/java/redis/clients/jedis/commands/MultiKeyBinaryCommands.java#L16-L18
