### ISSUE TITLE
Redis Client Connections are not closing

### ISSUE THREAD

**Issue by srikannanb** [xetorthio/jedis#1481]
Hi,

I have configured 16 connections per app server for redis client connection in my application and I have properly handled the return of the connection. But frequently i get running out of connections from some app servers.

When I run the command "client list" in redis. I can see connections from that app server having more idle time and keep on alive.

If I restart my application server and it works fine for few hours and again this issue occurrs.

I can set timeout to solve this issue. But i want to know the root cause for this issue. What could be the possible cause for this problem.

Regards
Srikannan B

**Comment by vishalsharma13** [comment]
Hi,

Please use  jedis.close() to close and return the connection in pool.

**Comment by marcosnils** [comment]
Please ask this question in the mailing list. github is used for design discussions and bugs mainly.

http://groups.google.com/group/jedis_redis
