### ISSUE TITLE
Timeout settings not applied to sentinel connection

### ISSUE THREAD

**Issue by bernard-xl** [xetorthio/jedis#1487]
### Expected behavior

The `connectionTimeout` and `soTimeout` arguments in `JedisSentinelPool` constructor are applicable to all connections (connection to Sentinels, and Master).

### Actual behavior

The connection timeout of Sentinel connection is 2000 ms regardless of `connectionTimeout` and `soTimeout` value. Is this purposely designed or a bug?

### Steps to reproduce:

1. Prepare non-routable address for timeout simulation, e.g. 10.0.0.0:26379
2. Set the connection timeout to 10000 ms
3. `new JedisSentinelPool(masterName, nonRoutable, config, connectionTimeout)`
4. Observe the actual timeout, it will happen after 2000 ms instead of 10000 ms

**Comment by marcosnils** [comment]
@HeartSaVioR ^?

**Comment by sazzad16** [comment]
@bernard-xl To clarify, except for `host:post`, nothing is used for sentinels even password. All the constructor parameters are assumed for master only. 

If we ought to care, we should also (and specially) think about password which is stated in #1636

**Comment by pavel-hp** [comment]
+1

**Comment by sazzad16** [comment]
Resolved by #1943
