### ISSUE TITLE
I think I found a spelling mistake

### ISSUE THREAD

**Issue by Armandwt** [xetorthio/jedis#1488]
Forgive my poor English.
### Expected behavior
I want set a keys' ttl by use JedisCluster.pexpireAt(final byte[] key, final long millisecondsTimestamp).

### Actual behavior
I get a wrong ttl number in redis

### Steps to reproduce:
It's may be a spelling mistake:
At path: src/main/java/redis/clients/jedis/BinaryJedisCluster.java  line 183
I think it should be
   return connection.pexpireAt(key, millisecondsTimestamp);
not 
   return connection.pexpire(key, millisecondsTimestamp);

### Redis / Jedis Configuration
null
#### Jedis version:
2.9
#### Redis version:
All
#### Java version:
1.8

**Comment by marcosnils** [comment]
@Armandwt that's right. Want to send a PR to fix it?

**Comment by Armandwt** [comment]
I hope can fix it in next version,Thank u

**Comment by spccold** [comment]
@Armandwt  PR = Pull Request

**Comment by Armandwt** [comment]
@spccold Thank you!

**Comment by cpeeyush** [comment]
@marcosnils  I have raised a pull request https://github.com/xetorthio/jedis/pull/1497 . Please take a look and merge it, if it looks good to you.

#1497

**Comment by sazzad16** [comment]
Fixed by #1497
