### ISSUE TITLE
How to Get Pool Details from Jedis Object

### ISSUE THREAD

**Issue by vishalsharma13** [xetorthio/jedis#1492]
### Expected behavior
How to get redis master and port details from jedis pool object.
Write here what you're expecting ...
I am using Jedis pool to connect twemproxy through my java application. But in application i want to get twemproxy ip and port details through Jedis object. Is this possoble to get details from jedis object.please suggest
### Actual behavior

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

### Redis / Jedis Configuration
Jedis Pool Code : -- 

 private static JedisPool pool;
    private RedisLookupWriteManager() {}
    public final static RedisLookupWriteManager getInstance() {
        return instance;
    }
    public void connect(String host, int port) {
        try {
        	if(pool==null || pool.isClosed()){
        		logger.debug("host {} port{}", host , String.valueOf(port));
				JedisPoolConfig poolConfig = new JedisPoolConfig();
				poolConfig.setMaxTotal(Integer.parseInt(ResourceLoader.getProperties("poolSize")));
				poolConfig.setTestOnBorrow(true);
				poolConfig.setTestOnReturn(true);
				poolConfig.setMaxIdle(Integer.parseInt(ResourceLoader.getProperties("maxIdle")));
				poolConfig.setMinIdle(Integer.parseInt(ResourceLoader.getProperties("minIdle")));
				poolConfig.setTestWhileIdle(true);
				poolConfig.setNumTestsPerEvictionRun(Integer.parseInt(ResourceLoader.getProperties("setNumTestsPerEvictionRun")));
				poolConfig.setTimeBetweenEvictionRunsMillis(Integer.parseInt(ResourceLoader.getProperties("setTimeBetweenEvictionRunsMillis")));
				pool = new JedisPool(poolConfig, host, port);
        	}
		} catch (Exception e) {
			e.printStackTrace();
			throw e;
		}
    }
    public void releasePool() {
        try {
			if(pool!=null&&!pool.isClosed()){
				pool.destroy();
				}
		} catch (Exception e) {
			e.printStackTrace();
			throw e;
		}
    }
    public Jedis getJedis() {
        return pool.getResource();
    }

	public void returnJedis(Jedis jedis) {
    	try {
			if(jedis!=null&&jedis.isConnected()){
				jedis.close();
			}
		} catch (Exception e) {
			e.printStackTrace();
			throw e;
		}
#### Jedis version:
2.8
#### Redis version:
3.2.6
#### Java version:
1.8

**Comment by vishalsharma13** [comment]
@marcosnils can you please help on above question.

**Comment by marcosnils** [comment]
`jedis.getClient().getSocket().getInetAddress();`
