### ISSUE TITLE
evalsha(String sha1, int numKeys, String... args) returns unexpected result.

### ISSUE THREAD

**Issue by fredo994** [xetorthio/jedis#1493]
When using lua scripts redis can return different types, and I was expecting that 
evalsha will return response that holds returned type that can be correctly parsed or cast to wanted type.
So I was expecting that  `Response<String> evalsha(String sha1, int numKeys, String... args) ` will return correct type only sa string representation, but it returned correct type and cast to `byte[]` failed in 
`BuilderFactory.STRING` factory. 

I think that 
```java
public Response<String> evalsha(String sha1, int numKeys, String... args) {
    getClient(sha1).evalsha(sha1, numKeys, args);
    return getResponse(BuilderFactory.STRING);
  }
```
should be:
```java
public Response<Object> evalsha(String sha1, int numKeys, String... args) {
    getClient(sha1).evalsha(sha1, numKeys, args);
    return getResponse(BuilderFactory.EVAL_BINARY_RESULT);
  }
```

**Comment by sazzad16** [comment]
Resolved by #1667
