### ISSUE TITLE
Is it possible to create Jedis instance based on existing one

### ISSUE THREAD

**Issue by malafeev** [xetorthio/jedis#1495]
Hi,

I need to intercept all commands (for implementing Tracing (http://opentracing.io/))

But it seems I cannot create Jedis from existing Jedis. 
Like `new Jedis(Jedis jedis);`
Is there any solution?

**Comment by marcosnils** [comment]
Please ask this question in the mailing list. github is used for design discussions and bugs mainly.

http://groups.google.com/group/jedis_redis
