### ISSUE TITLE
Jedis Pool with Two Twemprxoy IP

### ISSUE THREAD

**Issue by vishalsharma13** [xetorthio/jedis#1498]
### Expected behavior
@marcosnils 
Hi,

I have two twemproxy servers and i want to use in active active state programmatically through jedis. Is this the correct way to generate pool with two IP's of twemproxy or i need to do something to use twemproxy in active active state.

Write here what you're expecting ...

### Actual behavior

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

**Comment by marcosnils** [comment]
Please ask this question in the mailing list. github is used for design discussions and bugs mainly.

http://groups.google.com/group/jedis_redis
