### ISSUE TITLE
How to run Jedis maven tests?

### ISSUE THREAD

**Issue by rayjcwu** [xetorthio/jedis#1499]
### Expected behavior

See all tests passed

### Actual behavior

Tests run: 478, Failures: 0, Errors: 427, Skipped: 0

### Steps to reproduce:

- mvn clean test

### Redis / Jedis Configuration

brew install redis
clone from github then checkout tag 2.9.0

#### Jedis version:

2.9.0

#### Redis version:

3.2.8

#### Java version:

1.8

**Comment by marcosnils** [comment]
https://github.com/xetorthio/jedis/blob/1f1e23b26a4aa244ebfdbcbcdf489b630c841884/.github/CONTRIBUTING.md#jedis-test-environment
