### ISSUE TITLE
For JedisPool should add constructor method like default db index

### ISSUE THREAD

**Issue by jonwinters** [xetorthio/jedis#1501]
In my project ,we need to add a future like  select default db index,
but in Jedis I can't find a method or constructor method to config my db index,
for Jedis select() method , it means always select zero db index

so , I will add a constructor method to config default db index :D

**Comment by jonwinters** [comment]
sorry for my poor English  not my motherlanguage -_-!!

**Comment by marcosnils** [comment]
The constructor already exists

https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/JedisPool.java#L23-L26

**Comment by jonwinters** [comment]
@marcosnils but I can't find a pram to set default  redis database index
