### ISSUE TITLE
redis.clients.jedis.exceptions.JedisDataException: Please close pipeline or multi block before calling this method.

### ISSUE THREAD

**Issue by ankitdbst** [xetorthio/jedis#1505]
Hello,

I am batching some commands using pipelining and I sync them with a timer. 

### Scenario:
1. Pipeline commands to redis (in `process()` method)
2. `JedisConnectionException` occurs (inside `flush()`, return Jedis resource)
3. Pipeline new commands by re-using the same pipeline with `pipeline.setClient(mJedis)`
4. On performing `sync()` on the pipeline, Jedis throws the below exception
`redis.clients.jedis.exceptions.JedisDataException: Please close pipeline or multi block before calling this method.`

```
void process() {
    mPipeline.evalsha(...);
    // other application code
}

// Timer based flush
void flush() {
    try {
        if (mJedis == null) {
            mJedis = sJedisPool.getResource();
            mPipeline.setClient(mJedis);
        }
        mPipeline.sync();
    } catch (JedisException je) {
        mJedis.close();
        mJedis = null;
    }
}
```
I do not want to lose the already pipelined commands, so i do not do `mPipeline=mJedis.pipelined()` inside `flush()`

#### Jedis version:
2.9.0
#### Redis version:
3.2.6

#### Java version:
1.9

**Comment by marcosnils** [comment]
Please ask this question in the mailing list. github is used for design discussions and bugs mainly.

http://groups.google.com/group/jedis_redis

**Comment by ankitdbst** [comment]
@marcosnils : Thanks for pointing to the google group, I have posted it there. Can you please answer it?
https://groups.google.com/forum/#!topic/jedis_redis/1UM6z-lYMwg

**Comment by ankitdbst** [comment]
Actually I have simple question regarding Jedis behaviour: When we are in Pipeline, should the commands `set` `zadd` etc throw `JedisConnectionException` before `sync()` operation is fired (i know it may not be possible because we haven't sent the data across)?
I pipeline several thousand commands before firing `sync()` and if this command returns `JedisConnectionException`, I have no way of retrying the previous command.
