### ISSUE TITLE
RedisConnectionFailure

### ISSUE THREAD

**Issue by bkatwal** [xetorthio/jedis#1506]
### Expected behavior

Redis template/hashoperations should be able to perform get/save method successfully.

### Actual behavior

Occasionally redis template throws RedisConnectionfailure exception while using get/save/delete method. 
StackTrace for hasKey operation(Similar exception occurs for other operations too):

org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the poolorg.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:198)
org.springframework.data.redis.connection.jedis.JedisConnectionFactory.getConnection(JedisConnectionFactory.java:345)
org.springframework.data.redis.core.RedisConnectionUtils.doGetConnection(RedisConnectionUtils.java:129)
org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:92)
org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:79)
org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:191)
org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:166)
org.springframework.data.redis.core.RedisTemplate.hasKey(RedisTemplate.java:638)
### Steps to reproduce:

Can't reproduce as the case is intermittent.

### Redis / Jedis Configuration

@Configuration
public class RedisConfiguration {

  @Value("${redisCentralCachingURL}")
  private String redisHost;

  @Value("${redisCentralCachingPort}")
  private int redisPort;

  @Bean
  public StringRedisSerializer stringRedisSerializer() {
    StringRedisSerializer stringRedisSerializer = new StringRedisSerializer();
    return stringRedisSerializer;
  }

  @Bean
  JedisConnectionFactory jedisConnectionFactory() {
    JedisConnectionFactory factory = new JedisConnectionFactory();
    factory.setHostName(redisHost);
    factory.setPort(redisPort);
    factory.setUsePool(true);
    //factory.getPoolConfig().setMaxIdle(30);
    //factory.getPoolConfig().setMinIdle(10);
    return factory;
  }

  @Bean
  public RedisTemplate<String, Object> redisTemplate() {
    RedisTemplate<String, Object> redisTemplate = new RedisTemplate<>();
    redisTemplate.setConnectionFactory(jedisConnectionFactory());
    redisTemplate.setExposeConnection(true);
    // No serializer required all serialization done during impl
    redisTemplate.setKeySerializer(stringRedisSerializer());
    //`redisTemplate.setHashKeySerializer(stringRedisSerializer());
    redisTemplate.setHashValueSerializer(new GenericSnappyRedisSerializer());
    redisTemplate.afterPropertiesSet();
    return redisTemplate;
  }

  @Bean
  public RedisCacheManager cacheManager() {
    RedisCacheManager redisCacheManager = new RedisCacheManager(redisTemplate());
    redisCacheManager.setTransactionAware(true);
    redisCacheManager.setLoadRemoteCachesOnStartup(true);
    redisCacheManager.setUsePrefix(true);
    return redisCacheManager;
  }

}

**Comment by marcosnils** [comment]
Redistemplate issues are not part of Jedis. Please refer to spring-data-redis page for that.

http://projects.spring.io/spring-data-redis/
