### ISSUE TITLE
Jedis reply showing stale data

### ISSUE THREAD

**Issue by vishal98** [xetorthio/jedis#1507]
i have update one key with update values 
but reply call is still giving with stale data.

Data which i get is not even there in redis store .
Is it possible that jedis is saving data in local cache instead of redis cache.  

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

**Comment by marcosnils** [comment]
> Is it possible that jedis is saving data in local cache instead of redis cache.

No.  Please provide a reproducible case so we can assist.
