### ISSUE TITLE
jedis get method returning stale data

### ISSUE THREAD

**Issue by vishal98** [xetorthio/jedis#1508]
i have update one key with update values 
but reply call is still giving with stale data.

http://stackoverflow.com/questions/43866780/jedis-get-getting-stale-data

what we have found that 2nd getcall  still fetch stale data although redis contains updated data.
Server restarts make get method to fetch updated data.

So i assuming somewhere jedis is internally saving stream.
we are using same pool for both reads and writes

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
RedisCache<String, String> appSessionCach = new RedisCache<>(jedisPool, jsfSerializer, jffdkSerializer, "session".getBytes(),
    30 * 60);
  RedisCache<String, String> appSessionCach2 = null;
  appSessionCach.put("test", "131311");
  Application app=new Application(133);
   app.setName("test1");
  appKeySessionCache.put(app,appSessionCach);
  cacheTypeMap.put(cacheName.deviceSessionCache.toString(), (appKeySessionCache));
  appKeySessionCache=(Cache<IApplication, Cache<String, String>>) cacheTypeMap.getIfPresent(cacheName.SessionCache.toString());
  ((RedisCache)  appKeySessionCache).keySet();
   app=new Application(12133);
   app.setName("test2");
  appKeySessionCache.put(app,appSessionCach);
  cacheTypeMap.put(cacheName.deviceSessionCache.toString(), (appKeySessionCache));
  appKeySessionCache=(Cache<IApplication, Cache<String, String>>) cacheTypeMap.getIfPresent(cacheName.SessionCache.toString());
  ((RedisCache)  appKeySessionCache).keySet();

**Comment by vishal98** [comment]
we have implemented https://github.com/levyfan/guava-cache-redis library

**Comment by marcosnils** [comment]
Seems a problem related to guava-cache. Jedis doesn't do any type of caching. I can't really help if the example is not directly related to Jedis as I don't have knowledge in the guava-cache project. I'll recommend opening an issue there.

**Comment by vishal98** [comment]
we are internally calling jedis get and put methods 
	byte[] reply = jedis.get(keyBytes);
and this method is giving me older data although key is same

**Comment by marcosnils** [comment]
> we are internally calling jedis get and put methods
> byte[] reply = jedis.get(keyBytes);
> and this method is giving me older data although key is same

If you can reproduce without using guava-cache I can help. I don't have time to look into other projects code at this moment.

**Comment by vishal98** [comment]
ok lemme check

**Comment by vishal98** [comment]
public static void main(String[] args) {

  Jedis jedis = null;

  try {
   jedis = jedisPool.getResource();

   Application app = new Application(134);
   app.setName("tst1");
   Set setAp = Sets.newHashSet();
   setAp.add(app);

   jedis.set("key".getBytes(), addStream(setAp));
   byte[] objectData = jedis.get("key".getBytes());
   deSerializeData(objectData);

   app = new Application(33);
   app.setName("tst2");
   setAp.add(app);

   jedis.set("key".getBytes(), addStream(setAp));
   objectData = jedis.get("key".getBytes());
   deSerializeData(objectData);
  } finally {
   if (jedis != null) {
    jedis.close();
 
   }
  }

 }

public  static byte[] addStream(Object app){
   ByteArrayOutputStream baos = new ByteArrayOutputStream(1024);
   ObjectOutputStream out = null;
   try {
    // stream closed in the finally
    out = new ObjectOutputStream(baos);
    out.writeObject(app);
    

   } catch (final IOException ex) {
    throw new SerializationException(ex);
   } finally {
    try {
     if (out != null) {
      out.close();
     }
    } catch (final IOException ex) { // NOPMD
     // ignore close exception
    }
   }
   return baos.toByteArray();
 }
 
 public static void deSerializeData(byte[] objectData){

  ObjectInputStream in = null;
  try {
   // stream closed in the finally
   in = new ObjectInputStream(new ByteArrayInputStream(objectData));
   
   HashSet keySet = (HashSet) in.readObject();
  System.out.println("keyset");
  } catch (final ClassCastException ex) {
   throw new SerializationException(ex);
  } catch (final ClassNotFoundException ex) {
   throw new SerializationException(ex);
  } catch (final IOException ex) {
   throw new SerializationException(ex);
  } finally {
   try {
    if (in != null) {
     in.close();
    }
   } catch (final IOException ex) { // NOPMD
    // ignore close exception
   }
  }
 
 }

**Comment by vishal98** [comment]
here we are using simple jedispool with default params still we are seeing stale data on 2nd get call

**Comment by marcosnils** [comment]
@vishal98 just changed your example a bit because it doesn't compile due to some missing classes but it works in my case: 

```java
private static JedisPool jedisPool = new JedisPool();

    public static void main(String[] args) {

        Jedis jedis = null;

        try {
            jedis = jedisPool.getResource();

            String tst= new String("tst1");
            Set setAp = new HashSet();
            setAp.add(tst);

            jedis.set("key".getBytes(), addStream(setAp));
            byte[] objectData = jedis.get("key".getBytes());
            deSerializeData(objectData);

            tst = new String("tst2");
            setAp.add(tst);

            jedis.set("key".getBytes(), addStream(setAp));
            objectData = jedis.get("key".getBytes());
            deSerializeData(objectData);
        } finally {
            if (jedis != null) {
                jedis.close();

            }
        }

    }

    public  static byte[] addStream(Object app){
        ByteArrayOutputStream baos = new ByteArrayOutputStream(1024);
        ObjectOutputStream out = null;
        try {
            // stream closed in the finally
            out = new ObjectOutputStream(baos);
            out.writeObject(app);


        } catch (final IOException ex) {
            throw new SerializationException(ex);
        } finally {
            try {
                if (out != null) {
                    out.close();
                }
            } catch (final IOException ex) { // NOPMD
                // ignore close exception
            }
        }
        return baos.toByteArray();
    }

    public static void deSerializeData(byte[] objectData){

        ObjectInputStream in = null;
        try {
            // stream closed in the finally
            in = new ObjectInputStream(new ByteArrayInputStream(objectData));

            HashSet keySet = (HashSet) in.readObject();
            System.out.println(keySet);
        } catch (final ClassCastException ex) {
            throw new SerializationException(ex);
        } catch (final ClassNotFoundException ex) {
            throw new SerializationException(ex);
        } catch (final IOException ex) {
            throw new SerializationException(ex);
        } finally {
            try {
                if (in != null) {
                    in.close();
                }
            } catch (final IOException ex) { // NOPMD
                // ignore close exception
            }
        }

    }
```

The Sysout correctly prints "tst1" and "tst2". Please verify.

**Comment by vishal98** [comment]
hey thanks..things look fine..
there may some other issue.
will debug and let you if problem persist
