### ISSUE TITLE
data type of ttl in restore api should be of long type instead of int type

### ISSUE THREAD

**Issue by hsmhsm** [xetorthio/jedis#1509]
### Expected behavior

dump and restore commands expect ttl to be in milliseconds. So, we use pttl command api along with dump command api, and pttl api uses Long data type to hold ttl value. But, when we want to restore the serialized data using restore command api, it expects ttl value to be of int type. This is a problem for very large ttl values.    

### Actual behavior
type of ttl argument in restore command api should be of long type instead of int type.

Write here what happens instead ...
### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. convert 365 days to milliseconds, and save it as expire time of some key in redis
2. use dump and pttl jedis api to serialize the key's value and to get keys ttl value respectively 
3. restore above serialized value using restore api

### Redis / Jedis Configuration
single node setup

#### Jedis version:
2.7.3

#### Redis version:
3.2.8

#### Java version:
1.8.0_121

**Comment by marcosnils** [comment]
It's long in the master branch https://github.com/xetorthio/jedis/blob/5c2b5858fcac335b67fc0eb00b503a1c71644b19/src/main/java/redis/clients/jedis/commands/JedisCommands.java#L37
