### ISSUE TITLE
Jedis Config pool configuration for jedis get and set operations

### ISSUE THREAD

**Issue by bkatwal** [xetorthio/jedis#1510]
Its more of a query then issue. I might be facing issue may be because of incorrect configuration. So here are my below 2 questions:

1. For my production use I want to set separate timeout for jedis get operations and set operations. For all set operation I want to set timeout to 2000ms and for get 100ms. I have implemented below configuration.

JedisPoolConfig poolConfig = new JedisPoolConfig();
poolConfig.setMaxIdle(30);
poolConfig.setMinIdle(10);
poolConfig.setMaxWaitMillis(2000);
jedisPool = new JedisPool(poolConfig, RedisDBUrl, port, 100);
Let me know if above configuration will do the job. I am setting read timeout to 100ms and maxwait to 2000ms.

2. Let me know if my understanding is correct in below 2 points.
At times I get JedisConnectionException: java.net.SocketTimeoutException: Read timed out or sometimes connect timeout.

Here connect time out is thrown when my application is not able to make connection to redis withing configured time?

Secondly, read timeout comes when application is connected to redis but operations(get/set) are taking time or for some reason?

Lastly, how do i configure timeout for read timeout and connect timeout?

**Comment by marcosnils** [comment]
Please ask this question in the mailing list. github is used for design discussions and bugs mainly.

http://groups.google.com/group/jedis_redis
