### ISSUE TITLE
Transaction should have the waitReplicas method

### ISSUE THREAD

**Issue by jchurch33** [xetorthio/jedis#1511]
### Expected behavior

I expected to be able to use a Transaction to string together any commands I can perfom with the client. I intended to use a transaction to modify the database, update the expiration of a key, and wait for both of these actions to be replicated (for failure protection) all in one action before proceeding.

### Actual behavior

Transaction has no connection to the BasicCommands, therefore it lacks this method. Pipelining also doesn't allow it. Basically there is no convenient way to guarantee a wait on a prior call.

**Comment by sazzad16** [comment]
@jchurch33 Since you need this, would be able to craft a PR? Or, at least some related tests would be helpful for others' to craft it.

**Comment by sazzad16** [comment]
@jchurch33 

> ... wait for both of these actions to be replicated (for failure protection) all in one action ...

won't be happening. As [Redis](https://redis.io/commands/wait) states

> If the command is sent as part of a MULTI transaction, the command does not block but instead just return ASAP the number of slaves that acknowledged the previous write commands.

Still you are welcome to craft a PR or provide some tests. Thanks!
