### ISSUE TITLE
Cluster duplicate ips when using local ip

### ISSUE THREAD

**Issue by lcy362** [xetorthio/jedis#1517]
When setting up the cluster, if using 127.0.0.1, and then in jedis just connect to this node, there will be duplicate endpoints (both public ip and 127.0.0.1) in jedis cluster's nodes. And if connect to another node, it will be fine.

I'm not sure if it is a redis or jedis problem, but it seems all fine when using redis-cli.

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. In a cluster, choose a node(let's say A) to run "cluster meet 127.0.0.1 port" 
2. connect to the cluster, and setShardInfo with only A
3. Then there will be both A and 127.0.0.1 exist in the nodes. And if the slot is on this node, we can't connect to the node as there is in fact no redis node on 127.0.0.1

**Comment by allanwax** [comment]
When using a cluster, always use the local address of the machine when creating the cluster (e.g. 10.24.56.117).  In this way, other members of the cluster can see the other machines in the local network.
