### ISSUE TITLE
[feature] use redis as reliable message queue

### ISSUE THREAD

**Issue by charpty** [xetorthio/jedis#1519]
Hi, guys:
I found an article which tells how to use redis as a reliable message queue.

> https://redis.io/commands/rpoplpush

So I think jedis may implement this function, what do you think?
D:)

**Comment by sazzad16** [comment]
@charpty Thank you for your interest in Jedis.

Jedis already [implemented and released rpoplpush](https://github.com/xetorthio/jedis/blob/jedis-2.9.0/src/main/java/redis/clients/jedis/Jedis.java#L1089).

And about message queue, it's beyond Jedis's aim (_blazingly small and sane Redis java client_), at least for now.

**Comment by charpty** [comment]
Thank you for your reply. D:)~
