### ISSUE TITLE
How to use cluster's slaves for READONLY queries.

### ISSUE THREAD

**Issue by EasonFeng5870** [xetorthio/jedis#1522]
Hi all,

May I know how to use slaves as READONLY queries ?

Is there a easy way to make queries without caring which REDIS instance I need to connect ( All these stuff can be done in Jedis ) ?

Best Regards,

**Comment by marcosnils** [comment]
@EasonFeng5870 how about creating two jedis pools. One for master and another for slave?. Jedis doesn't do this automatically.

**Comment by sazzad16** [comment]
Closed due to inactivity.

**Comment by chandresh-pancholi** [comment]
@marcosnils How would you handle switchover of a slave to master? Read would still point to slave jedis pool.
