### ISSUE TITLE
connections not returning to the pool - pool exhausted

### ISSUE THREAD

**Issue by memiwo** [xetorthio/jedis#1523]
### Expected behavior

I am using JedisSentinelPool and uses it to get a Jedis resource. Once I am done with Jedis I close it. I have seen that the implementation checks if the resource is from the pool, it returns to the pool but this is not happening. I am doing a load test of my application and the pool get exhausted even if I close jedis after every operation. 

### Steps to reproduce:
Observation:
I did 50 concurrent execution and found that 50 resources are being used. Even after the application finished execution the status of the pool shows there are 50 active pooled objects. which means they are not returned to the pool as an idle pooled objects.

Repeating my test cases three times the pool get exhausted using all 120 resources.

### Redis / Jedis Configuration
My configuration is as follows:-
1. Pool configuration
        POOL_CONFIG.setTestOnBorrow(true);
        POOL_CONFIG.setTestOnReturn(false);
        POOL_CONFIG.setTestWhileIdle(false);
        POOL_CONFIG.setMinEvictableIdleTimeMillis(Duration.millis(60*1000).getMillis());
        POOL_CONFIG.setBlockWhenExhausted(false);
       POOL_CONFIG.setMaxTotal(120);
       POOL_CONFIG.setMaxIdle(50);
       POOL_CONFIG.setMinIdle(20);
2. Using Sentinel pool:
    //using try-with-resource
     try(Jedis jedis = jedisSentinelPool.getResource()){
           
       //operations
     }
//I have also one that use finally block as follows
Jedis jedis = jedisSentinelPool.getResource();
try{
   //operation
}catch(Exception e){
   // log exception
}finally {
   if(jedis != null){
          jedis.close();
  }
}

#### Jedis version:
2.9.0
#### Redis version:
Redis 3.2.8
#### Java version:
Java 7

**Comment by ssrinivasulu** [comment]
I'm seeing the same issue where numActive connections keep increasing and not leveraging connections from Idle connections, resulting in connection exception. 

Jedis Version: 2.9.0

Redis Version: 3.2.4

Caused by: redis.clients.jedis.exceptions.JedisException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:51)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:16)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:194)
	... 45 more
Caused by: java.util.NoSuchElementException: Timeout waiting for idle object
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:449)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at redis.clients.util.Pool.getResource(Pool.java:49)
![image](https://user-images.githubusercontent.com/13259535/31316820-288e2fb8-ac03-11e7-8bae-9055d5be5ef4.png)

**Comment by folochina** [comment]
Focus on this

**Comment by marcosnils** [comment]
@folochina. Would you like the help out?. Project is open source and PRs are welcome

**Comment by sazzad16** [comment]
>  ssrinivasulu
Update: 10/19/17
I'm not seeing this issue anymore, the issue was on my side where connections are not handled properly.
