### ISSUE TITLE
Missing method in RedisPipeline interface.

### ISSUE THREAD

**Issue by PhantomThief** [xetorthio/jedis#1524]
Missing method in RedisPipeline interface:

Response<Long> pttl(String key);
Response<String> set(String key, String value, String nxxx, String expx, int time);
Response<String> psetex(String key, long milliseconds, String value);

jedis ver: 2.9.0

**Comment by marcosnils** [comment]
@PhantomThief what about sending a PR as you seem to need them?. We always encourage new contributors!

**Comment by PhantomThief** [comment]
@marcosnils the PR is here:
https://github.com/xetorthio/jedis/pull/1531

while it seemed something wrong in jdk8, i would check later.
