### ISSUE TITLE
redis cluster set key speed is slow than single?

### ISSUE THREAD

**Issue by liuwenru** [xetorthio/jedis#1526]
### Expected behavior

i use this jar to insert 10000 key and value to redis cluster , but the speed is low than single redis ?

### Actual behavior

my code run and result :

![image](https://user-images.githubusercontent.com/7694194/27206359-a3f7fe8e-5269-11e7-9488-2693f0238042.png)

### Steps to reproduce:

this is my [test code]( https://github.com/liuwenru/intelliq-console/blob/dev/src/main/java/RedisTest/RedisClusterThread.java)

**Comment by HeartSaVioR** [comment]
Redis cluster requires client side to calculate key's slot and find which node belong to the slot. So there're some overheads for Redis cluster, hence slower than normal Redis.
Hope this helps.

**Comment by liuwenru** [comment]
@HeartSaVioR  hi , the `jedisCluster` can have any something like pool or cache when we use it can work better
