### ISSUE TITLE
Java equals/hashcode contract broken on Tuple class

### ISSUE THREAD

**Issue by tfeak** [xetorthio/jedis#1533]
### Expected behavior
Tuple hashCode() and equals() implementation should obey the Java contract for these methods.
Per the Java Object hashcode() javadoc:
"If two objects are equal according to the equals(Object) method, then calling the hashCode method on each of the two objects must produce the same integer result."

### Actual behavior
Tuple hashCode() implementation considers the score in its calculation, whereas equals() does not. As a result, you can have 2 Tuples that are equal, with differing hashCodes.

### Steps to reproduce:
This code shows the problem. The 3rd printout should be FALSE, not TRUE.

    public static void main(String[] args) {
        Tuple tuple1 = new Tuple("user1", 10.0);
        Tuple tuple2 = new Tuple("user1", 5.0);

        System.out.println(tuple1.hashCode());
        System.out.println(tuple2.hashCode());

        System.out.println(tuple1.equals(tuple2));
    }

#### Jedis version:
2.9

#### Redis version:
N/A

#### Java version:
1.8

**Comment by marcosnils** [comment]
hey @tfeak thx for reporting. Would you like to help fixing by sending a PR?

**Comment by sazzad16** [comment]
@marcosnils Is it really necessary to have `Tuple`? Isn't it possible to do SortedSet operations by `Map`, `Map.Entry`, similar to (Redis) Hash operations?

**Comment by marcosnils** [comment]
@sazzad16 sadly we can't remove it now as it'll break backwards compatibility.

**Comment by sazzad16** [comment]
@marcosnils May be in a big release in future?

**Comment by sazzad16** [comment]
@marcosnils 

Which answer should we expect from following code, **`[false,2]`** or **`[true,1]`**? (Currently it is `[true,2]`)

```
  public static void main(String[] args) throws Exception {
    Tuple t1 = new Tuple("user1", 10.0);
    Tuple t2 = new Tuple("user1", 5.0);

    HashSet<Tuple> hashSet = new HashSet<Tuple>();
    hashSet.add(t1);
    hashSet.add(t2);

    System.out.println("[" + Objects.equals(t1, t2) + "," + hashSet.size() + "]");
  }
```

**Comment by HeartSaVioR** [comment]
@sazzad16 Above example should be `[false, 2]`.

**Comment by marcosnils** [comment]
@sazzad16 due to latest changes this PR has needs rebasing. Mind rebasing?.

**Comment by sazzad16** [comment]
@marcosnils Rebased :)
