### ISSUE TITLE
Tuple compareTo method incorrectly implemented for use in SortedSet

### ISSUE THREAD

**Issue by tfeak** [xetorthio/jedis#1534]
### Expected behavior
When placing Tuples into a SortedSet, they should not be considered "equal" by compareTo() if equals() would return false.

From the SortedSet JavaDoc.
"Note that the ordering maintained by a sorted set (whether or not an explicit comparator is provided) must be consistent with equals if the sorted set is to correctly implement the Set interface.  (See the Comparable interface or Comparator interface for a precise definition of consistent with equals.)  This is so because the Set interface is defined in terms of the equals operation, but a sorted set performs all element comparisons using its compareTo (or compare) method, so two elements that are deemed equal by this method are, from the standpoint of the sorted set, equal.  The behavior of a sorted set is well-defined even if its ordering is inconsistent with equals; it just fails to obey the general contract of the Set interface."

### Actual behavior
CompareTo() currently short circuits to returning 0 (implying equality) if either the score or element member are equal. This is decidedly different than the implementation of the equals() method. As a result, you can't use Tuple with a SortedSet.

### Steps to reproduce:

This source code demonstrates the issue. Even though the 2 Tuple instances are not equal, the Set has a size of 1 after inserting both objects.

    public static void main(String[] args) {
        Tuple tuple1 = new Tuple("user1", 10.0);
        Tuple tuple2 = new Tuple("user2", 10.0);

        Set<Tuple> tuples = new TreeSet<>();
        tuples.add(tuple1);
        tuples.add(tuple2);

        System.out.println(tuples.size());
        System.out.println(tuple1.equals(tuple2));
    }

#### Jedis version:
2.9
#### Redis version:
N/A
#### Java version:
1.8

**Comment by sazzad16** [comment]
PR #1573

**Comment by sazzad16** [comment]
Resolved by #1573
