### ISSUE TITLE
jedis 2.9.0 in Maven Central is broken, it does not contain the fix from pull request #1368

### ISSUE THREAD

**Issue by stIncMale** [xetorthio/jedis#1536]
The pull request "[Revert empty-list-on-transaction-rollback change. #1368](https://github.com/xetorthio/jedis/pull/1368)" is supposed to be included in jedis 2.9.0, and it was actually merged into branch 2.9 (see commit "[Revert empty-list-on-transaction-rollback change. (#1368)](https://github.com/xetorthio/jedis/commit/b313661712875c2588e2e29b15c0ff55706f39d9)"), but all of this was done after 22-Jul-2016, which is the date of the last update of [redis.clients:jedis:2.9.0 in Maven Central](https://search.maven.org/#artifactdetails%7Credis.clients%7Cjedis%7C2.9.0%7Cjar). 

Thus redis.clients:jedis:2.9.0 in Maven Central does not contain the fix and is broken, and we had troubles because of this. So just for the sake of other people, please remove 2.9.0 from Maven Central (or update it) and definitely put an appropriate note in [release 2.9.0 notes](https://github.com/xetorthio/jedis/releases/tag/jedis-2.9.0).

**Comment by sazzad16** [comment]
@stIncMale Thank you for interest in Jedis. I think, you misunderstood a bit. #1368 was created after release of jedis-2.9.0 and expected to be released in upcoming release (e.g. jedis-2.9.1).

**Comment by stIncMale** [comment]
@sazzad16 Ah, in that case, I'm sorry for the confusion :) Thank you!

**Comment by sazzad16** [comment]
@stIncMale Thank your for understanding :)

**Comment by saketjha-okta** [comment]
These are the only usage of import redis.clients.jedis.Transaction class across peregrine and monolith code base.
