### ISSUE TITLE
no setex method , the method return set's result

### ISSUE THREAD

**Issue by ypg521** [xetorthio/jedis#1538]
why not have setex method ?   the method return set's result . like this:

  
```
  public Boolean setex(final String key, final String value, int seconds){
  
    }
```

just have method :
```
     public void setex(final String key, final int seconds, final String value) {
     }
```

**Sorry for my bad English!**

#### Java version:

1.8

**Comment by bobotianxia** [comment]
nice

**Comment by marcosnils** [comment]
@ypg521 why do you need/want to the Boolean result?. If `seconds` is invalid, then Jedis will throw an exception.
