### ISSUE TITLE
Api for Sync after disconncetion.

### ISSUE THREAD

**Issue by hollakarthik** [xetorthio/jedis#1544]
### Expected behavior
I am using redis without persistence to disk option. When Jedis disconnected with redis , after some time it connects back . I want to add some business logic during re connection like sync the latest data from DB.  Is there any API or hook available for the same?
Write here what you're expecting ...

### Actual behavior
Jedis will reconnect with redis when its back , but no option for the clients of jedis to notify ( apart from constant polling)

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. 
2.
3.

**Comment by marcosnils** [comment]
No, there's not. This should still be achievable when using a single instance as your code should get a JedisConnectionException when there's an error and you can use that to flag the need for a sync in the next run or something.

**Comment by hollakarthik** [comment]
Hi Marcos.
Thanks for the answer. I still have some doubt regarding JedisConnectionException. So what all the cases /scenarios when JedisConnectionException exception is thrown ? Is it only when  Jedis is not able to connect to redis ?

**Comment by hollakarthik** [comment]
@marcosnils  This is still not achievable, lets say when there is a disconnection and its connected back after some time ; if there is no CRUD operation is done during that interval then there wont be any JedisConnectionException will be thrown . So flag logic wont work in this scenario.

**Comment by marcosnils** [comment]
> and its connected back after some time
Jedis doesn't connect back after X time. It does it when you send the next command.
