### ISSUE TITLE
What is the recommended way of setting the maximum number of connections?

### ISSUE THREAD

**Issue by Saketme** [xetorthio/jedis#1549]
My heroku project has a limit of 20 for the maximum number of allowed connections. Although I have already added `maxclients 20` to my `redis.conf` file, do I have to also set this value to Jedis using `JedisPoolConfig#setMaxTotal()`?

#### Jedis version:
2.9.0

#### Redis version:
3.2.9

#### Java version:
8

**Comment by marcosnils** [comment]
Please ask this question in the mailing list. github is used for design discussions and bugs mainly.

http://groups.google.com/group/jedis_redis
