### ISSUE TITLE
JedisCluster Adding Unnecessary Nodes

### ISSUE THREAD

**Issue by KavinKrishnan** [xetorthio/jedis#1551]
So I am trying to set up a JedisCluster to run with my Redis Cluster running on an AWS instance
and was having a problem trying to run it with 6 nodes. The problem occurs even when I do it once node as shown bellow:

I added the master node URI (IP:port) to a Set and pass it to the constructor. Like so:

Set<HostAndPort> redisClusterNodes = new HashSet<HostAndPort>();
redisClusterNodes.add(new HostAndPort([AWS IP in String Form], 7000));
JedisCluster jedis = new JedisCluster(redisClusterNodes);

Since I am currently running the cluster with one node, I thought the JedisCLuster object I created would contain one node [AWS IP]:7000.  Instead it looks like this:

![image](https://user-images.githubusercontent.com/6765823/28334301-96a4beb6-6baf-11e7-8cfc-b7ca059210d8.png)

How do I delete that 127.0.0.1 node from the JedisCluster

### Redis / Jedis Configuration
Jedis Cluster and Redis Cluster

#### Jedis version:
2.8

#### Redis version:
3.2.9

**Comment by marcosnils** [comment]
What does your `cluster slots` command shows in your cluster?

**Comment by KavinKrishnan** [comment]
127.0.0.1:7000> cluster slots
(empty list or set)

**Comment by marcosnils** [comment]
what about `cluster nodes`?

**Comment by KavinKrishnan** [comment]
127.0.0.1:7000> cluster nodes
bdccda3b7495cd08272ab3df43c08ec643d7891d 127.0.0.1:7000 myself,master - 0 0 1 connected

**Comment by marcosnils** [comment]
@kevinsawicki for what I see you didn't configure the cluster slots in your cluster. Can you try fixing that and trying initializing Jedis again?

**Comment by marcosnils** [comment]
I found weird that `nodes` actually shows something as cluster discovery is based on `cluster slots` as you can see here: https://github.com/xetorthio/jedis/blob/2.8/src/main/java/redis/clients/jedis/JedisClusterInfoCache.java#L43-L77 but according to your command, you didn't set any slots.

**Comment by marcosnils** [comment]
Also, you said that you configured your cluster using 6 nodes, but again, the output of `cluster slots` and `cluster nodes` only shows one single node. Seems to me that you didn't configure your cluster nodes correctly

**Comment by KavinKrishnan** [comment]
No I mean, I am currently trying to get it work with one node I had the same problem with six nodes, but to simplify things I am trying to fix the problem using one node.

**Comment by marcosnils** [comment]
@KavinKrishnan in any case, I see that you didn't set the cluster slots for that node. You should assign all the cluster slots for that node in order for RedisCluster to work in a single node.

**Comment by marcosnils** [comment]
@KavinKrishnan just tried to replicate the same scenario with Jedis 2.8  but I couldn't succeed. 
I started a single redis node in cluster node as follows
```
redis-server - <<< "cluster-enabled yes"
```
Then I configured JedisCluster like this:
```java
JedisCluster jc = new JedisCluster(new HostAndPort("localhost", 6379));
```
However, my `nodes` collection is empty.

![image](https://user-images.githubusercontent.com/1578458/28394848-56fef340-6cc6-11e7-81a9-283d15bd796d.png)


Seems like there's something else on your end that causing this problem.

**Comment by KavinKrishnan** [comment]
![image](https://user-images.githubusercontent.com/6765823/28395009-ca2ba780-6ca5-11e7-8063-ba0e3789afd6.png)


Is there any way possible of manually removing that 127.0.0.1:7000 node from the JedisCluster object

**Comment by marcosnils** [comment]
No, the thing is that this shouldn't be happening. Can you share your redis config file?

**Comment by chenbo19867758** [comment]
中国

**Comment by marcosnils** [comment]
?

**Comment by wenjiahao** [comment]
when you create cluster,which ip address you type in ?would you type 127.0.0.1 in your command?

**Comment by sazzad16** [comment]
Closed due to inactivity.
