### ISSUE TITLE
when Jedis support redis4.0 module function?

### ISSUE THREAD

**Issue by jingbanghu** [xetorthio/jedis#1552]
when Jedis support redis4.0 module function?

**Comment by jingbanghu** [comment]
if jedis support command like : jedis.execute("cmdname key value arg1 arg2"), it can slove the problem

**Comment by marcosnils** [comment]
hey @jingbanghu. Not a planned date. We'd love a PR if you need that functionality.

**Comment by jingbanghu** [comment]
@marcosnils sorry,what does PR mean?

**Comment by marcosnils** [comment]
Pull request.

**Comment by jingbanghu** [comment]
fine, i will try it
