### ISSUE TITLE
java.net.SocketTimeoutException: Read timed out; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by ant103** [xetorthio/jedis#1561]
### Expected behavior

No "read time out" should occur.

### Actual behavior

"Read time out" often occurs in a live environment.

### Steps to reproduce:
I understand that this post might not be related to this board, but as I can’t find any solution to it, I am writing here. 
Please understand the situation.

Currently, I am using jedis version 2.1.
I am using pool setting as follow, and I often get “read time out”.

maxActive 600
maxIdle 800
minIdle 10
maxWait 100000

When it occurred, I suspected overload on the expected load capacity. 
However, looking at the server index, I found that it also occurred when there is no overload as well.

It mostly occurs when it is reading hash type data.

If there is anything I can check to solve this, please let me know.

===================================
=> java.net.SocketTimeoutException: Read timed out; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
org.springframework.data.redis.RedisConnectionFailureException: java.net.SocketTimeoutException: Read timed out; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
#011at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:47)
#011at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:37)
#011at org.springframework.data.redis.connection.jedis.JedisConverters.toDataAccessException(JedisConverters.java:117)
#011at org.springframework.data.redis.connection.jedis.JedisConnection.convertJedisAccessException(JedisConnection.java:169)
#011at org.springframework.data.redis.connection.jedis.JedisConnection.get(JedisConnection.java:1008)
#011at org.springframework.data.redis.connection.DefaultStringRedisConnection.get(DefaultStringRedisConnection.java:264)
#011at org.springframework.data.redis.core.DefaultValueOperations$1.inRedis(DefaultValueOperations.java:46)
#011at org.springframework.data.redis.core.AbstractOperations$ValueDeserializingRedisCallback.doInRedis(AbstractOperations.java:51)
#011at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:185)
#011at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:153)
#011at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:86)
#011at org.springframework.data.redis.core.DefaultValueOperations.get(DefaultValueOperations.java:43)
#011at com.nx.npa.dao.impl.NPPKMapDaoImpl.getUserMasterKeyByNxSN(NPPKMapDaoImpl.java:481)

===================================

### Redis / Jedis Configuration
Sentinel 
Master - Slave

#### Jedis version:
2.1

#### Redis version:
2.8.21

#### Java version:
openjdk 1.7

#### Etc:
spring-data-redis 1.1.0
commons-pool 1.5.7

Any help is good.
Thank you.
thanks.

**Comment by marcosnils** [comment]
You're using an extremely old Jedis version which we don't support anymore :(

**Comment by ant103** [comment]
If so, should I upgrade the version?
Is there a problem with changing from 2.1 to 2.7.X?
I am unsure if it is backwards compatible.
Ask for advice.

**Comment by marcosnils** [comment]
@ant103 I think there might be some binary compatibility issues. My suggestion would be to upgrade the dependency and then recompile your app to make sure.

**Comment by ant103** [comment]
Thank you for your kind reply.
I will upgrade according to your advice.
Have a nice day!

**Comment by bandikishores** [comment]
@ant103 We're facing a similar issue in our production boxes. Was your issue resolved on upgrading to newer binaries?
My Service was a legacy service and is using using `spring-data-redis 1.0.0`, It was working fine all these years but from last couple of weeks we started running out of connections in the pool and all our requests are hung at

 ```
java.lang.Thread.State: WAITING
	at java.lang.Object.wait(Native Method)
	- waiting on <28c26a60> (a org.apache.commons.pool.impl.GenericObjectPool$Latch)
	at java.lang.Object.wait(Object.java:502)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1104)
	at redis.clients.util.Pool.getResource(Pool.java:20)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.getConnection(JedisConnectionFactory.java:148)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.getConnection(JedisConnectionFactory.java:41)
```

Finally resulting in 

```
org.springframework.data.redis.RedisConnectionFailureException: java.net.SocketTimeoutException: Read timed out; nested exception is redis.clie
nts.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
        at org.springframework.data.redis.connection.jedis.JedisUtils.convertJedisAccessException(JedisUtils.java:75) ~[iam-service-4.0.37.jar:
4.0.37]
        at org.springframework.data.redis.connection.jedis.JedisConnection.convertJedisAccessException(JedisConnection.java:113) ~[iam-service-
4.0.37.jar:4.0.37]
        at org.springframework.data.redis.connection.jedis.JedisConnection.get(JedisConnection.java:789) ~[iam-service-4.0.37.jar:4.0.37]
        at org.springframework.data.redis.core.DefaultValueOperations$1.inRedis(DefaultValueOperations.java:45) ~[iam-service-4.0.37.jar:4.0.37
]
        at org.springframework.data.redis.core.AbstractOperations$ValueDeserializingRedisCallback.doInRedis(AbstractOperations.java:49) ~[iam-s
ervice-4.0.37.jar:4.0.37]
```

**Comment by bandikishores** [comment]
Found the issue.
In spring-data-redis 1.0.0 version there was a connection leak bug, which was causing this above issue. 

Explanation:
When [RedisTemplate](http://grepcode.com/file/repo1.maven.org/maven2/org.springframework.data/spring-data-redis/1.0.0.RELEASE/org/springframework/data/redis/core/RedisTemplate.java#150) invokes `RedisConnectionUtils.getConnection(factory)`which inturn invokes constructor `JedisConnection(Jedis jedis, Pool<Jedis> pool, int dbIndex)`, then the library was trying to make a call to redis to change the databaseIndex.


```
// select the db
		if (dbIndex > 0) {
			select(dbIndex);
		}
```
Unfortunately, we're facing some network issues these days due to which this call resulted in a SocketTimeout. When an exception is thrown from this particular line, none of the above callers handle this exception and close the connection.
because of which this particular connection is never returned to the pool (Connection leak), resulting in the pool thinking this connection is being used. So overtime all our connections from the pool are getting locked and exhausted finally we end up with the above mentioned trace, where there are no connections available.

As @marcosnils suggested, its better to upgrade the version of spring-data-redis, if you're facing this connection leak.

In our scenario, upgrading spring-data-redis has problems of upgrading other spring dependency framework and aspectj versions which are not compatible with some of our code. We're planning on taking this change as part of a bigger release.

For now, we extended the [RedisTemplate](http://grepcode.com/file/repo1.maven.org/maven2/org.springframework.data/spring-data-redis/1.0.0.RELEASE/org/springframework/data/redis/core/RedisTemplate.java#150) class overriding `execute` method to handle the closing of connections if `getConnection` fails.

PS : I verified in spring-data-redis 1.6.4 and this bug was fixed. (Checked only this version as I wanted redis sentinel feature)

**Comment by mrafeeq** [comment]
I am still having this issue in 1.5.9.RELEASE of  spring-boot-starter-data-redis
am using redis cache in spring boot application v 1.5.9.RELEASE

**Comment by xiongben-tongxue** [comment]
You're using an extremely old Jedis version which we don't support
            ```<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-redis</artifactId>
			<version>1.5.13.RELEASE</version>
		</dependency>```

**Comment by rakeshbmurthy** [comment]
Am using the latest version of Jedis 2.9.0 with spring-data-redis 1.8.14.RELEASE, facing the same issue

**Comment by cechaodeng** [comment]
using the latest version of Jedis 2.9.0 , facing the same issue
![issue](https://user-images.githubusercontent.com/20960990/47549470-c6183b80-d92e-11e8-8f47-a50313ff2841.jpg)

**Comment by Andi-Lo** [comment]
we got the same problem (as @cechaodeng ) with the version

**Comment by jssika** [comment]
we have been seeing these exceptions in live environment. Doesn't seem to happen in nonprod environments .  
" java.net.SocketTimeoutException: Read timed out; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out" 

### Redis / Jedis Configuration

spring-data-redis => 1.8.9.RELEASE 

#### Jedis version: 2.9.0

#### Redis version: 3.2

#### Java version:  1.8

In the above thread it is mentioned that these exceptions could occur if you are using older version of spring-data-redis this could occur , but in our case we are using latest version and we are still seeing these exceptions 
Any clue ? any body?

**Comment by licoco** [comment]
we got the same problem with the version 2.9.0  @marcosnils

**Comment by Felicite93** [comment]
we got the same problem in live production after run 1-2hours:
 nested exception is redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out

spring-data-redis 1.8.6
jedis 2.9.0

any clue?

**Comment by adrian-o** [comment]
Hi guys I don't know if help you, but, im my case, I was trying connect in Redis using SSL in the port 6379 in my localhost. So if possible, verify your connection is using SSL method or not and change de connection parameter to the correct scenario. 
In Spring the parameter to that is **[spring.redis.ssl=true]**

**Comment by galsivan** [comment]
Experiencing same issue. not using spring, but using version 2.9.0. funny thing is that i didn't get this when i was connecting to a redis instance running on a kubernetes cluster.
as soon as we switched to a physical machine - boom. i'll try this ssl thing. maybe it's part of the config of the redis servers that is different between the k8s cluster and the physical ubuntu box.

**Comment by prayjourney** [comment]
just use spring-session-data-redis,
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-data-redis</artifactId>
    </dependency>

**Comment by jjiema** [comment]
> spring.redis.ssl=true

@adrian-o is this in the app properties?

**Comment by jjiema** [comment]
> Hi guys I don't know if help you, but, im my case, I was trying connect in Redis using SSL in the port 6379 in my localhost. So if possible, verify your connection is using SSL method or not and change de connection parameter to the correct scenario.
> In Spring the parameter to that is **[spring.redis.ssl=true]**

@adrian-o is this for the application.properties?

**Comment by LuisEC2016** [comment]
> Experiencing same issue. not using spring, but using version 2.9.0. funny thing is that i didn't get this when i was connecting to a redis instance running on a kubernetes cluster. as soon as we switched to a physical machine - boom. i'll try this ssl thing. maybe it's part of the config of the redis servers that is different between the k8s cluster and the physical ubuntu box.

Excuse me, how do I solve the problem?

**Comment by pankushrii** [comment]
I am facing a similar kind of issue. daily at 12 AM for a few seconds I am getting a time-out. any clue how to fix this?

**Comment by pankushrii** [comment]
> I've the same issue sometimes connecting to AWS Elasticache. After some time (4 - 7 days), connections just start throwing timeout and after a few seconds everything returns to normal. Any clue?

@snaketl  how did you fix this?

**Comment by snaketl** [comment]
Actually never found a way to fix it, in case someone found I way, please share with us :)

**Comment by prayjourney** [comment]
我已收到您的来信，谢谢！祝您生活愉快！

**Comment by rajatjupiter** [comment]
How did we solve this one we are facing the same issue in production.
Libraries Involved:

- JedisVersion: 3.6.0 
- spring-boot-starter-data-redis-2.3.5.RELEASE.
- Redis: AWS Elastic Cache (Cluster Mode Off) (Node: cache.r6g.large)

we are getting intermittent timeouts with error.
error: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out

**Comment by prayjourney** [comment]
我已收到您的来信，谢谢！祝您生活愉快！

**Comment by rajatjupiter** [comment]
> 

hey did you resolve this ?

**Comment by vedev9** [comment]
> Has anyone found a resolution to this issue. I am also currently experiencing this issue.
> 
> ```
> redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
>     at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:208)
>     at redis.clients.jedis.util.RedisInputStream.readByte(RedisInputStream.java:46)
>     at redis.clients.jedis.Protocol.process(Protocol.java:126)
>     at redis.clients.jedis.Protocol.read(Protocol.java:192)
>     at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:316)
>     at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:243)
>     at redis.clients.jedis.Jedis.ping(Jedis.java:356)
>     at redis.clients.jedis.JedisFactory.validateObject(JedisFactory.java:221)
>     at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:343)
>     at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223)
>     at redis.clients.jedis.util.Pool.getResource(Pool.java:38)
>     at redis.clients.jedis.JedisPool.getResource(JedisPool.java:378)
>     at com.moonsidemc.moonsidebungeecore.databasemanager.redis.RedisManager.getJedis(RedisManager.java:42)
>     at com.moonsidemc.moonsidebungeecore.databasemanager.redis.RedisManager.getAllCacheAccountIDs(RedisManager.java:119)
>     at com.moonsidemc.moonsidebungeecore.utilities.StaffChatMethods.sendMessage(StaffChatMethods.java:13)
>     at com.moonsidemc.moonsidebungeecore.databasemanager.redis.utilities.RedisListener.onMessage(RedisListener.java:22)
>     at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:156)
>     at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:125)
>     at redis.clients.jedis.Jedis.subscribe(Jedis.java:7915)
>     at com.moonsidemc.moonsidebungeecore.databasemanager.redis.utilities.RedisConnection.run(RedisConnection.java:14)
>     at java.base/java.lang.Thread.run(Thread.java:831)
> Caused by: java.net.SocketTimeoutException: Read timed out
>     at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283)
>     at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
>     at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
>     at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
>     at java.base/java.net.Socket$SocketInputStream.read(Socket.java:976)
>     at java.base/java.io.InputStream.read(InputStream.java:218)
>     at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:202)
>     ... 20 more
>     ```
> ```

Same here
Have found the reason/solution? 

thanks

**Comment by itsKarad** [comment]
Has anyone found a resolution? I have also tried setting the connection timeout.

**Comment by prayjourney** [comment]
我已收到您的来信，谢谢！祝您生活愉快！

**Comment by juzunoglu** [comment]
Any solutions?

**Comment by prayjourney** [comment]
我已收到您的来信，谢谢！祝您生活愉快！

**Comment by itsKarad** [comment]
What I found:
You can upgrade Jedis and Redis to use newer versions since this issue is reoccurring only in older versions.
**What worked for me:** Since I was using AWS Elasticache, I tried to upgrade the `node_type` of my cache from t2.micro to m4.xlarge, which resolved the issue for me.

[More details ](https://codingchronicles.adityakarad.com/read-timed-out-exception-in-elasticache)

**Comment by queliang96** [comment]
> we have been seeing these exceptions in live environment. Doesn't seem to happen in nonprod environments . " java.net.SocketTimeoutException: Read timed out; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out"
> 
> ### Redis / Jedis Configuration
> spring-data-redis => 1.8.9.RELEASE
> 
> #### Jedis version: 2.9.0
> #### Redis version: 3.2
> #### Java version: 1.8
> In the above thread it is mentioned that these exceptions could occur if you are using older version of spring-data-redis this could occur , but in our case we are using latest version and we are still seeing these exceptions Any clue ? any body?

How did you solve the problem in the end?

**Comment by queliang96** [comment]
What about this problem? How to solve it
