### ISSUE TITLE
jedis borrow null instance from jedisSentinelPool using version 2.7.3

### ISSUE THREAD

**Issue by soulsoul** [xetorthio/jedis#1564]
hi,
   now i use jedis  connect to redis ( server:  Sentinel mode ) . i  got the redis instance from pool. i 
find that the instance is null.    the configuration and code show next:

### Redis / Jedis Configuration
         redis:  Sentinel mode     
#################################################################  

   Jedis jedis = null;
try
{
    jedis = RedisUtils.getJedis();
    tem = jedis.get("REDISUSERINFO_KEY_" + mob);
    log.info("Get UserInfo The Redis Success : " + tem);
}
 catch (Exception e)
{
    log.error("Get UserInfo The Redis Fail :" + e);     
}
finally
{
    RedisUtils.returnResource(jedis);
}
###################################################################

the log file record this:
Get UserInfo The Redis Fail :  java.lang.NullPointException

my jedis configuration is right.  it can work well on some machines , but the error appeard 
on some machines some time.  so i think it is the problem with the jedis jar package.  i 
checked the version change files.  it's different  from version 2.9.  

can somebody tell me why?

#######################################################################
	public static Jedis getJedis() {
		try {
			if (jedisSentinelPool != null) {
				HostAndPort currentHostMaster = jedisSentinelPool
						.getCurrentHostMaster();
				log.info("Redis ip and port: " + currentHostMaster.getHost()
						+ "--" + currentHostMaster.getPort());
				return jedisSentinelPool.getResource();
			}
			return null;
		} catch (Exception e) {
			e.printStackTrace();
		}
		return null;
	}
################################################################################

**Comment by marcosnils** [comment]
Please ask this question in the mailing list. github is used for design discussions and bugs mainly.

http://groups.google.com/group/jedis_redis
