### ISSUE TITLE
Can we disable connections to slave servers ?

### ISSUE THREAD

**Issue by ajay-bhosle** [xetorthio/jedis#1568]
As redis slaves do not server read requests unless you have READONLY on, the slaves do not server any purpose and redirect to master.
Can we disable connections to slave server, we experienced multiple issues like the ones mentioned below

We found out that slaves were not in sync with master, once we synced the slaves then it loaded all the data (45 GB) in memory which took around 30 mins. During this time, the slaves were not able to server any requests and gave an error "Loading data in memory"

**Comment by scyehan** [comment]
I agree with this propose. I read the jedis code 2.9.0, it seems client only connect the slave to update Cluster Slots Map, and never read from or write to the slave.
But slave's  issue also can cause problem to the client.
Rencently it has a malfunction in our company, a del of a huge ZSet block the slave for 43 seconds, and many client applications have problem at that time. We are still studying why slave block can cause client to have problem.

**Comment by sazzad16** [comment]
@ajay-bhosle Jedis doesn't use slaves except for configuration which is necessary. Any alternate suggestion?
