### ISSUE TITLE
Please, consider make a new release

### ISSUE THREAD

**Issue by thibaultmeyer** [xetorthio/jedis#1576]
Hello,

Since September 2016 and more than 600 commits, no new release has been published. It's a bit too long. Could you make a new release with all new fixes and features ?

Perhaps it would be interesting to consider having milestones shorter in term of time and not exceeding 50-60 tasks / milestone.

**Comment by marcosnils** [comment]
hey @0xbaadf00d, we're aware of this. We're only two maintainers at this moment and very inactive. I'll try to check the pending issues this weekend and if there's nothing important we can release.

**Comment by sheinbergon** [comment]
@marcosnils feel free to tag me if anything else needs reference.

**Comment by jiafu1115** [comment]
anyupdate？ we hope new release can be released.Thanks

**Comment by marcosnils** [comment]
I guess the first thing to do would be to check the "Waiting for more reviews" PR's and issues and decide if those should git the 2.x milestone. We need to find the time to go through them and prioritize

**Comment by jiafu1115** [comment]
@marcosnils  Ok, Thanks.

**Comment by ilyabiryukov-r7** [comment]
Any update on this? It'd be nice to release all the good stuff that's been committed in the last 6-8 months.

**Comment by jiafu1115** [comment]
+1. it is time to release new version. It is 2018 now. @marcosnils  @HeartSaVioR @xetorthio

**Comment by sheinbergon** [comment]
@marcosnils @HeartSaVioR  I have some spare time at the moment ( finally) and I'm willing to help with what's required.

**Comment by marcosnils** [comment]
@sheinbergon that'd be awesome. We need to review all the PRs that @sazzad16 has been opening lately and make sure we're not missing any "pending review" important issues or PRs. I was planning to dedicate some time exclusively for this next week but any help before would be really preciated

**Comment by HeartSaVioR** [comment]
Sorry I was very busy handling in other works, and TBH, sadly I'm still busy with another starting work. 
@marcosnils @sazzad16 It would be really helpful and I'd be really appreciated if you could mention me again in PRs which I need to review or make change, so that I can recognize remaining tasks left to me and plan accordingly. Thanks in advance.

**Comment by sheinbergon** [comment]
@marcosnils  @HeartSaVioR  we need to decide on which PRs will make it to the next release first. I'm assuming everything already committed to the master is already considered valid ?

**Comment by sazzad16** [comment]
@HeartSaVioR I believe you are already mentioned in several issues/PRs. If you can't find those, just start from https://github.com/xetorthio/jedis/labels and/or https://github.com/xetorthio/jedis/milestones :)

**Comment by jiafu1115** [comment]
agree with @sheinbergon. Scope decide is the first thing.then can ignore all other PRs to release.Even just release current merged PRs to avoid too many code change involved. WDYT？

**Comment by marcosnils** [comment]
As you may have noticed we've been moving a bit lately merging all the pending PR's and issues. We're aiming for an official release soon, I can't set a date as I don't want to commit to something that IDK when's exactly going to happen. Thanks everyone for the efforts. 

If you desperately need a version to address a specific issue, you can always clone the repo and build your jar with the targets in the makefile.

**Comment by sachinwalia2k8** [comment]
Alternately people who don't want to maintain their own repo can also use jitpack to generate it:
https://jitpack.io/#xetorthio/jedis/master-SNAPSHOT

**Comment by gkorland** [comment]
@marcosnils I think now that we figured up all the technical parts we can release 2.10.0 and 3.0.0-m1
Anything left to be merged to 2.10.0?

Would you like to branch/tag/release and I'll pack and publish the releases?
Or I can do it too.

**Comment by sazzad16** [comment]
@gkorland FYI, https://github.com/xetorthio/jedis/milestones and https://github.com/xetorthio/jedis/labels

**Comment by gkorland** [comment]
@sazzad16 since jedis was not released for very long time I suggest we'll push all the open issues left for 2.10.0 milestone and push those open issue to 3.0.0

**Comment by jiafu1115** [comment]
+1 @gkorland @sazzad16

**Comment by sazzad16** [comment]
2.9.1, 2.10.0, 3.0.0 were released on `Dec 6, 2018`. More releases followed later.
