### ISSUE TITLE
JedisClusterMaxRedirectionsException: Too many Cluster redirections?

### ISSUE THREAD

**Issue by JackyWoo** [xetorthio/jedis#1586]
### Expected behavior

Get a JedisRedirectionException 

### Actual behavior

Get a JedisClusterMaxRedirectionsException 

```
redis.clients.jedis.exceptions.JedisClusterMaxRedirectionsException: Too many Cluster redirections?
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:97)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:131)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:152)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:131)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:152)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:131)
        at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:30)
        at redis.clients.jedis.JedisCluster.get(JedisCluster.java:81)
```

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. build a redis-cluster and send request
2. creash a master node
3. get JedisClusterMaxRedirectionsException

### Redis / Jedis Configuration
Jedis maxRedirection=5
#### Jedis version:
2.8.0
#### Redis version:
3.2.0
#### Java version:
1.7

### Analysis
![image](https://user-images.githubusercontent.com/3991709/29854067-4411beb8-8d76-11e7-9878-ad21d79e0ecf.png)

Seen from the  error stack that program cycles at line 131 and 152 in "JedisClusterCommand" class.
And deep in the code I found in the below case may lead the cycle.

```
key --(hash)--> node A

Step 1: request goes to node A, but node A is not available
Step 2: request goes to random node B and node B reply a moved redirection to node A
Step 3: request goes to node A and node A is not available yet 
Step 4: goes to Step 2 and there is a cycle until redirection reach 5
Step 5: throw "JedisClusterMaxRedirectionsException"
```

I think when node A is not available jedis should return "JedisRedirectionException " but not "JedisClusterMaxRedirectionsException".

PS: there are same issues  but in jedis 2.8.0 the problem is not fixed.

**Comment by sazzad16** [comment]
@JackyWoo When a master node A is not available, Jedis looks for alternate master. It is behaving as expected.

**Comment by JackyWoo** [comment]
hi sazzad16, indeed Jedis looks for another master when master node A is not available. But my point is that in my case Jedis show "JedisClusterMaxRedirectionsException" instead of  "JedisRedirectionException " which indicates the issue obviously.

**Comment by sazzad16** [comment]
@JackyWoo There can be several `JedisRedirectionException` generated in that process. Which one would it throw? So a `JedisClusterMaxRedirectionsException` is thrown. As a bonus, this also means that there has been `maxRedirection` number of attempts made.
