### ISSUE TITLE
Do not know if this is a bug of ShardedJedisPool?

### ISSUE THREAD

**Issue by guoxu0514** [xetorthio/jedis#1588]
Do not know if this is a bug of ShardedJedisPool?

When I use a ShardedJedisPool with 20 shardings, specify testOnBorrow manually with true, and perform 20 ping operations every time before perform a "exists/set..." operation. If I have 40 shardings, 40 pings will be done every time first. 

Redis cpu all resources are spent in the ping operation. 

I feel this design is very unreasonable, because everyone can not use jedis  before read all the source code of jedis to know about every parameters..

jedis version:2.8.1
jdk version:1.8

![image](https://user-images.githubusercontent.com/5442388/29957528-8b8fd918-8f20-11e7-9709-b93083918ded.png)

![image](https://user-images.githubusercontent.com/5442388/29957515-75022764-8f20-11e7-827e-07ced3322e6c.png)

**Comment by marcosnils** [comment]
> When I use a ShardedJedisPool with 20 shardings, specify testOnBorrow manually with true, and perform 20 ping operations every time before perform a "exists/set..." operation. If I have 40 shardings, 40 pings will be done every time first.

That's how `testOnBorrow` works. You can only validate that the connection is alive if you actually send a command to Jedis. What do you propose to improve this situation?. 

If you don't want to deal with this overhead, you can just set `testOnBorrow` to false. I'll close this as it doesn't really opens the discussion for anything.
