### ISSUE TITLE
why JedisCluster doesn't implement parts of ClusterCommands?

### ISSUE THREAD

**Issue by jiafu1115** [xetorthio/jedis#1591]
as titled. Thanks  @HeartSaVioR  @marcosnils 
or can implement some operations no matter with which node receiving the requests can be supported, such as info/nodes

**Comment by marcosnils** [comment]
> or can implement some operations no matter with which node receiving the requests can be supported, such as info/nodes

and what would you send as the node info?. Name?, ip? Can you propose an API for that so we can discuss it?

**Comment by jiafu1115** [comment]
run with random any node.so just part of commands such as "cluster info "can be implemented. we can extract one new interface named ClusterInfoCommands.WDYT.Thanks

**Comment by marcosnils** [comment]
@jiafu1115 I prefer to leave this to the Jedis user. So instead of us deciding which node to send the command, you can just grab the any connection you like and run the command against that node. I prefer not to add code that doesn't seem "right" in Jedis. In any case, I'll leave this open for further discussion.

**Comment by jiafu1115** [comment]
@marcosnils  so if we want to get cluster info, we should use so long statement?
` 		String info=JedisCluster.getClusterNodes().clusterNodes.values().iterator().next().getResource().clusterInfo();`

I understand your point that you does't want to make user confuse. Thus, we may just add some javadoc and we can believe the user had basic knowledge about redis. So I perfer to implement some methods to get basic cluster infos such as slots/nodes/infos.

Or, if we can provide one method to shorter the statement?

such as JedisCluster.getAnyJedisPool().getResource().clusterInfo();`

WDYT? anywhere just want to get cluster info from JedisCluster with so long statement

**Comment by marcosnils** [comment]
@jiafu1115 again, the problem is that retrieving from a random node doesn't sound like a good solution. At some point in time `cluster info` and `cluster nodes` might return different information depending on the node that you're asking because there might be a slot migration in progress or maybe the node that you requested has been left out of the cluster for some reason. As the response is not deterministic I prefer not to expose an API that brings confusion to the users.

**Comment by jiafu1115** [comment]
totally agree with you. so what about provide one method such as JedisCluster.getAnyJedisPool to short the similar long statement to execute cluster related Commands.Thanks

**Comment by marcosnils** [comment]
@jiafu1115 I don't see a benefit in doing such method from the Jedis point of you. You can easily create that function in your application and write your custom logic to return the proper Jedis instance as desired. 
I don't like the idea of adding stuff that doesn't make a lot of sense from a usable point of view. 
@HeartSaVioR , @sheinbergon I'd like to hear your thoughts about this.

**Comment by jiafu1115** [comment]
@marcosnils  Thanks for your comment. And I create one PR #1593  for requirement define. Whatever, just want to simple the code for cluster commands.

**Comment by sheinbergon** [comment]
@marcosnils  I have mixed feelings about this.

Zooming out, we can agree that Redis is an odd-bird in term of clustering support: 

- From one-hand , the clustering solution works for most of the scenarios in a "seamless" manner. By using client side hashing, driver developers such yourself, are able to support of most of the wire protocol without the end-user needing to care about.

- From the other-hand, Redis' clustering solution does not provide a single end-point/namespace to perform all operations. Even though most of the partition-tolerant databases also use client side hashing, solution like ElasticSearch/Couchbase/Cassandra were designed as 'cluster-first' in mind, meaning operations locality is abstracted from the user. That's opposed to Redis, where clustering came as a much, much later addition, which incurred many design problem on libraries like jedis (and Redis itself).  **_I believe that is the reason we are having this discussion to begin with_**

Diving back in, As a driver, I agree with @jiafu1115  Jedis should strive to abstract and simplify as much as possible from the user. **However** - Cluster level Redis operations we're indeed meant to be applied explicitly on specific nodes with full intention that the user **_knows_** which node he's using. IMHO, sticking to the core behavior functionality is the single most important thing a driver can do. So I have to agree with you @marcosnils - Doing a "random" node op is a wrong approach.

We could however make the cluster connection selection API cleaner, and also implement some cluster aware commands to accept node id/ip/index parameters. That might be the the most correct approach possible, considering the current state of things.

@jiafu1115  I have no idea about the actual use-case. Could you shed some light on it ?

**Comment by jiafu1115** [comment]
thanks for your feedback. Totally agree with you.There are two user cases:
1 user want to use jedis to develop one cluster manage tool.such as cluster failover,reset one node.So jedis can have api to help to select the pointed node.
2 user just want to retrieve cluster informations no matter which node response them due to they had known the information is the truth for the node received the request.
so one node selector funtion maybe the final solution for most of cases.
WDYT
Thanks

**Comment by sheinbergon** [comment]
@jiafu1115 I think your 2nd use-case described misses the point. The driver is not supposed to "re-invent/make-up" functionality. Especially not one that was not ever intended to be used by the Redis wire protocol itself.

**Comment by jiafu1115** [comment]
ok. maybe keep it current status is the best solution. though I still feel it is so strange to call so long chain call to just show cluster information from Jedis cluster. Whatever.Thanks for your feedback and joining discussion.

**Comment by sheinbergon** [comment]
@jiafu1115  I agree with you, the API could and should be simplified.
