### ISSUE TITLE
Transaction.exec() erroneously returning empty list instead of NULL (version 2.9)

### ISSUE THREAD

**Issue by issalutfi** [xetorthio/jedis#1592]
Method Transaction.exec() should return null when the reply is null from server, not an empty array. Like so:

    if (unformatted == null) {
      return null;
    }

The code is correct on both the master and 2.9 branch. However, on the commit tagged jedis-2.9.0, it has the incorrect return value:

    if (unformatted == null) {
      return Collections.emptyList();
    }

When we pull down the jar from the maven repository for release 2.9, we’re getting the latter incorrect block (returning an empty list as opposed to a null). So appears that whats published on the maven repositories for version 2.9 is the source tagged jedis-2.9.0. So in addition to the above issue, you may have master/branch/tag out of sync for version 2.9.0.

…master branch
https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/Transaction.java

…2.9.0 branch
https://github.com/xetorthio/jedis/blob/2.9/src/main/java/redis/clients/jedis/Transaction.java

…2.9.0 tag
https://github.com/xetorthio/jedis/blob/jedis-2.9.0/src/main/java/redis/clients/jedis/Transaction.java

**Comment by sazzad16** [comment]
@issalutfi This issue is resolved and will be released in upcoming 2.9.1 and other versions.

**Comment by issalutfi** [comment]
@sazzad16 Thanks!

**Comment by evpaassen** [comment]
Just for future reference, this has already been fixed in #1368. But unfortunately, there hasn't been any release yet.
