### ISSUE TITLE
Jedis returns empty exception message 

### ISSUE THREAD

**Issue by sornalingam** [xetorthio/jedis#1604]
I am using Jedis v 1.5 in production with high load. I have the follwoing code. 

	public boolean write(String key,  String value){
		
		Boolean isSuccess = false;
		Long result = (long) 0;
		
		try{
			
			result = jedis.setnx(key,value);
			jedis.expire(key, TTL);
			if (result == 1){
				isSuccess = true;
			}
			
		} 
		catch (Exception e) {
			AppLogger.EventLogger.error(e.getMessage());    // empty message
		}
		return isSuccess;
		
	}
	
	public String read(String key){
		
		String result = null;
		try{
			result = jedis.get(key);
		}
		catch (Exception e) {
			AppLogger.EventLogger.error(e.getMessage());  // empty message
		}
		return result;
	}
	
	public Long getId(){
		
		Long result = null;
		try {
			result =  jedis.incr("id");   // returns 1 sometimes which is strange
		}
		catch (Exception e) {
			AppLogger.EventLogger.error(e.getMessage());
		}
		return result;
}

Some times it  writes empry exception and when i try to get the id from getId() it returns 1 ( in redis id is 4321134)
I am running with multi thread.

**Comment by sazzad16** [comment]
Jedis 1.5 is not supported anymore.
