### ISSUE TITLE
The count of ScanOptions is invalid

### ISSUE THREAD

**Issue by jnwsczh** [xetorthio/jedis#1607]
### Expected behavior
My English is not good, I hope I can understand the problem
I want to get 100 pieces of data. I use hscan to query, and there is no problem in server-cli.But there are problems in the code
I set the count to 100, but the data is all.Am I wrong?
  ```
Cursor<Map.Entry<byte[], byte[]>> entries = connection.hScan((table_name).getBytes(),ScanOptions.scanOptions().match(param).count(100).build());
        List<Object> result = new ArrayList<>();
        if(entries!=null) {
            while (entries.hasNext()) {
                Map.Entry<byte[], byte[]> entry = entries.next();
                byte[] actualValue = entry.getValue();
                result.add(JSON.parse(actualValue));
            }
        }
```

#### Jedis version:
spring-data-redis-1.8.6.RELEASE
#### Redis version:
Redis-x64-3.2.100
#### Java version:
1.8.0_131

**Comment by sazzad16** [comment]
@jnwsczh 
> I want to get 100 pieces of data.
Redis doesn't do that. Please refer to scan related Redis documentations.

**Comment by Ponmudi0192** [comment]
im facing the same issue. Is there any other way to limit the no. of matching data from redis ?
