### ISSUE TITLE
getSlots does not work properly for binary keys

### ISSUE THREAD

**Issue by allanwax** [xetorthio/jedis#1613]
### Expected behavior
Binary keys should not be parsed for a slot number using `{...}`.  Binary keys should go through a different 
slot parsing method.

### Actual behavior

`getSlot` parses a string key or binary key in the same way looking for a starting {' and an ending '}'

### Steps to reproduce:

run getSlot() on `"{\xbc'\xa2\xba\"}\xce"` and observe that the slot returned is based upon `\xbc'\xa2\xba\` and not the whole binary key

### Redis / Jedis Configuration

any cluster arrangement

#### Jedis version:
2.8
#### Redis version:
3.2.x
#### Java version:
1.8

**Comment by allanwax** [comment]
Imagine that you create keys using the CRC/MD5/etc of a long character string.  Because the net result is basically an array of bits organized as bytes, one of the possible bytes is the '{' or '}' character.  They have special meaning and will cause keys that would have been distributed to one Redis instance in a cluster to go to another instance, possibly producing an imbalance.

Using a String key, this is the documented and expected behavior.  But a binary is just a bunch of bits and should just be accepted as is in my opinion.

Changing current behavior is probably not good for current installations so I'm suggesting that an alternative `getSlot()` be added, with appropriate configuration where the input key is a byte array.

So `getSlot(String key)` would act differently than `getSlot(byte[] key)` and whether any different action is taken would be a configuration item defaulting to the current implementation.

**Comment by mp911de** [comment]
That's not how Redis Cluster works. Calculating a slot hash is primarily intended to talk to the right node in the first place, preventing additional roundtrips. A cluster node itself calculates the slot hash from a given key and redirects the client to the node serving that particular slot if it does not match.

If you want to prevent the effect of running having unintended slot hash tag delimiters in your keys, then escape your keys with base64, hex, …

Your request should rather go to the https://github.com/antirez/redis repo directly as client implementations are mostly a consequence of the server implementation.

**Comment by HeartSaVioR** [comment]
I also think this is a design corner case on Redis, but I guess possibility of binary keys having unintentionally pair of '{}' is not that huge, so key distribution wouldn't hurt too much.
I think @mp911de described enough why it shouldn't be. Closing.
