### ISSUE TITLE
Use  unwatch between multi and exec, and throw NullPointException when executing Exec

### ISSUE THREAD

**Issue by dismasson** [xetorthio/jedis#1614]
### Expected behavior
Unwatch can be exec before execution

### Actual behavior
Use  unwatch between multi and exec, and throw NullPointException when executing Exec

### Steps to reproduce:
        jedis.watch("key");
        Transaction transaction = jedis.multi();
        jedis.unwatch();
        transaction.set("key","value");
        transaction.exec();
#### Jedis version:
2.9.0
#### Java vcersion:
1.7

**Comment by sazzad16** [comment]
Resolved by #2031 and #2032
