### ISSUE TITLE
redis cluster pexpireAt error

### ISSUE THREAD

**Issue by lovyhui** [xetorthio/jedis#1629]
Jedis version: 2.9.0

When I execute `redisTemplate.expireAt(key, new Date(ms));`, `pexpire(key, ms)` was executed finally. It's wrong!

I found the code as below:

![image](https://user-images.githubusercontent.com/11762844/31486767-2867aaca-aefe-11e7-9d7e-2198d235df79.png)

**Comment by marcosnils** [comment]
This is fixed in the upstream branch already. We just need a new releases 

![image](https://user-images.githubusercontent.com/1578458/31498927-a9dec896-af39-11e7-938d-40b98c8e7d41.png)
