### ISSUE TITLE
java.lang.ClassCastException: java.lang.Long cannot be cast to java.util.List

### ISSUE THREAD

**Issue by MSaifAsif** [xetorthio/jedis#1634]
### Expected behavior

I am accessing a `hset` using the following method. The hset can and can not exist and I expect it to return me a `Map<String, String>`. 

```java
public Map<String, String> getHashes() {
        return getClient().hgetAll("channelmanager");
}
```

### Actual behavior

Sometimes it throws an exception as follows

```
java.lang.ClassCastException: java.lang.Long cannot be cast to java.util.List
        at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:233)
        at redis.clients.jedis.Jedis.hgetAll(Jedis.java:796)
```

### Steps to reproduce:

The method used to create connection to jedis

```java
...
jedisClient = new Jedis(redisHost, 6379);
...
jedisClient.hgetAll("myhsetkey");

```

#### Jedis version:

```xml
        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>2.8.1</version>
        </dependency>

```
#### Redis & Java version:

From amazon 3.2.4 Elasticache

**Comment by sazzad16** [comment]
@MSaifAsif There aren't enough info to understand the issue. May be you're using Jedis in multithreaded environment without Pool?

**Comment by marcosnils** [comment]
I'm closing this. @MSaifAsif please comment here and add further info if you still need this to be re-opened.

**Comment by MSaifAsif** [comment]
@marcosnils we can leave it closed at the moment, the issue seems to have disappeared with `2.9.0` without any code change. I just upgraded the library and let it run for a couple of days. Will get back if I stumble upon it again.
