### ISSUE TITLE
Support auth/requirepass on sentinels

### ISSUE THREAD

**Issue by marianowadel** [xetorthio/jedis#1636]
Hello, and first of all, sorry if I am wrong posting here. 
I cannot seem to connect to sentinels configured with `requirepass`, as explained [here](https://github.com/antirez/redis/pull/3329). 
I am talking about `requirepass` set for the sentinel in sentinel.conf, not for the redis server itself (which has `requirepass` set already). My configuration is as follows: 

	RedisSentinelConfiguration sentinelConfiguration = new RedisSentinelConfiguration();
	sentinelConfiguration.setSentinels(this.redisNodes);
	sentinelConfiguration.setMaster(this.masterName);
	sentinelConfiguration.setPassword(RedisPassword.of(password));
	JedisClientConfiguration clientConfiguration = JedisClientConfiguration.builder().connectTimeout(Duration.ofSeconds(this.timeout)).readTimeout(Duration.ofSeconds(this.timeout)).usePooling().build();
	JedisConnectionFactory factory = new JedisConnectionFactory(sentinelConfiguration, clientConfiguration);

Whenever I try to connect, I get `redis.clients.jedis.exceptions.JedisDataException: NOAUTH Authentication required`. 
I tried debugging the connection, and saw that no password is used in the [initSentinels](https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/JedisSentinelPool.java#L130) method.
Am I doing something wrong? Is this setup supported? If not, will it ever be?
I am using the latest stable version 2.9.0.
Many thanks in advance.

**Comment by manucr619** [comment]
is there any update on this thread?

Is there any alternate for this to use?

**Comment by manucr619** [comment]
@marianowadel we extracted the jar and passed the sentinel password through every method. Will it be ok? @xetorthio

**Comment by ssouris-te** [comment]
Apparently, after Redis 5.0.1 they now support authentication at the Sentinel [Release notes](https://raw.githubusercontent.com/antirez/redis/5.0/00-RELEASENOTES), 
Are there any plans to fix this?

**Comment by ssouris** [comment]
Apparently, after Redis 5.0.1 they now support authentication at the Sentinel Release notes,
Are there any plans to fix this?

**Comment by sazzad16** [comment]
Resolved by #1943
