### ISSUE TITLE
JedisCluster Could not return the resource to the pool 

### ISSUE THREAD

**Issue by 18099538715** [xetorthio/jedis#1643]
Hi  ,when I using jedisCluster，
Getting "redis.clients.jedis.exceptions.JedisException: Could not return the resource to the pool\n\tat redis.clients.util.Pool.returnBrokenResourceObject(Pool.java:96)\n\tat redis.clients.jedis.JedisPool.returnBrokenResource(JedisPool.java:235)\n\tat redis.clients.jedis.Jedis.close(Jedis.java:3419)\n\tat redis.clients.jedis.JedisClusterCommand.releaseConnection(JedisClusterCommand.java:172)\n\tat redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:166)\n\tat redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:33)\n\tat redis.clients.jedis.JedisCluster.setex
 
then I see the code as follow 
   } finally {
   releaseConnection(connection);   166   here throws  the  exception1 
    }

also it uses
returnBrokenResource(JedisPool.java:235) method ,so there must be another exception2 before.

so I think exception1 override the exception2 ,then  I cannot find out the true reason .

**Comment by marcosnils** [comment]
Can you please provide a reproducible example?. Otherwise it's hard to assist.
