### ISSUE TITLE
Redis 4.x

### ISSUE THREAD

**Issue by khoying** [xetorthio/jedis#1645]
Does jedis work with Redis 4.x versions?  We recently upgraded and are having issues.

**Comment by jamon4j** [comment]
I also want to know

**Comment by sazzad16** [comment]
@khoying Could you explain what kind of issues you are having?

**Comment by seungdols** [comment]
According to opinion of my colleuge, jedis of current version have issue.

cluster node print out to`host:portnumber@data-port-number` so, jedis don't working it.  plus data port number format.

when parsing of cluster nodes info, occur numberFormatException at jedis. maybe changed nodes print format in redis version 4.x.

**Comment by Hronom** [comment]
Guys sorry for rising this again, what the status, does anyone test it with the latest version? Is it compatible?

**Comment by manojramuk100** [comment]
Does Guava jar conflict with the HostAndPort class while parsing the portnumber@cluster-busport ?
