### ISSUE TITLE
Request for Jedis API  for Modules in Redis 

### ISSUE THREAD

**Issue by karthik56** [xetorthio/jedis#1650]
Is there any plan to introduce a generic API to execute modules (https://redis.io/modules) in jedis. Currently we are supposed to use eval and execute lua script to achieve module queries. However redis doesn't allow blocking commands inside script. If the module contains any blocking commands then it can't be executed in eval. So can you guys please provide a generic API for executing module commands in jedis. 

Required API's : 
1) loadModule(Modulefile)
2) executeModule(String command) -> It's return type can be object. In the app logic we can identify the type of it.

**Comment by sazzad16** [comment]
Related #1713
