### ISSUE TITLE
JedisSentinelPool JedisDataException Write Against Slave

### ISSUE THREAD

**Issue by djole103** [xetorthio/jedis#1657]
Trying a `set` after a `getResource` from a default configured `JedisSentinelPool` and receiving a:
`JedisDataException occurred : READONLY You can't write against a read only slave.`

Running Redis server v=3.2.10, 2 slaves and 3 sentinels all configured correctly. Java 8. Jedis 2.9.

Any ideas why I may be getting this error?

Side-question: why can I still send commands across a Jedis client after having `.close()`'d it?

Thank you

**Comment by sazzad16** [comment]
1. It seems like you have set such a Redis instance as master of sentinel which is slave of some other instance.
2. It's because before executing a command Jedis connects with Redis. So if it was closed before, it gets reconnected again and executes command.
