### ISSUE TITLE
fetch  info with method georadius 

### ISSUE THREAD

**Issue by Jakesd** [xetorthio/jedis#1660]
### Expected behavior

I wanna search sth with method georadius 

### Actual behavior
I  got the response list actually, but in the item of the list, the coordinate is null , and the distance is 0.0

#### Jedis version:
2.9.0
#### Redis version:
3.2.100
#### Java version:
1.8

**Comment by Jakesd** [comment]
I'm looking forward to your solution,thanks

**Comment by sazzad16** [comment]
@Jakesd Could you be more elaborate and share something (e.g. codes) to reproduce the issue?

**Comment by sazzad16** [comment]
Closed due to inactivity.
