### ISSUE TITLE
Hgetall returns {} for data which exists.

### ISSUE THREAD

**Issue by mominfazal** [xetorthio/jedis#1672]
### Expected behavior

I am putting a load of about 500 requests simultaneously to complete a total of 10000 requests. Multithreading using executors with 10 parallel execution.

I want same output for every request. 
Eg: jedis.hgetall(myhash)
OP: {"field1":"Hello","field2":"World"}

### Actual behavior

For about 9950 requests output is:
Eg: jedis.hgetAll(myhash)
OP: {"field1":"Hello","field2":"World"}

For about 50 requests output is:
Eg: jedis.hgetAll(myhash)
OP: {}

#### Java version:1.8.0_131 

Code:
allData = jedis.hgetAll(key); 
System.out.println(allData);

**Comment by sazzad16** [comment]
Using Jedis 2.9.0, I had no issue for even 1000000 requests and I just didn't try more requests.
