### ISSUE TITLE
Jedis Multithreading issues

### ISSUE THREAD

**Issue by kavySh** [xetorthio/jedis#1691]
Hi,
### Expected behavior
Jedis Multi threading should work with out exception - Could not return resource to pool and cast exception some times
### Actual behavior
We are using compose for redis service to cache data from our maven application. we are trying to implement multi threading concept using jedis. When we are trying to run for 5 threads 2 or 3 threads will fail saying below error attached in logs.
version in our pom.xml.
<groupId>redis.clients</groupId>
<artifactId>jedis</artifactId>
<version>2.9.0</version>

### Steps to reproduce:
I have included ThreadTest.zip that has source code that we are using. 
You might get exceptions for logs and util methods used, (please import jars necessary, sorry for inconvenience)

### Redis / Jedis Configuration
InControlCache constants has information about redis service used
#### Jedis version:
2.9.0
#### Redis version:
[threadTesting.zip](https://github.com/xetorthio/jedis/files/1538781/threadTesting.zip)

#### Java version:
8

I have attached logs for exceptions faced.
[threadTesting.zip](https://github.com/xetorthio/jedis/files/1538782/threadTesting.zip)
[JedisMultiThreadingLogs.txt](https://github.com/xetorthio/jedis/files/1538783/JedisMultiThreadingLogs.txt)

Thanks in advance.

**Comment by marcosnils** [comment]
@kavySh can you please isolate the example into a more readable and minimum code?. We really don't have the time to go and dive into app specific examples.

**Comment by kavySh** [comment]
Hi marc,
I apologize to have put so much code. Please check the attachment. It has 3 files, start from threadTesting.java. I hope this would be better for you to understand. I do not want to move everything to one file because I want you to understand how its initialized from our app, so you could be able to reproduce the issue what we are facing. Please let me know if any concerns.
[threadTesting.zip](https://github.com/xetorthio/jedis/files/1544716/threadTesting.zip)

**Comment by marcosnils** [comment]
hi @kavySh the code that you sent doesn't compile. It's missing several imports, some `@override` annotations are incorrect and the `getJedisConnection` method is incorrect. Can you plz fix this issues and share again?

**Comment by marcosnils** [comment]
@kavySh also take into account that the sources you've attached contain sensitive information about your environment like host and passwords. I'd strongly advise to change that and to remove it from the sources.

**Comment by marcosnils** [comment]
@kavySh after looking at the code found the issue. The `Jedis` field in the CacheServiceImpl is `static` which shouldn't be. Changing that and running the example again should work.

**Comment by kavySh** [comment]
Thanks so much. It worked.
