### ISSUE TITLE
redis.clients.jedis.exceptions.JedisDataException: ERR unknown command 'AUTH' for jedis version -- 2.9.0

### ISSUE THREAD

**Issue by banbeishui** [xetorthio/jedis#1708]
### Expected behavior
connect redis successfully

### Actual behavior

redis.clients.jedis.exceptions.JedisDataException: ERR unknown command 'AUTH'

### Redis / Jedis Configuration
            GenericObjectPoolConfig genericObjectPoolConfig = new GenericObjectPoolConfig();
            genericObjectPoolConfig.setMaxIdle(30);
            genericObjectPoolConfig.setMaxTotal(1024);
            genericObjectPoolConfig.setMinIdle(0);
            JedisCluster jc = new JedisCluster(jedisClusterNodesSet, 1500, 2000, 2, password, genericObjectPoolConfig);

#### Jedis version:
2.9.0
#### Redis version:
2.8.19
#### Java version:
1.8.0_51

**Comment by sazzad16** [comment]
@banbeishui Could you give more info, e.g. error logs?

**Comment by sazzad16** [comment]
Closed due to inactivity.

**Comment by HJacco** [comment]
how about this issue? Is there some solution now?

**Comment by SkyGrass** [comment]
same issue

**Comment by sazzad16** [comment]
Please your Redis instance(s). `AUTH` command is disabled there.
