### ISSUE TITLE
Should only have one thread renewal cluster slots under concurrency situation

### ISSUE THREAD

**Issue by flygit** [xetorthio/jedis#1711]
When 100 threads access to redis cluster on MOVE response, all the threads will get slots information. 

Can only have one thread renewal cluster slots under concurrency situation. When renewal process is completed, others should first check slots infosmation to decide whether renewal again. 

#### Jedis version:
2.9.0

#### Redis version:
3.x.x

#### Java version:

Java 8

**Comment by sazzad16** [comment]
Jedis already does what you've suggested.

https://github.com/xetorthio/jedis/blob/6c3e6d2e5752af2cd22f4fc56ae83c5282e5d4c6/src/main/java/redis/clients/jedis/JedisClusterInfoCache.java#L84-L85
