### ISSUE TITLE
Module command option in Jedis/BinaryJedis

### ISSUE THREAD

**Issue by sazzad16** [xetorthio/jedis#1713]
Currently, the only option to call module command is by using `Connection.sendCommand(ProtocolCommand, ...)`.

https://github.com/xetorthio/jedis/blob/6c3e6d2e5752af2cd22f4fc56ae83c5282e5d4c6/src/test/java/redis/clients/jedis/tests/ModuleTest.java#L41

Getting the output is solely upon the user, again using the `Connection` class.

https://github.com/xetorthio/jedis/blob/6c3e6d2e5752af2cd22f4fc56ae83c5282e5d4c6/src/test/java/redis/clients/jedis/tests/ModuleTest.java#L42

@HeartSaVioR @marcosnils 
Would we add an easier option in `Jedis` and/or `BinaryJedis` for this purpose? If so, how?

Related to #1554

**Comment by diegopacheco** [comment]
@marcosnils @xetorthio @sazzad16 

I'm looking forward to having generic commands support for Redis Modules in Jedis. 

In my use case, I'm doing some custom commands support like: happened,hstrlen,hgetrange,hsetrange,hincrby. So this commands will have a custom redis module. IF my understanding is correct Jedis does not support Redis Modules. So If redis has someone to send generics commands this would be useful for anyone who is using Redis-Modules. 

I did code some generic commands here: https://github.com/xetorthio/jedis/pull/1716 

Please give me your feedback and concerns. 

Cheers,
Diego Pacheco

**Comment by mp911de** [comment]
Similar situation in [Lettuce](https://github.com/lettuce-io/lettuce-core/issues/247). I think there are two separate use-cases:

1. User wants to use a particular module to invoke commands
2. Administrative user wants to enable/configure modules

The first one would be more common, the second one would be of interest to administrative tools/GUIs. From the client user landscape, there aren't too much admin clients and most could use custom command APIs anyway (`sendCommand(…)`).

IMHO module integrations should stay outside of the core client itself. Client addons should get implemented as a side project of the actual module.

**Comment by marcosnils** [comment]
> IMHO module integrations should stay outside of the core client itself. Client addons should get implemented as a side project of the actual module.

I like this. Let the module developers make a friendly SDK to interact with their modules.

**Comment by dvirsky** [comment]
As a module developer, this is the right approach. What's sorely missing as an official released version of Jedis that supports this.

**Comment by sazzad16** [comment]
Current approach seems enough for module developers. Closing this issue.

Just tagging @HeartSaVioR for convenience.

**Comment by marcosnils** [comment]
@dvirsky thx for the input. @sazzad16 is doing an amazing work pushing forward for a release. We're aiming for the next week. Keep an eye on the releases.

**Comment by dvirsky** [comment]
@marcosnils @sazzad16 thanks, eagerly waiting for this. I've been using an unstable version of Jedis for my client for the past 10 months or so. I'll finally be able to create a proper maven build for it :)

**Comment by StephenOTT** [comment]
Looking forward to it!  reJSON Module +1

**Comment by dvirsky** [comment]
@StephenOTT it already has a Jedis based client, but it uses an unreleased version of it. https://github.com/RedisLabs/JReJSON
