### ISSUE TITLE
When use JedisSentinelPool(masterName, sentinels, poolConfig, timeout, password) create sentinel pool; timeout value does not effect

### ISSUE THREAD

**Issue by johneexu** [xetorthio/jedis#1720]
**Expected behavior**

JedisSentinelPool connect sentinels use assigned timeout value.

**Actual behavior**

when use 
JedisSentinelPool jedisSentinelPool = new JedisSentinelPool(masterName, sentinels, poolConfig, timeout, password);
to connect to sentinel to read redis master host and port, JedisSentinelPool  use default 2000 mili seconds timeout value （ Protocol.DEFAULT_TIMEOUT ），but not assigned timeout.

see source code ：

  public JedisSentinelPool(String masterName, Set<String> sentinels,
      final GenericObjectPoolConfig poolConfig, final int connectionTimeout, final int soTimeout,
      final String password, final int database, final String clientName) {
    this.poolConfig = poolConfig;
    this.connectionTimeout = connectionTimeout;
    this.soTimeout = soTimeout;
    this.password = password;
    this.database = database;
    this.clientName = clientName;

    HostAndPort master = initSentinels(sentinels, masterName);
    initPool(master);
  }

  private HostAndPort initSentinels(Set<String> sentinels, final String masterName) {

    HostAndPort master = null;
    boolean sentinelAvailable = false;

    log.info("Trying to find master from available Sentinels...");

    for (String sentinel : sentinels) {
      final HostAndPort hap = HostAndPort.parseString(sentinel);

      log.fine("Connecting to Sentinel " + hap);

      Jedis jedis = null;
      try {
        jedis = new Jedis(hap.getHost(), hap.getPort());

        List<String> masterAddr = jedis.sentinelGetMasterAddrByName(masterName);
...........

      here use default connection timeout to create jedis:

        jedis = new Jedis(hap.getHost(), hap.getPort());

     if timeout been assign value or send from default, then use it , if shoule be

     private HostAndPort initSentinels(Set<String> sentinels, final String masterName, final int connectionTimeout) {
    .....
    jedis = new Jedis(hap.getHost(), hap.getPort(),connectionTimeout);

 ....

    test it works 

**Redis / Jedis Configuration**
blew api can reproduce issue: set timeout value to 20 millisencond

1. JedisSentinelPool jedisSentinelPool = new JedisSentinelPool(masterName, sentinels, poolConfig, 20, password);
2.JedisSentinelPool jedisSentinelPool = new JedisSentinelPool(masterName, sentinels, poolConfig, 20);
3. JedisSentinelPool jedisSentinelPool = new JedisSentinelPool(masterName, sentinels, poolConfig, 20,0);
4. JedisSentinelPool jedisSentinelPool = new JedisSentinelPool(masterName, sentinels, poolConfig, 20,0,clientName);

**Jedis version:**
2.9.0

**Redis version:**
3.2.8

**Java version:**
1.8.0_51

**Comment by johneexu** [comment]
may be below is better
jedis = new Jedis(hap.getHost(), hap.getPort(),connectionTimeout,soTimeout);

**Comment by sazzad16** [comment]
@johneexu You are welcome to craft a PR. Thanks!

**Comment by sazzad16** [comment]
Closed due to inactivity.
