### ISSUE TITLE
 Could not get a resource from the pool

### ISSUE THREAD

**Issue by stjava** [xetorthio/jedis#1724]
When jedis connects to a cluster, a value can be obtained, but a value can not be set.
Mistake: Could not get a resource from the pool

But it can set and take values through redis-cli connections

![image](https://user-images.githubusercontent.com/20898173/34289620-4998b686-e72e-11e7-8c6c-cc839c49cc3a.png)
![image](https://user-images.githubusercontent.com/20898173/34289635-59ee58c4-e72e-11e7-8d9d-2125dd9f4c8f.png)

**Comment by stjava** [comment]
But the problem is only on the public net, like 211.211.211.211
If it's an intranet, like 192.168.1.1, it won't happen.

**Comment by sazzad16** [comment]
I think, your Redis cluster is created using _intranet_. In such case, Jedis is working properly.
