### ISSUE TITLE
question

### ISSUE THREAD

**Issue by 18099538715** [xetorthio/jedis#1725]
In  JedisClusterCommand.java file  line  126(master)
  
```
   catch (JedisConnectionException jce) {
      releaseConnection(connection);
      connection = null;

      if (attempts <= 1) {
        this.connectionHandler.renewSlotCache();
        throw jce;
      }
```

when  releaseConnection(connection) got exception ,I will lose exception jce. Is that a problem?

**Comment by sazzad16** [comment]
@18099538715 Are you having any issue because of this? Or, do you have any alternate suggestion about this?

**Comment by sazzad16** [comment]
Closed due to inactivity.
