### ISSUE TITLE
Type safe keys

### ISSUE THREAD

**Issue by OndraZizka** [xetorthio/jedis#1745]
### Current behavior

Currently, you can do:

    jedis.hset("foo", "bar");
    jedis.get("foo");

That is easy to overlook on review (nothing hints the key is for a hash) and will end with a runtime exception.

### Suggested behavior

    public String hget(final String key, final String field) { }

    public class HashKey {
           public HashKey(String key) { ... }
    }
    public default String hget(final HashKey hkey, final String field) {
           return hkey.getKey();
    }

This would prevent such mistakes:

    public static final HashKey KEY_FOO = new HashKey("foo");
    
    jedis.key(KEY_FOO);  // Compilation error
    jedis.hkey(KEY_FOO); // Nicely works with code-completion as a bonus.

#### Jedis version:
2.9.0

**Comment by sazzad16** [comment]
@OndraZizka This alters user's data which we don't want.

**Comment by OndraZizka** [comment]
@sazzad16  What do you mean by that?

**Comment by OndraZizka** [comment]
Note for myself:
 (.*) h(.*)\(String key(.*)\);
default $1 h$2(HashKey key$3) { return h$2(key.getKey()$3); }

**Comment by OndraZizka** [comment]
I am still not sure what @sazzad16  meant by "alters user's data".

**Comment by sazzad16** [comment]
@OndraZizka Before your post was edited, it seemed to me you were talking about adding a prefix to user provided key which would alter (modify) user provided key.

However, about your current logic:
What if wrong type of key is created as below?
```
public static final HashKey KEY_FOO = new HashKey("foo");
public static final HashKey KEY_BOO = new StringKey("foo");

jedis.key(KEY_BOO);  // No compilation error, but runtime error
jedis.hkey(KEY_FOO);
```

Users have to know about the key type before creating the object. If a user can create an object which is safe to use, IMHO, s/he is able to do safe operations as well.

**Comment by OndraZizka** [comment]
What do you mean by `jedis.key(KEY_BOO)`? There's no such method: http://static.javadoc.io/redis.clients/jedis/2.9.0/redis/clients/jedis/Jedis.html

**Comment by OndraZizka** [comment]
I assume you mean get/hget.
In which case, that's exactly the point of the change: To reduce the places where you can make errors to the definition of constants. These constants can be maintained by an app architect. And then other developers who use them would not be able to use wrong Jedis method with given key constant.

Ofcourse, someone could create their own constant. But why would they do it?

**Comment by sazzad16** [comment]
@OndraZizka You assumed right. Sorry about my mistakes in previous comment.

Jedis tries to keep itself simple. Your suggestion opposes this intent. If the app architect and other developers want to be safe, they can easily build something on top of or based on Jedis.

Still not satisfied? You're welcome in [Jedis mailing list](https://groups.google.com/forum/#!forum/jedis_redis). Thanks!

**Comment by OndraZizka** [comment]
@sazzad16, I agree it should be simple. In my opinion, this is a simplification - developers would not have to remember which key leads to what type.

Okay, I will open this topic in the mailing list. Thanks.

**Comment by SirGlorg** [comment]
@sazzad16 looks like a strongly-typed approach to me, that's all. Using string / int / boolean as passed arguments is in general unsafe approach, and the encapsulation within a strongly typed carrier objects doesn't feel like much of a simplicity breaking change. However the strongly-typed coding is often a matter of belief and there's no strict rule to whether it's useful or not. Overdoing that may lead to a code polluted with thousands of arbitrary classes, however in some cases it may be a way forward. From the short overview of this case, I'd vote for the later and the change looks beneficial to me.
