### ISSUE TITLE
ShardedJedisPool.getResource blocked forever

### ISSUE THREAD

**Issue by henryZhangDev** [xetorthio/jedis#1764]
### Expected behavior

getResouce should return quickly under not heavy load environment

### Actual behavior

getResource got blocked forever, and core dump shows more than 200 threads wait lock as the following:
    4 "http-bio-1602-exec-696" daemon prio=10 tid=0x00007f5714422800 nid=0x3bdc waiting on condition [0x00007f53c84c2000]
    5    java.lang.Thread.State: WAITING (parking)
    6         at sun.misc.Unsafe.park(Native Method)
    7         - parking to wait for  <0x00000006801fbb70> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    8         at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
    9         at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
   10         at org.apache.commons.pool2.impl.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:583)
   11         at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:442)
   12         at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
   13         at redis.clients.util.Pool.getResource(Pool.java:49)
   14         at redis.clients.jedis.ShardedJedisPool.getResource(ShardedJedisPool.java:36)
   15         at com.jd.jss.service.cache.RedisCacheServiceImpl.get(RedisCacheServiceImpl.java:62)
### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

### Redis / Jedis Configuration
    <bean id="jedisPoolConfig" class="redis.clients.jedis.JedisPoolConfig">
        <property name="maxTotal">
            <value>20</value>
        </property>
        <property name="maxIdle">
            <value>5</value>
        </property>
        <property name="testOnBorrow" value="true"/>
        <property name="testOnReturn" value="true"/>
    </bean>

    <bean id="shardedJedisPool" class="com.jd.jss.service.cache.redis.clients.jedis"  scope="singleton">
        <constructor-arg index="0" ref="jedisPoolConfig" />
        <constructor-arg index="1">
            <list>
                <bean class="redis.clients.jedis.JedisShardInfo">
                    <constructor-arg name="host" value="${redis.uri}" />
                </bean>
            </list>
        </constructor-arg>
    </bean>
#### Jedis version:
2.9.0
#### Redis version:
3.2.11
#### Java version:
1.7

code snippet:

        String result = null;
        ShardedJedis shardedJedis = null;
        try{
            String redisKey = redisKey(object.getClass(), key);
            RunLog.LOG.info("{} set key={} into redis begin",PREFIX, redisKey);
            shardedJedis = shardedJedisPool.getResource();
            result = shardedJedis.setex(redisKey, expireInSec, JSON.toJSONString(object));
            RunLog.LOG.info("{} set key={} into redis end",PREFIX, redisKey);
        }finally {
            if (shardedJedis!=null)
                shardedJedis.close();
        }
the thread got stuck at getResource() method call.
The i monitor the resource occupy by override ShardedJedisPool class and ran testing under much higher load, but not reproduce the issue after more than one day.
the only difference is i replace shardedJedis.close() call with shardedJedisPool.returnResource(shardedJedis) (it's deprecated)

**Comment by sazzad16** [comment]
@henryZhangDev Try `setMaxWaitMillis` of GenericObjectPoolConfig.

**Comment by henryZhangDev** [comment]
Thanks, the root cause has been found, actually we forget to return resource to the pool, and also we set MaxWaitMillis in case to avoid issue in the futher, thanks a lot @sazzad16
