### ISSUE TITLE
JedisCluster cannot connect to redis cluster with password

### ISSUE THREAD

**Issue by bylijinnan** [xetorthio/jedis#1766]
https://stackoverflow.com/questions/48659715/jediscluster-cannot-connect-to-redis-cluster-with-password

Thank you very much!

**Comment by sazzad16** [comment]
@bylijinnan First check https://stackoverflow.com/questions/6876266/java-net-connectexception-connection-refused

Thanks!

**Comment by bylijinnan** [comment]
Thank you @sazzad16 

forgive my poor English. 
Let me show the code:

//it's successful to connect to all master nodes and get the keys' value
    @Test
    public void testOneByOne() {
        String[] keys = new String[] {
                "b",
                "c",
                "a"

        };
        for (int i = 0; i < 3; i++) {

            Jedis jedis = new Jedis("{myIp}", 5067 + i * 100);
            jedis.auth("{myPassword}");
            String a = jedis.get(keys[i]);
            System.out.println(a); //ok
        }
    }

    //all the masters and slaves can be connected, network is ok.
    @Test
    public void testConnectFromSourceCode() throws Exception {
        for (int i = 0; i < 6; i++) {
            int port = 5067 + i * 100;
            Socket socket = new Socket();
            socket.setReuseAddress(true);
            socket.setKeepAlive(true);
            socket.setTcpNoDelay(true);
            socket.setSoLinger(true, 0);
            socket.connect(new InetSocketAddress("{myIp}", port), 2000);
            socket.setSoTimeout(2000);
            System.out.println("port=" + port + "," + socket.isConnected());//isConnected=true
        }


    }

    //# error:
    // redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
    //Caused by: java.net.ConnectException: Connection refused: connect
    @Test
    public void testJedisCluster() {
        JedisPoolConfig jedisPoolConfig = new JedisPoolConfig();
        jedisPoolConfig.setMaxTotal(10);
        jedisPoolConfig.setMaxIdle(5);
        jedisPoolConfig.setMinIdle(5);
        jedisPoolConfig.setMaxWaitMillis(300000);
        jedisPoolConfig.setTestOnBorrow(true);
        jedisPoolConfig.setTestOnReturn(true);
        jedisPoolConfig.setTestWhileIdle(true);

        HostAndPort hostAndPort = new HostAndPort("{myIp}", 5067);
        JedisCluster jc=new JedisCluster(hostAndPort, 2000,2000,5, "{myPassword}", jedisPoolConfig);
        String a = jc.get("a");
        System.out.println(a);
    }

**Comment by bylijinnan** [comment]
cluster-announce-ip solved my problem
