### ISSUE TITLE
api should be more

### ISSUE THREAD

**Issue by power-man** [xetorthio/jedis#1768]
Some command can't be found like add node,reshard,del-node.And command "cluster forget" doesn't work 
well ,the node will back in a minute

**Comment by power-man** [comment]
here is my code:

`package com.example.test;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.springframework.beans.factory.annotation.Autowired;

/**
 * Hello world!
 *
 */


import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.data.redis.RedisProperties;
import org.springframework.boot.autoconfigure.data.redis.RedisProperties.Sentinel;
import org.springframework.cloud.netflix.eureka.EnableEurekaClient;
import org.springframework.context.annotation.Bean;
import org.springframework.data.redis.connection.RedisServerCommands;
import org.springframework.data.redis.connection.jedis.JedisClusterConnection;
import org.springframework.data.redis.connection.jedis.JedisConnection;
import org.springframework.data.redis.connection.jedis.JedisConnectionFactory;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.web.client.RestTemplate;

import redis.clients.jedis.HostAndPort;
import redis.clients.jedis.Jedis;
import redis.clients.jedis.JedisCluster;
import redis.clients.jedis.JedisClusterCommand;
import redis.clients.jedis.JedisPool;
import redis.clients.jedis.JedisPoolConfig;
import redis.clients.jedis.JedisSentinelPool;


@SpringBootApplication
@EnableEurekaClient
public class App {
	

//	   @Bean  
//		 public RedisServerCommands getRedisCommands(){
//		   
//		   JedisConnection jedisClusterConnection = new JedisConnection(new Jedis("10.10.68.43", 6379));
//	        return jedisClusterConnection;
//			 
//		 } 

	   @Bean  
		 public JedisClusterConnection getRedisCommands(){
		   Set<HostAndPort> jedisClusterNodes = new HashSet<HostAndPort>();
		   jedisClusterNodes.add(new HostAndPort("10.10.68.43", 6379));
		   jedisClusterNodes.add(new HostAndPort("10.10.68.145", 6379));
		   jedisClusterNodes.add(new HostAndPort("10.10.68.146", 6379));
		   jedisClusterNodes.add(new HostAndPort("10.10.68.43", 6380));
		   jedisClusterNodes.add(new HostAndPort("10.10.68.145", 6380));
		   jedisClusterNodes.add(new HostAndPort("10.10.68.146", 6380));
		   JedisCluster jc = new JedisCluster(jedisClusterNodes);
		   JedisClusterConnection jedisClusterConnection = new JedisClusterConnection(jc);
	        return jedisClusterConnection;
			 
		 } 

	public static void main(String[] args) {
		
		SpringApplication.run(App.class, args);
	}
}
@RestController

public class ShowRedisClusters {
	@Autowired
	private JedisClusterConnection jedisClusterConnection;
	private static final Logger logger = LoggerFactory.getLogger(ShowRedisClusters.class);
	

	
	@RequestMapping(value="deletenode",method = RequestMethod.POST)
	
		 public String deleteRedisClusterNodeByNode() {
		RedisClusterNode  redisClusterNode = new RedisClusterNode("4d3c1eae367cec0a97d5dd7f8dc4e0325d011694");// this Id is my slaveNode.
		//jedisClusterConnection.clusterDeleteSlots(slave, slots);
//		Set<RedisClusterNode>  rcn = jedisClusterConnection.clusterGetNodes();
//		for (RedisClusterNode node : rcn) {
//			jedisClusterConnection.clusterForget(node);
//		}
		jedisClusterConnection.clusterForget(redisClusterNode);
		return "ok";

		}
	
	/**
	 * ）
	 * @param masterHost
	 * @param masterPort
	 * @param slaveHost
	 * @param slavePort
	 * @return 
	 */
	@RequestMapping(value="changeNode",method = RequestMethod.POST)

	public String changeRedisClusterNode(String masterHost, int masterPort, String slaveHost, int slavePort) {
		RedisClusterNode  masterNode = new RedisClusterNode(masterHost,masterPort);
		RedisClusterNode  slaveNode = new RedisClusterNode(slaveHost,slavePort);
		jedisClusterConnection.clusterReplicate(masterNode,slaveNode);
		return "success";

		}
  }`

**Comment by power-man** [comment]
![redis](https://user-images.githubusercontent.com/28044978/36081278-7e6508b6-0fd7-11e8-970f-fa877f9db21e.PNG)
When use my deleteRedisClusterNodeByNode() method, the node is forgeten in one minute,it will wake up after one minute.I read redis doc it explains you should send commands to every node ? I want to know if I am not right or jedis can't do that?

**Comment by sazzad16** [comment]
@power-man According to [Redis CLUSTER FORGET](https://redis.io/commands/cluster-forget):

> ... in order for a node to be completely removed from a cluster, the CLUSTER FORGET command must be sent to all the remaining nodes, regardless of the fact they are masters or slaves.

Within Jedis, this call is propagated to only one node. You yourself may propagate this call to all nodes. I don't know what `org.springframework...JedisClusterConnection` does. You might also want to direct this to `springframework` community.
