### ISSUE TITLE
redis cluster can't reconnect when JedisCluster getClusterNodes()  return null 

### ISSUE THREAD

**Issue by changealice** [xetorthio/jedis#1778]
### Expected behavior
  can reconnect when  clazz JedisCluster.getClusterNodes()  is null  
### Actual behavior
  can't reconnect ,because JedisClusterInfoCache  getNodes is null 
### Steps to reproduce:
1.  run redis cluster 3.2.8  in kubernetes 
2. my app starting ,create jediscluster instances for code : 

        HashSet<HostAndPort> hset = new HashSet<HostAndPort>();
        String[] args = clusters.split(";");
        for (String arg : args) {
            String[] info = arg.split(":");
            hset.add(new HostAndPort(info[0], Integer.valueOf(info[1])));
        }
        JedisCluster jedisCluster = new JedisCluster(hset, timeout, timeout, 2, jedisPoolConfig);
        Map<String, JedisPool> nodes = nodes(jedisCluster);
        LOGGER.info("jedisCluster nodes={} ", nodes);
output:
       jedisCluster nodes={}

3. my application started ,execute redis set("1","1") but
throw new JedisNoReachableClusterNodeException("No reachable node in cluster");

### Redis / Jedis Configuration

    <bean id="jedisPoolConfig" class="redis.clients.jedis.JedisPoolConfig">
        <property name="maxTotal" value="5000"/>
        <property name="maxIdle" value="500"/>
        <property name="minIdle" value="100"/>
        <property name="blockWhenExhausted" value="false"/>
        <property name="maxWaitMillis" value="100"/>
        <property name="testOnBorrow" value="false"/>
        <property name="testOnReturn" value="false"/>
        <property name="testWhileIdle" value="false"/>
    </bean>

    <bean id="jedisCluster" class="org.sdn.common.utils.redis.JedisClusterFactory">
        <property name="clusters" value="${spring.redis.cluster.nodes}"/>
        <property name="jedisPoolConfig" ref="jedisPoolConfig"/>
        <property name="timeout" value="${spring.redis.cluster.timeout}"/>
    </bean>

#### Jedis version:
2.9.0
#### Redis version:
3.2.8
#### Java version:
1.8

@xetorthio 
i saw jedis code : 
  @Override
  public Jedis getConnectionFromSlot(int slot) {
    JedisPool connectionPool = cache.getSlotPool(slot);
    if (connectionPool != null) {
      // It can't guaranteed to get valid connection because of node
      // assignment
      return connectionPool.getResource();
    } else {
      renewSlotCache(); //It's abnormal situation for cluster mode, that we have just nothing for slot, try to rediscover state
      connectionPool = cache.getSlotPool(slot);
      if (connectionPool != null) {
        return connectionPool.getResource();
      } else {
        //no choice, fallback to new connection to random node
        return getConnection();
      }
    }
  }

my think so : 
nodes return null,cause cache.getSlotPool(slot) return null .and return null connectionPool,even if execute renewSlotCache, because nodes is empty ,jedis client  do nothing....

Ho to Fix

**Comment by marcosnils** [comment]
Seems like a miss configuration in the cluster. Can you please provide the output of `cluster nodes` and `cluster slots` please?

**Comment by changealice** [comment]
127.0.0.1:6379> CLUSTER nodes
ff1cd6b9341f679dd5a2ea21b9cabe44610d994b 192.169.173.96:6379 myself,master - 0 0 3 connected 10923-16383
c37906f41a7a5270e7e5a89022f6ef49fd273967 192.169.82.230:6379 slave ff1cd6b9341f679dd5a2ea21b9cabe44610d994b 0 1519486876190 6 connected
4f0a4ed2899d9b46b6ed32c1808a4a4d903cc5ba 192.169.173.97:6379 slave 076888e7b2e659feb2bf05867ecb10eca75f2e45 0 1519486877192 4 connected
d99cb312f5f26281890445bd658c481b5aedb8e4 192.169.166.236:6379 master - 0 1519486871165 2 connected 5461-10922
de06eee1ccee954d9acca74f894f5d468a779d74 192.169.82.229:6379 slave d99cb312f5f26281890445bd658c481b5aedb8e4 0 1519486875186 2 connected
076888e7b2e659feb2bf05867ecb10eca75f2e45 192.169.166.235:6379 master - 0 1519486874178 1 connected 0-5460


127.0.0.1:6379> CLUSTER SLOTS
1) 1) (integer) 10923
   2) (integer) 16383
   3) 1) "192.169.173.96"
      2) (integer) 6379
      3) "ff1cd6b9341f679dd5a2ea21b9cabe44610d994b"
   4) 1) "192.169.82.230"
      2) (integer) 6379
      3) "c37906f41a7a5270e7e5a89022f6ef49fd273967"
2) 1) (integer) 5461
   2) (integer) 10922
   3) 1) "192.169.166.236"
      2) (integer) 6379
      3) "d99cb312f5f26281890445bd658c481b5aedb8e4"
   4) 1) "192.169.82.229"
      2) (integer) 6379
      3) "de06eee1ccee954d9acca74f894f5d468a779d74"
3) 1) (integer) 0
   2) (integer) 5460
   3) 1) "192.169.166.235"
      2) (integer) 6379
      3) "076888e7b2e659feb2bf05867ecb10eca75f2e45"
   4) 1) "192.169.173.97"
      2) (integer) 6379
      3) "4f0a4ed2899d9b46b6ed32c1808a4a4d903cc5ba"

@marcosnils

**Comment by marcosnils** [comment]
@changealice thanks. Have you checked that the application has access to those IP's and ports from where your running it?

**Comment by changealice** [comment]
@marcosnils thanks , i don't think cluster node and slot has problems ,
 i think this question is redis client network can't connect redis cluster ,so jedis client return empty nodes ,but jedis client return empty node instead of   throw NoNodesException 
i' m try exec tcpdump command in order by find this questions , 
when my app start , i 'm invoke redis.set(key,value). nothing packing found to connect redis server

**Comment by marcosnils** [comment]
> ,so jedis client return empty nodes ,but jedis client return empty node instead of throw NoNodesException

Jedis doest lazy initialization when working with clusters. That's why you got `JedisNoReachableClusterNodeException("No reachable node in cluster");` when you tried to execute an operation. As I said before I believe the problem is that the machine where you're running your app cannot reach the redis servers with the IP that `cluster slots` return.

**Comment by changealice** [comment]
@marcosnils 
But my network is recovered , 
the jedis client is not recreate  cluster  nodes, is not it should be initialized jediscluster ?
So get the conclusion
jedis reconnection mechanism must be the first to get to cluster nodes to work?

**Comment by changealice** [comment]
@marcosnils My current solution is stupid and rude, the first time I am  start jedis client connection redis cluster server, if the cluster nodes is empty, I will throw new InstantiationError("redis nodes is empty"); 
failed to prevent the application starts normally
