### ISSUE TITLE
Make JedisPool and JedisCluster expose full metrics of pool to help monitoring pool usage

### ISSUE THREAD

**Issue by warrenzhu25** [xetorthio/jedis#1779]
### Expected behavior

`JedisPool` encapsulates an internal object pool and only exposes 5 metrics. There is no way to know pool config and more metrics provided by pool.
`JedisCluster` internally uses many JedisPools, but doesn't expose any metrics about internal pools

### Actual behavior

1. `JedisPool` should expose all metrics sames as object pool and pool config.
2. `JedisCluster` should expose all metrics of all internal pools related with connected node.

**Comment by sazzad16** [comment]
@warrenzhu25 A `GenericObjectPoolConfig` object can be passed in the constructor of mentioned classes. Monitoring that object is equivalent of monitoring internal pools.

**Comment by sagarsitap596** [comment]
JedisCluster with jedisPoolConfig : Do we need to explicitely return/release jedis connection to pool???

**Comment by zhanglijun1217** [comment]
> @warrenzhu25 A `GenericObjectPoolConfig` object can be passed in the constructor of mentioned classes. Monitoring that object is equivalent of monitoring internal pools.

but the Apache GenericObjectPoolConfig is be combined with in the JedisPool， and in high version this field is private, it seems that we can not find api to obtain the inner pool

**Comment by sazzad16** [comment]
Apologies. There seems inconsistencies with my previous comment (which is almost 7 years old).

The proper class for getting metrics is `GenericObjectPool`.
There are different ways to get the GenericObjectPool from different client classes.
- JedisPool itself is a direct sub-class of GenericObjectPool. So you can directly use that class for metrics.
- JedisPooled has a `getPool()` method which returns a GenericObjectPool.
- JedisCluster has a `getClusterNodes()` method which returns a Map where values are GenericObjectPool(s).
