### ISSUE TITLE
MultiKeyCommands and MultiKeyJedisClusterCommands interfaces do not expose both a `scan(final String cursor)` method.

### ISSUE THREAD

**Issue by LavinJ** [xetorthio/jedis#1784]
### Expected behavior
I'm expecting both `Jedis` and `JedisCluster` to expose a method `scan(final String cursor)`. 

### Actual behavior
`JedisCluster` does **not** expose such a method. (Because `MultiKeyCommands` and `MultiKeyJedisClusterCommands` are not equal)

### Steps to reproduce:
Simply instantiate both of such objects and try to execute a scan method.

### Redis / Jedis Configuration
Does not apply

#### Jedis version:
2.9.0

#### Redis version:
Does not apply

#### Java version:
1.8_151

**Comment by marcosnils** [comment]
This is for a reason. https://github.com/xetorthio/jedis/issues/990 If you have a better idea about how to implement, please feel free to add a design proposal in the discussion thread.
