### ISSUE TITLE
Moving from no password redis cluster to password protected redis cluster with existing clients

### ISSUE THREAD

**Issue by LadyGaladriel** [xetorthio/jedis#1785]
### Expected behavior
We have a Redis Cluster with master-slave replication (3 Master, 3 slaves) and our applications use the jedisCluster client to connect to it.  Now we wanted to set a password in our redis cluster using the requirepass option. 
If you try setting password while creating instance of Jedis CLuster but there is no password set for redis store it will throw following error.
"Exception in thread "main" redis.clients.jedis.exceptions.JedisDataException: ERR Client sent AUTH, but no password is set"

There is no way that it can ignore this password sent if requirepass is not set for the store. 
Redis-cli ignores "-a" option. I wonder why not available in JedisCLuster client. Also, there is no way to authenticate your client instance later. Is there any particular reason for this behavior? 

We use singleton Instance of JedisCLuster in our application and there is no way I will be able to construct a jedisCLuster instance with password and release the application without any downtime of connection with redis store. (I can always put a dirty hack to avoid this downtime and then remove it later) 
Still wondering is there any better way to go about it?

**Comment by sazzad16** [comment]
@LadyGaladriel First of all

> Redis-cli ignores "-a" option.

WRONG!!! **Redis-cli uses the `-a` option and ignores the response**.

However, your *dirty hack* could be the apparent solution. Do have any idea regarding this, also considering password change scenario?

**Comment by sazzad16** [comment]
Closed due to inactivity.
