### ISSUE TITLE
MIGRATE SHOULD SUPPORT OPTION [COPY/REPLACE]

### ISSUE THREAD

**Issue by MochaJavaCchip** [xetorthio/jedis#1786]
Redis supports whether to mark the new key on the machine at the end of the command when executing the migration operation. This API is not inherited by Jedis.

Redis API：
MIGRATE host port key destination-db timeout [COPY] [REPLACE]

Jedis API：
public Response<String> migrate(String host, int port, String key, int destinationDb, int timeout) 

I'm developing a rapid migration system for Redis cluster scaling based on Jedis and Pipeline. Since it does not support option "REPLACE", I am very upset when I got an error. I have to write a lot of extra code to serialize the results of PIPELINE and determine if there is a "BUSY KEY ERROR" exception in the pipeline.

**Comment by marcosnils** [comment]
@MochaJavaCchip why instead of writing a lot of extra code and being upset you send a PR to Jedis to add this functionality you seem to need and feel good by helping the Open Source community?

**Comment by sazzad16** [comment]
@marcosnils There's a pending PR #1748

**Comment by marcosnils** [comment]
Thanks @sazzad16 in that case, I'll go ahead and close this

**Comment by MochaJavaCchip** [comment]
@marcosnils I apologize for what I said. When I encountered this error, I felt a bit out of control.

However, use REPLACE can not solve “BUSY KEY ERROR”, too. Since it may cause dirty write problems.
Finally, the problem which I encountered in the migration, have solved by use HashSet to mark the retries.

@sazzad16 This modification can fix this issue, thanks a lot.
