### ISSUE TITLE
How to select a database index for a pool?

### ISSUE THREAD

**Issue by sandeepboys** [xetorthio/jedis#1790]
Essentially I have the same question mentioned in: https://github.com/xetorthio/jedis/issues/418

But the solution provided in that thread by @nykolaslima selects the database index to only that specific resource. Next time if I get a resource from pool, I may get a different resource which points to older database index. How can I set the index for pool or for all the resources in the pool (also for newly created resources)?

**Comment by sazzad16** [comment]
@sandeepboys You can set the database index for all resources by providing the index in the constructor of the pool.

**Comment by sandeepboys** [comment]
@sazzad16 My question is how to select the database for the pool after the pool is created? To be precise, lets say I have created a pool with default database and then I would like to select the database 1.

**Comment by sazzad16** [comment]
@sandeepboys Currently, it's not supported.

**Comment by sandeepboys** [comment]
@sazzad16 thanks for your reply! I see that there is an option to select database for the resource. If pool is created with default database 0 and after getting first resource if I select database 1 for that resource, then if I get another resource which database will it point to?

On a side note, I have seen several requests for this functionaly in the questions sections which was back from 2012 and it would be really helpful if this feature can be implemented.

**Comment by sazzad16** [comment]
@sandeepboys 0

**Comment by BairDev** [comment]
@sazzad16 

>You can set the database index for all resources by providing the index in the constructor of the pool.

But how? The docs 

* http://javadox.com/redis.clients/jedis/2.8.0/redis/clients/jedis/JedisPoolConfig.html
* https://github.com/redis/jedis/wiki/Getting-started#basic-usage-example

are not very telling.

And what is [*0* ](https://github.com/redis/jedis/issues/1790#issuecomment-374184638) is supposed to mean?

**Comment by sazzad16** [comment]
@BairDev 

> http://javadox.com/redis.clients/jedis/2.8.0/redis/clients/jedis/JedisPoolConfig.html 

1. This doc is very old, for version 2.8.0.
2. This doc is for JedisPoolConfig. But this post is (mostly) about Pool, i.e. JedisPool.

> https://github.com/redis/jedis/wiki/Getting-started#basic-usage-example 

Jedis is a community driven project. Wanna improve the doc? You're very much welcome! Any help is appreciated.

> And what is 0 is supposed to mean?

Check [the comment just before that one](https://github.com/redis/jedis/issues/1790#issuecomment-374105927). There's a question. It's the answer to that question.

**Comment by sazzad16** [comment]
@BairDev 

> http://javadox.com/redis.clients/jedis/2.8.0/redis/clients/jedis/JedisPoolConfig.html 

1. This doc is very old, for version 2.8.0. Check more latest ones.
2. This doc is for JedisPoolConfig. But this post is (mostly) about Pool, i.e. JedisPool. So I'm a bit confused which one is your concern.

> https://github.com/redis/jedis/wiki/Getting-started#basic-usage-example 

Jedis is a community driven project. Wanna improve the doc? You're very much welcome! Any help is appreciated.

> And what is 0 is supposed to mean?

Check [the comment just before that one](https://github.com/redis/jedis/issues/1790#issuecomment-374105927). There's a question. It's the answer to that question.

**Comment by BairDev** [comment]
@sazzad16 Thanks, I've got it anyway: `JedisPool(GenericObjectPoolConfig poolConfig, String host, int port, int timeout, String password, int database, String clientName)`

**Comment by sazzad16** [comment]
@BairDev Great! There are many others as well.
