### ISSUE TITLE
Jedis encounter too many TCP established and not release properly

### ISSUE THREAD

**Issue by dacoolbaby** [xetorthio/jedis#1794]
we are using jedis for redis connection. 

And zabbix agent has detect so many tcp ESTABLISHED connection. 

we try configure on JedisPoolConfig: 
setTestWhileIdle(Boolean.True)、setTimeBetweenEvictionRunsMillis(xxx)
but it doesnt work .

Besides the redis db was configure timeout 0 

#### Jedis version:
jedis-2.9.0 

#### Java version:
jdk1.7

**Comment by marcosnils** [comment]
Sorry but we can't do much with these issue. Please provide more data or a way to reproduce your problem. I'll close as there's not much we can do from our end and haven't seen this issue before, so it's likely that it might be something related to your network or your jedis/redis configuration
