### ISSUE TITLE
After JedisPool's close() method is executed, the recycled connection can still be used

### ISSUE THREAD

**Issue by bycuimiao** [xetorthio/jedis#1795]
### Expected behavior

After the close() method of JedisPool is executed, continue to use the connection to throw an exception

### Actual behavior

After JedisPool's close() method is executed, the recycled connection can still be used

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.Create a default JedisPool and get a connection
2.Close the connection
3.Use an already closed connection to operate

#### Jedis version:
2.9.0
#### Redis version:
2.8.2101
#### Java version:
1.8

**Comment by sazzad16** [comment]
@bycuimiao Jedis is behaving as per current expectation. You might want to modify/extend `JedisPool` and/or `Jedis`, specially `close()` method, to meet your requirements.

**Comment by marcosnils** [comment]
> After the close() method of JedisPool is executed, continue to use the connection to throw an exception

Why would you expect this?. What's the use-case?. The idea of a connection pool is to re-use connections and avoid establishing new ones constantly. I agree with @sazzad16 that this works designed, but I'd like to understand what's your use-case. Maybe there's something we could do for certain scenarios.

**Comment by bycuimiao** [comment]
Thanks for your answer !

**Comment by bycuimiao** [comment]
I think that when a connection pool closes a link, it should have an identifier. It means that the link has been reclaimed by the connection pool. It is not recommended to continue using it. If you want to use the link, you should obtain it from the connection pool instead of using the link that has already been recycled. This is my idea, what do you think? @marcosnils

**Comment by bycuimiao** [comment]
I asked some senior programmers. They said they may have problems with my understanding. Maybe I understand it wrong. I am sorry to trouble you. once again, thank you @marcosnils
