### ISSUE TITLE
Count() of ScanOptions - not working ?

### ISSUE THREAD

**Issue by Ponmudi0192** [xetorthio/jedis#1796]
### Expected behavior
Hi,

I have a Redis key with some 20000 values(be it set or hashmap) and Im trying to fetch a limited set of records(say 100 here) matching a given pattern but redis always returns all the matching records. Consider my ScanOptions  be like 
**ScanOptions.scanOptions().match(param).count(100).build()** and the actual code be like 
```
Cursor<Map.Entry<byte[], byte[]>> entries = connection.hScan((table_name).getBytes(),ScanOptions.scanOptions().match(param).count(100).build());
      List<Object> result = new ArrayList<>();
       if(entries!=null) {
           while (entries.hasNext()) {
              Map.Entry<byte[], byte[]> entry = entries.next();
               byte[] actualValue = entry.getValue();
               result.add(JSON.parse(actualValue));
           }
       }
```
Is there any way to limit the records returned by the cursor ?

### Actual behavior

Cursor returns all the matching records. The count() doesnt seem to be working.

### Steps to reproduce:
Java version:
1.8.0_131
### Redis / Jedis Configuration
spring-data-redis-1.8.6.RELEASE
#### Jedis version:
spring-data-redis-1.8.6.RELEASE
#### Java version:
1.8.0_131

**Comment by allanwax** [comment]
This could be several things that have nothing to do with the code.  What is your param value?  If it is just `*` then it will match everything.  If it is `*something*` then it could also be matching keys you don't intend to match.

Also, the count is a _limit_, not _size_ specification.  Each scan could produce fewer than 100 (but no more than 100), including zero.  The only way to tell if you're done is to check the cursor value returned from the scan to see if it is zero.  A zero value means done. [this applies to a straight redis scan and may not apply in the spring case]

And between scans, more keys can be added, which scan takes care of by returning a non-zero value to tell you there's more.

So if you post the values you used, it will be easier to see what's happening.

**Comment by marcosnils** [comment]
thx @allanwax for providing further info. I'll flag this as `could not reproduce` and close as it hasn't recevied any activity in a while.
