### ISSUE TITLE
Why does Jedis + Spring Data Redis issue a MULTI command?

### ISSUE THREAD

**Issue by mcouillard** [xetorthio/jedis#1803]
### Expected behavior

Basic usage of Jedis 2.9 and Spring Data Redis 1.7.11 or 1.8.11 should not issue a MULTI command to perform a basic PUT operation, yet it is. Am I doing something wrong to make Jedis think it needs to do this?

Why does MULTI matter? I'm attempting to use Dynomite (project by Netflix on Github) and it doesn't support the MULTI command.

### Actual behavior

A MULTI command is seen from the Redis system during the usage of cache.put(k,v).

### Steps to reproduce:

Basic usage of JedisConnectionFactory, RedisTemplate & RedisCacheManager as seen from official guides.

`
        JedisConnectionFactory cf = new JedisConnectionFactory();
        cf.setHostName(getHostname());
        cf.setPort(getPort());
        cf.setTimeout(1000);

        JedisPoolConfig poolConfig = new JedisPoolConfig();
        poolConfig.setJmxEnabled(false);
        poolConfig.setLifo(true);
        poolConfig.setTestOnBorrow(true);
        poolConfig.setTestWhileIdle(true);
        poolConfig.setMinIdle(5);
        poolConfig.setMaxIdle(10);
        poolConfig.setMaxTotal(100);
        cf.setPoolConfig(poolConfig);
        cf.setUsePool(true);

...

        RedisTemplate<String, String> redisTemplate = new RedisTemplate<>();
        redisTemplate.setConnectionFactory(cf);
        redisTemplate.setEnableTransactionSupport(false);

...

        RedisCacheManager cacheManager = new RedisCacheManager(redisTemplate);
        //setCacheNames, setExpires...

...

       cacheManager.getCache("name").put("key", "value");//a MULTI command is seen here

`

#### Jedis version:
2.9.0

#### Redis version:
3.2.11

#### Java version:
1.7

**Comment by marcosnils** [comment]
@mcouillard we don't support spring-data-redis here. Please go ahead and open the issue in their repo. @mp911de might help as well as he's an active contributor of that library.

**Comment by mcouillard** [comment]
Gotcha, thank you.

Spring issue for those following along: https://jira.spring.io/browse/DATAREDIS-816
