### ISSUE TITLE
Some guidance on using Jedis Cluster

### ISSUE THREAD

**Issue by tosehee75** [xetorthio/jedis#1804]
Sorry. Not a bug report, but a question regarding how to use the jedis cluster.

I am using the AWS Redis cluster with 3+ nodes and 0 replica.

In looking at wiki, it has only the example of using Jedis with Pool where it returns the resource at the end of the finally clause.

With cluster set-up, what API do I use to get the Jedis instance and how do I return it back to the pool?

`
    private void init() {
        Set<HostAndPort> jedisClusterNodes = new HashSet<HostAndPort>();
        jedisClusterNodes.add(new HostAndPort("xxxxxxxx", 6379));
        GenericObjectPoolConfig poolConfig = new GenericObjectPoolConfig();
        poolConfig.setMaxTotal(16);
        poolConfig.setMaxIdle(16);

        this.jedisCluster = new JedisCluster(jedisClusterNodes, 2000, 500, 3, poolConfig);

        LOG.info("CacheManager initialized");
    }
`

I have a singleton class that initiates as above. Sorry for naive question.

**Comment by tosehee75** [comment]
I can't seem to find any thing that is related to Resource release..

Do I just use the jedisCluster above with get() and set() freely? I don't have to worry about the resource management?

Or do I have to create the above with every method invocation? With PoolConfig, I am guessing it's doing a resource pooling, so I should initiate above code once.. 

Am I right?

**Comment by varrix** [comment]
Yeah, the pool will manage itself. I personally use try-with-resource for
simpler queries and it will automatically return to the pool when it's done
with it and Jedis will manage the pool for you.

**Comment by marcosnils** [comment]
> Sorry. Not a bug report, but a question regarding how to use the jedis cluster.

Please ask this question in the mailing list. github is used for design discussions and bugs mainly.

http://groups.google.com/group/jedis_redis

**Comment by tosehee75** [comment]
varrix. What try/resource can I use with JedisCluster?

**Comment by tosehee75** [comment]
Will do, marcosnils
