### ISSUE TITLE
Random but high-frequency NPE while mget

### ISSUE THREAD

**Issue by hrishijoshi** [xetorthio/jedis#1805]
### Expected behavior

When jedis.exists(bytes) returns true, then jedis.get(bytes) should return the value held at the key

### Actual behavior
This is my method for getting a value for a string key. The value is also a String.

```  
public <T extends Serializable> T getPersistedCache(@Nonnull String key) {
    requireNonNull(key);

    EntitySerializer serializer = new EntitySerializer();

    byte[] value;

    try (Jedis jedis = getPool().getReadOnlyResource()) {
      byte[] bytes = key.getBytes(UTF_8);
      if (!jedis.exists(bytes)) {
        return null;
      }
      value = jedis.get(bytes);
    } catch (Exception e) {
      logRedisException(e);
      return null;
    }

    return (T) serializer.deserialize(value);

  }
```

I understand jedis.exists(key) is not the best way to check if the key exists in Redis, but that is not the issue I want to raise here.
The issue is, even after checking for exists which returns
returns true, the jedis.get(bytes) returns null. This does not happen for all the keys and all the time but some time

### Steps to reproduce:

There is no systematic way of reproducing the issue right now. It is happening only in my production environment

#### Jedis version:
2.7.3
#### Redis version:
 3.2.5
#### Java version:
1.8.161

**Comment by marcosnils** [comment]
I don't see any `mget` calls in here as the title describes. What's `getReadOnlyResource` BTW?. That's not Jedis code.

Please try to provide a reproducible case using Jedis code only. Otherwise it's hard for us to help.

**Comment by marcosnils** [comment]
Sorry, can't help without a some complete sample code where we can run some benchmarks or tests. There are some pieces missing here which we can't really guess. On a different subject, almost all of the concurrency issues that we've seen are related to custom user code .

I'd suggest taking a second look to your wrapper or provide some small **complete** example which we can run to try and trigger the bug. I'll close this in the mean time as there's not much we can do.

**Comment by hrishijoshi** [comment]
@marcosnils apologies for the noise caused. Just to put closure to this discussion, the issue was we were trying to get the expired tokens. There is some weird behavior seen in REDIS when a key has been expired, in a close proximity to that time, the exists(key)  return true but the get(key) returns null.
My approach to solve this issue is to stop using exists for now as its behavior is not deterministic. Instead I will handle the `null` returned by redis in application.
