### ISSUE TITLE
If this.password is empty, it should not be auth

### ISSUE THREAD

**Issue by MartinZhang12** [xetorthio/jedis#1808]
https://github.com/xetorthio/jedis/blob/df040537f47c8bf51ed66d16007c2a3f9f1bb802/src/main/java/redis/clients/jedis/JedisFactory.java#L118

**Comment by MartinZhang12** [comment]
If using this "redis://:@127.0.0.1:6379/0" URI, a password is empty. My REDIS don't auth

**Comment by marcosnils** [comment]
@MartinZhang12 that's not even a valid URL. Jedis won't even try to authenticate as the URL format it nos valid.

**Comment by MartinZhang12** [comment]
OK. Excuse me, I use this method  "public JedisPool(final GenericObjectPoolConfig poolConfig, final URI uri, final int timeout)" and REDIS and there is no password. How do I fill in the URI?

**Comment by MartinZhang12** [comment]
OK, thank
