### ISSUE TITLE
Thread leaks when using with Spring Boot

### ISSUE THREAD

**Issue by bryangreencharge** [xetorthio/jedis#1810]
### Expected behavior

There should not be any thread leaks

### Actual behavior

When using jedis with Spring Boot, there's a thread leak bug where it will kill the process eventually due to it running out memory

### Steps to reproduce:
Set up jedis as a component in Spring Boot, hit the service really hard and observe it in VisualVM, there's a new thread created for every redis requests and for some reasons they are stalled rather than being cleaned up. Eventually it will cause the memory ceiling will be hit the java process will return outofmemory exception

#### Jedis version:
2.9.0

#### Redis version:
v3.0.6

#### Java version:
1.8 u 171

**Comment by cpeeyush** [comment]
@bryangreencharge It will be really helpful if you provide your code to check actually what are you doing and what could be the issue here.

**Comment by marcosnils** [comment]
Please, open this issue in the spring-data-redis repo. Nothing we can do from here.
