### ISSUE TITLE
is it time to release new version now

### ISSUE THREAD

**Issue by jiafu1115** [xetorthio/jedis#1811]
it is one year + for there is no any new release. And there are many important PRs about redis cluster in this period such as  #1770

is it time to release now? it is too long time and need one release to prove the jedis is still alive.

WDYT? Thanks

@sazzad16  @marcosnils  @HeartSaVioR

**Comment by marcosnils** [comment]
@jiafu1115 I agree. I'd love some help in reviewing @sazzad16 PR's which are PENDING FOR REVIEWING  before actually releasing as I think those are important PR's.  Would you like to help reviewing?

**Comment by jiafu1115** [comment]
ok.NP. I will take some time to review and then you can double check the review result.Thanks

**Comment by gkorland** [comment]
Any progress with the new version? Do you need more help with PR review?

**Comment by thewaychung** [comment]
Also waiting for new release.

**Comment by gkorland** [comment]
@marcosnils what is left for this version?

**Comment by balazskreith** [comment]
Roughly when a release takes place for jedis?

**Comment by lzysuqianqiu** [comment]
waiting

**Comment by sazzad16** [comment]
2.9.1, 2.10.0, 3.0.0 were released on `Dec 6, 2018`. More releases followed later.
