### ISSUE TITLE
Incomprehensible purpose of JedisCluster's sample key 

### ISSUE THREAD

**Issue by nestorsokil** [xetorthio/jedis#1813]
Hello, this issue was already discussed here: https://github.com/xetorthio/jedis/issues/1257
But I still would like to ask for an explanation of this `sampleKey` argument.

I am doing a `scriptLoad` on my application start, what should I pass as a sample key? The script will get replicated to all the shards right? Why is this key a part of the API then?

**Comment by sazzad16** [comment]
@nestorsokil The script will be sent to only one node, not all nodes (or shards, if you must). The node is the one which could contain the key, `sampleKey`. This `sampleKey` may or may not be an existing key.

**Comment by nestorsokil** [comment]
@sazzad16 how do I make sure that all of the shards can accept the sha1 hash of this script?

**Comment by sazzad16** [comment]
@nestorsokil You can use `getClusterNodes()` method to get all cluster nodes and send that script to each node.
