### ISSUE TITLE
JedisClusterInfoCache.nodes will hold a removed node

### ISSUE THREAD

**Issue by fuyuanpai** [xetorthio/jedis#1816]
### Expected behavior
When a node is remove from cluster and after connectionHandler.renewSlotCache() is called, the JedisClusterInfoCache should not be holding the removed node.

### Actual behavior
When a node is remove from cluster and after connectionHandler.renewSlotCache() is called, the JedisClusterInfoCache.nodes still holding the removed node.
That is to say JedisCluster.getClusterNodes() will contain the removed node.
And what is worst, when the removed node is added to another cluster, After connectionHandler.renewSlotCache(), it might renew the slot in the new cluster from the removed node. All redis operation will go to a totally wrong cluster.

### Steps to reproduce:
1. Create a JedisCluster instance for redis clsuter with node1, node2, node3.
2. Use redis commands to remove node1 from the redis cluster.
3. Call JedisCluster method to trigger a connectionHandler.renewSlotCache()
4. Call JedisCluster.getClusterNodes(), it still holding node1.

#### Java version: 1.8

**Comment by sazzad16** [comment]
@fuyuanpai You are welcome to craft PR. Just keep in mind that we might want to keep a node if it's just *unreachable*. Because it can be reachable again.

**Comment by sazzad16** [comment]
Closed due to inactivity.
