### ISSUE TITLE
Improving socket performance

### ISSUE THREAD

**Issue by wjw465150** [xetorthio/jedis#182]
In the Connection.java file connection() method add:

```
            socket.setReuseAddress(true);
            socket.setKeepAlive(true);  
            socket.setTcpNoDelay(true); 
            socket.setSoLinger(true,0);  
```

**Comment by eXcellme** [comment]
I think it's not very graceful for sending RST message while every disconnect(). 
maybe `socket.setSoLinger(true, timeout); ` better?

**Comment by marcosnils** [comment]
@eXcellme probably. Do you have a use-case that is hitting this issue?
