### ISSUE TITLE
About the new feature of Redis 5.0

### ISSUE THREAD

**Issue by mbigger** [xetorthio/jedis#1820]
The Redis 5.0 is comming soon，some new features，such so STREAM is not supported in Jedis at moment，is there a plan to support them？

**Comment by gkorland** [comment]
@xetorthio @sazzad16 are there any plans to add STREAM support?

**Comment by sazzad16** [comment]
@mbigger @gkorland Simply speaking, the issues and PRs make up the plans. So if there is a convenient PR for supporting streams, it will definitely be considered. And anyone is welcome to craft a PR.

@marcosnils @HeartSaVioR Just to notify!

**Comment by gkorland** [comment]
@sazzad16 thanks for the quick answer, I'll be glad to craft new PRs.

**Comment by efenderbosch** [comment]
@gkorland have you started on a PR for 5.0 streams?

**Comment by gkorland** [comment]
Yes, see https://github.com/gkorland/jedis/tree/streams

**Comment by sazzad16** [comment]
Resolved by #1880
