### ISSUE TITLE
Reopening issue #426 - Specify socket timeout for blocking calls

### ISSUE THREAD

**Issue by mkozioro** [xetorthio/jedis#1823]
Hi,

Could you check again https://github.com/xetorthio/jedis/issues/426? 
It's closed as already supported, but I'm not sure that implementation with setTimeoutInfinite() is really correct.
We're having brpoplpush hangs on our production when using jedis 2.9.0. We know that in the meantime of problem, there was some kind of redis maintenance done by our redis service provider.

**Comment by sazzad16** [comment]
@mkozioro #426 was reopened on 21st Jan, 2018. Thank you for being careful.

**Comment by mkozioro** [comment]
I'm sorry. I "Closed" icon from referenced issue fooled me.
