### ISSUE TITLE
JedisConnectionFactory.setDatabase(int index)  is deprecated

### ISSUE THREAD

**Issue by 351524388** [xetorthio/jedis#1826]
The method 'JedisConnectionFactory.setDatabase(int index)'  is deprecated, so what I should use now.

**Comment by sazzad16** [comment]
@351524388 `JedisConnectionFactory` is of Jedis, but of Spring Data Redis. So please ask in proper place.

However, a quick googling says,
> void setDatabase(int index)
Deprecated.
since 2.0, configure the client name using RedisSentinelConfiguration or RedisStandaloneConfiguration.
