### ISSUE TITLE
Support for scala 2.11

### ISSUE THREAD

**Issue by Jez55** [xetorthio/jedis#1830]
i'm getting unresolved dependency error in sbt while trying to use jedis 2.9.0 with scala 2.11.12.
Does jedis 2.9.0 support scala 2.11.12 ?

**Comment by Wei-1** [comment]
I am using Scala 2.11.12 with Jedis 2.9.0 with sbt without any problem.

```
libraryDependencies += "redis.clients" % "jedis" % "2.9.0" % "provided"
```
