### ISSUE TITLE
Support for read only variants of Geo

### ISSUE THREAD

**Issue by tckb** [xetorthio/jedis#1835]
Hi, as of Nov 2017 (https://github.com/antirez/redis/issues/4084),  `GeoRadius` supports the read only variants. I believe jedis doesnt support it yet.  Do we already have plans to support it yet? Also there has been quite a few commits that went after 2.9.0, any plans to release this any time soon?

PS: I could start work on a PR for supporting the readonly variants if necessary 

cc: @sazzad16

**Comment by sazzad16** [comment]
@tckb 
> I could start work on a PR for supporting the readonly variants if necessary

You're welcome!

**Comment by sazzad16** [comment]
Closed by #1841
