### ISSUE TITLE
Jedis Clients do not verify hostnames if no HostnameVerifier Set

### ISSUE THREAD

**Issue by kmeurer** [xetorthio/jedis#1842]
### Expected behavior
if no hostname verifier is set, Jedis should perform basic hostname verification on the target.

### Actual behavior
The Jedis Connection class will perform no hostname verification if the HostnameVerifier is set to null. See here: https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/Connection.java#L192-L197

### Steps to reproduce:
Pass null for the hostname verifier field or fail to set it.

**Comment by marcosnils** [comment]
How do you recommend performing hostname verification?

**Comment by sazzad16** [comment]
Closed due to inactivity.

**Comment by richmidwinter** [comment]
Was that a trick question? I was surprised to find this too.
