### ISSUE TITLE
Problem about PR

### ISSUE THREAD

**Issue by wxisme** [xetorthio/jedis#1845]
@marcosnils @sazzad16 Has the merged PR(#1550) been rollback? I found that several recently submitted PRs have an extra commit about PR(#1550) now. But I haven’t seen it a few days ago. 
I fetched the upstream master branch, but the commit about PR(#1550) still exists.

**Comment by marcosnils** [comment]
> @marcosnils @sazzad16 Has the merged PR(#1550) been rollback?

Yes, it has been rollbacked because it caused tests to fail and has some design problems. I've added a comment in the PR
