### ISSUE TITLE
Jedis.Java eval method client.setTimeoutInfinite() severe problem diffrently from get/set/evalSha

### ISSUE THREAD

**Issue by nakamototavarez** [xetorthio/jedis#1859]
### Expected behavior
eval method should be disconnected in timeout same as other get/set/evalSha method when fail over,

### Actual behavior
eval method should not be disconnected for very long time after fail over
so it affects severe problem to application server 
because thread is not hanging in evel methods very long time, application server cannot process next request.

### Steps to reproduce:
1. only using eval method every request as stress test in application server 
2. trigger fail over
3. observe application server, tps is decreasing and compare before and after

#### Jedis version:
2.9.0 latest

#### Redis version:
4.0.10

#### Java version:
1.7

I manually updates like below, it worked normally
before)
 public Object eval(String script, int keyCount, String... params) {
    client.setTimeoutInfinite();
    try {
      client.eval(script, keyCount, params);
      return getEvalResult();
    } finally {
      client.rollbackTimeout();
    }
  }

after)
 public Object eval(String script, int keyCount, String... params) {
    checkIsInMultiOrPipeline();
    client.eval(script, keyCount, params);
    return getEvalResult();  
  }

**Comment by nakamototavarez** [comment]
@sazzad16 can you update new version of jedis 2.9.1?

**Comment by sazzad16** [comment]
@nakamototavarez No.

**Comment by nakamototavarez** [comment]
this bug should be fixed.

**Comment by nakamototavarez** [comment]
> @nakamototavarez No.

this bug should be fixed.

**Comment by nakamototavarez** [comment]
> @sazzad16 No.

this bug should be fixed.

> @nakamototavarez No.

**Comment by nakamototavarez** [comment]
> @nakamototavarez No.

this bug should be fixed.

**Comment by nakamototavarez** [comment]
@marcosnils Hi this bug should be fixed. could you apply this bug to next version?
