### ISSUE TITLE
At high concurrency, jedis is significantly slower.

### ISSUE THREAD

**Issue by kimsung604** [xetorthio/jedis#1861]
Recently using jedis, jedis processing speed is very slow when high concurrency.
I added the debug code with stopwatch.

*  /src/main/java/redis/clients/jedis/Protocol.java
```java:/src/main/java/redis/clients/jedis/Protocol.java
private static byte[] processBulkReply(final RedisInputStream is) {
  StopWatch stopwatch = new StopWatch();
  StopWatch stopwatch2 = new StopWatch();

  stopwatch2.start();
  final int len = is.readIntCrLf();
  if (len == -1) {
    return null;
  }

  final byte[] read = new byte[len];
  int offset = 0;
  while (offset < len) {
    stopwatch.start();
    final int size = is.read(read, offset, (len - offset));     // it takes about 50+-ms, at the time of high concurrency.
    stopwatchLogger.info(stopwatch.getTime());
    if (size == -1) throw new JedisConnectionException(
        "It seems like server has closed the connection.");
    offset += size;
    stopwatch.stop();
    stopwatchLogger.info(stopwatch.getTime());
    stopwatch.reset();
  }
  stopwatch2.stop();
  stopwatchLogger.info(stopwatch2.getTime());    // it takes about 1000+ms
  // read 2 more bytes for the command delimiter
  is.readByte();
  is.readByte();

  return read;
}
```

jdk : 1.6
jedis : 2.9.0

How can i solve it?

**Comment by marcosnils** [comment]
This could be due to many factors like networking or machine resources causing bottleneck. Please provide more info with a reproducible test case if possible to check what might be happening.

**Comment by basion** [comment]
> Recently using jedis, jedis processing speed is very slow when high concurrency.
> I added the debug code with stopwatch.
> 
> * /src/main/java/redis/clients/jedis/Protocol.java
> 
> ```java
> private static byte[] processBulkReply(final RedisInputStream is) {
>   StopWatch stopwatch = new StopWatch();
>   StopWatch stopwatch2 = new StopWatch();
> 
>   stopwatch2.start();
>   final int len = is.readIntCrLf();
>   if (len == -1) {
>     return null;
>   }
> 
>   final byte[] read = new byte[len];
>   int offset = 0;
>   while (offset < len) {
>     stopwatch.start();
>     final int size = is.read(read, offset, (len - offset));     // it takes about 50+-ms, at the time of high concurrency.
>     stopwatchLogger.info(stopwatch.getTime());
>     if (size == -1) throw new JedisConnectionException(
>         "It seems like server has closed the connection.");
>     offset += size;
>     stopwatch.stop();
>     stopwatchLogger.info(stopwatch.getTime());
>     stopwatch.reset();
>   }
>   stopwatch2.stop();
>   stopwatchLogger.info(stopwatch2.getTime());    // it takes about 1000+ms
>   // read 2 more bytes for the command delimiter
>   is.readByte();
>   is.readByte();
> 
>   return read;
> }
> ```
> 
> jdk : 1.6
> jedis : 2.9.0
> 
> How can i solve it?
I have got this bug too.
Now i use 2.7.3 to avoid this.

**Comment by sazzad16** [comment]
@basion There is no change between implementation of [2.7.3](https://github.com/xetorthio/jedis/blob/jedis-2.7.3/src/main/java/redis/clients/jedis/Protocol.java#L162-L182) and [2.9.0](https://github.com/xetorthio/jedis/blob/jedis-2.9.0/src/main/java/redis/clients/jedis/Protocol.java#L172-L192) in concerned method.

@kimsung604 @basion Please refer to @marcosnils' [comment](https://github.com/xetorthio/jedis/issues/1861#issuecomment-417939199)
