### ISSUE TITLE
Executed an wrong function in BinaryJedisCluster#pexpireAt

### ISSUE THREAD

**Issue by china-wangzhihui** [xetorthio/jedis#1865]
###  Source Code

>  public class BinaryJedisCluster implements BasicCommands, BinaryJedisClusterCommands,
    MultiKeyBinaryJedisClusterCommands, JedisClusterBinaryScriptingCommands, Closeable {
  ...
  @Override
  public Long **pexpireAt**(final byte[] key, final long millisecondsTimestamp) {
    return new JedisClusterCommand<Long>(connectionHandler, maxAttempts) {
      @Override
      public Long execute(Jedis connection) {
        return connection.**pexpire**(key, millisecondsTimestamp);
      }
    }.runBinary(key);
  }
  ...
  }`

**Comment by sazzad16** [comment]
Dupe #1488 #1497 #1630
