### ISSUE TITLE
Socket Timeout isse

### ISSUE THREAD

**Issue by swatcat01** [xetorthio/jedis#1872]
I am getting following error

[org.springframework.data.redis.RedisConnectionFailureException: java.net.SocketTimeoutException: connect timed out; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: connect timed out]

**Comment by marcosnils** [comment]
This could be due to several things. You're also using spring-data-redis in your app which we don't maintain. Please provide more info and with reproducible test case. Otherwise it's very difficult for us to provide help.
