### ISSUE TITLE
There is a bug in the renewClusterSlots method in the Jedis cluster function

### ISSUE THREAD

**Issue by lixyou** [xetorthio/jedis#1877]
### Expected behavior

Jedis is able recache slots when a JedisRedirectionException occurs.

### Actual behavior

Jedis's implemention is as follows:

```
public void renewClusterSlots(Jedis jedis) {
  //If rediscovering is already in process - no need to start one more same rediscovering, just return
  if (!rediscovering) {
    try {
      w.lock();
      rediscovering = true;
      if (jedis != null) {
        try {
          discoverClusterSlots(jedis);
          return;
        } catch (JedisException e) {
          //try nodes from all pools
        }
      }
      for (JedisPool jp : getShuffledNodesPool()) {
        Jedis j = null;
        try {
          j = jp.getResource();
          discoverClusterSlots(j);
          System.out.println(j.getClient().getHost() + ":" + j.getClient().getPort());

          // Note: Don't use return here!
          return;
        } catch (JedisConnectionException e) {
          e.printStackTrace();
          // try next nodes
        } finally {
          if (j != null) {
            j.close();
          }
        }
      }
    } finally {
      rediscovering = false;
      w.unlock();
    }
  }
}
```
Use the for loop to traverse the JedisPool, but use return in the for loop, resulting in a direct return, not all the slots are cached. Please look at  the note above.

### Steps to reproduce:

1. Use '127.0.0.1:7000, 127.0.0.1:7001, 127.0.0.1:7002' build redis cluster. All three machine are master.
eg: 

```
>redis-3.2.4/src/redis-trib.rb check  127.0.0.1:7000
>>> Performing Cluster Check (using node 127.0.0.1:7000)
M: 22c26c1565a89d97c21437ced30fefa0f0d20b7b 127.0.0.1:7000
   slots:0-5460 (5461 slots) master
   0 additional replica(s)
M: 63aed469c611404cd3ccf4a5841b449fb14f7676 127.0.0.1:7001
   slots:5461-10922 (5462 slots) master
   0 additional replica(s)
M: ee749e3425646d8c8ae79a470e9595f78cebb906 127.0.0.1:7002
   slots:10923-16383 (5461 slots) master
   0 additional replica(s)
[OK] All nodes agree about slots configuration.
>>> Check for open slots...
>>> Check slots coverage...
[OK] All 16384 slots covered.
```

2. Write test cases, the slot of the key for 'cluster1' is 12539, this slot is at the node of 7002.  
```
Set<HostAndPort> jedisClusterNode = new HashSet<>();
HostAndPort node0 = new HostAndPort("127.0.0.1", 7000);
jedisClusterNode.add(node0);
HostAndPort node1 = new HostAndPort("127.0.0.1", 7001);
jedisClusterNode.add(node1);
HostAndPort node2 = new HostAndPort("127.0.0.1", 7002);
jedisClusterNode.add(node2);
JedisCluster cluster = new JedisCluster(jedisClusterNode);
cluster.set("key", "value");
Assert.assertEquals(cluster.get("cluster1"), "value1");
```

3.  Redis cluster reshard slot, the slot 12539 migrate to the node of 7001. But jedis don't recache slots for the node of 7001 because returning in for loop.

### Redis / Jedis Configuration
In order to save the machine, All three clusters use '127.0.0.1'. Redis cluster: 127.0.0.1:7000, 127.0.0.1:7001, 127.0.0.1:7002.

JedisCluster use default configuration.

#### Jedis version:
v2.9.0

#### Redis version:
Redis 3.2.4 (00000000/0) 64 bit

#### Java version:
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

**Comment by sazzad16** [comment]
@lixyou I think you are misjudging. Before your concerned `return;` (after your note), use `System.out.println(slots.size());`. You'll find that it is always `16384`, at least for complete, stable Redis cluster.

**Comment by lixyou** [comment]
You are right. Use jedis.clusterSlots() in the discoverClusterSlots method to get all slots of Redis cluste.

Thank you!
