### ISSUE TITLE
looks no way to extend jedis for sending a command.

### ISSUE THREAD

**Issue by x2361** [xetorthio/jedis#1889]
### Expected behavior

please consider how a user can implement their command by extending jedis.

### Actual behavior

JedisCommands interface is the only interface for now to execute redis command, we need a dynamic interface like sendCommand(...).is that possible?

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

**Comment by marcosnils** [comment]
> JedisCommands interface is the only interface for now to execute redis command, we need a dynamic interface like sendCommand(...).is that possible?

How would the interface look like?

**Comment by gkorland** [comment]
Jedis already have such API (on the binary client), you can see here how JRediSearch is utilizing it:

https://github.com/RedisLabs/JRediSearch/blob/4ed12684378dd573d560ffa8ea059208ed202af5/src/main/java/io/redisearch/client/Client.java#L118

https://github.com/RedisLabs/JRediSearch/blob/4ed12684378dd573d560ffa8ea059208ed202af5/src/main/java/io/redisearch/client/Client.java#L185

**Comment by arass** [comment]
Any movement on this? Jedis is WAY behind on 5.0 features to support streams. Would be great if SOMEONE was able to expand that support or more projects will be forced to switch to another lib.

**Comment by gkorland** [comment]
Streams support was already merged to 3.1 did you check 3.1-m1? 
See: https://mvnrepository.com/artifact/redis.clients/jedis/3.1.0-m1

**Comment by arass** [comment]
Um, all the good stuff is missing. Like the blocking calls and xadd, etc calls. It's 5.x features. 
Check for BZPOPMAX - not there in 3.1m.

**Comment by sazzad16** [comment]
Resolved by #2007 and some later PRs.
