### ISSUE TITLE
ClassCastException error while using jedispool

### ISSUE THREAD

**Issue by ImranArtwel** [xetorthio/jedis#1891]
### Expected behavior

I am expecting an efficient execution of mapreduce job without any errors. The idea behind is to aggregate map outputs originating from the same node using jedis instance.
`18/11/08 22:54:37 INFO mapreduce.Job: Task Id : attempt_1541514310767_0026_m_000031_0, Status : FAILED
Error: java.lang.ClassCastException: java.lang.Long cannot be cast to java.util.List
	at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:276)
	at redis.clients.jedis.Jedis.hgetAll(Jedis.java:848)
	at masters.final_aggregate.inNodeMapper.flush(inNodeMapper.java:98)
	at masters.final_aggregate.inNodeMapper.cleanup(inNodeMapper.java:114)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:149)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:793)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:177)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1886)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:171)
`

### Actual behavior

I keep getting weird errors from sockettimeout exception to classcast exception errors

### Mapper code section of the job:
`public class inNodeMapper extends Mapper<Object, Text, Text, IntWritable> {
	
	 String host,newHost;
	 String hashKey = "finale";
	 static final int FLUSH_SIZE = 5000;
	 Enumeration nets;
	 Iterator it;
	 NetworkInterface netint;
	 FileSystem fileSystem = null;
	 Path filepath = null;
	 Jedis jedis = null;
	 JedisPool pool = null;
	 
	
	
	protected void setup(Context context)
			throws IOException, InterruptedException, NullPointerException {
		
		nets = NetworkInterface.getNetworkInterfaces();
	    for (it = Collections.list(nets).iterator(); it.hasNext();) {
	          netint = (NetworkInterface) it.next();
	        IpAddress.displayInterfaceInformation(netint);
	        host = IpAddress.hostAdd;
	    }
	     pool = new JedisPool(new JedisPoolConfig(), host);
	     jedis = pool.getResource();
	     
	    
		    
	}
	
	@Override
	protected void map(Object key, Text value,Context context)
			throws IOException, InterruptedException, SocketException, NullPointerException {
		
		 String [] val = value.toString().split(",");
		 String token = val[11];
			 
			 if(jedis.hexists(hashKey, token))
			 {
				 int total = Integer.parseInt(jedis.hget(hashKey, token));
				   total +=1;
				   jedis.hset(hashKey, token, Integer.toString(total));
			 }
			 else {
				 jedis.hset(hashKey, token, Integer.toString(1));
			 }
			
		
			flush(context, false);
		
	}

	private void flush(Context context, boolean force) throws IOException, InterruptedException,
	NullPointerException, ClassCastException {
		Text key = new Text();
		
			
			if(!force) {
				int size = jedis.hlen(hashKey).intValue();
				if(size < FLUSH_SIZE)
				return;
			  }
			Iterator<Entry<String, String>> keyValueMapIter = jedis.hgetAll(hashKey).entrySet().iterator();
			while (keyValueMapIter.hasNext()) {
				  Entry<String, String>currentEntry = keyValueMapIter.next();
				  key.set(currentEntry.getKey());
				  int total = Integer.parseInt(currentEntry.getValue());
				  
				  context.write(key, new IntWritable(total));
			  }
			 jedis.close();		
		
	}
		
	
	protected void cleanup(Context context)throws IOException, InterruptedException, NullPointerException {
		flush(context, true);
		
			pool.close();	 
	}

}`

### Redis / Jedis Configuration
default configuration with the only change on maxclients
#### Redis version:
4.0.11
#### Java version:
1.8

**Comment by sazzad16** [comment]
@ImranArtwel You are using same Jedis instance in your entire application which is apparently multi-threaded. Try to make proper use of JedisPool. This may help https://github.com/xetorthio/jedis/wiki/Getting-started#using-jedis-in-a-multithreaded-environment
