### ISSUE TITLE
Redis connection in FIN_WAIT

### ISSUE THREAD

**Issue by abhaymukewar** [xetorthio/jedis#1892]
### Expected behavior
Redis Server (Pub/Sub) should close connection - but instead gets hung
Server Side:
/data # netstat -anp | grep 6379
tcp        0      0 0.0.0.0:6379            0.0.0.0:*               LISTEN      -
tcp        0      0 10.36.192.22:6379       10.32.224.12:48532      ESTABLISHED -
tcp        0      0 10.36.192.22:6379       10.43.128.14:37272      ESTABLISHED -
tcp      774      0 10.36.192.22:6379       10.35.192.10:34860      ESTABLISHED -
tcp        0      0 10.36.192.22:6379       10.47.128.6:37052       ESTABLISHED -
tcp        0      0 10.36.192.22:6379       10.47.128.6:56584       ESTABLISHED -
tcp        0    774 10.36.192.22:6379       10.38.0.5:50316         ESTABLISHED -
tcp        0      0 10.36.192.22:6379       10.35.192.10:53984      ESTABLISHED -
tcp        0 8665863 10.36.192.22:6379       10.32.32.6:45806        FIN_WAIT1   -
tcp        0      0 10.36.192.22:6379       10.43.128.14:46948      ESTABLISHED -
tcp        0      0 10.36.192.22:6379       10.32.80.4:55806        ESTABLISHED -
tcp        0 8648939 10.36.192.22:6379       10.40.128.6:43956       FIN_WAIT1   -
tcp        0      0 10.36.192.22:6379       10.43.64.14:46480       ESTABLISHED -

Check the last but one line. The server side is in FIN_WAIT1 state

Client Side Netstat
root@binding-s121:/# netstat -anp  |grep 6379
tcp6       0      0 10.40.128.6:52032       10.47.128.11:6379       ESTABLISHED 36/java
tcp6       0      0 10.40.128.6:57454       10.34.128.9:6379        ESTABLISHED 36/java
tcp6       0      0 10.40.128.6:50460       10.43.128.10:6379       ESTABLISHED 36/java
tcp6       0      0 10.40.128.6:51617       10.47.128.11:6379       ESTABLISHED 36/java
tcp6  5191640      0 10.40.128.6:43956       10.36.192.22:6379       ESTABLISHED 36/java
tcp6       0      0 10.40.128.6:37738       10.43.0.3:6379          ESTABLISHED 36/java

Check the last but one line the client shows the connection as ESTABLISHED.

Write here what you're expecting ...
The client socket is still in ESTABLISHED state and probably reading messages from server.

### Actual behavior

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. Restart Redis server multiple times
2. Have multiple clients publishing to redis pub/Sub server

### Redis / Jedis Configuration
Tool: Bnd-2.3.0.201405100607
Bundle-Name: Jedis
Created-By: Apache Maven Bundle Plugin
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.6))"
Build-Jdk: 1.7.0_51
Bundle-Version: 2.7.2
Bnd-LastModified: 1430242075566
Bundle-ManifestVersion: 2

org.apache.commons.pool2;version="[2.3,3)",org.apache.
 commons.pool2.impl;version="[2.3,3)"
#### Jedis version:

JedisPoolConfig cfg = new JedisPoolConfig();
			cfg.setMaxTotal(50);
			cfg.setMaxIdle(30);
			cfg.setBlockWhenExhausted(false);

#### Redis version:
# Server
redis_version:3.2.6
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:42a2a51d1e54a998
redis_mode:standalone
os:Linux 4.4.0-127-generic x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:6.2.1
process_id:1
run_id:c0df8f8ae9fc999050b05455dc4ed498de580f49
tcp_port:6379
uptime_in_seconds:968338
uptime_in_days:11
hz:10
lru_clock:15210067
executable:/data/redis-server
config_file:

#### Java version:
JRE 1.7

**Comment by gkorland** [comment]
It seems like a network configuration issue.
Please review: https://access.redhat.com/discussions/2990731

**Comment by marcosnils** [comment]
@abhaymukewar ping!.

**Comment by sazzad16** [comment]
Closed after OP's comment.
