### ISSUE TITLE
incrByFloat changes Two decimal position is changed to  17 decimal position 

### ISSUE THREAD

**Issue by duraisridhar** [xetorthio/jedis#1894]
### Expected behavior
When incrByFloat  operation/command executed on two decimal value, 
 the result should be two decimal position 

### Actual behavior
after incrByFloat , the result is not two  decimal position 

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. Had key value - "76.52"
127.0.0.1:6379> get "HDF-LMNode1"
"76.52"

2. Executed the incrByFloat    - incrByFloat   ("HDF-LMNode1",145.94)
The function call returned - correct value - 222.46
3.But in redis datastore the value is "222.45999999999999999"

127.0.0.1:6379> get "HDF-LMNode1"
"222.45999999999999999"

#### Java version:

Expected behavior
When incrByFloat operation/command executed on two decimal value,
the result should be two decimal position

Actual behavior
after incrByFloat , the result is not two decimal position

Write here what happens instead ...

Steps to reproduce:
Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random

Had key value - "76.52"
127.0.0.1:6379> get "HDF-LMNode1"
"76.52"

Executed the incrByFloat using the dyno/DynoJedisClient. - incrByFloat ("HDF-LMNode1",145.94)
The function call returned - correct value - 222.46
3.But in redis datstore the value is "222.45999999999999999"

127.0.0.1:6379> get "HDF-LMNode1"
"222.45999999999999999"

#### Jedis version:
2.9.0

Redis version:
4.0.10

Java version:
Java 8 - 1.8.0_181

**Comment by gkorland** [comment]
It's not a jedis issue but an issue in how Redis implements floats.
Please open an issue in Redis https://github.com/antirez/redis/issues
