### ISSUE TITLE
finally return resource jedis to pool 

### ISSUE THREAD

**Issue by birdfe76** [xetorthio/jedis#1895]
### Expected behavior
As blow my code.
```java
static JedisPool jedisPool;
public Jedis getResource(){
return jedisPool.getResource();
}
public void returnJedisResource(Jedis resource){
  try{ 
        resource.close();
   }catch(Exception e){
   }finally{
      if( resource.isConnected() ){
             resource.close();
      }
   }
}
```
First of all, We closed once. but, sometime did not work. only appeared exception. 
So we added code 'finally......'  We want to return resource to pool surely.

### Actual behavior
It doesn't work. 
It made more exception. (message: Object has already been returned to this pool or is invalid) 
We want to return resource to pool surely. 
Can I check resource state whether the resource return to pool  instead of 'resource.isConnected()' ?

#### Java version: 1.6

How about change jar file to jedis 2.9.0.jar ? 
Is it working safety for returning resouce to pool ?

**Comment by sazzad16** [comment]
@birdfe76 I suppose your situation is one of the ideal reason for #1775. It's merged but not released yet. Hope your issue will be resolved after a new release.

**Comment by birdfe76** [comment]
> @sazzad16  Actually I doubted that. but, JAVA is procedure oriented language. 
So When 'finally...' code will be worked after first 'close'.  Am I right ? 
Anyway I'll see your comment link. Thank you so much your advise.

**Comment by birdfe76** [comment]
@gkorland 
Caused by: redis.clients.jedis.exceptions.JedisException: Could not return the resource to the pool
	at redis.clients.util.Pool.returnResourceObject(Pool.java:66)
	at redis.clients.jedis.JedisPool.returnResource(JedisPool.java:124)
	... 127 more
Caused by: java.lang.IllegalStateException: Object has already been returned to this pool or is invalid
	at org.apache.commons.pool2.impl.GenericObjectPool.returnObject(GenericObjectPool.java:551)
	at redis.clients.util.Pool.returnResourceObject(Pool.java:64)
	... 128 more

**Comment by gkorland** [comment]
@birdfe76 can you please check the following snapshot?

```
 <repositories>
    <repository>
      <id>snapshots-repo</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
  </repositories>


  <dependencies>
    <dependency>
      <groupId>redis.clients</groupId>
      <artifactId>jedis</artifactId>
      <version>3.0.1-20181217.192606-2</version>
    </dependency>
  </dependencies>
```

It might be related to this issue https://github.com/xetorthio/jedis/issues/1910

**Comment by sazzad16** [comment]
@gkorland I don't think so. #1910 is entirely about `JedisSentinelPool`. @birdfe76 is using only `JedisPool`.

**Comment by birdfe76** [comment]
> @gkorland I don't think so. #1910 is entirely about `JedisSentinelPool`. @birdfe76 is using only `JedisPool`.

yeap. We don't use JedisSentinelPool and we just gave up that issue.
We've cleaned that code which is 'finally closed'.
Anyway thanks u guys interesting.
