### ISSUE TITLE
 Why JedisSentinelPool is not support separation of reading and writing?

### ISSUE THREAD

**Issue by violetgo** [xetorthio/jedis#1898]
Why JedisSentinelPool is not support separation of reading and writing?just like read from Slaves/Master ,write to Master.
In some systems with more reads and fewer writes, using only the master node for read and writ will cause the master node to be busy and the slave node to be too idle.

**Comment by gkorland** [comment]
@violetgo sounds like a nice idea, would you consider submitting a PR?

**Comment by sazzad16** [comment]
Closed due to inactivity.
