### ISSUE TITLE
why change the package name

### ISSUE THREAD

**Issue by shizhengchao** [xetorthio/jedis#1900]
1.why chage the package name in jedis3.0.0-m1
"redis.clients.util"  to "redis.clients.jedis.util"
#### Jedis version:
3.0.0-m1
#### Redis version:
4.0
#### Java version:
jdk8

**Comment by sazzad16** [comment]
@shizhengchao Because, considering the contents (classes, methods, implementations) of that package, it is more logical. Moreover, as it breaks backward compatibility, it is done in 3.x, not in 2.x.
