### ISSUE TITLE
Scan not supporting hash tag

### ISSUE THREAD

**Issue by inrix-adasgupta** [xetorthio/jedis#1901]
https://github.com/xetorthio/jedis/blob/53194dd03bf397211566ba48a60e9f1e549c85ae/src/main/java/redis/clients/jedis/JedisCluster.java#L1337

Shouldn't there be a NOT (!) sign for this? Looks like this is saying if the matchPattern is cluster compliant, then throw error, whereas it should be otherway.

I'm currently trying to scan for keys with match pattern of "crossing:{123}-*" (without double quotes), and it's throwing the exception from line 1338 of JedisCluster.

**Comment by sazzad16** [comment]
@inrix-adasgupta You're right. Thanks for noticing.
