### ISSUE TITLE
use JedisCluster to read RedisBloomFIiter

### ISSUE THREAD

**Issue by joyang1** [xetorthio/jedis#1903]
### Expected behavior
I can customize jedis to read redis bloomfilter
but I can't use JedisCluster to read redis bloomfliter.

### Actual behavior
JedisClusterCommand don't customize.

**Comment by marcosnils** [comment]
@joyang1 want to open a PR to add that feature?

**Comment by joyang1** [comment]
ok, I'm implementing this features and then open a PR.

**Comment by joyang1** [comment]
@marcosnils https://github.com/xetorthio/jedis/pull/1905, If use think no problem, please merge this request and release this version. I'm very anxious to use this function.
thanks!!!
😄 😄

**Comment by gkorland** [comment]
moved to https://github.com/RedisLabs/JReBloom/issues/3
