### ISSUE TITLE
subscriber can not receive any msg form the channel in cluster mode

### ISSUE THREAD

**Issue by csulyl** [xetorthio/jedis#1907]
in redis cluster mode，when i via   jedisCluster.subscribe(new Test.PB(),"uiuiui996") subcribe a  channel，via ”info Stats“ command see pubsub_channels is 1，but some times later，the pubsub_channels is 0，and subscriber can not receive any msg form the channel。

**Comment by csulyl** [comment]
redis version：3.2.3
jedis version：3.0.3

**Comment by gkorland** [comment]
```
jedis version：3.0.3
```

**Comment by sazzad16** [comment]
Closed due to inactivity.
