### ISSUE TITLE
Jedis compatibility with Redis 4.x and 5.x

### ISSUE THREAD

**Issue by ZenJason22** [xetorthio/jedis#1912]
Hi Rockstars,

Doe Jedis support 4.x and 5.x for now? The front page document says it fully is compatible with 2.8.x and 3.x.x. Our organization wants to upgrade Redis to 4.x or 5.x and we are using Jedis 2.8.1, any advice so that we will not suffer from breaking existing features?

### Redis / Jedis Configuration
Default
#### Jedis version:
2.8.1
#### Redis version:
4.X or 5.X
#### Java version:
Java 8

**Comment by gkorland** [comment]
Jedis 2.10.0 and 3.0.0 are working and tested with Redis 4 & 5. 
Notice there are still couple of new functionalities added Redis 5 missing in Jedis like Streams.

**Comment by gkorland** [comment]
Fix in #1917

**Comment by mmanikar** [comment]
Any advice on compatibility between Jedis 2.9 and Redis 5.0.6?
