### ISSUE TITLE
Jedis can't connect to Redis if it wasn't available during the launch of the Jedis client

### ISSUE THREAD

**Issue by Lrakulka** [xetorthio/jedis#1915]
I am new to Jedis. I hope my issue will useful.
 
### Expected behavior
1) Redis server unavailable
2) Launch Jedis client
3) Make Redis server available
4) Successfully start to work with Redis 

### Actual behavior
1) Redis server unavailable
2) Launch Jedis client
3) Make Redis server available
4) Get exception ```JedisNoReachableClusterNodeException: No reachable node in cluster"```

From Jedis code, I learned that during the creation of object ```JedisClusterConnectionHandler``` method ```discoverClusterNodesAndSlots``` will be called. This method will retrieve Redis nodes but if it fails to do so the number of nodes will be zero and the framework will not try to reobtain nodes as a result exception ```JedisNoReachableClusterNodeException```.

**Comment by sazzad16** [comment]
@Lrakulka 

> Expected behavior
> 1. Redis server unavailable
> 2. Launch Jedis client
> 3. Make Redis server available
> 4. Successfully start to work with Redis

Seems logical. But there is `JedisNoReachableClusterNodeException: No reachable node in cluster`. So, apparently, you didn't *Make Redis server available*. Did you?

**Comment by Lrakulka** [comment]
If be more precise, my Redis server is always online and healthy but to access it you need VPN.
0. Redis server online
1. VPN turn off
2. Launch Jedis client
3. VPN turn on
4. Make a request to Jedis server get an exception JedisNoReachableClusterNodeException

If VPN enabled during Jedis launch, everything is fine.

**Comment by Lrakulka** [comment]
I solved this issue by extending JedisConnectionFactory.
```
public class CustomJedisConnectionFactory extends JedisConnectionFactory {
    private static final Logger LOGGER = LoggerFactory.getLogger(JedisConnectionFactoryProxy.class);

    private JedisCluster jedisCluster;

    public JedisConnectionFactoryProxy(RedisClusterConfiguration clusterConfiguration) {
        super(clusterConfiguration);
    }

    @Override
    protected JedisCluster createCluster(RedisClusterConfiguration clusterConfig, GenericObjectPoolConfig poolConfig) {
        jedisCluster = super.createCluster(clusterConfig, poolConfig);
        return jedisCluster;
    }

    @Override
    public RedisConnection getConnection() {
        if (jedisCluster.getClusterNodes().isEmpty()) {
            afterPropertiesSet();
        }
        return super.getConnection();
    }
}

**Comment by seanstephenson-taulia** [comment]
I know this is an old issue and you have a workaround, but this is definitely a valid bug in my opinion.  If the Redis cluster is temporarily unavailable as the app starts up it will never recover.
