### ISSUE TITLE
Jedis Test Failed when running against Redis 5.0.2

### ISSUE THREAD

**Issue by ZenJason22** [xetorthio/jedis#1919]
### Expected behavior
No Test Fail
Write here what you're expecting ...
Jedis is compatibale with Redis 5.x
### Actual behavior
Test Failed
### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. Install Redis 5.0.2 from Redis Official Website
2. Pull source code version 2.10.0
3. Run make test

```
Failed tests: 
  ShardedJedisPoolTest.shouldReturnActiveShardsWhenOneGoesOffline:182 expected:<497> but was:<499>
Tests in error: 
  JedisSentinelPoolTest.checkResourceIsCloseable:166 » JedisData READONLY You ca...
  JedisSentinelPoolTest.ensureSafeTwiceFailover:83->forceFailover:206->waitForFailover:220 » JedisData
```

Are you sure all tests are passed?

#### Jedis version:
2.10.0
#### Redis version:
5.0.2
#### Java version:
Java 8

**Comment by ZenJason22** [comment]
It looks like ShardedJedisPool will lose more data than the one of the pool instance responsible for. But we are not using this feature so it is fine.

**Comment by marcosnils** [comment]
![image](https://user-images.githubusercontent.com/1578458/50259029-297b9280-03e1-11e9-81b9-6b205d0ca530.png)
Builds are passing in the master branch which point to the lastest redis `unstable` branch. It surely is something in your environment. Give it a try by running just that test method like this:

```
TEST=ShardedJedisPoolTest#shouldReturnActiveShardsWhenOneGoesOffline make test
```
