### ISSUE TITLE
Make File is missing one Redis Cluster node and Release is skipping tests

### ISSUE THREAD

**Issue by ZenJason22** [xetorthio/jedis#1921]
I have raised an issue before about tests are failing running against Redis 4.x but someone closed the issue and mark it as not reproducible.
I also tested with Redis 5.x(lastest stable version) and this test case is still reproducing.
```
Failed tests: 
  ShardedJedisPoolTest.shouldReturnActiveShardsWhenOneGoesOffline:182 expected:<237> but was:<499>
```
I found something interesting in the makefile:

```
release:
	make start
	mvn release:clean
	mvn release:prepare
	mvn release:perform -DskipTests
	make stop
```

Please do not skip tests and claim tests are all passed.

```
echo "$$REDIS_CLUSTER_NODE1_CONF" | redis-server -
	echo "$$REDIS_CLUSTER_NODE2_CONF" | redis-server -
	echo "$$REDIS_CLUSTER_NODE3_CONF" | redis-server -
	echo "$$REDIS_CLUSTER_NODE4_CONF" | redis-server -
	echo "$$REDIS_CLUSTER_NODE5_CONF" | redis-server -
```
In the Redis Cluster testsuite it is using 6 nodes but here it only defines and run 5 nodes. I manually modified the make script and some other cluster related test case failings are fixed. Please add one more node in make file as your testsuite is running against 6 node redis cluster.

Best,

**Comment by sazzad16** [comment]
Closed due to inactivity.
