### ISSUE TITLE
What's the test period when `testwhileidle=true`?

### ISSUE THREAD

**Issue by a2232189** [xetorthio/jedis#1922]
### Expected behavior
Keep connections in Jedis pool alive and not be killed by Redis server. Our Redis server turn on timeout function, i.e., when a connection is idle for, e.g., 1 minute, Redis server will consider it timeout and close connection. However at client side Jedis doesn't know this.

### Actual behavior
I cannot find any information about the period of testWhileIdle, I'd like to make sure that Jedis will test the connection in period <1 minute, such that My Redis server won't kill my connection in Jedis pool

**Comment by gkorland** [comment]
It's a property of Apache Commons-Pool 
see: https://commons.apache.org/proper/commons-pool/apidocs/org/apache/commons/pool2/impl/BaseGenericObjectPool.html#getTestWhileIdle--
