### ISSUE TITLE
redis.clients.jedis.exceptions.JedisException: Could not get a resource from the pool        Caused by: java.util.NoSuchElementException: Timeout waiting for idle object

### ISSUE THREAD

**Issue by RanjithBabu001** [xetorthio/jedis#1929]
### Expected behavior

While running with heavy load , we are facing this issue . When we tried to increase the number of connections, the throughput is very high. (from ms to sec)

### Actual behavior

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

### Redis / Jedis Configuration
            JedisPoolConfig poolConfig = new JedisPoolConfig();
	    poolConfig.setMaxTotal(200);
	    poolConfig.setMaxIdle(100);
	    poolConfig.setBlockWhenExhausted(true);
	    poolConfig.setMaxWaitMillis(1000);
	    poolConfig.setMinIdle(50);

**Comment by gkorland** [comment]
@RanjithBabu001 can you please retry the scenario with jedis 3.01 or 2.10.1?

**Comment by jebeaudet** [comment]
I get the exact same exception with the update from 2.9.0 to 2.9.1. We also have 1000ms as the max wait time for a connection.

**Comment by jebeaudet** [comment]
I'm not entirely sure why but I think this might be caused by https://github.com/xetorthio/jedis/pull/1775 .I've dumped the `GenericObjectPool` with a proper `AbandonedConfig` to get the stack traces of the usage. On my application, I could see slowly unreturned object to the pool. The stacktrace doesn't tell much though but it just confirms that the problem doesn't lie within my code : 
```class org.apache.commons.pool2.impl.SecurityManagerCallStack$PrivateSecurityManager
class org.apache.commons.pool2.impl.SecurityManagerCallStack$PrivateSecurityManager
class org.apache.commons.pool2.impl.SecurityManagerCallStack
class org.apache.commons.pool2.impl.DefaultPooledObject
class org.apache.commons.pool2.impl.GenericObjectPool
class org.apache.commons.pool2.impl.GenericObjectPool
class redis.clients.util.Pool
class redis.clients.jedis.JedisPool
class redis.clients.jedis.JedisPool
class org.springframework.data.redis.connection.jedis.JedisConnectionFactory
class org.springframework.data.redis.connection.jedis.JedisConnectionFactory
class org.springframework.data.redis.core.RedisConnectionUtils
class org.springframework.data.redis.core.RedisConnectionUtils
class org.springframework.data.redis.core.RedisConnectionUtils
class org.springframework.data.redis.core.RedisTemplate
class org.springframework.data.redis.core.RedisTemplate
class org.springframework.data.redis.core.RedisTemplate
```

**Comment by RanjithBabu001** [comment]
> @RanjithBabu001 can you please retry the scenario with jedis 3.01 or 2.10.1?

Let me try upgrading the jedis version .
Thank you , for the response.

**Comment by eiselems** [comment]
Just felt like saying, you guys are my personal heroes of the week.
Struggled a lot on debugging it on production and came to the same conclusion.
We were just using Spring Boot out of the box with Spring Data Redis and after updating to the release containing 2.9.1 it started to struggle. Just wanted to give a shout. Thanks 👍

**Comment by xuqisheng** [comment]
> I've dumped the `GenericObjectPool` with a proper `AbandonedConfig` to get the stack traces of the usage

hi @jebeaudet can you explain how to get  dumped the bean's stack traces? Thanks

**Comment by msw91103** [comment]
I have met the same exception. This exception arises when our program runs for about a dozen hours every time.  Is it related to Jedis version or other causes? I haven't solved this problem yet.

**Comment by pankajydv** [comment]
Still facing this issue in version 3.0.0. How can I configure AbandonedConfig related settings for JedisPool, it doesn't exposes GenericObjectPool and neither provides a way to set AbandonedConfig related configs like removeAbandonedOnBorrow or removeAbandonedTimeout.
