### ISSUE TITLE
Connection leaking in 2.9.1 GenericObjectPool

### ISSUE THREAD

**Issue by jebeaudet** [xetorthio/jedis#1945]
Follow up of https://github.com/xetorthio/jedis/issues/1929 since the author closed the issue. I would really appreciate a backport like mentioned in the linked issue. Also, fyi, jedis 2.9.1 is the "official" version provided by Spring Boot 1.5.19.RELEASE as the `dependencyManagement` so this probably affects a lot of users. The 1.5.x branch is not in active development anymore but they are still supporting it through end of summer 2019 IIRC.  
### Expected behavior
No connection leak
### Actual behavior
There's a connection leak with heavy usage
### Steps to reproduce:
With a heavy usage of jedis 2.9.1, the connections are slowly getting leaked and the pool starts rejecting connections after a while.

### Redis / Jedis Configuration
Nothing special
#### Jedis version:
2.9.1
#### Redis version:
N/A
#### Java version:
java 8

Thanks!!

**Comment by gkorland** [comment]
@jebeaudet can you please try 2.10.2?

**Comment by jebeaudet** [comment]
It's not possible for me unfortunately. Do you think that https://github.com/xetorthio/jedis/pull/1935 could be backported to the 2.9.x branch? Spring-data-redis 1.8.x, 2.0.x and 2.1.x branch all depends on the 2.9.x branch and like mentioned, Spring Boot 1.5.x branch just bumped the jedis managed version to 2.9.1.

I suspect a lot of users are or will be affected by this pretty serious issue, if you don't have a `maxWait` parameter set, you get the default -1 and the thread will hang forever which could easily lead to thread starvation in a webserver for example.

Thanks again

**Comment by gkorland** [comment]
2.10.2 is backward compatible to 2.9.1 so you should be able to upgrade it

**Comment by jebeaudet** [comment]
Upgrading a lib can be hard in big organizations, even if it's backward compatible. Also, I'm thinking about all the users that will get jedis 2.9.1 with Spring boot that will spend a lot of time debugging this like I did, or even worse get problems in production. We were lucky enough to catch the regression in our develop environment during a load test but might have been no load test, we could have missed it since it's a slow leak.

Don't mean no offense but you did not release a bugfix release for 2.9.x for more than 2 years and now a serious regression is introduced, I would expect another bugfix for this release or maybe a rollback in maven central?

**Comment by gkorland** [comment]
Even if we fix it in 2.9.2 it won't be automatically available as part of spring boot, but will require a new release of it so there should not be any different between 2.10.2 and 2.9.2.
Anyway I just created a PR in spring boot for 2.10.2

**Comment by jebeaudet** [comment]
Yes I understand that, however the 1.5.x branch only accepts bugfix releases AFAIK, not feature releases. Actually, I just realized that the 2.0.x and 2.1.x are also on 2.9.1, I assumed that they were on 2.10.x already so a lot more people are affected by the bug.

**Comment by jebeaudet** [comment]
Thanks for the quick turnaround!

**Comment by snicoll** [comment]
@gkorland I understand that this issue was backported but I don't see any `2.9.2` release on Maven central. @jebeaudet (thank you!) gave you enough information about our upgrade policy and I've declined your request to update as we would do it automatically.

We did, but no candidate release was available so we just released Spring Boot `2.1.3.RELEASE` with this bug still present. Can you please let us know if a `2.9.2` release is scheduled?  Thank you.

**Comment by gkorland** [comment]
done

**Comment by snicoll** [comment]
Thank you for the follow-up, much appreciated.

**Comment by eiselems** [comment]
>  Also, I'm thinking about all the users that will get jedis 2.9.1 with Spring boot that will spend a lot of time debugging this like I did, or even worse get problems in production
@jebeaudet  I give you a "+1" for this 👍 
Exactly what happened to us. But nice writeup here and in the other issues.
