### ISSUE TITLE
Observing spikes in newConnections and currConnections with engineCPU reaching 90% on AWS Elasticache Cluster with jedis cluster client.

### ISSUE THREAD

**Issue by mdhussain418** [xetorthio/jedis#1946]
### Expected behavior

We are using AWS Elasticache cluster with 10 shards and Jedis Cluster client with a load of 40K requests/1min on production environment. After running for 1 or 2 days we started observing spike of 20K - 40K connections on one shard of elasticahe cluster and after shard failover load will move to another shard. We have 10 EC2 instances talking to Elasticache cluster. Each EC2 instance will have 1000 connections with each master on shard, So total connections should be 10(ec2 instances)x10(number of shards)x1000(maxConnections) = 100K connections on all shards. One shard should have 10x1x1000 = 10K connections. We were unable to reproduce this issue with less load. Any quick suggestions or help appreciated as it is degrading production environment.

### Actual behavior

There should not be any connections spike on AWS Elasticahe cluster which is causing shard failover.

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. 
2.
3.

### Redis / Jedis Configuration
Jedis cluster configuration
MaxTotal = 1000
MaxIdle = 1000
MinIdle = 1

#### Jedis version:
2.9.0

#### Java version:
Jdk8

**Comment by sazzad16** [comment]
Closed due to inactivity.
