### ISSUE TITLE
Where is cache key in Redis?

### ISSUE THREAD

**Issue by Tin-Nguyen** [xetorthio/jedis#1950]
I have a Java application using Jedis as Redis Java library in order to communicate with Redis.  I created a function to check Rate Limit below

```java
public boolean isOverRateLimit (String key, int expiredSeconds, int maxLimit) throws IOException {
        try (Jedis jedis = pool.getResource()) {
            String currentValue = jedis.get(key);

            if ( currentValue != null && Integer.parseInt(currentValue) > maxLimit ) {
                return true;
            }
            else {
                Transaction transaction = jedis.multi();
                transaction.incr(key);
                if ( currentValue == null ) {
                    // set expire time only on the first increment
                    // key must be exist first or else expire time will not work
                    transaction.expire(key, expiredSeconds);
                }
                transaction.exec();
                transaction.close();

                return false;
            }
        }
        catch (JedisException exp) {
            throw new IOException(exp);
        }
    }
```

Currently, I'm facing an issue that it seems the function isn't working correctly. Then, I dig into Redis to check the cache key, but I could not find out any cache key with the preview I set for the case.

I'm wondering if this is an issue of Jedis on the version below or my code. Looking forward someone can help to figure out.

#### Jedis version:
2.9.0
#### Redis version:
3.2.10
#### Java version:
1.8

**Comment by Leeviiii** [comment]
hi，
 I rerun your code using
jedis version:
3.0.1
Redis version:
4.0.9
Java version:
1.8
It seems the function is working correctly in my env.

**Comment by marcosnils** [comment]
Please ask this question in the mailing list. github is used for design discussions and bugs mainly.

http://groups.google.com/group/jedis_redis
