### ISSUE TITLE
how to use redis Stream?I can't find api

### ISSUE THREAD

**Issue by skydh** [xetorthio/jedis#1951]
### Expected behavior

Write here what you're expecting ...

### Actual behavior

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

**Comment by marcosnils** [comment]
Please ask this question in the mailing list. github is used for design discussions and bugs mainly.

http://groups.google.com/group/jedis_redis

**Comment by skydh** [comment]
I'm sorry. Thank you
