### ISSUE TITLE
Race condition in JedisSentinelPool.initPool() in version 2.9.2

### ISSUE THREAD

**Issue by mp911de** [xetorthio/jedis#1953]
Issue #1910 is fixed in version 2.10 but not in version 2.9.2. Can you backport the fix please to the 2.9 branch and provide a release that ships the fix?

**Comment by sazzad16** [comment]
@gkorland ping!

**Comment by gkorland** [comment]
@sazzad16  @mp911de  I'll be glad to release 2.9.3 with the fix can you please prepare the PR?

**Comment by snicoll** [comment]
@gkorland I am not sure I understand why you need a PR so apologizes if I misunderstood but I've just submitted https://github.com/xetorthio/jedis/pull/1957

**Comment by sazzad16** [comment]
Resolved by #1957 and in 2.9.3
