### ISSUE TITLE
Mistake in javadocs for +/-inf score values

### ISSUE THREAD

**Issue by betpawa-kadyrov** [xetorthio/jedis#1955]
Method: **redis.clients.jedis.Jedis#zrangeByScore(java.lang.String, double, double)**

has wrong JavaDoc definition for max and min values:

```
   * @param min a double or Double.MIN_VALUE for "-inf"
   * @param max a double or Double.MAX_VALUE for "+inf"
```
If you want to use infinity values then you have to use:

```
Double.NEGATIVE_INFINITY for "-inf"
Double.POSITIVE_INFINITY for "+inf"
```
See how method **redis.clients.jedis.Protocol#toByteArray(double)** is implemented.

#### Jedis version:
2.9.0

**Comment by marcosnils** [comment]
Thx for reporting. Would you like to send a PR to fix it?

**Comment by betpawa-kadyrov** [comment]
Checked out current master, it already contains fix. So no need to do anything :)
