### ISSUE TITLE
the thread of commons-pool-evictor-thread can't quit normally

### ISSUE THREAD

**Issue by cyxinda** [xetorthio/jedis#1956]
### Expected behavior
The program can quit jvm after main thread finished.

### Actual behavior
The thread of commons-pool-evictor-thread which is started by jedis will not quit after the main thread finished.that is a bug,I think.

### Steps to reproduce:
1.I try the version 2.6.1 and 2.8.1,the program is OK.
2.I try run my program with the config of  TimeBetweenEvictionRunsMillis = -1 , it is OK.
3.When I run my program with the jedis version of 2.9.1 or 3.0.1 with  the config of  TimeBetweenEvictionRunsMillis <> -1 ,the problem happen.

### Redis / Jedis Configuration
TimeBetweenEvictionRunsMillis = 3000
#### Jedis version:
above  the version 2.9.1 
#### Redis version:
any version
#### Java version:
all version of jdk 

My code
`public class Test {
public static void main(String[] args) {
ICacheClient client = null;
try {
client = new RedisClient();
client.setnx("name", "mmmmmmmmmmmmmmmmm");
} finally {
if (client != null)
client.release();
}

    System.out.println("end..........................");
}
}`

**Comment by xujiazhuan** [comment]
metoo

**Comment by sazzad16** [comment]
@cyxinda It's difficult to address any issue outside Jedis. `ICacheClient`, `RedisClient` don't come from Jedis.
