### ISSUE TITLE
Jedis twemproxy connection issue , restrict jedis to not send specific commands

### ISSUE THREAD

**Issue by shreychaturvedi123** [xetorthio/jedis#1969]
### Expected behavior

connection should work while setting data in redis via twemproxy

### Actual behavior

Twemproxy logs:
nc_redis.c:1092 parsed unsupported command 'CLIENT'
nc_redis.c:1092 parsed unsupported command 'MULTI'

Can we restrict jedis to not send specific commands to twemproxy and just allow get,set as many commands are not supported by twemproxy

### Redis / Jedis Configuration
   final JedisConnectionFactory jedisConnectionFactory = new JedisConnectionFactory();
    jedisConnectionFactory.setHostName(redisHostName);
    jedisConnectionFactory.setPort(redisPort);
    jedisConnectionFactory.setUsePool(usePool);
    return jedisConnectionFactory;
#### Jedis version:
2.10.2
#### Redis version:
5.0.2
#### Java version:
1.8.0_192

Application Log:
[Request processing failed; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.] with root cause
redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:199) ~[jedis-2.10.2.jar:?]

**Comment by sazzad16** [comment]
@shreychaturvedi123 Simply speaking, Jedis is a Java client for Redis, not Twemproxy.

If you know, you're using Twemproxy, why would you use `CLIENT`, `MULTI`, etc. commands? Why don't you just stop using those unsupported commands (by Twemproxy)?
