### ISSUE TITLE
How to issue Cypher commands along with MULTI EXEC using Jedis API ?

### ISSUE THREAD

**Issue by kant111** [xetorthio/jedis#1971]
How can I issue the following commands using Jedis API? After going through the docs I am not seeing a way to issue something like below. Can anyone provide an example?

`MULTI GRAPH.QUERY <graph_id> MERGE (a:person {prop:value1}) GRAPH.QUERY <graph_id> MERGE (b:person {prop:value2}) GRAPH.QUERY <graph_id> MERGE (c:person {prop:value3}) EXEC`

**Comment by sazzad16** [comment]
Jedis is a client for Redis, not RedisGraph.
