### ISSUE TITLE
No way to dispatch this command to Redis Cluster

### ISSUE THREAD

**Issue by andrew-asa** [xetorthio/jedis#1976]
### i want to del all keys and i can usr in single,but user JedisCluster is no work ,how can i make it work?

the code is 
 jedisCluster = new JedisCluster(nodes, 15000, 10000, 5, jedisPoolConfig);
 String script = "local t1=redis.call('KEYS','*')\n" +
                    "for k,v in pairs(t1) do\n" +
                    "redis.call('del',v)\n" + "end";
 jedisCluster.eval(script, 0);

**Comment by marcosnils** [comment]
why not using flushdb? https://redis.io/commands/flushdb

**Comment by andrew-asa** [comment]
sometime i want to del key start with prefix just like this,and not just clear all
jedisCluster = new JedisCluster(nodes, 15000, 10000, 5, jedisPoolConfig);
String script = "local t1=redis.call('KEYS','__key__prefix')\n" +
"for k,v in pairs(t1) do\n" +
"redis.call('del',v)\n" + "end";
jedisCluster.eval(script, 0);

**Comment by marcosnils** [comment]
You can't really do that in jedis cluster because each key might live in a different node.
