### ISSUE TITLE
Jedis operation time more than socketTime*maxRetries during node overload

### ISSUE THREAD

**Issue by krackoder** [xetorthio/jedis#1978]
### Expected behavior
I am running redis in cluster mode.  I have created BinaryJedisCluster object as -

```
Set<HostAndPort> hostAndPorts = ImmutableSet.of(new HostAndPort("jedis-endpoint", 6379));
 JedisPoolConfig jedisPoolConfig = new JedisPoolConfig();
 jedisPoolConfig.setMaxIdle(600);
 jedisPoolConfig.setMaxTotal(600);
 jedisPoolConfig.setMinIdle(10);
 BinaryJedisCluster binaryJedisCluster = new BinaryJedisCluster(hostAndPorts, 2000, 5, jedisPoolConfig);
```
I am calling HGETALL operation with the binaryJedisCluster object and timing it as-

```
long before = Instant.now().toEpochMilli();
binaryJedisCluster.hgetall(key);
log.info("hgetall operation time {}", Instant.now().toEpochMilli() - before);
```

Because socket timeout is set to 2000ms and maxattempts is 5, the maximum delay in operation that should be measured is  2000ms*5  = 10s

### Actual behavior
When at least one node of the cluster is overloaded in terms of memory (memory is almost full, either due to actual data or large number of active client connection causing client buffer memory in redis to go up. In my case it was almost full due to a large number of active connections), and there are a number of HGETALL operations hitting that node, the delay seen in the above log line is way above expected 10s. I have seen it in the order of 70s. When this scenario happened, CPU usage on the node was around 70%. This is in multithreaded environment where threads are adding data with HMSET and retrieving with HGETALL.

### Steps to reproduce:

1. Overload a Jedis node with memory being full. Keep adding more data so that evictions happen.
2. Hit that node with HGETALL calls
3. Time the HGETALL calls

**Comment by sazzad16** [comment]
@krackoder You're forgetting about `Pool.getResource()`. (Binary)JedisCluster internally uses Pool and getResource() may consume significant amount of time depending on load and configuration.
