### ISSUE TITLE
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection closed by remote host

### ISSUE THREAD

**Issue by sau3078** [xetorthio/jedis#1980]
Jedis / Jedis Configuration : 

package com.luminous.cdcs.redis;

import java.time.Duration;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.redis.connection.jedis.JedisConnectionFactory;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.data.redis.serializer.Jackson2JsonRedisSerializer;
import org.springframework.data.redis.serializer.RedisSerializer;
import org.springframework.data.redis.serializer.StringRedisSerializer;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.PropertyAccessor;
import com.fasterxml.jackson.databind.ObjectMapper;

import redis.clients.jedis.JedisPoolConfig;

@Configuration
public class RedisConfig {

	private static final Logger LOGGER = LoggerFactory.getLogger(RedisConfig.class);

	/** The host name. */

	@Value("${spring.redis.host}")
	private String hostName;

	/** The port. */
	@Value("${spring.redis.port}")
	private int port;

	@Value("${spring.redis.password}")
	private String password;

	/**
	 * Jedis connection factory.
	 *
	 * @return the jedis connection factory
	 */
	@Bean
	JedisConnectionFactory jedisConnectionFactory() {

		JedisPoolConfig poolConfig = new JedisPoolConfig();
		// Maximum number of active connections that can be allocated from this pool at
		// the same time
		poolConfig.setMaxTotal(1000);
		// Number of connections to Redis that just sit there and do nothing
		poolConfig.setMaxIdle(1000);
		// Minimum number of idle connections to Redis - these can be seen as always
		// open and ready to serve
		poolConfig.setMinIdle(500);
		// The maximum number of milliseconds that the pool will wait (when there are no
		// available connections) for a connection to be returned before throwing an
		// exception
		poolConfig.setMaxWaitMillis(10000);
		// The minimum amount of time an object may sit idle in the pool before it is
		// eligible for eviction by the idle object evictor
		poolConfig.setMinEvictableIdleTimeMillis(Duration.ofSeconds(1000).toMillis());
		// The minimum amount of time a connection may sit idle in the pool before it is
		// eligible for eviction by the idle connection evictor
		poolConfig.setSoftMinEvictableIdleTimeMillis(Duration.ofSeconds(100).toMillis());
		// Idle connection checking period
		poolConfig.setTimeBetweenEvictionRunsMillis(Duration.ofSeconds(500).toMillis());
		// Maximum number of connections to test in each idle check
		poolConfig.setNumTestsPerEvictionRun(3);
		// Tests whether connection is dead when connection retrieval method is called
		poolConfig.setTestOnBorrow(true);
		// Tests whether connection is dead when returning a connection to the pool
		poolConfig.setTestOnReturn(true);
		// Tests whether connections are dead during idle periods
		poolConfig.setTestWhileIdle(true);
		poolConfig.setBlockWhenExhausted(true);

		JedisConnectionFactory connectionFactory = new JedisConnectionFactory(poolConfig);
		connectionFactory.setUsePool(true);
		connectionFactory.setHostName(hostName);
		connectionFactory.setPort(port);
		connectionFactory.setTimeout(900000);
		connectionFactory.setPassword(password);
		connectionFactory.setUseSsl(true);
		return connectionFactory;

	}

	/**
	 * Redis template.
	 *
	 * @return the redis template
	 */
	@Bean
	@Autowired
	public RedisTemplate<String, Object> redisTemplate() {
		final RedisTemplate<String, Object> template = new RedisTemplate<>();
		template.setConnectionFactory(jedisConnectionFactory());
		RedisSerializer<String> redisSerializer = new StringRedisSerializer();

		Jackson2JsonRedisSerializer<?> jackson2JsonRedisSerializer = new Jackson2JsonRedisSerializer<>(Object.class);
		ObjectMapper om = new ObjectMapper();
		om.setVisibility(PropertyAccessor.ALL, JsonAutoDetect.Visibility.ANY);
		om.enableDefaultTyping(ObjectMapper.DefaultTyping.NON_FINAL);
		jackson2JsonRedisSerializer.setObjectMapper(om);
		template.setKeySerializer(redisSerializer);
		template.setValueSerializer(jackson2JsonRedisSerializer);
		template.setHashValueSerializer(jackson2JsonRedisSerializer);
		template.setEnableTransactionSupport(true);
		return template;
	}

}

#### Jedis version:
2.9
#### Redis version:
Azure Redis
#### Java version:
1.8

Can anyone please help me ??

**Comment by sau3078** [comment]
I need to save Inverter data frequently in 10 minutes in Redis using jedis client for few IOT Devices.

While saving data in redis getting exception : redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection closed by remote host.

I am using HTTPClient configuration connection pooling . Below is code ;

package com.luminous.cdcs.configuration;

import org.apache.http.client.config.RequestConfig;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClientBuilder;
import org.apache.http.impl.conn.PoolingHttpClientConnectionManager;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.client.ClientHttpRequestFactory;
import org.springframework.http.client.HttpComponentsClientHttpRequestFactory;
import org.springframework.web.client.RestTemplate;

@Configuration
public class ClientHttpPoolConfiguration {

	private static final Logger logger = LoggerFactory.getLogger(ClientHttpPoolConfiguration.class);
   
	@Autowired
    private HttpConnectionPoolConfiguration poolConfiguration;

    @Bean
    public ClientHttpRequestFactory createRequestFactory() {
    	logger.info("ClientHttpRequestFactory Object created");
        PoolingHttpClientConnectionManager connectionManager = new PoolingHttpClientConnectionManager();
        connectionManager.setDefaultMaxPerRoute(Integer.parseInt(poolConfiguration.getMaxPerRoute()));
        connectionManager.setMaxTotal(Integer.parseInt(poolConfiguration.getMaxTotal()));
        RequestConfig config = RequestConfig.custom().setConnectTimeout(900000).setSocketTimeout(900000).build();
        CloseableHttpClient httpClient = HttpClientBuilder.create().setConnectionManager(connectionManager)
                .setDefaultRequestConfig(config).build();
        return new HttpComponentsClientHttpRequestFactory(httpClient);
    }
    
    @Bean
    public RestTemplate createRestTemplate(ClientHttpRequestFactory factory) {
    	logger.info("Rest Template Object created");
        RestTemplate restTemplate = new RestTemplate(factory);
        return restTemplate;
    }
}

**Comment by LuisEC2016** [comment]
Excuse me, I presented the same problem, how do I solve it?

**Comment by LuisEC2016** [comment]
> Necesito guardar los datos del inversor con frecuencia en 10 minutos en Redis usando el cliente jedis para algunos dispositivos IOT.
> 
> Mientras se guardan los datos en redis, se obtiene una excepción: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: conexión cerrada por host remoto.
> 
> Estoy usando la agrupación de conexiones de configuración HTTPClient. A continuación se muestra el código;
> 
> paquete com.luminous.cdcs.configuration;
> 
> import org.apache.http.client.config.RequestConfig; import org.apache.http.impl.client.CloseableHttpClient; import org.apache.http.impl.client.HttpClientBuilder; import org.apache.http.impl.conn.PoolingHttpClientConnectionManager; import org.slf4j.Logger; import org.slf4j.LoggerFactory; importar org.springframework.beans.factory.annotation.Autowired; importar org.springframework.context.annotation.Bean; importar org.springframework.context.annotation.Configuration; import org.springframework.http.client.ClientHttpRequestFactory; import org.springframework.http.client.HttpComponentsClientHttpRequestFactory; importar org.springframework.web.client.RestTemplate;
> 
> @configuration public class ClientHttpPoolConfiguration {
> 
> ```
> private static final Logger logger = LoggerFactory.getLogger(ClientHttpPoolConfiguration.class);
> 
> @Autowired
> private HttpConnectionPoolConfiguration poolConfiguration;
> 
> @Bean
> public ClientHttpRequestFactory createRequestFactory() {
> 	logger.info("ClientHttpRequestFactory Object created");
>     PoolingHttpClientConnectionManager connectionManager = new PoolingHttpClientConnectionManager();
>     connectionManager.setDefaultMaxPerRoute(Integer.parseInt(poolConfiguration.getMaxPerRoute()));
>     connectionManager.setMaxTotal(Integer.parseInt(poolConfiguration.getMaxTotal()));
>     RequestConfig config = RequestConfig.custom().setConnectTimeout(900000).setSocketTimeout(900000).build();
>     CloseableHttpClient httpClient = HttpClientBuilder.create().setConnectionManager(connectionManager)
>             .setDefaultRequestConfig(config).build();
>     return new HttpComponentsClientHttpRequestFactory(httpClient);
> }
> 
> @Bean
> public RestTemplate createRestTemplate(ClientHttpRequestFactory factory) {
> 	logger.info("Rest Template Object created");
>     RestTemplate restTemplate = new RestTemplate(factory);
>     return restTemplate;
> }
> ```
> 
> }

Excuse me, I presented the same problem, how do I solve it?
