### ISSUE TITLE
[NEW FEATURE] Support for SRV record

### ISSUE THREAD

**Issue by ganeshs** [xetorthio/jedis#1998]
We use redislabs to manage our redis clusters. They optimize the hardware and run multiple clusters on the same ip with different port. Since the port is different, we could manage the DNS mapping better. Say, I destroy the cluster and recreate a new one, it requires application to be restarted. With SRV record support, this should be a straightforward change without requiring a restart.

**Comment by gkorland** [comment]
@ganeshs adding support for SRV record seems like a too specific feature, but I think we can add a generic "address resolver" (see https://github.com/xetorthio/jedis/tree/address_resolver).
This way you'll be able to easily add srv record resolver based on https://github.com/dnsjava/dnsjava for example.

**Comment by ganeshs** [comment]
@gkorland That should work. Let me try it out.

**Comment by gkorland** [comment]
https://github.com/xetorthio/jedis/pull/2036

**Comment by sazzad16** [comment]
Resolved by #2151
