### ISSUE TITLE
Time consuming of ensureFile()

### ISSUE THREAD

**Issue by yumazhe** [xetorthio/jedis#1999]
jedis： 3.1.0， jdk：1.8

When I was doing a stress test, I found that **redis.clients.jedis.util.RedisInputStream.ensureFill()** 
was very serious time consuming and that was under larger concurrency.
so why? and what happened?

please anyone can help me， thanks!

the code ：

    private void ensureFill() throws JedisConnectionException {
           if (count >= limit) {
               try {
                   long start = System.currentTimeMillis();

                   limit = in.read(buf);
                   long end = System.currentTimeMillis();

                  if ((end - start) > 100) {
                    System.out.println("in.read: " + (end - start) + "ms, buf size : " + buf.length +", count:"+count+", limit: "+limit +",  in.available():" + in.available());
                }
                count = 0;
                if (limit == -1) {
                    throw new JedisConnectionException("Unexpected end of stream.");
                }
            } catch (IOException e) {
                throw new JedisConnectionException(e);
            }
        }
    }

the following is log:
in.read: 219ms, buf size : 4096, count:5, limit: 7,  in.available():0
in.read: 219ms, buf size : 4096, count:7, limit: 7,  in.available():0
in.read: 216ms, buf size : 4096, count:7, limit: 7,  in.available():0
in.read: 216ms, buf size : 4096, count:7, limit: 7,  in.available():0
in.read: 216ms, buf size : 4096, count:7, limit: 4,  in.available():0
in.read: 216ms, buf size : 4096, count:7, limit: 7,  in.available():0
in.read: 216ms, buf size : 4096, count:5, limit: 7,  in.available():0
in.read: 216ms, buf size : 4096, count:7, limit: 7,  in.available():0
in.read: 220ms, buf size : 4096, count:7, limit: 7,  in.available():0
in.read: 220ms, buf size : 4096, count:7, limit: 5,  in.available():0
in.read: 220ms, buf size : 4096, count:7, limit: 5,  in.available():0

**Comment by sazzad16** [comment]
@yumazhe Let's see the documentation for [`in.read(buf)`](https://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html#read(byte[])):

> Reads some number of bytes from the input stream and stores them into the buffer array b. The number of bytes actually read is returned as an integer. **This method blocks until input data is available, end of file is detected, or an exception is thrown.**
>
> If the length of b is zero, then no bytes are read and 0 is returned; otherwise, there is an attempt to read at least one byte. If no byte is available because the stream is at the end of the file, the value -1 is returned; otherwise, at least one byte is read and stored into b.

Let me remind you, the InputStream (`in`) is actually received from `Socket` object. Time consumption supposed to be very normal for an InputStream reading from a Socket.
