### ISSUE TITLE
Define Jedis Roadmap

### ISSUE THREAD

**Issue by hradilf** [xetorthio/jedis#2010]
Please could you define Roadmap for Jedis?
When and what will be released?

Without Roadmap it is hard to plan and hard to estimate if the new version will be compatible with spring-data-redis.

Would it be possible to have a wiki page and keep it up to date?

**Comment by hradilf** [comment]
Any preliminary info about next release? Thank you

**Comment by hradilf** [comment]
@sazzad16 Please, any idea when Jedis 3.2.0 will be released? Thanks.

**Comment by sazzad16** [comment]
@hradilf 

@gkorland would know.

**Comment by gkorland** [comment]
@sazzad16 we still have a long list of open issues on https://github.com/xetorthio/jedis/milestone/36
Should we move most of them to 3.2?

**Comment by sazzad16** [comment]
@gkorland You have already moved 4. I have moved 6 more. Right now, there are 6 on the list. WDYT about those?

**Comment by hradilf** [comment]
@gkorland @sazzad16 Please, why this one (#2035 ) was moved from v3.2.0? It is reviewed already. We are waiting for it quite a long time. Once it is done, we would need also a change in spring-data-redis.

https://github.com/xetorthio/jedis/pull/2077

**Comment by gkorland** [comment]
@hradilf since Redis 6 wasn't released I think releasing ACL support can wait a bit, lets release the long waiting 3.1.0 and then release 3.2.0 short after

**Comment by sazzad16** [comment]
@gkorland You actually mean 3.2.0 and 3.3.0 respectively, right?

**Comment by gkorland** [comment]
Yes thanks

**Comment by hradilf** [comment]
@gkorland 
Make sense. On the other hand, could you please define "short after"? 

We are running enterprise application, there is another dependency on spring-data-redis (https://jira.spring.io/browse/DATAREDIS-1046). 

It is hard to plan releases on our side without having preliminary info about Jedis releases.

Thank you.

**Comment by startjava** [comment]
please&nbsp;@gkorland&nbsp;implements Streams type api。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Frantisek Hradil"<notifications@github.com&gt;; 
发送时间: 2019年11月29日(星期五) 下午4:10
收件人: "xetorthio/jedis"<jedis@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [xetorthio/jedis] Define Jedis Roadmap (#2010)




@gkorland
 Make sense. On the other hand, could you please define "short after"?
 
We are running enterprise application, there is another dependency on spring-data-redis (https://jira.spring.io/browse/DATAREDIS-1046).
 
It is hard to plan releases on our side without having preliminary info about Jedis releases.
 
Thank you.

**Comment by gkorland** [comment]
@startjava what do you mean? Streams were part of v3.1.0

**Comment by gkorland** [comment]
The roadmap defines here https://github.com/xetorthio/jedis/milestones/
