### ISSUE TITLE
[Enhancement] sadd support collection

### ISSUE THREAD

**Issue by asmburning** [xetorthio/jedis#2016]
### Expected behavior

sadd method support java.util.Collection or java.util.Iterator
for now jedis only support
public void sadd(final String key, final String... members) 
but we can't convert a collection to String... members 
hope add method 
public void sadd(final String key, final java.util.Collection<String> members)  or
public void sadd(final String key, final java.util.Iterator<String> members) 

### Actual behavior

When we use java, we often get a collection data, but we have to loop the data to add 
each of them to a set when we use sadd method, that's not convenient, and not atomic,
we have to do extra work to make sure the smembers that we get from redis is a complete data 
we sadd to , that's really a lot work.

**Comment by sazzad16** [comment]
This a long pending issue for Jedis. You're welcome to submit a PR for all related methods, not only SADD.

And about 
> we can't convert a collection to String... members

feel free to use following piece of code

```
Collection<String> c = null;
String[] a = c.toArray(new String[c.size()]);
```

Thanks!
