### ISSUE TITLE
NOAUTH Exception Cache

### ISSUE THREAD

**Issue by LucyWengCSS** [xetorthio/jedis#2023]
Hi Team,

**Issue Definition:**  NOAUTH Exception Cache

Recurrence: The binary was running without any errors since the past 9 months. However, since 9th Jun the error NOAUTH Exception Cache can be observed. Occurrence of this issue is very less. Most of the time this is working fine.

Client SDK: 
<dependency>
                <groupId>redis.clients</groupId>
                <artifactId>jedis</artifactId>
                <version>2.8.0</version>
                <type>jar</type>
                <scope>compile</scope>
</dependency>
redis.clients jedis 2.8.0 jar compile

Investigation:
By checking the server side logs,the NOAUTH issue is “Closing unauthenticated client, either AUTH didn't succeed or AUTH was never sent within the timeout period”, which means AUTH was not sent on some of the connections.

May I ask if it is a known issue in Jedis library or what kind of reasons will cause the NOAUTH issue?

Thanks a lot

**Comment by sazzad16** [comment]
`2.8.0` is very old version for us to dig into this issue. Sorry!

Please try a newest version of Jedis. Thanks!
