### ISSUE TITLE
Support redis submodule command?

### ISSUE THREAD

**Issue by wxisme** [xetorthio/jedis#2026]
Whether to add the commands of the redis submodule to Jedis? such as BF.ADD and BF.EXISTS of RedisBloom. I am willing to submit PR if I can.
https://redislabs.com/blog/rebloom-bloom-filter-datatype-redis/

**Comment by sazzad16** [comment]
@wxisme NO? Unless it is included in core Redis.

There is a `sendCommand` included in upcoming 3.1.0. May be that will help you.

**Comment by wxisme** [comment]
@sazzad16 OK, I get it.
