### ISSUE TITLE
Too many open connections in redis server in ESTABLISHED state

### ISSUE THREAD

**Issue by sushilsingh94** [xetorthio/jedis#2038]
When we close the Jedis connection, it closes on client side but on server connection is still in ESTABLISHED mode. connections are never getting closed on server for the same client and it keeps growing. And we are getting redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException:

when we run netstat on client it shows only 4 connections alive (ESTABLISHED ) but when we do netstat on redis server we see 900 connection in ESTABLISHED state with the same client.
CLIENT LIST on redis server also shows 900 connections ilde for days.

timeout value in redis.conf is 0 : will this cause issue?
### Redis / Jedis Configuration
```
redis.with.sentinel = true
redis.pool.connection.timeout.millis=10000
redis.pool.max.total=100
redis.pool.max.idle=25
redis.pool.min.idle=10
redis.pool.max.wait.seconds=5000
```

```
GenericObjectPoolConfig poolConfig = new GenericObjectPoolConfig();
poolConfig.setMaxTotal(maxTotal);
poolConfig.setMaxIdle(maxIdle);
poolConfig.setMinIdle(minIdle);
poolConfig.setMaxWaitMillis(maxWaitInSeconds*1000);
pool = new JedisSentinelPool(clusterName, sentinels,poolConfig,timeoutInMillis);
```
Client code to access resource from redis:
```
try (Jedis jedis = pool.getResource()) {
     jedis.get(key);
}catch (Exception e) {
}
```
#### Redis version: Redis server v=3.0.3 malloc=jemalloc-3.6.0 bits=64 build=a6bf2be256a3f774

Why is redis server still keeping all the connections ESTABLISHED even though client has closed it.
Client host:
![image](https://user-images.githubusercontent.com/8100644/62106471-e9f41d80-b2c2-11e9-805f-aeca76d4abb3.png)

Redis host:
![image](https://user-images.githubusercontent.com/8100644/62106492-f7a9a300-b2c2-11e9-8a84-b6af008025a2.png)

Redis Server sentinel client list:
![image](https://user-images.githubusercontent.com/8100644/62141693-a4f3d980-b30a-11e9-9542-1511af510037.png)

Next Steps: We are going to set timeout value in redis.conf to some positive value to see if it helps. 
Please suggest why so many connections are in open state. We are not using any load balancers or proxy.

**Comment by sushilsingh94** [comment]
I have observed that most of the open connections are for sentinel which is running on port 6379 on slave host in cluster

**Comment by sazzad16** [comment]
@sushilsingh94 Both Jedis 2.8.0 and Redis 3.0.3 are very old to support.
