### ISSUE TITLE
jedis.subscribe success  then  colse netwok , jedis.subscribe cannot throw exception!

### ISSUE THREAD

**Issue by jgchen** [xetorthio/jedis#2042]
### Expected behavior

jedis.subscribe success,  then  colse netwok , jedis.subscribe() throw exception!

### Actual behavior

Write here what happens instead ...

### Steps to reproduce:
        try {
            Jedis jedis  = new Jedis("xx.xx.166.38", 6379,2000,2000);
            System.out.println("start subscribe");
            jedis.subscribe(new JedisPubSub() {},"channel1","channel2");
        } catch (Exception ex) {
            System.out.println("discount...");
            ex.printStackTrace();
        }

when I close the network,there is no exception had been caught!

### Redis / Jedis Configuration
2.9.0
#### Redis version:
2.8
#### Java version:
1.8

**Comment by JerryChin** [comment]
@jgchen can you explain a little about why this issue was getting closed so quickly?
