### ISSUE TITLE
having issue in reading keys from jedis client

### ISSUE THREAD

**Issue by Unnamalai57** [xetorthio/jedis#2043]
have to create caches concurrently in redis and read the values from the cache. Through jedis client keys have been created concurrently. When I am reading from the cache some keys are missing.

int keyExists = 0;
int keyCreated = 0 ;
Map<Integer, String> keycreate = new HashMap<Integer, String>();
Map<Integer, String> keyexist = new HashMap<Integer, String>();

try (Jedis jedis = RedisConnection.getJedisPool().getResource()) {
	if (!jedis.exists(key)) {
		jedis.hmset(key, map); // creating map data type in redis
                String s = jedis.hmget(key, "requestId").get(0).replaceAll("-", "");
	        keycreate.put(keyCreated++, s);
		jedis.expireAt(key, time);
	 }
	if(jedis.exists(key)) {
		String s = jedis.hmget(key, "requestId").get(0).replaceAll("-", "");
		keyexist.put(keyExists++, s);
	}
      System.out.println("Key created" + keycreate);
      System.out.println("Key exits" + keyexist);
} 

I am facing this issue for long. Please help me to fix it

Jedis version:
2.9.0 maven dependency

Redis version:
redis-cli 5.0.3

Java version:
1.8

Console logs for key created and key exists in redis
![Screenshot from 2019-08-09 11-38-53](https://user-images.githubusercontent.com/49053809/62758565-6beefe00-ba9c-11e9-9e9d-1323da023995.png)

Key which was missed in checking existing:
![missingKeysinRedis](https://user-images.githubusercontent.com/49053809/62758622-96d95200-ba9c-11e9-9f0f-4260cb70b765.png)

**Comment by sazzad16** [comment]
@Unnamalai57 What is `time` in `jedis.expireAt(key, time);`?

**Comment by sazzad16** [comment]
Closed due to inactivity.
