### ISSUE TITLE
ERR wrong number of arguments for 'mget' command jedis

### ISSUE THREAD

**Issue by IEnoobong** [xetorthio/jedis#2066]
### Expected behavior
Calling `Jedis#mget()` with an empty array for keys i.e `Jedis#mget(new String[0]);` should rather return an empty list or list with single null value (which is more in line with it's documentation) rather than throwing an exception

### Actual behavior
It throws the exception below

```
redis.clients.jedis.exceptions.JedisDataException: ERR wrong number of arguments for 'mget' command
	at redis.clients.jedis.Protocol.processError(Protocol.java:127)
	at redis.clients.jedis.Protocol.process(Protocol.java:161)
	at redis.clients.jedis.Protocol.read(Protocol.java:215)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
	at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:276)
	at redis.clients.jedis.Connection.getMultiBulkReply(Connection.java:269)
	at redis.clients.jedis.Jedis.mget(Jedis.java:407)
```

I know that this is what redis returns, but I believe that returning an empty list rather than an exception is one of the benefits of a library, also this would avoid hitting redis.

`Jedis.mget(new byte[0])` returns a list with a `null` element

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. call `Jedis#mget(new String[0]);`

#### Java version:  1.8.0_202
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

Happy to submit a PR for this

**Comment by sazzad16** [comment]
@IEnoobong 

> which is more in line with it's documentation

Which documentation are we talking about?

**Comment by IEnoobong** [comment]
@sazzad16 See https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/Jedis.java#L457

And I quote

**Get the values of all the specified keys. If one or more keys don't exist or is not of type String, a 'nil' value is returned instead of the value of the specified key, but the operation never fails.**

Also 

`BinaryJedis#mget(new byte[0])` https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/BinaryJedis.java#L629 does return a list with a single null element

**Comment by sazzad16** [comment]
You are getting mixed up between `array of bytes` and `array of Strings`.
- An `array of bytes` is equivalent to a `String`.
- An `array of arrays of bytes` is equivalent to an `array of Strings`.

Hints for you to think it through:

- Binary equivalent of **`new String[0]`** IS **`new byte[0][]`** NOT `new byte[0]`.

- String equivalent of **`new byte[0]`** IS **`new String()`**, NOT `new String[0]`.
  - So, String equivalent of **`BinaryJedis#mget(new byte[0])`** IS **`Jedis#mget(new String())`**, NOT `Jedis#mget(new String[0])`.

Makes sense?

**Comment by IEnoobong** [comment]
Aha. I see, Thanks a lot for the clarification!
