### ISSUE TITLE
Threads are blocked forever in getting Jedis cluster connection

### ISSUE THREAD

**Issue by chang-chao** [xetorthio/jedis#2068]
Using Spring-Data-Redis + Jedis to connect to a Redis Cluster, under high concurrency, threads are blocked forever in getting Jedis connection resource, even though all borrowed Jedis connections are supposed to be returned (I just used Spring CacheManager and RedisTemplate, whom I expect to manage the connection well).

This is the the project to reproduce

https://github.com/chang-chao/jedis-cluster-pool-issue

The stacktrace and jmx captures can be found in the [README](https://github.com/chang-chao/jedis-cluster-pool-issue/blob/master/README.md) of the reproducing project.

**Comment by sazzad16** [comment]
@chang-chao What happens if you use Jedis `2.9.3` or `2.10.2`?

**Comment by chang-chao** [comment]
@sazzad16 After upgrading to Spring Boot to `2.1.8.RELEASE`, which uses Jedis `2.9.3`.
And it did not happen again.
So , I think this is the same issue with https://github.com/xetorthio/jedis/issues/1945 , I will close this.
