### ISSUE TITLE
no xinfo() method??

### ISSUE THREAD

**Issue by startjava** [xetorthio/jedis#2081]
jedis-3.2.0-SNAPSHOT.jar version !

where find it ?

thank you very much!

**Comment by startjava** [comment]
Expect zpopmax and xinfo and another to be added as soon as possible, now the update progress is somewhat slow, thank you very much

**Comment by marcosnils** [comment]
We don't publish snapshots regularly. @gkorland we can setup a cron task to automatically push a HEAD snapshot everytime something get's merged to master. WDYT?

**Comment by sazzad16** [comment]
Dupe #2121
