### ISSUE TITLE
RedisGraph commands partially supported

### ISSUE THREAD

**Issue by siphonelee** [xetorthio/jedis#2087]
### Expected behavior

I'm using Jedis to send query command to RedisGraph, like this:
graph.query key, "MERGE(:User{dbId: 123})"

it is supposed to create a node labelled as User in RedisGraph.
 
### Actual behavior

No node created. No failure response. The "MERGE" clause appears not supported yet.

But this can work:
graph.query key, "CREATE(:User{dbId: 123})"

### Steps to reproduce:

Code: 
jedisPool.getConnection()..sendCommand("graph.QUERY", new String[]{graphId, preparedQuery, "--COMPACT"});
in which graphId is the graph key name, and prepared query is the query string mentioned above.

### Redis / Jedis Configuration

spring.redis.host=xxxx
spring.redis.port=xxxx
spring.redis.password=xxxx
spring.redis.timeout=10000
spring.redis.jedis.pool.max-total=1000
spring.redis.jedis.pool.max-wait=10000
spring.redis.jedis.pool.max-idle=200
spring.redis.jedis.pool.min-idle=10
spring.redis.block-when-exhausted=true

#### Jedis version:
3.1.0

#### Redis version:
5.0.5, with RedisGraph module enabled

#### Java version:
1.8

**Comment by siphonelee** [comment]
BTW, the command:

graph.query key, "MERGE(:User{dbId: 123})"

can be executed successfully in redis command line tool.

**Comment by DvirDukhan** [comment]
Hi @siphonelee 
I'm an engineer at RedisLabs and part of the RedisGraph team. 
First, I was unable to reproduce the problem based on your description. Can you please provide a valid sample of the code you tried to execute, as well as the RedisGraph version?
Second, I have tested your query with our Java client, JRedisGraph which uses Jedis 3.1.0 as its Redis driver. JRedisGraph is basically doing what you have tried to achieve with native Jedis API. Executed the following test code:
```
package com.redislabs.redisgraph;

import com.redislabs.redisgraph.impl.api.RedisGraph;
        import org.junit.Assert;
        import org.junit.Test;

public class JedisIssueTest {

    @Test
    public void testJedisIssue2087(){
        RedisGraph api = new RedisGraph();
        ResultSet resultSet = api.query("g", "MERGE(:User{dbId: 123})");
        Assert.assertEquals("1", resultSet.getStatistics().getStringValue(Statistics.Label.NODES_CREATED));
        Assert.assertEquals("1", resultSet.getStatistics().getStringValue(Statistics.Label.PROPERTIES_SET));
        Assert.assertNotNull(resultSet.getStatistics().getStringValue(Statistics.Label.QUERY_INTERNAL_EXECUTION_TIME));
        api.deleteGraph("g");
        api.close();
    }
}
```
The test executed against RedisGraph `master` branch, that you can clone or get on docker with 
`docker run -p 6379:6379 -it --rm redislabs/redisgraph:edge`
The tests executes the `MERGE` command and tests the response for indications about the amount of nodes created, amount of properties set and the existance of the query exection time. The test has passed seccusfully.

I'm waiting for your response with the code sample, regarding the Jedis API. If you think it is a RedisGraph issue, open us an issue at https://github.com/RedisGraph/RedisGraph/issues.

**Comment by siphonelee** [comment]
Hi @DvirDukhan
Sorry for replying late because I changed my code to lettuce and had to revert it back to Jedis. Interestingly I can't reproduce the issue any longer @_@ Guess it's my issue, but thanks for the help! 
BTW, hope you guys could support the full cypher syntax soon :)
