### ISSUE TITLE
version3.2 ~~  It's been a long time for me to wait.

### ISSUE THREAD

**Issue by startjava** [xetorthio/jedis#2092]
next version what time release??

thank you very much !

**Comment by gkorland** [comment]
It seems like are getting close to have enough to release 3.2

**Comment by startjava** [comment]
@gkorland please improve the integrity of every data type api

**Comment by gkorland** [comment]
@startjava can you be more specific?

**Comment by startjava** [comment]
@gkorland  Streams Type:xinfo()
zpopmax 
and other etc ....

**Comment by hradilf** [comment]
@gkorland Please, would it be possible to have this feature in v3.2.0: https://github.com/xetorthio/jedis/pull/2077 Thanks.

**Comment by gkorland** [comment]
@hradilf  Sorry but 3.2.0 is ready to be released we pushed it to 3.3.0.

**Comment by gkorland** [comment]
@marcosnils @sazzad16 I think we are ready to release 3.2.0, any last min objections?

**Comment by sazzad16** [comment]
@gkorland nope

**Comment by gkorland** [comment]
released
