### ISSUE TITLE
BinaryJedisCluster hvals returns Collection<byte[]>

### ISSUE THREAD

**Issue by jeschou** [xetorthio/jedis#2093]
### Expected behavior

all  JedisCluster, Jedis, BinaryJedis   hvals(..) method return List type

### Actual behavior

But, BinaryJedisCluster .hvals ... returns  Collection  (actually it is List type)

### Steps to reproduce: 

view src  code

**Comment by sazzad16** [comment]
@jeschou Thank you for noticing!

**Comment by sazzad16** [comment]
This breaks backwards compatibility. So adding it to 4.0.

@gkorland @marcosnils ping!
