### ISSUE TITLE
GeoCommandsTest fails on CI

### ISSUE THREAD

**Issue by gkorland** [xetorthio/jedis#2113]
```
Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.023 sec <<< FAILURE! - in redis.clients.jedis.tests.commands.GeoCommandsTest

geohash(redis.clients.jedis.tests.commands.GeoCommandsTest)  Time elapsed: 0.009 sec  <<< FAILURE!

org.junit.ComparisonFailure: expected:<s0dnu20t9j[0]> but was:<s0dnu20t9j[]>

	at redis.clients.jedis.tests.commands.GeoCommandsTest.geohash(GeoCommandsTest.java:94)
```

**Comment by gkorland** [comment]
@sazzad16 why did you change it? does it look like Redis 6 has a backward issue?

**Comment by gkorland** [comment]
It seems like Redis unstable does have a backward issue 
  https://github.com/antirez/redis/commit/009862ab7eee394061eeaf1aa187fa339ca50be4

**Comment by sazzad16** [comment]
@gkorland to be exact, I didn't change. I was _experimenting_, in a separate branch of course.

**Comment by gkorland** [comment]
Rolled back on https://github.com/antirez/redis/commit/e6e58e455c1adce82592a5dcf276dd8083088e2b
