### ISSUE TITLE
please implements xinfo() method!

### ISSUE THREAD

**Issue by startjava** [xetorthio/jedis#2121]
please implements xinfo() method!

**Comment by sazzad16** [comment]
@startjava You're very much welcome to craft a PR. But please stop creating same issues over and over again. One open issue should be enough for one feature. Thanks.

**Comment by dengliming** [comment]
I noticed that someone has already implemented this feature，See [https://github.com/xetorthio/jedis/pull/2069](https://github.com/xetorthio/jedis/pull/2069)

**Comment by sazzad16** [comment]
Resolved by #2069

**Comment by momomo** [comment]
what, i need this too. or maybe not. why is this not in.
