### ISSUE TITLE
Is there an automatic way of dynamically creating new instances and managing master/slave promotion?

### ISSUE THREAD

**Issue by AdityaAnand1** [xetorthio/jedis#2127]
![image](https://user-images.githubusercontent.com/13274079/71538486-dc19f580-2951-11ea-9922-c2daedce4929.png)

The docs imply that we should somehow at runtime detect that master has gone down and we should promote a slave. 

I'm creating a pretty traditional REST API server with Ktor and using jedis to cache API responses. This means that before every access to jedis, I have to confirm whether the instances are up and manage master/slave promotions. This would not be ideal when handling thousands of API calls/minute.

Also, is there a way to dynamically create new instances? This would be great for development on localhost (whereas during deployment to, e.g AWS, Elasticache manages the pool on it's own)

**Comment by itamarhaber** [comment]
Hello @AdityaAnand1 

If you're looking to run your own highly-available Redis, you should look at [Sentinel](https://redis.io/topics/sentinel) - it basically removes the need to manage failovers yourself (as the docs imply).
