### ISSUE TITLE
ClassCastException exception in getUnflushedObjectMultiBulkReply

### ISSUE THREAD

**Issue by amitweinblum** [xetorthio/jedis#2133]
### Expected behavior
started immediately after upgrade from Jedis 2.9.0 to 3.2.0
our code did not change so this exception is unexpected

### Actual behavior
java.lang.ClassCastException: [B cannot be cast to java.util.List
        at redis.clients.jedis.Connection.getUnflushedObjectMultiBulkReply(Connection.java:280)
        at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:285)
        at redis.clients.jedis.Transaction.exec(Transaction.java:46)

### Steps to reproduce:
this is the code where we had the exception:

            try (Jedis jedis = pool.getResource()) {
                TransactionWithEval t = TransactionWithEval.multi(jedis);
                for (final String topic : requestedTopics) {
                    Long lastNullable = lastSeenIndex.get(topic);
                    if (lastNullable != null) {
                        // recurring subscription to topic - fetch all messages since last subscription.
                        final Response<Object> response = t.evalObj(
                                "local r = redis.call;" +
                                        "local sent = tonumber(r(\"get\", KEYS[2]) or 0);" +
                                        "local off = ARGV[1] - sent;" +
                                        "if off >= 0 then return {sent, {}} end;" +
                                        "return {sent , r(\"lrange\", KEYS[1], off, -1)};",
                                2,
                                topic,
                                indexKey(topic),
                                lastNullable.toString()
                        );

                        onCommit.add(new Runnable() {
                            @Override
                            public void run() {
                                Iterator iter = ((List) response.get()).iterator();
                                long newLast = (Long) iter.next();
                                List msgs = (List) iter.next();
                                for (Object msg : msgs) {
                                    execMessage(topic, (String) msg);
                                }
                                lastSeenIndex.put(topic, newLast);
                            }
                        });
                    } else {
                        // initial subscription to topic - sync index with redis.
                        final Response<String> response = t.get(indexKey(topic));
                        onCommit.add(new Runnable() {
                            @Override
                            public void run() {
                                long idx = 0;
                                String idxString = response.get();
                                if (!(idxString == null || idxString.isEmpty())) {
                                    idx = Long.parseLong(idxString);
                                }
                                lastSeenIndex.put(topic, idx);
                            }
                        });
                    }
                }
                t.publish(controlTopic, "synced");
                t.exec();
            }

#### Jedis version:
3.2.0

**Comment by gkorland** [comment]
@amitweinblum thanks for reporting the issue, can you please add a simple example that we can use to recreate the issue?

**Comment by amitweinblum** [comment]
Hi Guy,
I found that the issue happened due to a misuse on our side
thanks
