### ISSUE TITLE
https://oss.sonatype.org/  no has 3.3.0-SNAPSHOT version 

### ISSUE THREAD

**Issue by startjava** [xetorthio/jedis#2134]
only find :
<dependency>
  <groupId>redis.clients</groupId>
  <artifactId>jedis</artifactId>
  <version>3.2.0-SNAPSHOT</version>
</dependency>

where 3.3 snapshot version ?

**Comment by gkorland** [comment]
Thanks for reporting, you're right we didn't release 3.3.0-SNAPSHOT till today.
I just pushed a snapshot
