### ISSUE TITLE
public String xgroupDelConsumer(final String key, final String groupname, final String consumerName) has bug?

### ISSUE THREAD

**Issue by startjava** [xetorthio/jedis#2143]
https://github.com/xetorthio/jedis/blob/master/src/test/java/redis/clients/jedis/tests/commands/StreamsCommandsTest.java

at 236 line only find：
//TODO test xgroupDelConsumer

no xgroupDelConsumer method test demo !

so run bottom code:
jedis.xgroupDelConsumer("mykey1", "mygroup1", "myconsumer1");

result show exception:
java.lang.ClassCastException: java.lang.Long cannot be cast to [B
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:236)
	at redis.clients.jedis.Jedis.xgroupDelConsumer(Jedis.java:3809)
	at test.Test28.main(Test28.java:42)

----------------------------
redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:236) code :
final byte[] resp = (byte[]) readProtocolWithCheckingBroken();

no the method test case, so so so it is bug ????

thank you very much!

**Comment by startjava** [comment]
use jedis-3.3.0-SNAPSHOT.jar version

**Comment by startjava** [comment]
@gkorland

**Comment by startjava** [comment]
Welcome again.

**Comment by startjava** [comment]
use redis5.0.7

**Comment by startjava** [comment]
Jedis.java:

  @Override
  public String xgroupDelConsumer(final String key, final String groupname, final String consumerName) {
    checkIsInMultiOrPipeline();
    client.xgroupDelConsumer(key, groupname, consumerName);
    return ""+client.getIntegerReply();
  }

it run ok !

but return value type is String .  return long better !

**Comment by dengliming** [comment]
It's a bug(I think).Solved [https://github.com/xetorthio/jedis/pull/2148](https://github.com/xetorthio/jedis/pull/2148)

**Comment by sazzad16** [comment]
Resolved by #2148
