### ISSUE TITLE
How to upgrade from 2.9.0 to the new version

### ISSUE THREAD

**Issue by asdxiaoqex** [xetorthio/jedis#2155]
### Expected behavior

Write here what you're expecting ...

### Actual behavior

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
Old code:
 try (Jedis jedis = jedisPool.getResource()) {
            String result = jedis.set(lockKey, requestId, "NX", "PX", expireTime);
            return LOCK_SUCCESS.equals(result);
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
New Code：
 SetParams setParams=new SetParams().nx().px(expireTime);
String result = jedis.set(lockKey, requestId, setParams);

Is it the same？

2.
3.

**Comment by sazzad16** [comment]
@asdxiaoqex As it seems, you've got it correct.

PS: There is a Jedis mailing list https://groups.google.com/forum/#!forum/jedis_redis and that is well suited for this sort of query.
