### ISSUE TITLE
resouce cannot be released

### ISSUE THREAD

**Issue by auyang-0626** [xetorthio/jedis#2160]
### redis.clients.jedis.exceptions.JedisExhaustedPoolException: Could not get a resource since the pool is exhausted

![image](https://user-images.githubusercontent.com/22674253/75960434-04e2dc00-5efb-11ea-9b01-6bb66306ab21.png)

Concurrent execution，sometimes resources cannot be returned properly here.
version:2.10.0

**Comment by yangbodong22011** [comment]
@auyang-0626 Maybe you need to upgrade jedis version, because it's been fixed，refer：[this](https://github.com/xetorthio/jedis/commit/df1bffa3c77f4ede4c912f2c3e78b5c8857725e7).
