### ISSUE TITLE
Do JedisCluster has SSL/TLS support?

### ISSUE THREAD

**Issue by jusech5** [xetorthio/jedis#2175]
I'm seeing https://github.com/xetorthio/jedis/issues/1210 and https://github.com/xetorthio/jedis/pull/1550 but I can't understand the exactly version that includes that caracteristic.

Thanks for be clear, I can't see information in readme or any documentation about that.

**Comment by sazzad16** [comment]
JedisCluster supports SSL/TLS from 3.1.0

**Comment by daviddelucca** [comment]
How can I use JedisCluster to connect using SSL? Documentation is not clear.

**Comment by sazzad16** [comment]
@daviddelucca Right now, there are no documentation regarding JedisCluster using SSL. Please check the [test codes](https://github.com/xetorthio/jedis/blob/master/src/test/java/redis/clients/jedis/tests/SSLJedisClusterTest.java) https://github.com/xetorthio/jedis/blob/master/src/test/java/redis/clients/jedis/tests/SSLJedisClusterTest.java . Hopefully, those may help you. 

And, if are succeeded the use it properly, would you like to write the documentation for others?
