### ISSUE TITLE
JedisFactory does not provide an implementation of the passivateObject method, will Jedis also remove idle objects?

### ISSUE THREAD

**Issue by xueleicug** [xetorthio/jedis#2179]
We use jedis 2.9.0 in project to provide a redis connection pool, and enbabled test and evict idle object by setTestWhileIdle(true) and setTimeBetweenEvictionRunMills(30000L).
However, we found that in the production environment jedis will send a lot of ping command, which may cause a sudden increase of redis server cluster ops.

I read the jedis code and found that jedis uses  GenericObjectPool from apache, which will start an evictor to evict idle object regularly if TestWhileIdle and TimeBetweenEvictionRunMills configured, in jedis, validateObject() provided by JedisFactory will invoke ping(). Besides,  I found that JedisFactory does not provide an implementation for method passivateObject, I am curious if there is no implementation of method passivateObject(PooledObject<Jedis> pooledJedis), will jedis remove idle objects? Thanks.

The key code is as follows
org.apache.commons.pool2.impl.GenericObjectPool#evict()
```
if(evict) {
        destroy(underTest);
        destroyedByEvictorCount.incrementAndGet();
    } else {
        if (testWhileIdle) {
            boolean active = false;
            try {
                factory.activateObject(underTest);
                active = true;
            } catch (final Exception e) {
                destroy(underTest);
                destroyedByEvictorCount.incrementAndGet();
            }
            if (active) {
                if (!factory.validateObject(underTest)) {
                    destroy(underTest);
                    destroyedByEvictorCount.incrementAndGet();
                } else {
                    try {
                        factory.passivateObject(underTest);
                    } catch (final Exception e) {
                        destroy(underTest);
                        destroyedByEvictorCount.incrementAndGet();
                    }
                }
            }
        }
    }
```

**Comment by yangbodong22011** [comment]
> I am curious if there is no implementation of method passivateObject(PooledObject pooledJedis), will jedis remove idle objects? Thanks.

Yes，see`redis.clients.jedis.JedisFactory#destroyObject`.


> I found that JedisFactory does not provide an implementation for method passivateObject

passivateObject(org.apache.commons.pool2.PooledObject<T>) is invoked on every instance when it is returned to the pool, means uninitialize an instance to be returned to the idle object pool, see [doc](http://commons.apache.org/proper/commons-pool/api-2.2/org/apache/commons/pool2/PooledObjectFactory.html), Jedis doesn't have to implement it, so the code is:

```
@Override
  public void passivateObject(PooledObject<Jedis> pooledJedis) throws Exception {
    // TODO maybe should select db 0? Not sure right now.
  }
```

**Comment by xueleicug** [comment]
@yangbodong22011 Thanks for your attention, I found that I misunderstood how the redis connection pool works.
