### ISSUE TITLE
Cannot use Jedis when in Pipeline. Please use Pipeline or reset jedis state .

### ISSUE THREAD

**Issue by madhushreegc** [xetorthio/jedis#2184]
#### Jedis version: 2.9. 0

pipeline.del(key1);
                        
Map<String, String> gatewayDeviceList = jedis.hgetAll(key2);
if(list.containsKey(id)) {
      	list.remove(id);
        pipeline.del(key3)
}

jedis.hgetAll(key2) is called directly after declaring pipeline . 

Please help to resolve this issue

**Comment by sazzad16** [comment]
@madhushreegc Please do what it says. Either use Pipeline or reset Jedis state. Thanks!
