### ISSUE TITLE
HGETALL returns unexpected result when the key does not exist

### ISSUE THREAD

**Issue by hauter** [xetorthio/jedis#2255]
### Expected behavior
When the key does not exist, HGETALL returns a null/empty value

### Actual behavior

HGETALL returns an unexpected result and an exception occurs in BuilderFactory.STRING_MAP.

### Steps to reproduce:

This is how I use the `exhgetall` operation:

```
Object obj = jedis.sendCommand(ModuleCommand.EXHGETALL, key);
BuilderFactory.STRING_MAP.build(obj);
```

But I get an exception:

![image](https://user-images.githubusercontent.com/8326287/94108933-c1d65f00-fe72-11ea-8459-1b297d1c933a.png)

Normally, the 'obj' should be a byte array, but it's actually different when the key does not exist:

![image](https://user-images.githubusercontent.com/8326287/94109451-9142f500-fe73-11ea-8db9-636b061021f7.png)

the second item in obj is an ArrayList, this occur a exception:

![image](https://user-images.githubusercontent.com/8326287/94109113-1a0d6100-fe73-11ea-8690-cf5b18a7df07.png)

#### Jedis version:
3.1.0

#### Java version:
1.8

**Comment by sazzad16** [comment]
@hauter 

First of all, it's not `HGETALL` you're talking about, but a custom `EXHGETALL` command.

For an empty hash, HGETALL returns a list of size `0`. But, as we can see, EXHGETALL is returning a list of size `2` where the second element is apparently a list of size 0.

Please, check your EXHGETALL command and its output properly.
