### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by swarupe04** [xetorthio/jedis#258]
Hi,
We're tried all precautions but seems to still get these classCastExceptions but not that frequently now.

Redis - 2.4.2
jedis - 2.0.0

- using jedisPool
- made sure all returnBrokenResource(jedis) is called during exceptions
- final block returnResource(jedis);
- set JedisPoolConfig.testOnBorrow=true

Any other suggestions to stop this broken/invalid connection issue

**Comment by lucas-opentown** [comment]
@igaidai4uk Though the issue has been closed for a long time, I encountered the same problem with the same caution, using JedisPool (SedisPool using scala). Could you share your specific code and how you fix it? We are bothered by the issue for months, it is like a ghost with random occurrences.

**Comment by igaidai4uk** [comment]
@lucas-opentown in my case I had non thread safe code. I defined a variable outside the synchronized block as far as I remember.
