### ISSUE TITLE
about jedispool

### ISSUE THREAD

**Issue by cifeng101** [xetorthio/jedis#270]
hi.i want to ask you how i can check the jedispool current status just like current link/current idle link ,and so on.

**Comment by marcosnils** [comment]
@cifeng101 JedisPool internally uses commons-pool from apache which exposes a lot of information about the pool through JMX. If you attach any JMX client to your JVM you'll be able to see the pool internal status.

JedisPool also provides some methods to get some basic statistics about the pool such as:
`getNumActive`
`getNumIdle`
`getNumWaiters`
