### ISSUE TITLE
Jedis Client - Connection usage by Multiple threads

### ISSUE THREAD

**Issue by chaitradalawai** [xetorthio/jedis#3026]
### Expected behavior

I am using RediSearch through Jedis API Client, here I create client objects using the below code, after the required operation( writing or reading to an index), I close the connection using '**redis.clients.jedis.UnifiedJedis.close()**' , I have many indexes which am using for caching purpose, for which I want different threads from a threadpool for loading data to different indexes asynchronously and also handle multiple cache querying requests.

UnifiedJedis client = new JedisPooled(getGenericObjectPoolConfig(), host, port, timeout, password);

GenericObjectPoolConfig<Connection> getGenericObjectPoolConfig() {
	GenericObjectPoolConfig<Connection> config = new ConnectionPoolConfig();
	config.setMaxTotal(poolSize);
	return config;
}

//adding elements (once all the elements for this index are added, client.close() is called)
try {
	client.hset(docId, RediSearchUtil.toStringMap(documentFields));
}catch(Exception ex) {
	log.error("add element failed for docId:{}, exception:{} ",docId, ex.getMessage());
}

//getting elements
SearchResult sr = client().ftSearch(indexName, query);
closeClient(client);
return sr;

### Actual behavior
I am getting the exception 'Could not get a resource from the pool' when I allowed multiple threads to do the above operations.
I am guessing this might be because of client being closed after different operations, some threads are affected because of some other threads closing the connection.

Please help me know what happens if the connection is kept open all the time without calling close() at all. Is there any way to keep the connection open which will be closed after a certain idle time?

### Redis / Jedis Configuration
UnifiedJedis client = new JedisPooled(getGenericObjectPoolConfig(), host, port, timeout, password);

GenericObjectPoolConfig<Connection> getGenericObjectPoolConfig() {
	GenericObjectPoolConfig<Connection> config = new ConnectionPoolConfig();
	config.setMaxTotal(poolSize);
	return config;
}

**Comment by sazzad16** [comment]
> ... if the connection is ...

To be precise, it is not THE connection, it is a pool of `poolSize` number of connections.

> what happens if the connection is kept open all the time without calling close() at all

You would have a minimum of `0` to a maximum of `poolSize` number of idle socket connections till the rest of the lifetime of your application.

> Is there any way to keep the connection open which will be closed after a certain idle time?

No.

**Comment by chaitradalawai** [comment]
So, the ideal way is to close the pool connection after each of the operations ?

**Comment by sazzad16** [comment]
> So, the ideal way is to close the pool connection after each of the operations ?

NO, most definitely not.

**Comment by chaitradalawai** [comment]
Could you please suggest what is the best way to deal with this kind of situation? 
leave the connection pool open always and not use the close method for such multithreading operations?

**Comment by sazzad16** [comment]
@chaitradalawai It's hard to suggest without seeing your code, without knowing your code flow and application flow.

Assuming your `poolSize` is large enough, you can create `JedisPooled` only once at beginning of your application and close only once at the end of your application and use that JedisPooled in the entire application even in a multi-threaded scenario.

**Comment by chaitradalawai** [comment]
I have kept poolsize to be 1000.
	
I have tried to reduce my code to below pseudo code.
I have two java classes, I have kept all RediSearch operations in RedisCacheClient file, here I have client object as global variable as it can be resued for different indexes(I have 5 different indexes and one cacheimpl class for each of them), the client object is used by multiple operations. When I do getClient() before starting any operations, then the global variable is getting the JedisPooled object and close operation is reflected on the same global variable.

loading and searching methods are kept as asynchronous.

RedisCacheClient.java-----------------------

private UnifiedJedis client;

//creating required JedisPooled object
UnifiedJedis getClient() {
	this.client = new JedisPooled(getGenericObjectPoolConfig(), host, port, timeout, password);
	return client;
}

GenericObjectPoolConfig getGenericObjectPoolConfig() {
	GenericObjectPoolConfig config = new ConnectionPoolConfig();
	config.setMaxTotal(poolSize);
	return config;
}			

addElement()
try {
	client.hset(docId, RediSearchUtil.toStringMap(fields));
}catch(Exception ex) {
	log.error("add element failed for docId:{}, exception:{} ",docId, ex.getMessage());
}

void closeClient() {
	client.close();
}
---------------------------------------------



CacheImpl.java--------------------------------------
@Async
loadCache() {
	redisCacheClient.getClient();
	client.ftCreate(indexName1, indexOptions, schema1);
	listData.forEach(data -> {
		if(data != null) {
			redisCacheClient.addElement(PREFIX+data.getId(), dataFields);
		}
	});
	redisCacheClient.closeClient();
}

@Async
searchElements() {
	redisCacheClient.getClient();
	SearchResult sr = client().ftSearch(indexName, query);
	redisCacheClient.closeClient();
	return sr;
}
----------------------------------------------------------

**Comment by sazzad16** [comment]
@chaitradalawai You could've got your answers from https://github.com/redis/jedis/issues/3026#issuecomment-1157462931.

> Assuming your `poolSize` is large enough, you can create `JedisPooled` only once at beginning of your application and close only once at the end of your application and use that JedisPooled in the entire application even in a multi-threaded scenario.

Anyways...

1. You have large enough poolSize.
2. Create `client` only once. Can use `Lock` or something similar in `getClient()`.
3. Remove all `redisCacheClient.closeClient();`. May call `closeClient()` only once at the end of your application.

**Comment by chaitradalawai** [comment]
Yes, I got the answer from the previous comment, but wanted to add the code to get it confirmed :).
I had used poolsize as 100 earlier, seeing the error 'Could not get a resource from the pool', I increased it for testing purpose, as am not sure what is the ideal one to give.
Will check about the same.

Thanks for all the answers.
