### ISSUE TITLE
Thread hung?

### ISSUE THREAD

**Issue by zou** [xetorthio/jedis#333]
"pool-7-thread-1" prio=10 tid=0x00007fbda12eb800 nid=0x4984 in Object.wait() [0x00007fb2f125e000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:485)
        at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1104)
        - locked <0x00007fb7c20a9d80> (a org.apache.commons.pool.impl.GenericObjectPool$Latch)
        at redis.clients.util.Pool.getResource(Pool.java:20)

It seems that my thread that requesting a connection from the pool is hung, and it has the above stack. Is this a known problem?

**Comment by marcosnils** [comment]
@trasa @dhananjaypatkar any updates about this?. Have you tried your code making the necessary modifications?

**Comment by trasa** [comment]
Yes, I updated and used the new closeable pattern without problems.

**Comment by hao5ang** [comment]
Same problem with spring-data-redis.
My reaon is open RedisTemplate transaction support, but forget add @Transactional annocation on the util.
