### ISSUE TITLE
Add an official toString method for SlowLog Class

### ISSUE THREAD

**Issue by Hello-Frankey** [xetorthio/jedis#334]
In ourapplication, we check the slow logs with Jedis.slowlogGet() sometime and display them in a JSP. In this situation, construting a toString method for SlowLog is very useful to print slow log. So, adding an official toString method for SlowLog Class is possible? Of course, different applications may need different toString implementation, hence a  an official toString method may not be that beneficial ^.^

**Comment by sazzad16** [comment]
Fixed in #1041
