### ISSUE TITLE
Wording of Jedis description.

### ISSUE THREAD

**Issue by jockm** [xetorthio/jedis#347]
I haven't used Jedis but it does look quite good.  However I did want to point out one small thing about your description.  "Blazingly" isn't really an adjective one would associate with being small.

From [Dictionary.com](http://dictionary.reference.com/browse/blazingly?s=t)
> blaz·ing   [bley-zing] 
> adjective
> 1. burning brightly and with great heat, force, etc.
> 2. of tremendous intensity or fervor: a performance of blazing ferocity.

I might suggest "very small" or even "exceedingly small" instead.

That being said it is your project, I just thought I would pass this on.  

All the best,
Jock

**Comment by marcosnils** [comment]
@jockm thanks for the feedback I believe "blazing small" can be used as a compound from to say that something is "really small" the same way as "blazing fast". However as you correctly mentioned "blazingly small" is not appropriately used. 
We'll change the description accordingly.
