### ISSUE TITLE
Transaction aborted and forgetting txn.exec() cause the same exception

### ISSUE THREAD

**Issue by anonymouscodeholic** [xetorthio/jedis#352]
A test case:
- a transaction (let's call it txn1) watches a key with watch
- another txn (txn2) is created, modifies the same key,  txn2.exec() is called
- txn1 modifies the key, txn1.exec() is called
- Bug: Jedis gives error "Please close pipeline or multi block before calling this method." during the execution of txn1.exec()

The bug is that the exception risen points to a programming error - says that please close multi block even if that's what we're doing.

A concrete test case, see the test2-method in https://github.com/anonymouscodeholic/jedis/blob/a2c9430315d5fe04dbee792483bb344c274d99af/src/test/java/redis/clients/jedis/tests/commands/TransactionCommandsTest.java. 

Note the test doesn't work as such with the Jedis code, I created JedisTransactionAbortedException which is thrown when a txn is aborted. To test the issue with the Jedis code, remove thy try and catch in the end of the watch2-method. The test will crash in the line "njt.exec();"

An exception might be a good way to inform the caller of txn.exec() that the txn was aborted. Anyway, there should be a way for the caller to distinguish whether the txn was aborted or if the transaction didn't return anything.

Another way to fix the issue would be that the response of the txn.exec() would somehow telll that the txn was aborted. That's doable, return null as the response. But what's not that simple is:

...
Response<String> njGetResponse = t.get("mykey");
List<Object> njTransactionResp = njt.exec();
String njValue = njGetResponse.get();

Now if the txn was aborted, let's assume njValue gets the value null. How do you now distinguish between the key not found (in which case njValue == null) and the txn being aborted? If the caller cannot distinguish, that's a serious limitation. Things like "Using WATCH to implement ZPOP" (http://redis.io/topics/transactions) are hard to implement.

As a background, I stumbled upon this bug/limitation when doing a load test of correctly implemented code, which was giving "Please close pipeline or multi block before calling this method." without any obvious reason.

J

**Comment by sazzad16** [comment]
Closed due to inactivity.
