### ISSUE TITLE
Frequent JedisConnectionException when calling "select" in sharding environment.

### ISSUE THREAD

**Issue by labelnolongerexists** [xetorthio/jedis#396]
Exception stacktrace:

Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
at redis.clients.jedis.Protocol.process(Protocol.java:79)
at redis.clients.jedis.Protocol.read(Protocol.java:131)
at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:162)
at redis.clients.jedis.Jedis.select(Jedis.java:329)

Code:

        ShardedJedis shardedJedis = null;
        int index = {some number};

        try {
            shardedJedis = pool.getResource();

            Collection<Jedis> shards = shardedJedis.getAllShards();
            for( Jedis jedis: shards ) {
                jedis.select(index);
            }
            
            do somthing via shardedJedis...
            etc.
            shardedJedis.hgetAll(key);

        } catch (Throwable t) {
            pool.returnBrokenResource(shardedJedis);
            shardedJedis = null;
            throw new Exception("Cannot get cache from redis - " + key, t);
        } finally {
            if (shardedJedis != null) {
                pool.returnResource(shardedJedis);
            }
        }

dbsize: about 4M keys

pool config:

max_active: 750
max_idle: 100
max_wait: -1
timeout: 10000

**Comment by marcosnils** [comment]
Have you tried increasing the timeout?
