### ISSUE TITLE
JedisByteHashMap does not implement equals

### ISSUE THREAD

**Issue by christophsturm** [xetorthio/jedis#405]
failing test:

<pre>

    @Test
    public void testJedisByteHashMapImplementsEquals() {
        JedisByteHashMap m1 = new JedisByteHashMap(),
                m2 = new JedisByteHashMap();

        m1.put("he".getBytes(),"ho".getBytes());
        m2.put("he".getBytes(),"ho".getBytes());
        assertThat(m1).isEqualTo(m2);
    }
</pre>

**Comment by marcosnils** [comment]
It doesn't make sense to implement it as it's only used internally for commands that return Map<byte[], byte[]> which can't be equaled.

**Comment by christophsturm** [comment]
i think it makes sense for use in unit tests.

**Comment by christophsturm** [comment]
also its not only used internally, its part of the api

**Comment by marcosnils** [comment]
@christophsturm the class is part of an util package which is only used internally to handle `Map<byte[], byte[]>` types. As you may know primitive arrays in Java do not have en `equals` implementation, you need to either use an Util or wrap them around and write the `equals` yourself. 
`Jedis` never returns a JedisByteHashMap in any of their public API's, so it's a class that users should not instantiate or use in their code.

**Comment by marcosnils** [comment]
I'd like to know though how you came up with the scenario where you needed to use the class `equals` method.

**Comment by christophsturm** [comment]
ah ok you are right. its not really part of the api
I use hmset(byte[] key, Map<byte[], byte[]> hash) to set multiple keys in a map, and I use JedisByteHashMap to build the map that I pass to that method. 

I could of course my own hash map that implements equals instead. But its easy to do in JedisByteHashmap, and does no harm, so why not do it there.

**Comment by marcosnils** [comment]
@christophsturm I see. I'm not saying it can't be done, I believe that it wasn't something that we had in mind and we weren't thinking that someone might use that class outside Jedis. Writing an `equals` method for such class will require some rework for the reasons I've stated before. 

PR's are always welcome :wink:
