### ISSUE TITLE
JedisPool does not really block threads when pool is exhausted 

### ISSUE THREAD

**Issue by vicpara** [xetorthio/jedis#407]
Hi,
I'm using Jedis from a multi threaded environment and I'm constantly getting the
```redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:22)```

Here is my jedisPool config 
```
JedisPoolConfig poolConfig = new JedisPoolConfig();
		poolConfig.setMaxActive(WorkingThreads * 4);
		poolConfig.setMaxIdle(WorkingThreads * 4);
		poolConfig.setMinIdle(5);

	poolConfig.setWhenExhaustedAction(GenericObjectPool.WHEN_EXHAUSTED_BLOCK);
		poolConfig.setMaxWait(- 1);
		poolConfig.setTestOnBorrow(true);
```
In the above example `WorkingThreads = 6` because there are 6 threads running in the same time.
Here is the usage pattern of using Jedis connections:

```
class Worker
{
    private static JedisPool pool;

// on a thread of execution
   void DoSmth()
{
    Jedis cn =null;
    try
    {
         cn = pool.getResource()
        // do something
    }
    catch { pool.returnBrokenResource(cn); cn=null; }
    finally { if (cn!=null) pool.returnResource(cn);}

}

}
```

Now the problem is that I never see threads that wait for an available resource and I always get `Could not get a resource from the pool` error message.

All threads execute the DoSmth method about 100 times a second. I get an error message about 1 per 100K executions. After getting this exception, the thread tries again to obtain a Jedis connection in <5ms and most of the times gets one. If the threadpool is exhausted why doesn't it blocks until a new connection gets available? Also, if all other threads own a connection for an instance of the time, there are still plenty of connections available in the pool. The Redis server is set to close a connection after 30s of inactivity.

Everything got better when using `poolConfig.lifo = false;` but still i get plenty of errors. Is JedisPool really threadsafe ?

I'm using Redis 2.4 and Jedis 2.1.

**Comment by mjmanav4** [comment]
Do we need to return resource after getting it from pool ?

**Comment by sazzad16** [comment]
@mjmanav4 Yes, but not right after getting it. You should return a resource after completing works with it. Also it is important to note that in current days you don't need to call returnResource anymore. A call to `close()` of the resource (Jedis) is what you need.
