### ISSUE TITLE
How to select the database index for a pool?

### ISSUE THREAD

**Issue by kaadams4** [xetorthio/jedis#418]
I have seen a few questions like this but not in quite a while and was wondering if anything was done.  I'm creating a JedisPool and would like to select the db index.  Here is what I have:

    JedisPoolConfig config = new JedisPoolConfig();
    config.setMaxActive(env.getRedisPoolMaxActive());
    ......
    redisServerPool = new JedisPool(config, host, port);

I would like to be able to either set the database as a config value:
config.setDatabaseIndex(2);

or pass the database in:
new JedisPool(config, host, port, db);

or select it after the fact:
redisServerPool = new JedisPool(config, host, port);
redisServerPool.select(db);

Are any of these, or something like them, possible?

**Comment by jessicasco** [comment]
same question,  is there any progress on this issue?  or is there another way out ?

**Comment by nykolaslima** [comment]
You can select the database after getting the resource:

```
Jedis jedis = jedisPool.getResource();
jedis.select(db);
```

**Comment by HeartSaVioR** [comment]
Currently you can provide password to JedisPool's constructor.
So this issue is no longer valid. Closing.

**Comment by sandeepboys** [comment]
@nykolaslima using your solution it select the database index to only that specific resource? Next time if I get a resource from pool, I may get a different resource which points to older database index. How can I set the index for pool or for all the resources in the pool (also for newly created resources)?

**Comment by LifeXplorer** [comment]
Don't get why there are so many dislikes for @HeartSaVioR 's comment.
Now you can easily pass database index directly to `JedisPool` constructor:
```
public JedisPool(final GenericObjectPoolConfig<Jedis> poolConfig, final String host, int port,
      int timeout, final String password, final int database) {...}
```
