### ISSUE TITLE
Jedis expiring a psubscribe connection after a couple of minutes

### ISSUE THREAD

**Issue by RomainPiel** [xetorthio/jedis#428]
Hey,

I am using Jedis 2.0.2 and I just found out that a PSUBSCRIBE request is throwing a JedisConnectionException with this message:

```
It seems like server has closed the connection.
```

I've read in other issues that it is due to an expiration time of 300s. A request can't stay longer than 300s in Idle state, correct?

I'm not sure how to handle that exception. Ideally, the connection should stay alive until we do an unsubscribe.
I fixed the issue by:
- closing the broken pool when an exception is caught
- subscribing again to the corresponding channel

It's a bit dirty but at least it works. Is there another workaround?

Thanks

**Comment by marcosnils** [comment]
Timeout on the connection can now be specified.
