### ISSUE TITLE
Pipeline connection not closed

### ISSUE THREAD

**Issue by subshiri** [xetorthio/jedis#430]
I am using Jedis 2.0, JedisPoolConfig() and Redis 2.6.
I got the JedisConectionException  on calling Pipeline sync() and on the next iteration it throws JedisDataException. The code catches JedisConnectionException and handled with returnBrokenResource(), then also on the next iteration it causes JedisDataException. What should I do in this case?

JedisFactory.getInstance() returns a jedis object from the JedisConfigPool

for( each timerange){
getRecordsInTimeRange();
}

getRecordsInTimeRange(timerange[]){
Jedis jedis = null;
try{
	jedis = JedisFactory.getInstance();
        Pipeline pipeline = jedis.pipelined();
	Response<Set<Tuple>> setOfRecords =pipeline.zrangeByScoreWithScores(cachekey, timeRange[0], timeRange[1], from,size);
	Response<Long> countRes = pipeline.zcount(cachekey, timeRange[0], timeRange[1]);
	pipeline.sync();
			
	Set<Tuple> records = setOfRecords.get();
	Long count = countRes.get();
....
}catch(JedisConnectionException e){
	e.printStackTrace();
	JedisFactory.returnBrokenResource(jedis);
}finally{
	JedisFactory.returnResource(jedis);
}

This is the exception on first iteration.
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
	at redis.clients.jedis.Protocol.process(Protocol.java:74)
	at redis.clients.jedis.Protocol.read(Protocol.java:122)
	at redis.clients.jedis.Connection.getAll(Connection.java:207)
	at redis.clients.jedis.Connection.getAll(Connection.java:200)
	at redis.clients.jedis.Pipeline.sync(Pipeline.java:23)
	at com.test.queue.util.QueueUtil.getRecordInTimeRange(QueueUtil.java:388)

And on the next iteration the below exception occured. I guess the pipelined action from the previous iteration causes this problem. 
redis.clients.jedis.exceptions.JedisDataException:
 Please close pipeline or multi block before calling this method.
	at redis.clients.jedis.Response.get(Response.java:23)
	at com.test.queue.util.QueueUtil.getRecordsInTimeRange(QueueUtil.java:391)

**Comment by marcosnils** [comment]
This should be fixed already. Using `jedis.close()` should properly clear unused resources.
