### ISSUE TITLE
PubSub getting stuck in loop until crashing.

### ISSUE THREAD

**Issue by a1ph4g33k** [xetorthio/jedis#436]
Consider the following:

    public static void waitForSignal( String channel ) {

    // Validate input.
    checkNotNull( channel, "The provided channel is null." );
    checkState( channel.length() != 0, "The provided channel cannot be an empty string." );

    getInstance().subscribe( new JedisPubSub() {

      @Override
      public void onMessage( String received_channel, String received_message ) {

        _logger.debug( "Received message: '" + received_message + "' on channel: '" + received_channel + "'." );

        this.unsubscribe();
      }

      // stubs not necessary within our use case.
      @Override
      public void onPMessage( String s, String s2, String s3 ) {
      }

      @Override
      public void onSubscribe( String s, int i ) {
      }

      @Override
      public void onUnsubscribe( String s, int i ) {
      }

      @Override
      public void onPUnsubscribe( String s, int i ) {
      }

      @Override
      public void onPSubscribe( String s, int i ) {
      }

    }, channel );

    // This method will block on the above subscribe call until an appropriate message has been received.
    }

Given that, I expect my method to instantiate a JedisPubSub object, receive a single signal, & call unsubscribe ... which should unblock and leaving the method, uninstantiate the JedisPubSub instance ... 

It seems the objects stick around because I start to get extremely long log rolls from each of the PubSub objects receiving the broadcast.

**Comment by marcosnils** [comment]
@a1ph4g33k I'm pretty sure this has been fixed already. Can you upgrade your Jedis / Redis version and retry?
