### ISSUE TITLE
ConnectionPool and BrokenConnection

### ISSUE THREAD

**Issue by giridharkannan** [xetorthio/jedis#437]
As of present implementation if there has occurred an IOException it will be wrapped over JedisConnectionException (RuntimeException). As jedis users, When we use ConnectionPool we just get and release connection in a try finally block, we forget the catch block.

Here's an example:
```java
try {
    Jedis conn = getConn();
    conn.set("foo","bar");
} finally {
   release(conn);
}
```

If closing and returning a broken connection when IOEception occurs had been handled by jedis it would be much easier. As at present we are using already closed connection from the pool and writing to it, which result in a inconsistent state.

**Comment by marcosnils** [comment]
Resource cleanup has been unified in `Jedis.close` function.
