### ISSUE TITLE
Package Jedis as an OSGi bundle

### ISSUE THREAD

**Issue by timothyjward** [xetorthio/jedis#443]
The Jedis jar isn't suitable for use in OSGi, but with the addtion of some simple manifest entries it could be e.g.

    Manifest-Version: 1.0
    Bundle-ManifestVersion: 2
    Bundle-SymbolicName: org.jedis
    Bundle-Version: 2.1.0
    Export-Package: redis.clients.jedis;version="2.1.0",
     redis.clients.jedis.exceptions;version="2.1.0",
     redis.clients.util;version="2.1.0"
    Import-Package: org.apache.commons.pool;version="[1.5,2)",
     org.apache.commons.pool.impl;version="[1.5,2)"

This is just an example. I would recommend using a tool like bnd to generate this metadata for you. It should be very easy to plug in to the existing gradle build.

**Comment by marcosnils** [comment]
closed by #920
