### ISSUE TITLE
Transaction haven't all needed function

### ISSUE THREAD

**Issue by imysak** [xetorthio/jedis#454]
For example: 
1)
Jedis class have both 
 zrangeByScore(String key, double min, double max, int offset, int count)
 zrevrangeByScore(String key, double min, double max, int offset, int count)

but Transaction have just 
 zrangeByScore(String key, double min, double max, int offset, int count)
 but zrevrangeByScore is missed,

2)
Jedis have
   zrevrange(String key, double start, double end)
but Transaction have wrong types for start and end
   zrevrange(String key, int start, int end)

**Comment by marcosnils** [comment]
These are already implemented.
