### ISSUE TITLE
evalsha loses args

### ISSUE THREAD

**Issue by dmk23** [xetorthio/jedis#456]
If evalsha(byte[] sha1, List<byte[]> keys, List<byte[]> args) flavor of the evalsha method is used args are lost and used anywhere.

The problem is self-explanatory in the code:
https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/BinaryJedis.java#L3179

**Comment by marcosnils** [comment]
This has been fixed
