### ISSUE TITLE
Pure Java Redis mock

### ISSUE THREAD

**Issue by mcandre** [xetorthio/jedis#470]
For testing purposes, it would be nice if we could use Jedis with pure Java data structures (Lists, Hashes, Sets), rather than a real Redis server. Does anyone else think this would be a useful addition? Maybe the user could do something like `Jedis jedis = new PureJedis();`

**Comment by pyloque** [comment]
mock-jedis doest not support zset operation, so it's mostly useless!

**Comment by pyloque** [comment]
I was waiting zset support for year, there's nothing happended with mock-redis

**Comment by marcosnils** [comment]
@pyloque that's why it's better to test against a real redis service ;)

**Comment by pyloque** [comment]
python has mockredis, very easy to use, why java can't !

**Comment by smagellan** [comment]
@pyloque, did you try https://github.com/mockito/mockito ?
