### ISSUE TITLE
Jedis have no bundle exist?

### ISSUE THREAD

**Issue by timactive** [xetorthio/jedis#501]
Hi,
i have not found a official jedis bundle for my osgi container,
i have only found 
<dependency>
    	<groupId>org.apache.servicemix.bundles</groupId>
    	<artifactId>org.apache.servicemix.bundles.jedis</artifactId>
    	<version>2.2.1_1</version>
    	<type>bundle</type>
    </dependency>
Can you say where i found the official bundle?

**Comment by marcosnils** [comment]
closed by #920
