### ISSUE TITLE
Jedis Cluster is not thread safe?

### ISSUE THREAD

**Issue by mayankdang** [xetorthio/jedis#560]
I created a simple web app and deployed it on localhost using tomcat. It uses the jedis cluster to get and set a random value upon each 'get' request. 

```
@Override
    public void init() {
        rand = new Random();
        Set<HostAndPort> jedisClusterNodes = new HashSet<HostAndPort>();
        jedisClusterNodes.add(new HostAndPort("127.0.0.1", 7000));
        jedisClusterNodes.add(new HostAndPort("127.0.0.1", 7001));
        jedisClusterNodes.add(new HostAndPort("127.0.0.1", 7002));
        jc = new JedisCluster(jedisClusterNodes, new RTBSJedisPoolConfig());
        count = 1;
        logger.info("Init successful.");
    }

    @Override
    public void doGet(HttpServletRequest req, HttpServletResponse res) throws IOException {
        PrintWriter out = res.getWriter();
        res.setContentType("text/javascript");
        try {
            String response;
            String str = getRandomKey();
            String value = getRandomValue();
            String keyValue = jc.get(str);
            jc.set (str,value);
            out.println(value);
            logger.info("Message delivered - success! - " + count);
            count += 1;
        }
        catch (Exception e) {
            logger.error(e);
        }
    }
```

Apache Benchmark for this deployment using concurrency as 1 and any number of requests runs perfectly. 

```
ab -c 1 -n 10000 "localhost:8080/jedisClusterBenchmark/allStrings"
```

However, on increasing the concurrency to even 2, I get many exceptions.

```
ab -c 2 -n 100 "localhost:8080/jedisClusterBenchmark/allStrings"
```

Some of the exceptions are: 

```
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
redis.clients.jedis.exceptions.JedisException: Could not return the resource to the pool
```

Stack trace for one such exception is: 

```
message: Could not return the resource to the pool

description: The server encountered an internal error that prevented it from fulfilling this request.

exception:

redis.clients.jedis.exceptions.JedisException: Could not return the resource to the pool
    redis.clients.util.Pool.returnResourceObject(Pool.java:51)
    redis.clients.jedis.JedisPool.returnResource(JedisPool.java:88)
    redis.clients.jedis.JedisSlotBasedConnectionHandler.returnCurrentConnection(JedisSlotBasedConnectionHandler.java:24)
    redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnectionFromSlot(JedisSlotBasedConnectionHandler.java:40)
    redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:38)
    redis.clients.jedis.JedisCluster.get(JedisCluster.java:66)
    testing.servlets.AllStrings.doGet(AllStrings.java:46)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
    org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
root cause

java.lang.IllegalStateException: Returned object not currently part of this pool
    org.apache.commons.pool2.impl.GenericObjectPool.returnObject(GenericObjectPool.java:534)
    redis.clients.util.Pool.returnResourceObject(Pool.java:49)
    redis.clients.jedis.JedisPool.returnResource(JedisPool.java:88)
    redis.clients.jedis.JedisSlotBasedConnectionHandler.returnCurrentConnection(JedisSlotBasedConnectionHandler.java:24)
    redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnectionFromSlot(JedisSlotBasedConnectionHandler.java:40)
    redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:38)
    redis.clients.jedis.JedisCluster.get(JedisCluster.java:66)
    testing.servlets.AllStrings.doGet(AllStrings.java:46)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
    org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.47 logs.
```

Also, out of the 100 benchmark requests, ~ >50% of the requests give Exceptions. The exception percentage increases with increase in concurrency.
Any suggestions?
The benchmark runs perfectly for a sample app using a simple JedisPool using the same configuration as passed above in JedisCluster, for concurrency as high as 300.

Thanks!

**Comment by imran1609** [comment]
This is my RedisImpl class and on load test it is giving error
package com.onmobile.omega.shorturl.utils;

import java.util.Set;

import org.apache.log4j.Logger;

import redis.clients.jedis.Jedis;
import redis.clients.jedis.JedisPool;
import redis.clients.jedis.JedisPoolConfig;
import redis.clients.jedis.exceptions.JedisException;

public class RedisImpl {

	private static  JedisPool jedispool;
	private static  Jedis     jedis;
	
	private static Logger basicLogger = Logger.getLogger(RedisImpl.class);
	
	static {
		try{
			String useredis = I_Constants.USE_REDIS_CACHE;
			if(useredis!=null&&useredis.equalsIgnoreCase("true")){
				/*JedisPoolConfig jedisPoolConfig = new JedisPoolConfig();
				jedisPoolConfig.setMaxTotal(Integer.parseInt(I_Constants.MAX_REDIS_CONNECTIONS));*/
				jedispool = new JedisPool(I_Constants.REDIS_HOST,Integer.parseInt(I_Constants.REDIS_PORT));
				jedis = jedispool.getResource();
				jedis.flushDB();
			}
		}catch(Exception e){
			basicLogger.error("Error while initializing the redis server ",e);
		}
	}
	




	public static JedisPool getPool() {
		return jedispool;
	}

	public static void setPool(JedisPool pool) {
		RedisImpl.jedispool = pool;
	}

	public static Jedis getJedis() {
		return jedis;
	}

	public static void setJedis(Jedis jedis) {
		RedisImpl.jedis = jedis;
	}

	public static void setShorturlvalue(String key, String value){
		try{
			jedis = jedispool.getResource();
			jedis.set(key, value);
		}catch (JedisException e) {
            if (null != jedis) {
                jedispool.returnBrokenResource(jedis);
                jedis = null;
            }
        } finally {
            if (null != jedis)
                jedispool.returnResource(jedis);
        }
	}

	public static String getShorturlvalue(String key ){
		String value =null;
		try{
			jedis = jedispool.getResource();
			value = jedis.get(key);
			basicLogger.debug("value retireved " + value);
		}catch (JedisException e) {
            if (null != jedis) {
                jedispool.returnBrokenResource(jedis);
                jedis = null;
            }
        } finally {
            if (null != jedis)
                jedispool.returnResource(jedis);
        }
		return value;
	}


	public static  boolean isEmpty(){
		Set<String> listofkey = jedis.keys("*");
		if(listofkey.size()==0)
			return true;
		return false;
	}

	public static long getkeySize(){
		Set<String> listofkey = jedis.keys("*");
		
		return listofkey.size();
	}


}
and i am getting the following error

redis.clients.jedis.exceptions.JedisException: Could not return the resource to the pool
	at redis.clients.util.Pool.returnResourceObject(Pool.java:54)
	at redis.clients.jedis.JedisPool.returnResource(JedisPool.java:98)
	at com.onmobile.omega.shorturl.utils.RedisImpl.getShorturlvalue(RedisImpl.java:82)
	at com.onmobile.omega.shorturl.handler.ShortUrlController.findShortURL(ShortUrlController.java:135)
	at com.onmobile.omega.shorturl.handler.ShortUrlController.processRequest(ShortUrlController.java:74)
	at com.onmobile.omega.shorturl.handler.ShortUrlController.doGet(ShortUrlController.java:37)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Object has already been retured to this pool or is invalid
	at org.apache.commons.pool2.impl.GenericObjectPool.returnObject(GenericObjectPool.java:582)
	at redis.clients.util.Pool.returnResourceObject(Pool.java:52)
	... 23 more

**Comment by 18099538715** [comment]
I use the latest version but also meet this error , I just make a singleton JedisCluster and use it in multi thread
