### ISSUE TITLE
got data corrupt when set timeout = 1ms

### ISSUE THREAD

**Issue by zhenchuan** [xetorthio/jedis#572]
where i set the timeout == 1
Jedis edis = new Jedis("127.0.0.1", 6379, 1);
after any read timeout exception,it seems i got the incorrect value with my get request.
it seems that RedisInputStream has buffered my old (timeout error) responses ...

but if i set the timeout = 1000,even the read timeout exception occurs,i could also get the correct value ...

is there anything difference ? 
thanks for your reply.

test code from here . 
https://gist.github.com/zhenchuan/238eea8cc13917eaff8a

**Comment by marcosnils** [comment]
@zhenchuan updates?

**Comment by chensb** [comment]
any updates?
It seems I've meet the same issue now.
