### ISSUE TITLE
Command Timeout in jedis cluster

### ISSUE THREAD

**Issue by mayankdang** [xetorthio/jedis#602]
```JedisCluster``` class, while creating ```JedisClusterCommand``` in any function (say, ```get```) passes a timeout that gets saved as a private variable ```commandTimeout``` in ```JedisClusterCommand``` class. I did not find this variable getting used anywhere. Does the commandTimeout work?

**Comment by zd987** [comment]
Is there any update for this issue? JedisCluster need a way to update the timeout parameter. Thanks!

**Comment by marcosnils** [comment]
@zd987 JedisCluster already provides a way of updating the pool timeout. A constructor which receives a `GenericObjectPoolConfig` is available where you can setup your timeout parameters. 

I originally added the commandTimeout but then it became obsolete when we added the PoolConfig to the JedisCluster constructor. 
I guess we can safely remove it now. What do you think?

**Comment by marcosnils** [comment]
btw in case you want to know the parameter was introduced to accomplish the same functionality that the antirez ruby client does (https://github.com/antirez/redis-rb-cluster/blob/master/cluster.rb)

**Comment by HeartSaVioR** [comment]
Currently we can't set connection timeout / socket timeout to JedisCluster, cause timeout parameter is not passed to JedisClusterConnectionHandler, finally JedisClusterInfoCache, which initializes JedisPool.

**Comment by marcosnils** [comment]
@HeartSaVioR you're right, I thought we were passing the timeout parameter all the way back to the pool. I'll fix it tonight.
