### ISSUE TITLE
rename-command at redis.conf

### ISSUE THREAD

**Issue by DiegoSpinola** [xetorthio/jedis#625]
Hello there,

I'm currently using the following method (http://stackoverflow.com/questions/21539261/rename-command-example-with-jedis-client) to cope with the rename-command configuration at redis.conf (It's a really interesting feature ,see http://redis.io/topics/security)

is it possible to make the protocol command names in jedis configurable ?

**Comment by marcosnils** [comment]
@DiegoSpinola any suggestions about how you'd expect an API to be?
