### ISSUE TITLE
Exposing set nxxx, expx options for RedisCluster and ShardedRedis

### ISSUE THREAD

**Issue by SteveParrington** [xetorthio/jedis#640]
Hi all, because they were not exposed in the current RedisCluster/ShardedRedis classes, I added the set method with the nxxx and expx options to both of them. Before submitting a PR I'd like to add some tests for this but I'm not sure where the most appropriate place to put the tests is. Any guidance much appreciated!

**Comment by marcosnils** [comment]
This is already in master branch
