### ISSUE TITLE
performance getting slower while using jedis 

### ISSUE THREAD

**Issue by teresayan** [xetorthio/jedis#643]
We are trying to implement a benchmark tool jedis_benchmark.sh using jedis to connect to redis, jedis version 2.4.2 and redis version 2.8.8.

The performance as printed out from the tool decreases when we run the benchmark tool continously for a day.  First we get around 1000 set/sec, 2000 get/sec, as it gets to the end of the day, it drops to 100 set or get/sec.  However, redis-benchmark that redis comes with still performs well. 

the jedis_benchmark is using multithreading to send parallel requests to redis server, we are also using redis.clients.Jedis.JedisSentinelPool within each thread.

Teresa

**Comment by nykolaslima** [comment]
@teresayan any update on this?

**Comment by teresayanaxs** [comment]
We haven't focused much on the effort afterwards, but the problem goes away after a while.  We did take the suggestions, thanks @HeartSaVioR , though not sure if it is the one that fix the problem.

**Comment by teresayan** [comment]
We haven't focused much on the effort afterwards, but the problem goes away after a while. We did take the suggestions, thanks @HeartSaVioR , though not sure if it is the one that fix the problem.

**Comment by nykolaslima** [comment]
Since we got no more issues about it, probably @HeartSaVioR suggestions solved the problem.

I think we can close this. What do you think @teresayan @HeartSaVioR @marcosnils?

**Comment by HeartSaVioR** [comment]
@nykolaslima Yes, and @teresayan doesn't want to follow up much.
