### ISSUE TITLE
Thread not able to exit in redis.clients.Jedis.JedisSentinelPool 

### ISSUE THREAD

**Issue by teresayan** [xetorthio/jedis#644]
We are trying to implement a benchmark tool jedis_benchmark.sh using jedis to connect to redis, jedis version 2.4.2 and redis version 2.8.8.

The benchmark will create parallel requests to redis server using JedisSentinelPool

Thread inside redis.clients.Jedis.JedisSentinelPool is not able to exit (not able to catch connection exception) when calling Jedis disconnect() when the parallel requests from jedis_benchmark become larger than 100, the benchmark tool hangs after finishing sending all requests since a few thread is not able to exit.

Teresa

Teresa

**Comment by marcosnils** [comment]
@bearrito any updates?

**Comment by bearrito** [comment]
I haven't revisited this issue, but I haven't seen it appear in 2.6 code. We are transitioning our sole remaining 2.4 app to 2.6 this week. 

You can close this issue since I don't have any more info and won't for 2.4. 

Thanks.

**Comment by marcosnils** [comment]
Amazing, let us know if you need any help during the transition.
