### ISSUE TITLE
After Sentinel crash, jedisPool still subscribe master siwtich message from it

### ISSUE THREAD

**Issue by springside** [xetorthio/jedis#655]
The default TCP keep alived behavior is that when no data pass the connection after 2 hour, the linux system will start the keep alive probe.

Since message subscribe is one direction message, after sentineal server crash(like vm destroy), jedisSentinelPool didn't know that, so that it won't  reconnect to another sentinel server before 2 hour.

One way is change the tcp keep alived time, but it can'd be very short(like 10 seconds), should we run another thread to ping the sentinel server?

**Comment by sazzad16** [comment]
Closed due to inactivity.
