### ISSUE TITLE
Pipeline missing Scan functionality

### ISSUE THREAD

**Issue by macgngsta** [xetorthio/jedis#676]
it seems that regular Jedis has the Scan functionality, but the pipeline interface doesn't seem to support it?

scan, sscan, hscan, zscan

**Comment by mpetricek-corp** [comment]
Pipeline actually can help here. It cannot help with single scan, but now I have a use case where I need to scan many sets (i.e. sscan), in the order of tens of thousands of sets.
Without pipeline, I get latency penalty on each scan ... which is unusably slow. With pipeline I would be able to pipeline for example 1000 scans and then fetch 1000 results. In next pipeline I send up to 1000 cursors (those that were nonzero) for continued sscan ... repeating until I get all the data I need, much quicker.
