### ISSUE TITLE
Getting Timeout-Exception in Redis

### ISSUE THREAD

**Issue by Nitesh7** [xetorthio/jedis#684]
Hi All,

I am trying to do the following:
JedisPool jedispool = new JedisPool(new JedisPoolConfig(), host, port, timeout);
jedis = jedisPool.getResource();
Transaction t = jedis.multi();
t.del(advId);
t.hmset(advId, hashToBidValue);
t.set("{" + advId + "}" + "_ts", timeStamp.toString());

But I am getting the following exception:

 redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Broken pipe

I have tried multiple timeout values raising it as high as 180000 but am still seeing the broken-pipe error.

I observed that the exception I am getting after 2000 msec; meaning that somehow increasing timeout has no effect, any pointers on how to fix the issue.

Thanks,

**Comment by nykolaslima** [comment]
Those connection timeout problems doesn't looks like Jedis problem, so can we close it? @marcosnils @HeartSaVioR

**Comment by marcosnils** [comment]
@Nitesh7. Do you have any updates about this?

**Comment by rushabhnagda11** [comment]
Hey I'm not sure if this is the right place to post this, but I'm facing a very similar issue when doing an hmset.

Basically, what I've observed is that when the size of the map increases beyond 100 MB, then hmset begins throwing the above mentioned exception (As stated by Nitesh7). If the map size is relatively small, then everything happens correctly.

I've tried increasing the timeout to 1000000 but still doesn't help. Any ideas what could be going wrong here?

**Comment by HeartSaVioR** [comment]
@rushabhnagda11 You may want to check https://github.com/xetorthio/jedis/issues/906.

**Comment by marcosnils** [comment]
@rushabhnagda11 tl;dr redis has a limit on the amount of paramters you can send in a bulk string request. If you're sending more than 1024 * 1024 bulk requests redis will close the connection.

**Comment by rushabhnagda11** [comment]
In that case, using the jedis client how can I add more than 1 million keys to a redis hashmap? 

Because this is the documentation on hmset 
"Set the respective fields to the respective values. HMSET replaces old values with new values."

So everytime I do an hmset, it'll replace the existing million keys with the new batch, instead of appending to it. Is there another way to go about this?

**Comment by rushabhnagda11** [comment]
I'm going to go ahead with hset. Thanks for the help.

**Comment by lquterqtd** [comment]
@rushabhnagda11 
my solution is to split the huge map to that with 500000 keys map and save it in many times.

public void saveAll(Map<String, String> currentStrategy) {
        Map<String, String> tempMap = new HashMap<String, String>();
        for (Map.Entry<String, String> entry : currentStrategy.entrySet()) {
            tempMap.put(entry.getKey(), entry.getValue());
            if (tempMap.size() >= JedisBaseOper.BATCH_OPER_LIMIT) {
                Hmset(tempMap);
                tempMap.clear();
            }
        }
        
        if (tempMap.size() > 0) {
            Hmset(tempMap);
        }
    }

BATCH_OPER_LIMIT is 500000 , of course you could set it to 1024*1024/2=524288
