### ISSUE TITLE
Connection.isConnected() falsly returns true after network disconnect/reconnect

### ISSUE THREAD

**Issue by ssijak** [xetorthio/jedis#688]
When I connect to the Redis instance with Jedis and then disable ethernet adapter in windows and reanable it, isConnected() method will return true, when in reality it is not and all redis commands like ping, lpush, etc. will throw java.net.SocketException.

``` java
Caused by: java.net.SocketException: Connection reset by peer: socket write error
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
    at redis.clients.util.RedisOutputStream.flushBuffer(RedisOutputStream.java:31)
    at redis.clients.util.RedisOutputStream.flush(RedisOutputStream.java:223)
    at redis.clients.jedis.Connection.flush(Connection.java:276)
    ... 11 more
```

**Comment by galsivan** [comment]
I know this is old, but I am not sure I follow this answer. If it makes sense and intentional, then what's the use of the method isConnected()?

**Comment by sazzad16** [comment]
@galsivan Frankly speaking, you check `Jedis` code base to find some use cases of `isConnected()`.

**Comment by galsivan** [comment]
I actually checked, and isConnected() is in a try-catch clause everywhere in the code. But it doesn't even look like it's supposed to throw an error. I still don't understand its purpose if it doesn't report actual state of connection, but rather whether a connection has been initialized.

In another instance there is also a ping check. I still don't get what helpful info isConnected() is supposed to supply the caller, if it needs to be used in conjunction with ping()...
`public boolean validateObject(final Object obj) {
    if (obj instanceof Jedis) {
        final Jedis jedis = (Jedis) obj;
        try {
            return jedis.isConnected() && jedis.ping().equals("PONG");
        } catch (JedisException e) {
            logger.error(e.getMessage());
            return false;
        }
    } else {
        return false;
    }
}`

**Comment by sazzad16** [comment]
@galsivan 

Think `ping()` is from the perspective of Redis instance, whether it's running and ready to serve you.

Think `isConnected()` is from the perspective of your system application running with Jedis, whether it's holding the necessary resources in your system and *already prepared* with those resources to communicate with Redis. It may have already that contact or may not!

Makes sense?

**Comment by galsivan** [comment]
It still doesn't make a lot of sense because it is not really connected. Normally an isConnected() function checks that the connection is still alive, not that the object is initialized or resources are present. I think something like isInitialized() would make more sense. Just my two cents.

**Comment by defnull** [comment]
Welcome to the joys of socket programming: The only way to find out if you can send data over a socket, is sending data over a socket. That is true for any network library, not just Jedis.

`isConnected() == false` tells you that the client needs to reconnect (which it does automatically). `isConnected() == true` does not tell you anything. The next command might get through, or it might not. Even if the TCP stream is perfectly fine and healthy at the time you call `isConnected()` or `ping()`, network might go down the millisecond after. You ALWAYS have to expect command to fail. Checking `isConnected()` beforehand is useless.

That said, `isConnected()` will only lie to you if the socket is in an undefined state (disconnected, but the operating system does not know that yet). It returns true if the socket appear to be connected. That's fair, I think.
