### ISSUE TITLE
Fail to make package (error: 'cluster-node-timeout 50')

### ISSUE THREAD

**Issue by airpingu** [xetorthio/jedis#696]
make start
rm -vf /tmp/redis_cluster_node*.conf 2>/dev/null
rm dump.rdb appendonly.aof - 2>/dev/null
make[1]: [cleanup] Error 1 (ignored)
echo "$REDIS1_CONF" | redis-server -
echo "$REDIS2_CONF" | redis-server -
echo "$REDIS3_CONF" | redis-server -
echo "$REDIS4_CONF" | redis-server -
echo "$REDIS5_CONF" | redis-server -
echo "$REDIS6_CONF" | redis-server -
echo "$REDIS7_CONF" | redis-server -
echo "$REDIS_SENTINEL1" > /tmp/sentinel1.conf && redis-server /tmp/sentinel1.conf --sentinel
echo "$REDIS_SENTINEL2" > /tmp/sentinel2.conf && redis-server /tmp/sentinel2.conf --sentinel
echo "$REDIS_SENTINEL3" > /tmp/sentinel3.conf && redis-server /tmp/sentinel3.conf --sentinel
echo "$REDIS_CLUSTER_NODE1_CONF" | redis-server -

**\* FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 3

> > > 'cluster-node-timeout 50'
> > > Bad directive or wrong number of arguments
> > > make[1]: **\* [start] Error 1
> > > make: **\* [package] Error 2

This really confuses me because I couldn't figure out how to solve this. I saw some comments at https://groups.google.com/forum/#!msg/jedis_redis/66Z-VWiybe0/ftsPyUCGFJAJ but I don't how to install Redis-3.0 because by default `brew install redis` will just install Redis-2.8.13 on MacOSX. I also tried to manually download and install Redis-3.0 by http://redis.io/download, but I got no lucky on MacOSX, which showed me:

Undefined symbols for architecture x86_64:
  "___atomic_add_fetch", referenced from:
      _zmalloc in zmalloc.o
      _zcalloc in zmalloc.o
      _zrealloc in zmalloc.o
      _zmalloc_used_memory in zmalloc.o
      _zmalloc_get_fragmentation_ratio in zmalloc.o
  "___atomic_sub_fetch", referenced from:
      _zrealloc in zmalloc.o
      _zfree in zmalloc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: **\* [redis-server] Error 1
make: **\* [all] Error 2

Does anyone which Jedis branch/tag can be compatible with Redis-2.8.13? I just tried switching branch to 2.5 and 2.6 but it still shows 'cluster-node-timeout 50' building error.

**Comment by Zitrax** [comment]
The main page say that "Jedis is fully compatible with redis 2.8.5." so is this only a build issue ? If so are there pre built jars somewhere ?

**Comment by nykolaslima** [comment]
@Zitrax `make start` command starts the Redis servers needed to run the tests.
Probably, the Redis installed on your machine is not the latest unstable version of Redis, that's why your `make start` is getting errors.

I think you can't install the latest unstable version of Redis from `brew install`. You need to checkout the Redis repo(https://github.com/antirez/redis) and build it manually.
