### ISSUE TITLE
Some tests in error when make package

### ISSUE THREAD

**Issue by airpingu** [xetorthio/jedis#697]
I just checked the latest Jedis master branch and the latest Redis master branch (unstable branch) 20 minutes ago. Then I tried to run ```make package``` under Jedis. It shows some tests in error as below:

Results :

Tests in error:
  ControlCommandsTest.waitReplicas:123 » JedisData ERR unknown command 'WAIT'
  JedisClusterReplicateTest.testClusterFailover:159 » JedisData ERR You should s...
  JedisSentinelPoolTest.ensureSafeTwiceFailover:43->forceFailover:143 » JedisData
  JedisSentinelTest.sentinelFailover:94 » JedisData NOGOODSLAVE No suitable slav...

Tests run: 365, Failures: 0, Errors: 4, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:09 min
[INFO] Finished at: 2014-08-14T00:19:49+08:00
[INFO] Final Memory: 16M/310M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test (default-test) on project jedis: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/genelian/yahoo/twdata/legolas/jedis/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
make: *** [package] Error 1

Can any one help me out? Thanks!

**Comment by xetorthio** [comment]
One thing we can do is to start every redis with a random available port instead of a fixed one.
This can be done with something like this:
```
python -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()' 
```
