### ISSUE TITLE
Intermittent JedisConnectionException

### ISSUE THREAD

**Issue by djhalaninext** [xetorthio/jedis#704]
Hi,
I am seeing JedisConnectionException intermittently.
Exception: redis.clients.jedis.exceptions.JedisConnectionException: It seems like server has closed the connection. 

Here are my connection pool config:
                maxActive = 128
                maxIdle = 5
                minIdle = 1
                testOnBorrow = true
                testOnReturn = true
                testWhileIdle = true
                numTestsPerEvictionRun = 10
                timeBetweenEvictionRunsMillis =
                maxWait = 60000
                timeout = 60000

**Comment by nykolaslima** [comment]
@marcosnils  @HeartSaVioR since it's not a Jedis bug, can we close it?

**Comment by marcosnils** [comment]
@nykolaslima we better ask the @djhalaninext if he has any updates about this issue. In case he doesn't come back, then we can close it.

**Comment by djhalaninext** [comment]
Its not a Jedis bug. Thanks for all the help.
