### ISSUE TITLE
result of binary hgetAll() method from pipeline

### ISSUE THREAD

**Issue by idyedov** [xetorthio/jedis#711]
I noticed that hgetAll(byte[] key) returns a HashMap<byte[], byte[]>() object when called from a pipeline.

byte arrays don't override hashCode() method so I believe that it would use the object identity for hashCode(), and thus this test fails:
```java
Map<byte[], byte[]> map = new HashMap<byte[], byte[]>();
map.put(new byte[]{0x01, 0x02, 0x03, 0x04}, new byte[]{0x05, 0x06, 0x07, 0x08});
assertEquals(new byte[]{0x05, 0x06, 0x07, 0x08}, map.get(new byte[]{0x01, 0x02, 0x03, 0x04}));
```

in jedis we have similar code in the test for hgetAll():

```java
Map<byte[], byte[]> bh = new HashMap<byte[], byte[]>();
bh.put(bbar, bcar);
jedis.hmset(bfoo, bh);
Map<byte[], byte[]> bhash = jedis.hgetAll(bfoo);
assertArrayEquals(bcar, bhash.get(bbar));
```

which is fine because BinaryJedis uses JedisByteHashMap wrapper for hgetAll, but that's not the case for hgetAll() in PipelineBase, so this test will fail:

```java
Map<byte[], byte[]> bh = new HashMap<byte[], byte[]>();
bh.put(bbar, bcar);
jedis.hmset(bfoo, bh);
Pipeline pipeline = jedis.pipelined();
Response<Map<byte[], byte[]>> bhashResponse = pipeline.hgetAll(bfoo);
pipeline.sync();
Map<byte[], byte[]> bhash = bhashResponse.get();
assertArrayEquals(bcar, bhash.get(bbar));
```

does it make sense to switch the BYTE_ARRAY_MAP Response Builder to use JedisByteHashMap wrapper as well? will it break anything elsewhere?

**Comment by DivineTraube** [comment]
Hi,

this is still not fixed resp. released:
https://github.com/xetorthio/jedis/blob/2.7/src/main/java/redis/clients/jedis/BuilderFactory.java
https://github.com/xetorthio/jedis/blob/jedis-2.7.2/src/main/java/redis/clients/jedis/BuilderFactory.java

contains the *old* code that still instantiates a HashMap. Thus, though the fixed code is in the master, using the newest distribution still does not include the fix...

**Comment by marcosnils** [comment]
@DivineTraube you're correct. @HeartSaVioR do you know why 9f4faf53ffdc87387d84bb9b4d1b1a9de393afed didn't reach 2.6 and 2.7?

Thaks!.

**Comment by HeartSaVioR** [comment]
@marcosnils 
Seems like I did a mistake, it was merged to only master.
I'll cherry-pick that commit into 2.7 branch.

**Comment by HeartSaVioR** [comment]
FYI, PR was https://github.com/xetorthio/jedis/pull/715

**Comment by marcosnils** [comment]
@HeartSaVioR good catch. I guess we can reopen the issue so we can close it once we release.

**Comment by HeartSaVioR** [comment]
Btw, Github points out that 9f4faf5 exists from 2.7.0 tag, while it shouldn't.

**Comment by marcosnils** [comment]
@HeartSaVioR yeah I saw that.. github is lying to us :D

**Comment by HeartSaVioR** [comment]
Just cherry-picked 9f4faf5 into 2.7 branch via b309237.

**Comment by HeartSaVioR** [comment]
@marcosnils OK, I reopened this. Also set milestone to 2.7.3 so that we don't forget again.
