### ISSUE TITLE
why  timeout default is 2000ms ???

### ISSUE THREAD

**Issue by luyee** [xetorthio/jedis#724]
why timeout of jedispool  default is 2000ms  ,it based what ?  and what the 2000ms  means ? how could  i set in production env ?   >2000ms or <2000ms or use default

this timeout is the same value, is it reasonable？？should  these be two difference timeout
socket.connect(new InetSocketAddress(host, port), timeout);
socket.setSoTimeout(timeout);

this may result  socket's connnet() and read() function has the same timeout

**Comment by nykolaslima** [comment]
I think we can close this with #842

**Comment by nykolaslima** [comment]
@HeartSaVioR I think we can close this with #842

**Comment by marcosnils** [comment]
@nykolaslima we can close once #842 is labeled as "ready to merge"

**Comment by zanella** [comment]
Guess this one can be closed by now then :-)
