### ISSUE TITLE
How to use Jedis API to handle failover (i.e. when the master server goes down)?

### ISSUE THREAD

**Issue by airpingu** [xetorthio/jedis#725]
I'm using Jedis 2.5.1 + Redis 2.8.14 which are considered the most stable versions respectively.

As far as I know, Redis supports master/slave mode, which allows different servers replicate data with each other as backups. However how can we use Jedis API to automatically switch to the slave server when the master server goes down?

This link https://github.com/xetorthio/jedis/wiki/Getting-started only shows us some simple examples about how to use Jedis API to configure the master-slave relations (i.e. `slaveOf(...)`). However, it seems that I still need to write my own Jedis codes to achieve the automatic failover.

For example, I need to call the `ping()` to test if the master server is still alive. If it throws exception (because the master server goes down), then I know I have to reset one of the slave servers as the new master server and let my client start reading/writing data on this new one. That is, I have to collect all the available master/slave servers in advance and write codes to dynamically choose one as my master and accordingly reset others as slaves, whenever the original server goes down.

Is my understanding correct? Or is there any smarter way of leveraging the Jedis API to handle failover?

Sorry for dropping a question in the issues. I'll close this issue by myself if it can get answered. Thank you very much!

Gene

**Comment by Balaji001** [comment]
Hi can you give me any idea to get jedis connection factory with jedissentinalpool
