### ISSUE TITLE
JedisSentinelPool will keep pinging the redis-sentinel which blocks my service.

### ISSUE THREAD

**Issue by airpingu** [xetorthio/jedis#726]
Supposing my redis-sentinel is not running, when I call:

```
HashSet<String> sentinels = new HashSet<String>();
sentinels.add("127.0.0.1:1234");
JedisSentinelPool jedisPool = new JedisSentinelPool("mymaster", sentinels);
```

It will endlessly output the following log:

Sep 02, 2014 8:18:20 PM redis.clients.jedis.JedisSentinelPool initSentinels
INFO: Trying to find master from available Sentinels...
Sep 02, 2014 8:18:20 PM redis.clients.jedis.JedisSentinelPool initSentinels
WARNING: Cannot connect to sentinel running @ 127.0.0.1:1234. Trying next one.
Sep 02, 2014 8:18:20 PM redis.clients.jedis.JedisSentinelPool initSentinels
SEVERE: All sentinels down, cannot determine where is mymaster master is running... sleeping 1000ms.
Sep 02, 2014 8:18:21 PM redis.clients.jedis.JedisSentinelPool initSentinels
INFO: Trying to find master from available Sentinels...
Sep 02, 2014 8:18:21 PM redis.clients.jedis.JedisSentinelPool initSentinels
WARNING: Cannot connect to sentinel running @ 127.0.0.1:1234. Trying next one.
Sep 02, 2014 8:18:21 PM redis.clients.jedis.JedisSentinelPool initSentinels
SEVERE: All sentinels down, cannot determine where is mymaster master is running... sleeping 1000ms.
Sep 02, 2014 8:18:22 PM redis.clients.jedis.JedisSentinelPool initSentinels
INFO: Trying to find master from available Sentinels...
Sep 02, 2014 8:18:22 PM redis.clients.jedis.JedisSentinelPool initSentinels
WARNING: Cannot connect to sentinel running @ 127.0.0.1:1234. Trying next one.
Sep 02, 2014 8:18:22 PM redis.clients.jedis.JedisSentinelPool initSentinels
SEVERE: All sentinels down, cannot determine where is mymaster master is running... sleeping 1000ms.
... (the following is the same)

I'm very confused by this phenomenon because I cannot catch any exceptions to do fallback when the redis-sentinel goes down or is not available. It just keep pinging the sentinel which blocks my Web service.

Does anyone know how to handle this case?

Cheers,
Gene

**Comment by fulnLee** [comment]
i got the same question, However the jedis version i used  is 2.7.3 .
