### ISSUE TITLE
Add default of only eight connections to the wiki FAQ

### ISSUE THREAD

**Issue by sodoku** [xetorthio/jedis#739]
Please add this to the wiki (would have saved me alot of time):

## JedisPool blocks after getting 8 connections

JedisPool defaults to 8 connections, you can change this in the PoolConfig:

```java
JedisPoolConfig poolConfig = new JedisPoolConfig();
poolConfig.setMaxTotal(maxTotal); // maximum active connections
poolConfig.setMaxIdle(maxIdle);  // maximum idle connections
```

**Comment by mogren** [comment]
I agree, add sensible values for this in JedisPoolConfig.java and update the FAQ.

**Comment by marcosnils** [comment]
Added here https://github.com/xetorthio/jedis/wiki/FAQ#jedispool-blocks-after-getting-8-connections

Thanks for contributing!.

**Comment by sodoku** [comment]
Thanks!

**Comment by boughtonp** [comment]
Where does the number 8 come from - is it arbitrary or based on some criteria?
