### ISSUE TITLE
Provide added redis calls for JedisCluster to enable directing to single machine commands

### ISSUE THREAD

**Issue by allanwax** [xetorthio/jedis#764]
Doing a ping() on the cluster could be interpreted as meaningless and currently it will fail since no key is provided in the call.  We should (perhaps) overload ping() and similar commands to accept parameters that allow you to direct the command to a certain machine.  For example.

ping(String key): hash the key an pick the machine/slot associated with the key.  Then send a ping() to it.

ping(int slot): send a ping() to the machine currently handling that slot.

Using this I can direct things to a single redis instance that does not make sense as a cluster..

Other possible candidates: blpop, brpop, echo, quit, flushdb, dbsize, select, etc.

**Comment by allanwax** [comment]
@sazzad16   Having a work-around by processing the node information is not the same as providing clean functionality.  I would have liked to have seen this discussed more before closing the ticket.

**Comment by sazzad16** [comment]
@HeartSaVioR @marcosnils WDYT?

**Comment by marcosnils** [comment]
@allanwax do you have a current use-case for this specifically right now?. I haven't seen so many requests for something like this and taking in consideration that a key and a slot `can` possibly migrate nodes (scaling or resilience), I'm not completely convinced about allowing something like this.

**Comment by allanwax** [comment]
@marcosnils I have and continue to have a use for this case.  One of our redis clusters is 12 masters and 12 slaves.  To improve performance we use the slaves in readonly mode to get information and writes go as normal to the masters.  We are tolerant of data being stale or non-existant in the slave.  To make this happen properly we have to periodically get the cluster nodes, process the information, taking into account that the information has changed between version 3 and 4 of redis cluster, and make the right decisions as to what to do and where to send it.  It would be much easier to ping the slave when we know the slave, to know whether it is probable that it is safe to do an operation, without knowing the underlying details and do our operations.

However, this is a specific use and I was trying to get discussion on making it easier to surface specific information on the nodes without having to parse the result string.

That said, what we have works (out of necessity) and I don't see the need to expend great effort for this.
