### ISSUE TITLE
When a timeoutexception occurs,I get the wrong values.

### ISSUE THREAD

**Issue by qingchen191** [xetorthio/jedis#816]
When I do get option , the value has read into the buffer, and then It's timeout.
It throws a timeout Exception, then ,the next get option come, because the connection is also the old one before the timeout exception, so I have the value got by the first get option.
because of this , my project has some problems for two times.
I think it's a bug, and I have fix this in my project.
When the exception occurs , close the connection.

Protocol.java

    private static void sendCommand(final RedisOutputStream os,
	    final byte[] command, final byte[]... args) {
	try {
	    os.write(ASTERISK_BYTE);
	    os.writeIntCrLf(args.length + 1);
	    os.write(DOLLAR_BYTE);
	    os.writeIntCrLf(command.length);
	    os.write(command);
	    os.writeCrLf();

	    for (final byte[] arg : args) {
		os.write(DOLLAR_BYTE);
		os.writeIntCrLf(arg.length);
		os.write(arg);
		os.writeCrLf();
	    }
	} catch (IOException e) {
            // when exception close the connection.
            connection.disconnect();  
	    throw new JedisConnectionException(e);
	}
    }

    private static Object process(final RedisInputStream is) {
	try {
	    byte b = is.readByte();
	    if (b == MINUS_BYTE) {
		processError(is);
	    } else if (b == ASTERISK_BYTE) {
		return processMultiBulkReply(is);
	    } else if (b == COLON_BYTE) {
		return processInteger(is);
	    } else if (b == DOLLAR_BYTE) {
		return processBulkReply(is);
	    } else if (b == PLUS_BYTE) {
		return processStatusCodeReply(is);
	    } else {
		throw new JedisConnectionException("Unknown reply: " + (char) b);
	    }
	} catch (IOException e) {
            // when exception close the connection.
            connection.disconnect(); 
	    throw new JedisConnectionException(e);
	}
	return null;
    }

**Comment by nykolaslima** [comment]
I don't think that Jedis need to close the connection if any error occurs. Users should catch `JedisConnectionException` and close the connection.

Having this in mind I think we can close this issue, what do you think @HeartSaVioR?

It has been opened since 11, Dec 2014.

**Comment by HeartSaVioR** [comment]
@nykolaslima Agreed!
@qingchen191 Please reopen this issue if you think it's not resolved now. Closing.
