### ISSUE TITLE
Implement CLIENT KILL filters

### ISSUE THREAD

**Issue by marcosnils** [xetorthio/jedis#818]
I'm opening the issue for tracking. I'll try to do it today. 
http://redis.io/commands/client-kill

**Comment by nykolaslima** [comment]
@marcosnils what do you mean by `filters`?

The target of this issue is to implement the `client-kill` command?

**Comment by marcosnils** [comment]
@nykolaslima currently Jedis only allows to issue a `client kill` by sending the client id. Not so long ago Redis also included a new way to kill clients by sending different filters which are documented here: http://redis.io/commands/client-kill. 

The purpose of this issue is to change Jedis so filters can be used.

**Comment by nykolaslima** [comment]
I got you. I'll try to implement it.
