### ISSUE TITLE
There is no way to select database in ShardedJedis

### ISSUE THREAD

**Issue by nykolaslima** [xetorthio/jedis#820]
There is no way to select database with `ShardedJedis`?
```
//With Jedis class, it works
jedis.select(0);
//With ShardedJedis, there is no method select
shardedJedis.select(0);
```

**Comment by HeartSaVioR** [comment]
@nykolaslima Hello, any update on it?

**Comment by nykolaslima** [comment]
Hi @HeartSaVioR. I'm sorry, I've been busy this days. I'll implement it this weekend and send you a PR.
