### ISSUE TITLE
JedisShardInfo cannot set both the name and weight

### ISSUE THREAD

**Issue by EdwardLee03** [xetorthio/jedis#825]
Hi, JedisShardInfo cannot set both the name and weight, because now I need to them.
Can add the following constructor method that includes name and weight parameters:

    public JedisShardInfo(String host, int port, String name, int weight, int timeout)

**Comment by EdwardLee03** [comment]
Thanks @nykolaslima, great job! :+1:

**Comment by nykolaslima** [comment]
@EdwardLee03 no problem. Thank you for reporting :rocket:
