### ISSUE TITLE
[Question] Is Jedis backward compatible when upgrading the version?

### ISSUE THREAD

**Issue by airpingu** [xetorthio/jedis#840]
Hi Jedis Developers,

This is just a question about the compatibility of Jedis (I'll close the issue by myself when the question is clarified). I'm attempting to upgrade Jedis from 2.4.2 to 2.6.2 to support Cluster. I'd like to make sure all my previous functions are still working as expected, including JedisPool and JedisSentinelPool related APIs.

In addition to the practical test, I'd like to understand the compatibility of Jedis from the point of view of design philosophy. Is Jedis always backward compatible with the previous features and the way of how the existing clients call the APIs in any way?

Gene

**Comment by marcosnils** [comment]
Gene, 

Jedis versions follow the semver (http://semver.org/) convention. You will find the answer to your question by reading how semver works. 

To quickly response your question, you won't have any problem if you upgrade from Jedis 2.4.x to 2.6.x as MINOR or PATCH changes don't break backward compatibility.

**Comment by airpingu** [comment]
Awesome! Good to learn the semver convention. Thank you for the response.

Closing the issue.
