### ISSUE TITLE
Could not get a resource from the pool

### ISSUE THREAD

**Issue by feidaodalian** [xetorthio/jedis#844]
Hi ,Ihave a question,my jedis 2.6.2and redis is 2.6.4,Sometimes I use jedisPool,,Exception appear " redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
......................................
Caused by: java.util.NoSuchElementException: Unable to validate object
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:502)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:361)
        at redis.clients.util.Pool.getResource(Pool.java:48)
"
But,My jedisPoolConfig is "
maxTotal" value="5000"
		"maxIdle" value="1000"
		"minIdle" value="50"
		"maxWaitMillis" value="1000"
		 "testOnBorrow" value="true"
		"testOnReturn" value="true"
		 "testWhileIdle" value="true"
"

**Comment by marcosnils** [comment]
@feidaodalian, have you checked this?

https://github.com/xetorthio/jedis/issues/661

**Comment by Gillingham** [comment]
The default JedisPool size is really small, that should be mentioned in the docs. There is #739 open currently.

I was running into the same issue where randomly during a lot of writes to redis I would get the same error message, I solved this by increasing the pool max size via JedisPoolConfig setMaxTotal()

**Comment by marcosnils** [comment]
Wiki has been updated accordingly
