### ISSUE TITLE
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Broken pipe

### ISSUE THREAD

**Issue by gauravparmar85** [xetorthio/jedis#848]
Hi I am using Jedis 2.4.2 and i am getting this exception almost every time I make a call.
I am initializing jedis pool as 
JedisPool jedisPool = new JedisPool(config, uri.getHost(), uri.getPort(), 10000);

and trying to get keys using 

public Set<String> keySet(String pattern) {
		boolean valid = true;
		Jedis jedis = jedisPool.getResource();
		try {
			auth(jedis);
			return jedis.keys(defaultKeyPrefix + pattern);
		} catch (JedisException e) {
			valid = false;
			logger.warn("Redis read exception", e);
		} finally {
			if (valid) {
				jedisPool.returnResource(jedis);
			} else {
				jedisPool.returnBrokenResource(jedis);
			}
		}
		return null;
	}

redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Broken pipe
        at redis.clients.jedis.Connection.flush(Connection.java:70)
        at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:210)
        at redis.clients.jedis.Jedis.keys(Jedis.java:186)
        ..few more
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:111)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:223)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549)
Caused by: java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:92)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:136)
        at redis.clients.util.RedisOutputStream.flushBuffer(RedisOutputStream.java:31)
        at redis.clients.util.RedisOutputStream.flush(RedisOutputStream.java:223)
        at redis.clients.jedis.Connection.flush(Connection.java:68)
        ... 10 more

**Comment by nykolaslima** [comment]
@gauravparmar85 I think this problem was fixed by https://github.com/xetorthio/jedis/issues/636

Can you upgrade to version 2.5.1 and test again?

**Comment by HeartSaVioR** [comment]
@nykolaslima Unfortunately, it seems to not related to issue/PR you stated. It was ArrayIndexOutOfRangeException.
@gauravparmar85 
Do you have any timeout configuration from Redis? Seems like Redis suddenly disconnected.
Could you share your Pool Config?
We can validate Jedis instance before getting it from pool, by GenericObjectPoolConfig.setTestOnBorrow(true);

**Comment by gauravparmar85** [comment]
@HeartSaVioR Actually the scenario is, I have this job configured using spring cron and it runs once in 24 hours to create some report from the data that i keep in redis DB. I works fine for the first time when i create the JedisPool but starts failing after that.
JedisPool jedisPool = new JedisPool(config, uri.getHost(), uri.getPort(), 10000);
in the above initialization config is : config = new GenericObjectPoolConfig();

**Comment by gauravparmar85** [comment]
Thanks all for your help. Modifying the pool config fixed this issue.

**Comment by hiakashjain** [comment]
@gauravparmar85 I am getting the same error, Can you please help me what exactly you changed/added in pool config to fix this problem.

**Comment by remy1991** [comment]
@gauravparmar85 : Hey, can you share the changes done in the pool config. I am facing the same error.

**Comment by liuxuan207** [comment]
@gauravparmar85 , guy, could you share the pool config fixed the issue? I have the same problem.

**Comment by elvis9xu** [comment]
I encountered the same error, my code is as follows, and I use jdk 1.8
try (Jedis jedis = jedisPool.getResource()) {
     byte[] bytes = jedis.get(key.toString().getBytes(defaultCharset));
}

There is a guy said change the redis config can solve this problem. Can any one find out which config to change?

**Comment by marcosnils** [comment]
@elvis9xu he said that a pool config solved the issue, not a redis config. Maybe @gauravparmar85 can provide further info.

**Comment by zackypick** [comment]
Just had a similar issue and setting the test on borrow to true did the trick. I have a hunch that's what  gauravparmar85 meant when he wrote "Thanks all for your help. Modifying the pool config fixed this issue" and vanished forever LOL :)

**poolConfig.setTestOnBorrow(true);**

**Comment by jamesone** [comment]
I just restarted my server which was using `jedis`, that fixed it for me.

**Comment by anjieych** [comment]
yeah,I do restart my app which is useing jedis, and it fixed.

**Comment by comauguste** [comment]
It worked for me on windows. Thanks you

**Comment by vanzez** [comment]
The issue cause by your connection was out at the moment, you need to connect again.
