### ISSUE TITLE
Undefined method setMaxActive of class JedisPoolConfig

### ISSUE THREAD

**Issue by JunLuo** [xetorthio/jedis#849]
HI there,
  I have used Jedis 2.2.0 for about half a year and recently change the version to 2.6.2.  But eclipse tells me the method setMaxActive of JedisPoolConfig cannot be resolved, Can anybody tell me the way to fix it? Is it ok to use SetMaxTotal to instead? Thanks.

**Comment by HeartSaVioR** [comment]
@JunLuo 
Seems like it's removed from Apache Commons Pool 2.0.
You can apply it by setMaxTotal() and setMaxIdle(), cause max total - max idle would be max active. :)
Hope this helps.
