### ISSUE TITLE
NullPointerException initializing JedisPool with URI with no path

### ISSUE THREAD

**Issue by bennesher** [xetorthio/jedis#850]
When constructing a JedisPool using the URI constructor, if you supply a minimalist basic URI without path, such as `localhost:6379`, the result is an NPE in the `JedisURIHelper`:

```java
  public static Integer getDBIndex(URI uri) {
    String[] pathSplit = uri.getPath().split("/", 2);  // <-- Exception here, because uri.getPath() is null
    if (pathSplit.length > 1) {
    // ...
    }
  }
```

**Comment by bennesher** [comment]
To be clear, I know that the simple workaround is to instead pass `localhost:6379/` as the URI.  However, the slash should not be required.

**Comment by HeartSaVioR** [comment]
@bennesher Thanks for finding!
If you don't mind, could you craft a patch and post a pull request?

**Comment by nykolaslima** [comment]
@bennesher actually if you use `redis://localhost:6379` it should work.

I think we are having problem when user does not pass the `redis` part. I'll fix it.

**Comment by nykolaslima** [comment]
@HeartSaVioR should we support URIs without `scheme`?

**Comment by marcosnils** [comment]
@nykolaslima we shouldn't. We need to throw an InvalidUrlException or something if the scheme is not supplied.
