### ISSUE TITLE
Eval tests inconsistent

### ISSUE THREAD

**Issue by marcosnils** [xetorthio/jedis#851]
I came across this tests here https://github.com/xetorthio/jedis/blob/master/src/test/java/redis/clients/jedis/tests/commands/ScriptingCommandsTest.java#L178-L196 and I don't understand what they're actually testing. 

The tests names say that they're supposed to handle null values but I don't see any null handling or possible null return. Am I missing something. 

@HeartSaVioR, do you have any clue about this?

**Comment by HeartSaVioR** [comment]
@marcosnils 
I also don't know about it, so I dug logs and found its origin commit.

It was introduced from 9d538a0 and revised once from 5973663 .

@xetorthio Could you describe 9d538a0?

**Comment by HeartSaVioR** [comment]
@marcosnils @xetorthio Seems like I got it.
In 9d538a0, key1 and key2 doesn't exist so lua script returns two null values.
Maybe @mardambey misunderstood @xetorthio's intention and change it to just return value.

So we can be safe with reverting methods to 9d538a0.

**Comment by HeartSaVioR** [comment]
Fixed via 220cba575afac4d935977d2bda986c1378fa5c72
