### ISSUE TITLE
Why JedisCluster provides select()?

### ISSUE THREAD

**Issue by airpingu** [xetorthio/jedis#853]
Hope to clarify the usage of ```select()``` on JedisCluster. According to http://redis.io/topics/cluster-spec which mentioned:

```Redis Cluster does not support multiple databases like the stand alone version of Redis, there is just database 0, and SELECT is not allowed.```

But why JedisCluster provides ```select()```? Please see https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/JedisCluster.java#L1182.

**Comment by HeartSaVioR** [comment]
It will be removed, please refer to https://github.com/xetorthio/jedis/pull/671 for more details.

**Comment by airpingu** [comment]
Thanks @HeartSaVioR 

One more follow-up question which might be more related to Redis: since Redis/Jedis cluster doesn't attempt to support multiple databases. Does it mean a set of Redis nodes in a cluster can only serve to manage one feature? It sounds a kind of bit waste to me because all the CPU/memory resources only work for one application.

How to make the maximum usage of a cluster on multiple features/applications?

**Comment by airpingu** [comment]
Yeap, I post the question on https://github.com/antirez/redis/issues/2280 as well.

**Comment by HeartSaVioR** [comment]
@airpingu 
Hey, Redis only uses single thread for processing commands by each instance, which means you can't use multi-core powers whether you use multi-DBs in one instance or not.

Other way you can use your machine efficiently is, you can construct crossed masters-slaves which means one node serves one master and multiple slaves (or just one slave) that slaves are replicated to other nodes.

**Comment by HeartSaVioR** [comment]
@airpingu Could I close this issue? Seems like I've answered root issue and follow-up question. :D

**Comment by airpingu** [comment]
Sure! Appreciate your help!
