### ISSUE TITLE
Pooled connections not closing socket on destroy()

### ISSUE THREAD

**Issue by sutanudalui** [xetorthio/jedis#855]
Hello,
I am using JedisPool for pooled connections. We use blocking pop calls on Redis, and have a general method to close the socket connection.

When we were not using JedisPool, we were simply doing disconnect() and interrupting the blocking thread. However, this pattern does not seem to be working when using JedisPool. It seems the underlying socket connections are not being closed while calling destroy(), and our shutdown blocks (till a configured waiting time).

Even if I ignore the interrupt (since now the thread may or may not be the 'actual' blocking one due to pooling), still I expected to get the underlying socket closed, and some exception be thrown back to the blocking operation. Am I missing something here?

	public void close()
	{
		while(!closed.compareAndSet(false, true));
		try {
			if (blockingThread != null && !blockingThread.isInterrupted())
			{
				blockingThread.interrupt();
				log.debug("interrupted blocking");
			}
				
						
		} catch (Exception e) {
			log.debug(e, e);
		}
		finally
		{
			connection.close();
			connection.destroy();
		}
		log.debug("Closed connection- "+closed.get());
	}

**Comment by sutanudalui** [comment]
FYIP - We are using Java 7 try-with-resources while using a connection, and not explicitly closing it. Using Jedis 2.6.1

**Comment by marcosnils** [comment]
@sutanudalui can you share the code when you make a try-with-resources to get a connection from the pool?

Thanks!.

**Comment by sutanudalui** [comment]
@marcosnils 
Basically we are using Redis as a blocking queue. As a result some connections from the pool are always waiting on a Redis blocking pop. Well, ideally we should not use a pooled resource for blocking operation and that is an alternate design approach that can be taken.

However, I would expect whenever the resource connection is destroyed/closed, any blocking operation should be notified somehow, even by throwing an exception if needed, which is handled. As a consequence, our consumer doesn't stop gracefully on application shutdown.


	protected Jedis getConnection() {
		return connection.getResource();
	}

	public T take() throws InterruptedException
	{
		try(Jedis j = getConnection())
		{
			String obj = null;
			try
			{
				blockingThread = Thread.currentThread();
				obj = transactional ? j.brpop(0, queueName).get(
						1) : j.blpop(0, queueName).get(1);

			}
			catch (Exception e)
			{
				blockingThread.interrupt();
				log.debug(e,e);
			}
			finally
			{
				blockingThread = null;
			}
			return stringToObject(obj);
		}
	}

**Comment by allanwax** [comment]
See https://github.com/xetorthio/jedis/issues/847 as well

**Comment by lboue** [comment]
Any news for this issue? I have same issue.

**Comment by allanwax** [comment]
See the code for a new disconnect() in https://github.com/xetorthio/jedis/issues/847 which makes sure to close the socket even if there are other problems.  As far as I know it has not been incorporated into the code yet.

**Comment by jsumners** [comment]
I'm also having this issue under Tomcat, and I'm using just a simple `Jedis` object. I'm using it under Spring, so I tell Spring to invoke the `.close()` method on shutdown. Spring claims it is doing so, but the Tomcat instance just hangs waiting for that close to happen and never quits. Clearly I can't go into production with a system that I have to `kill -9` to shutdown or restart.

Can we get a method for Jedis to "close connections, no, I really mean it"?

**Comment by marcosnils** [comment]
@jsumners I'll test it right away and fix the problem. This thing needs to be handled properly for sure.

Thanks for the feedback!.

**Comment by marcosnils** [comment]
@jsumners are you also getting the error about the commons-pool EvictionTimer when trying to shutdown tomcat? It's weird that you're getting that error if you're not instantiating JedisPool at all because commons-pool the doesn't get involved. I've tried reproducing the problem using a simple tomcat application and I didn't get any errors. 

Can you please provide further information about your problem?

Thanks.

**Comment by marcosnils** [comment]
@jsumners @lboue I've tried to reproduce the error by different ways and I couldn't make it. 

I've setup a sample project here (https://github.com/marcosnils/jedis-tomcat-issue) to show you what I did in case I'm missing something. 

Basically I'm registering a JedisPool in the ServletContext here : https://github.com/marcosnils/jedis-tomcat-issue/blob/master/src/main/java/web/TestListener.java and then using it in the index.jsp file to store 10k redis keys. 

Finally I destroy it when tomcat is shutdown and I don't get any errors from the tomcat at all and everything closes fine. 

I'm using tomcat 7 and Java 1.7.

**Comment by jsumners** [comment]
I'm sorry, Jedis is evidently not my problem. I created a small test myself and it's not hanging on shutdown -- https://github.com/jsumners/tomcat-hang-test

**Comment by marcosnils** [comment]
@jsumners don't worry, stuff happens :smile:. @lboue can you please provide further feedback about your situation?

**Comment by lboue** [comment]
We will try to destroy JedisPool with contextDestroyed on shutdown and see if I fix it. Actually, we only do that with DriverManager.

**Comment by lboue** [comment]
We try to add that to the JedisConnectionFactory:
```Java
public void destroy() {
		if (usePool && pool != null) {
			try {
				pool.destroy();
			} catch (Exception ex) {
				log.warn("Cannot properly close Jedis pool", ex);
			}
			pool = null;
		}
	}
```

So I that first this log when we stop application
<pre>2015-04-10_14:57:30.526 [http-bio-8080-exec-13] DEBUG o.s.b.f.s.DisposableBeanAdapter - Invoking destroy() on bean with name 'connectionFactory'
2015-04-10_14:57:30.526 [http-bio-8080-exec-13] DEBUG o.s.b.f.s.DisposableBeanAdapter - Invoking destroy() on bean with name 'jedisConnectionFactory'
2015-04-10_14:57:30.527 [http-bio-8080-exec-13] DEBUG o.s.b.f.s.DisposableBeanAdapter - Invoking destroy() on bean with name 'entityManagerFactoryTcv'
</pre>

But still 
<pre>GRAVE: The web application [/app-ws] appears to have started a thread named [commons-pool-EvictionTimer] but has failed to stop it. This is very likely to create a memory leak.
</pre>

Did I miss something?

**Comment by marcosnils** [comment]
@lboue can you provide more info about which tomcat version you're using?. Is there a way you can isolate the error as @jsumners did and provide some way to reproduce it?

**Comment by lboue** [comment]
We are using Apache Tomcat Version 7.0.57 with spring-data-redis-1.5.0. This issue may be located at the Spring Data Redis library. I will try to isolate some of the code to reproduce it.
