### ISSUE TITLE
NullPointerException in smembers()

### ISSUE THREAD

**Issue by kennethjor** [xetorthio/jedis#858]
Today I've noticed quite a few of these exceptions being logged on our servers:

```
Caused by: java.lang.NullPointerException
        at java.util.HashSet.<init>(HashSet.java:118)
        at redis.clients.jedis.Jedis.smembers(Jedis.java:1206)
        [...]
```

I have tried to reproduce it locally, but was unable to. However, it seems this could be fixed by adding a null check just before `return new HashSet<String>(members);` in `smembers()`:

```java
  public Set<String> smembers(final String key) {
    checkIsInMulti();
    client.smembers(key);
    final List<String> members = client.getMultiBulkReply();
    return new HashSet<String>(members);
  }
```

This was noticed in version 2.6.5 on Jedis running against Redis 2.8.4.

**Comment by HeartSaVioR** [comment]
Thanks for finding missed spot!
Could you craft a pull request if you don't mind? Thanks in advance!

**Comment by marcosnils** [comment]
@HeartSaVioR @kennethjor I'm wondering why `getMultiBulkReply` would return null and not an empty list. Any clues about that?

**Comment by marcosnils** [comment]
@kennethjor I'm wondering if maybe you can catch the NPE in your application and print the smembers key value. Also it would help if you could paste the whole stack so we can track the source of the problem.

**Comment by HeartSaVioR** [comment]
@marcosnils @kennethjor 
I'm also wondering what situation causes getMultiBulkReply() to return null.
Anyway if there's a probability for members to be null, returning null is proper way instead of throwing NPE.

**Comment by kennethjor** [comment]
@HeartSaVioR @marcosnils I could craft a pull request. What should it return in this case? Null or an empty Set?

That's the entire stack trace. Everything below that is within my application and wouldn't really shed any light on it.

This only happens when the server is under high load, so it might be an issue with Redis itself? I wasn't able to reproduce it unfortunately, so I don't know what data would cause the issue. Though as you say, if there is an obscure chance it might return null, it'd be wise to catch that.

**Comment by marcosnils** [comment]
@kennethjor, do you see any errors in the redis logs? Maybe that can give
us a clue if something is not working properly.

**Comment by kennethjor** [comment]
@marcosnils Sorry no I don't have a log from Redis at hand.

**Comment by kennethjor** [comment]
I'm happy to do a pull request for this, if you can tell me whether in this event an empty set or null should be returned.

**Comment by marcosnils** [comment]
@kennethjor I'd return an empty Array because if null is returned it's probable that we break our user's code. 

@HeartSaVioR what do you think?

**Comment by HeartSaVioR** [comment]
@marcosnils I'm OK with returning empty set.
Btw, I'm still curious what parameters cause null response.

**Comment by kennethjor** [comment]
@HeartSaVioR @marcosnils Unfortunately this was a random error we saw on our system, so I don't have the logs at hand.

I wanted to dig into this a little further to see why `smembers(String)` might return null.

First of all [`BuilderFactory.STRING_LIST.build` has a direct check in there to passthru null values](https://github.com/xetorthio/jedis/blob/ffbca78f348b0ccd6aab8c42c7f39e2bac18775d/src/main/java/redis/clients/jedis/BuilderFactory.java#L68), which would indicate that null is considered a valid return value of that method. If this is true, then all methods using that builder should have null checks before constructing any such collection objects.

Secondly, in order for the builder to return null the `getBinaryMultiBulkReply()` must return null, which it might do from [`Protocol.process(RedisInputStream)`](https://github.com/xetorthio/jedis/blob/ffbca78f348b0ccd6aab8c42c7f39e2bac18775d/src/main/java/redis/clients/jedis/Protocol.java#L130) if some went weird with any of streams it reads from.

**Comment by HeartSaVioR** [comment]
@kennethjor @marcosnils 
I'm sorry, but I found that null reply in array reply should be handled with "null".

http://redis.io/topics/protocol#array-reply

```
The concept of Null Array exists as well, and is an alternative way to specify a Null value (usually the Null Bulk String is used, but for historical reasons we have two formats).
For instance when the BLPOP command times out, it returns a Null Array that has a count of -1 as in the following example:
"*-1\r\n"
A client library API should return a null object and not an empty Array when Redis replies with a Null Array. This is necessary to distinguish between an empty list and a different condition (for instance the timeout condition of the BLPOP command).
```

Unless Redis replies "null reply" to smembers, there should be no chance to return null from two spots as @kennethjor memtioned.
(First spot is for null reply, second spot will throw JedisException before returning null.)
  
Anyway, as Redis documentation said, we may have to handle it with "null", not "empty set".
What do you think about it?

**Comment by kennethjor** [comment]
@HeartSaVioR Personally I think responding with null makes a lot more sense. Empty lists and sets may be convenient, but do not really add anything when `null` is the true nature of the reply. Let me know and I'll update the pull request accordingly.

**Comment by nykolaslima** [comment]
Hello guys, I'm late on this, I'm sorry.

But looking into the PR, looks a lot verbose to handle null in many places and it may cause future problems if we forget about it.

I still didn't understand why `getMultiBulkReply()` would return null. If this occurs when Redis had some problem, it wouldn't be nice if we check null in `getMultiBulkReply()` and throw a proper Jedis Exception for it?

This defensive coding with null checks everywhere doesn't looks good to me.

@kennethjor @marcosnils @HeartSaVioR

**Comment by HeartSaVioR** [comment]
@nykolaslima 
If you read Redis protocol specification deeply, you can find out Redis defines "null bulk string" or "null array", "null value" in array, and force to treat it to null.

http://redis.io/topics/protocol

I addressed null array earlier, and here's another part of Redis protocol spec, null bulk string.

```
When an empty string is just:
"$0\r\n\r\n"
RESP Bulk Strings can also be used in order to signal non-existence of a value using a special format that is used to represent a Null value. In this special format the length is -1, and there is no data, so a Null is represented as:
"$-1\r\n"
This is called a Null Bulk String.
The client library API should not return an empty string, but a nil object, when the server replies with a Null Bulk String. For example a Ruby library should return 'nil' while a C library should return NULL (or set a special flag in the reply object), and so forth.
```

Therefore, returning null from getMultiBulkReply() is just a Redis protocol spec. If it isn't, we have a bug.

**Comment by nykolaslima** [comment]
I understand your point @HeartSaVioR. So the PR looks good to me. I searched and didn't find any missing spot. :+1:
