### ISSUE TITLE
Exception in thread "Thread-1798" redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Software caused connection abort: recv failed

### ISSUE THREAD

**Issue by Pratap6** [xetorthio/jedis#863]
Iam checking Redis Read and Write with Concurrent Users at A time(Multi-threading).it is working fine upto 380 Users and then it throws above Exception.

Any help greatly appreciated.

Thanks.

**Comment by HeartSaVioR** [comment]
@Pratap6 
Hello.
Could you share your snippet which part is using Jedis?
I've not seen that message and haven't reported.

If you use JedisPool (and you should in a multithreaded env.) could you configure GenericObjectPoolConfig to test before borrow?

**Comment by HeartSaVioR** [comment]
@Pratap6 Please describe Jedis version, Redis version, single/multi threaded also.

**Comment by Pratap6** [comment]
@HeartSaVioR My versions are jedis 2.6.2 and redis-2.8.7 and commons-pool2-2.3.jar,

I'm attaching the class files for Reading, Writing and Jedis Connection SingleTon Classes.

Any help to resolve this issue.

Thanks in advance.
![myapprediswritecilent](https://cloud.githubusercontent.com/assets/10598012/5870715/d9ac5cfa-a2f8-11e4-8ddd-79359cb3bef9.JPG)

---------------------------------
Reading From Redis:
---------------------------------
public class MyAppRedisReadClient {
	public static void main(String[] args) {
	    String t1 ="7:spuser6:6:e5cc606d7f00000113159de7b49f89e9:6:Demand by Geo";
	    String t2 =":CAM~~TW";
	    for (int i = 0; i < 400; i++) {
	    	List<String> keysList = new ArrayList<String>();
		    String key =null;	
		    Runnable thread=null;
		    Executor e=null;
		    for (int j = 0,k=1; j<2500; j++) {
		    	key = t1+j+t2;
		    	keysList.add(key);
				if(keysList.size()==500){
			    	thread=new MyAppRedisReader("Thread-"+i+"-"+k,keysList);
				new Thread(thread).start();
				keysList=new ArrayList<>();
				}	}	} 	}  }

public class MyAppRedisReader implements Runnable {
	private List<String> keysToRead;
	public static JedisPool jedisPool;
	public MyAppRedisReader(String name, List<String> keysToRead) {
		this.name = name;
		this.keysToRead = keysToRead;
	}
	@Override
	public void run() {
		List list = new ArrayList<>();
		try (Jedis jedis = JedisConnectionManager.getInstance().getJedis()) {
		long pollStartTime = System.currentTimeMillis();
		if (keysToRead != null) {
				for (Iterator<String> iterator = keysToRead.iterator(); iterator.hasNext();) {
					Set<String> set = new HashSet<>();
					String key = iterator.next();
					set = jedis.zrangeByScore(key, "-inf", "+inf");
					list.add(set.size());
				}			 
			} }	catch (JedisConnectionException e) {
			System.out.println(e + "....... : fail to get connection...");
		}finally {
			// jedisPool.returnResource(jedis);
		}
	}

}

-----------------------------------------------
Jedis Connection SingleTon Class
------------------------------------------------

Jedis Connection SingleTon Class:
-----------------------------------
public class JedisConnectionManager {	
	    private static  JedisConnectionManager instance =null;
	    private static JedisPool pool;
	    private JedisConnectionManager() {
	    	connect();
	    }
	public final static JedisConnectionManager getInstance() {
		if (instance == null) {
			synchronized (JedisConnectionManager.class) {
				if (instance == null) {
					instance = new JedisConnectionManager();
				}
			}
		}
		return instance;
	}
	    private void connect() {
	    	
	        // Create and set a JedisPoolConfig
	        JedisPoolConfig poolConfig = new JedisPoolConfig();
	        poolConfig.setMaxWaitMillis(8000);//10000
	        poolConfig.setTestOnBorrow(true);
	        poolConfig.setTestOnReturn(true);
	        poolConfig.setTestWhileIdle(true);
	        poolConfig.setNumTestsPerEvictionRun(50);
	        poolConfig.setMinEvictableIdleTimeMillis(60000);
	        poolConfig.setTimeBetweenEvictionRunsMillis(50000);
	        poolConfig.setMaxTotal(2000);
	        poolConfig.setMaxIdle(150);
	        poolConfig.setMinIdle(100);
	        pool = new JedisPool(poolConfig, "host", 6379, 0);
	        }
	    public void release() {
	        pool.destroy();
	    }
	    public Jedis getJedis() {
	    	StackTraceElement[] stacktrace = Thread.currentThread().getStackTrace();
	    	StackTraceElement se = stacktrace[2];//maybe this number needs to be corrected
			Jedis jedis = null;
			int cnt = 1;
			do {
				try {
					cnt++;
					if(cnt>=1000) {
						System.out.println("Not getting Jedis even after "+cnt+" Attempts.");
						return null;
					}
					jedis = pool.getResource();
				} catch (Exception e) {
					System.err.println("("+cnt+") Got exception during getting jedis connection. "+e.getMessage()+" Called from "+se.getClassName()+"."+se.getMethodName());
					if(cnt>3) {
						e.printStackTrace();
					}
				}
			} while(jedis==null);
			if(cnt>2) {
				System.out.println("Got Jedis after "+cnt+" Attempts.");
			}
			return jedis;
	    }

	    public void returnJedis(Jedis jedis) {
	        pool.returnResource(jedis);
	    }

}

**Comment by HeartSaVioR** [comment]
@Pratap6 Could you please attach your source code into Gist if you don't mind?

**Comment by Pratap6** [comment]
@HeartSaVioR, As per your request, I have shared my source code into Gist, could you please verify and help me to resolve this issue.
Thanks in advance.

**Comment by HeartSaVioR** [comment]
@Pratap6 Please leave your gist link.

**Comment by Pratap6** [comment]
@HeartSaVioR Please find my source code link below:

https://gist.github.com/Pratap6/a7c2903eeb3f8757ec51

**Comment by marcosnils** [comment]
@Pratap6 I've just run your Writer and Reader code in my computer and I didn't get any errors. 

I've tested it with latest Jedis code (master branch) and with latest Redis (unstable branch) code. 

Can you give it a try with that setup so we can start narrowing down the problem?

**Comment by HeartSaVioR** [comment]
@Pratap6 
I skimmed your gist codes but cannot find any issue.
One different environment would be commons-pool2-2.3.jar. Could you change your project's commons pool with 2.0 and try again?

**Comment by Pratap6** [comment]
@marcosnils Thank you for quick response, If you increase concurrent users in Writer class (300+)users and Reader Class(400+) users,then at that time I'm getting those 2 errors.

Writer Class:
---------------
public class MyAppRedisWriteCilent {
	public static void main(String[] args) {
//Increase ConCurrent Users here --- 300+ users above	
		for (int i = 0; i <300; i++) {
			Runnable thread = null;
			for (int j = 0; j < 2500; j = j + 500) {
				thread = new MyAppRedisWriter("Thread-" + i, j, (j + 500));
				new Thread(thread).start();
			}
		}
	}
}

Reader Class:
------------------
public class MyAppRedisReadClient {
	public static void main(String[] args) {
		String t1 ="7:spuser6:6:e5cc606d7f00000113159de7b49f89e9:6:Demand by Geo";
	    String t2 =":CAM~~SW";
//Increase ConCurrent Users here --- 400+ users above
	    for (int i = 0; i < 380; i++) {
	    	List<String> keysList = new ArrayList<String>();
		    String key =null;	
		    Runnable thread=null;
		    Executor e=null;
		    for (int j = 0,k=1; j<2500; j++) {
		    	key = t1+j+t2;
		    	keysList.add(key);
				if(keysList.size()==500){
					//System.out.println("Size:"+keysList.size());
			    	thread=new MyAppRedisReader("Thread-"+i+"-"+k,keysList);
					new Thread(thread).start();
					keysList=new ArrayList<>();
				}
			}			
		}
	}

}

Thanks in advance.

**Comment by Pratap6** [comment]
@marcosnils As per your suggestion I've tested with new setup having latest Redis-2.8.19 stable version and Jedis-2.6.2. I got those 2 problem's again.

At Writer Class, I have tested with 400+users I got the below error: 
------------------------------------------------------------------------------------------
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Software caused connection abort: recv failed : fail to get connection

At Reader Class, I have tested with 420+ users I got the below error:
------------------------------------------------------------------------------------------
Got exception during getting jedis connection. Could not get a resource from the pool Called from info.redis.test.MyAppRedisReader.run
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:50)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:88)
	at info.redis.test.JedisConnectionManager.getJedis(JedisConnectionManager.java:59)
	at info.redis.test.MyAppRedisReader.run(MyAppRedisReader.java:27)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.util.NoSuchElementException: Timeout waiting for idle object
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:442)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
	at redis.clients.util.Pool.getResource(Pool.java:48)

**Comment by Pratap6** [comment]
@HeartSaVioR 

As per your suggestion, I have changed that pool into commons-pool2-2.0.jar and tested again. I got the same error.

**Comment by marcosnils** [comment]
@Pratap6 how do you exactly run your test?, do you run both Writer and Reader at the same time or one after the other?. I've just increased the values to 400 for the Writer and 420 for the Reader and I didn't get any errors at all.

The way I'm testing is running first the WriterClient and then the Reader. I've also used latest redis stable version and Jedis master branch.

**Comment by marcosnils** [comment]
@Pratap6 can you try increasing the pool MaxTotal to 5000 in JedisConnectionManager, try again and share your results please?

Also which Java version and OS are you performing your tests on?

**Comment by Pratap6** [comment]
@marcosnils 
Thanks for your quick reply, 
I'm testing One after the other. As per your suggestion I have increased pool MaxTotal to 5000 and tested again, Same errors are coming.
Java Version: 1.7.0_65
OS:  Ubuntu 14.04 LTS
![writerclasserror](https://cloud.githubusercontent.com/assets/10598012/5918033/c99d7354-a649-11e4-80d8-9d68caf29f19.PNG)
![readerclass error](https://cloud.githubusercontent.com/assets/10598012/5918034/c99dbf76-a649-11e4-82ac-e2a2e89bfc05.PNG)

**Comment by marcosnils** [comment]
@Pratap6 do you have some custom configuration set in your sysctl.conf file?. Are you using the default redis.conf in your server? 

"recv failed" usually happens when someone (either the OS or Redis) closes the connection to the Java client.

**Comment by Pratap6** [comment]
@marcosnils 
Yes I'm using default redis.conf in my server, I haven't made any custom configuration in sysctl.conf file. Could you please help me what are the required changes needed in sysctl.conf file.
And how to resolve this issue -- recv failed error

Please suggest me on this.

Thanks.

**Comment by marcosnils** [comment]
@Pratap6 I'll give it a look later today and let u know if I can find something.  @HeartSaVioR do you have any ideas what may be happening?, have you tried running the code in your computer?

**Comment by HeartSaVioR** [comment]
@marcosnils No, I'll give it a try.

**Comment by HeartSaVioR** [comment]
@marcosnils I ran Writer and Reader at same time, and receive some error messages.
(Also modified code to always print stack trace)
```
(2) Got exception during getting jedis connection. Could not get a resource from the pool Called from test.MyAppRedisReader.run
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:50)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:88)
	at test.JedisConnectionManager.getJedis(JedisConnectionManager.java:58)
	at test.MyAppRedisReader.run(MyAppRedisReader.java:23)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.NoSuchElementException: Unable to validate object
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:497)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
	at redis.clients.util.Pool.getResource(Pool.java:48)
	... 4 more
```

JedisFactory returns false without any messages if it cannot validate object so I can't follow up.
I'll try to modify JedisFactory to print stack trace if it throws and try again.

@Pratap6 
Could you please check Redis log and paste it if Redis wrote error log?
If you see errors from Redis log like below, please try to increase max open files.
```
883:M 28 Jan 23:42:53.299 # Accepting client connection: accept: Too many open files in system
```

**Comment by HeartSaVioR** [comment]
@marcosnils 
I found that there're some 'connection reset' in validating object.
But I have no idea about causing socket to broken.

@Pratap6 
Btw, your ReadClient requests a lot of objects from pool, worst scenario is 380 * 2500 = 950000.
Jedis should create sockets too fast, and Redis should handle your 950000 requests and relevant 950000 * N PINGs (testOnBorrow and testOnReturn, and testWhileIdle) in a short time.

**Comment by Pratap6** [comment]
@HeartSaVioR 
I haven't find any errors in my Redis log file. please find my redis.log file
![redislog](https://cloud.githubusercontent.com/assets/10598012/5955857/571e0980-a7cd-11e4-96ff-30eef7302ebb.PNG).

**Comment by HeartSaVioR** [comment]
@Pratap6 Could you please disable THP and try again?

**Comment by Pratap6** [comment]
@HeartSaVioR 

Hi,I tried with below command to disable THP in my Environment.
$ echo never > /sys/kernel/mm/transparent_hugepage/enabled 

After that I have tested Redis Write and Read one after another, again same errors are coming.

Thanks,

same errors are

**Comment by marcosnils** [comment]
@HeartSaVioR If you run Write first and then Read, do you get the same errors @Pratap6 is getting?

Best!.

**Comment by HeartSaVioR** [comment]
@marcosnils 
I didn't get 'Software caused connection abort: recv failed'. I got another errors, which can be seen easily.
(broken pipe, connection reset, etc.)

**Comment by HeartSaVioR** [comment]
@Pratap6 
Please refer http://unix.stackexchange.com/a/99172 for disabling THP completely.

**Comment by Pratap6** [comment]
@HeartSaVioR 

Thanks for the quick reply, As per above link I have disabled THP completely in my Environment.
And then Rebooted my machine and started my Redis server.
After that I tested Redis Write with 400 users, I got same error after disabled THP.

(2) Got exception during getting jedis connection. Could not get a resource from the pool Called from info.redis.test.MyAppRedisWriter.run
Got Jedis after 3 Attempts.
Got Jedis after 3 Attempts.
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Software caused connection abort: recv failed : fail to get connection...
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Software caused connection abort: recv failed : fail to get connection...

**Comment by marcosnils** [comment]
@Pratap6 can you change the redis loglevel to "debug" and check if something pops out?

**Comment by HeartSaVioR** [comment]
@Pratap6 
Could you increase /proc/sys/net/core/somaxconn to higher value, 1024 or 32768?
Somaxconn is described by https://computing.llnl.gov/linux/slurm/high_throughput.html
and you can change it, refer http://serverfault.com/a/271386 for help.

**Comment by Pratap6** [comment]
@HeartSaVioR

As you suggested, I made changes in /proc/sys/net/core/somaxconn file ,but Redis Write is working upto 400 users only(when I check with 500 users, It is not working. I got same errors as mentioned above)
And Redis Read(I run with 420+ users) takes lots of time after 120 users(but still program is running).
Is there any Ubuntu environment changes are needed,please suggest me.

Thanks in advance.

**Comment by Pratap6** [comment]
@marcosnils 
As you suggested, I have Run the Redis in Debug mode, I haven't find any issue in Redis Logger file.
I found this one in log file: 
[2571] 30 Jan 12:19:13.103 - Reading from client: Connection reset by peer
[2571] 30 Jan 12:19:13.103 - Reading from client: Connection reset by peer

Is this Issue?

Thanks in advance.

**Comment by HeartSaVioR** [comment]
@Pratap6 
1. Did you reboot to take effect?
2. Connection reset by peer : I don't know about Network deeply, but this SO answer can help you.
http://stackoverflow.com/a/1434506
3. Try poolConfig.setMaxIdle() to 2000, and see it helps. (Invalidated socket will be removed by "test on borrow" and "test while idle")

Btw, I'm wondering what scenario needs initiating a hundred thousand threads (400 * 2500 = 100,000) in a row. Actually I'm really wondering why it starts 2500 threads when user comes in.
Initializing thread, starting thread, stopping thread, context switching between threads, initializing socket, closing socket, all things has overhead.
I'll be honest with this issue, issue may not resolved unless you take another approach.

**Comment by Pratap6** [comment]
@HeartSaVioR 

It seems something related to Heap. I have installed Redis in 32 GB RAM machine and now that issue is not occurring. Please suggest ideal H/W requirement for Redis and also help us to get location of configuration files where VM and Heap memory for Redis can be updated.

**Comment by marcosnils** [comment]
@Pratap6 are you refering to the JVM Heap?. I'm totally confused when you're asking for Redis hardware specs when Jedis is coded in Java. Can you please give some more arguments why you believe it's the `Heap` and what exactly do you mean by `Heap`?

**Comment by Pratap6** [comment]
@HeartSaVioR 
@marcosnils , Sorry for the confusion. It's regarding to JVM Heap only. I exported my project as a executable jar file and tested above scenario. here I was succeeded upto 700 concurrent users there is no pool exception. After that when I increase the users I'm getting Pool Exception...

My current scenario is, If A user send a request to Web service, then we get response as list of keys(Example: List contains 2500 keys), then the response list is splitting into 5 parallel processing (ex: 5 parallel process --> each list having 500 keys), then I'm doing Read & Write operations on Redis with concurrent users (Creating huge threads).NOW I have succeeded upto 700 users with your support and suggestions.

Please suggest me any another approach to resolve my problem.

Best!.

**Comment by marcosnils** [comment]
@Pratap6 and how did you come to the conclusion that the problem was the JVM heap?. Increasing the RAM of the underlying system doesn't modify the JVM heap automatically. Did you manually tune up the Xmx and Xms parameters into your program to increase the amount of users?

Regarding to optimizations for your current problem (if you only have one redis server) I believe that by using sharding and pipelining you should get the response times and throughput expected. How many keys are you supposed to handle in a worst case scenario?. 

Redis is extremely fast, I've seen it handle up to 30k queries per second through the network for a single thread application.

**Comment by marcosnils** [comment]
hi @Pratap6 any updates about this?

**Comment by Pratap6** [comment]
hi @marcosnils ,sorry for the late response.

I have tested upto 800 users with a single redis instance with my jedis client code. 

Thanks for your support @HeartSaVioR and @marcosnils .

Very good support...
