### ISSUE TITLE
Jcache support 

### ISSUE THREAD

**Issue by yairogen** [xetorthio/jedis#867]
Please add support for jcache intercae with jedis binding.

**Comment by HeartSaVioR** [comment]
I skimmed JSR107 spec just now (cause I didn't know Jcache).

"Note that it is a personal opinion", but I think it's better to not support it.
We always focus to make Jedis simpler, and therefore Jedis didn't serialize or deserialize object.
We deligates serde to Spring Data Redis now, so someday Spring Data Redis will support Jcache if it doesn't.

But I want to hear other voices, so let's keep opened this issue. :D

**Comment by igreenfield** [comment]
I think it will be great to have this interface.

**Comment by yairogen** [comment]
@HeartSaVioR we can take a staged approach here. Even wrapping Jedis with the JCache Cache interface is a big advantage for projects that want to code against JCache API and switch cache providers easily. 
Many providers already support JCache such as: hazelcast, infinispan and others.

**Comment by HeartSaVioR** [comment]
@xetorthio @marcosnils What do you think about supporting JCache?

**Comment by yairogen** [comment]
Any updates?

**Comment by nykolaslima** [comment]
Hi guys,

As we've discussed in Slack, if we want to Jedis 3.0 to support plugins, I think that support JCache should be a plugin and should not be in core.

I agree that we need JCache support, but we follow the plugin approach I think it should be a plugin. If we don't follow the plugin approach, I think it should be in core.
We need to define if we will follow the plugin approach or not @HeartSaVioR @marcosnils @xetorthio

**Comment by HeartSaVioR** [comment]
We didn't even decide we really need to support JCache.
And I'm still thinking it's better to delegate "serde" to other libraries that uses Jedis.

And hazelcast should support JCache since JCache spec co-author is the CEO of Hazelcast.

**Comment by yairogen** [comment]
Can you please explain the relation to Hazelcast in this discussion? Maybe I'm missing something?
Having said that why not add as a plugin? I think that would work great (as long as the end result would be - use JCache API and underneath go to Redis).

**Comment by HeartSaVioR** [comment]
I'm just explaining that there's no surprise for hazelcast to support JCache, which doesn't mean JCache is great enough to support ASAP.

I discussed about supporting JCache with @xetorthio just now, and decide it's not Jedis core feature.
We're trying to make Jedis simple and simple, so you can use Jedis as a base layer for your project.
You can maintain your own class or project supporting JCache with Jedis easily.
(Welcome to open source project world! :) )

Please note that Spring Data Redis already support serde with Redis, which use another library as connector to Redis. (including Jedis)
So I said Spring Data Redis is more fit for JCache.

Hope this helps.

**Comment by yairogen** [comment]
Are you suggesting I open the feature request to support JCache within Spring Data Redis? Or do say they already support that?

**Comment by HeartSaVioR** [comment]
@yairogen 
I'm sorry but I don't know that Spring Data Redis supports JCache now.
So I suggest you to open new issue from Spring Issue System.
https://jira.spring.io/browse/DATAREDIS

**Comment by yairogen** [comment]
Done.
https://jira.spring.io/browse/DATAREDIS-373
Would appreciate your votes on this.

**Comment by igreenfield** [comment]
Done

**Comment by nykolaslima** [comment]
Voted! @yairogen thank you for reporting it.

Can we close this issue?

**Comment by yairogen** [comment]
sure. thanks for your support

**Comment by HeartSaVioR** [comment]
OK, for now I'm closing this issue. Thanks everyone.
