### ISSUE TITLE
cluster-node-timeout 50

### ISSUE THREAD

**Issue by eivantsov** [xetorthio/jedis#880]
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 3
>>> 'cluster-node-timeout 50'
Bad directive or wrong number of arguments

This is what I get when running make package. Redis version is 2.8.5. redis-server command does not return anything suspicious. Ubuntu 14.04

**Comment by marcosnils** [comment]
@eivantsov Jedis is fully compatible with Redis version 2.8.5 However, in order for Jedis tests to pass you need to have the __latest__ redis (unstable) version installed. You need to clone the redis repo (https://github.com/antirez/redis) and `make && make install`. 

Please let us know if you have some other issues.

**Comment by eivantsov** [comment]
Thank you. That worked :)
