### ISSUE TITLE
jedis excetion with redis-cluster binding multi ip addresses

### ISSUE THREAD

**Issue by mechine** [xetorthio/jedis#881]
1.firstly, i try to comment the bind setting in the redis.conf
2. then i build the cluster with  ./redis-trib.rb create 127.0.0.1:6379  127.0.0.1:6380 127.0.0.1:6381
3.then i use JedisCluster to visit my cluster with such Exception: 
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
.......
4.same problems with "bind 0.0.0.0" in redis.conf

**Comment by HeartSaVioR** [comment]
@mechine 
Thanks for reporting.
Can you elaborate it by specifying Redis version / Jedis version, and pasting full stack trace?

**Comment by marcosnils** [comment]
@mechine are you still having this issue?

Can you please issue a `cluster info` and `cluster nodes` in your master redis cluster nodes and post the results here?. 
I've just made a test and it works without problem for me.

**Comment by mechine** [comment]
@HeartSaVioR  @marcosnils 
Thanks for answering.
Sorry for being  late.
I think i have found the reason by using "cluster nodes":
when i create the cluster by:
./redis-trib.rb create 160.165.0.5:6379 160.165.0.5:6380 160.165.0.5:6381
i can visit the cluster using jedis,while when create the cluster by:
./redis-trib.rb  create 127.0.0.1:6379 127.0.0.1:6380 127.0.0.1:6381 
then the cluster is unvisitable.
