### ISSUE TITLE
ZREM* WITHSCORES Feature Request

### ISSUE THREAD

**Issue by jamespedwards42** [xetorthio/jedis#884]
ZRANGE* calls for jedis already support the WITHSCORES feature. Are there any plans to also add it for ZREM calls?

**Comment by nykolaslima** [comment]
We want to be fully compatible with latest Redis version, so the answer is:
yes, we need to support it.

Would you like to implement it and open a pull request?

Thank you for reporting!

**Comment by jamespedwards42** [comment]
Sorry for the false issue.  I sat down to work on this and realized I misread the documentation, zrem* calls only support returning the number of members removed..

**Comment by nykolaslima** [comment]
No problem. Thank you!
