### ISSUE TITLE
JedisPool "Could not return the resource to the pool" exception

### ISSUE THREAD

**Issue by ganesh239** [xetorthio/jedis#885]
Getting "Could not return the resource to the pool" Exception while calling JedisPool.returnResource()

Can i know when it will happen ?

JedisPoolConfig poolConfig = new JedisPoolConfig();
        poolConfig.setMaxTotal(400);
        poolConfig.setMaxIdle(400);
        poolConfig.setTestOnBorrow(true);
        poolConfig.setLifo(false);
        
        jedisPool = new JedisPool(poolConfig, "localhost", 6379);

**Comment by nykolaslima** [comment]
@ganesh239 can you show us the error stacktrace?

**Comment by addonis1990** [comment]
Do you destroy the pool when you shutdown the app ?

**Comment by marcosnils** [comment]
@ganesh239 do you still have this problem?

**Comment by ganesh239** [comment]
Problem got resolved, i have a resource leak while using jedispool.
Sorry for no response.

**Comment by qiansj** [comment]
@ganesh239 when the resource leak happen in your code?

**Comment by ganesh239** [comment]
resource leak happened in my code not in the library, 

i was getting a jedis handler from the jedispool, which is leaked.
As i shared the jedispool among multiple threads, the jedis handler i made it as global variable.

When multiple threads are getting resource at same time using global jedis handler variable, the resource is leaking.

**Comment by qiansj** [comment]
@ganesh239 tks.
My exception is "Returned object not currently part of this pool", occurred with exception "Could not return the resource to the pool", have you occurred this problem?

**Comment by benkris1** [comment]
@marcosnils  I have occurred the problem too!
com.zcloud.sun.cache.jedis.RedisException: UnShardingRedisProxy zrevrange(key,start,stop) exception, key is :push.agent.slaver1-push.msg.group.queue, start is : 0, stop is : 0
	at com.zcloud.sun.cache.jedis.UnShardingRedisProxy.zrevrange(UnShardingRedisProxy.java:1512)
	at com.zcloud.sun.cache.jedis.RedisCache.zPop(RedisCache.java:208)
	at com.zcloud.vtx.module.push.channel.message.DispatcherMsgGroup$1.run(DispatcherMsgGroup.java:71)
Caused by: redis.clients.jedis.exceptions.JedisException: Could not return the resource to the pool
	at redis.clients.util.Pool.returnResourceObject(Pool.java:65)
	at redis.clients.jedis.JedisPool.returnResource(JedisPool.java:113)
	at com.zcloud.sun.cache.jedis.UnShardingRedisProxy.zrevrange(UnShardingRedisProxy.java:1507)
	... 2 more
Caused by: java.lang.IllegalStateException: Returned object not currently part of this pool
	at org.apache.commons.pool2.impl.GenericObjectPool.returnObject(GenericObjectPool.java:534)
	at redis.clients.util.Pool.returnResourceObject(Pool.java:63)
	... 4 more


code:
 public Set<String> zrevrange(String key, long start, long stop) throws RedisException {
        Set<String> result = null;
        try {
            if (key == null) return result;
            Jedis jedis = pool.getResource();
            try {
                result = jedis.zrevrange(key, start, stop);
            } catch (Exception e) {
                returnBrokenResource(jedis);
                throw e;
            } finally {
                if (null != jedis) {
                    pool.returnResource(jedis);
                }

            }
        } catch (Exception e) {
            throw new RedisException("UnShardingRedisProxy zrevrange(key,start,stop) exception, key is :" + key + ", start is : " + start + ", stop is : " + stop, e);
        }
        return result;
    }

**Comment by addonis1990** [comment]
@ganesh239  Would you mind if you share with us the code that caused the leak and how did you fix it ? I am having a connection too but haven't been able to solve so far.

**Comment by darouwan** [comment]
@ganesh239  I meet the same problem, do you mind to share your solution?

**Comment by marcosnils** [comment]
@darouwan this is usually because you're leaking jedis instances that you're not returning properly. Check everywhere in your code where you're using the pool to return your Jedis instances.

**Comment by darouwan** [comment]
@marcosnils  But actually I am using JedisCluster.  It seems no resource returning method like 
`JedisFactory.jedisPool.returnResource(jedis);` based on this https://groups.google.com/forum/#!topic/jedis_redis/Fx0in4E2ATI

**Comment by nhe150** [comment]
check your error place and find exactly the line given out error, and look at how you get the jedis Resource. Hopefully you find you new Jedi("host", port), then get rid of it
