### ISSUE TITLE
Problems with jedis connections. Closing connections

### ISSUE THREAD

**Issue by best241** [xetorthio/jedis#894]
Hi! I'm running a quite big server where are about 400-500 clients connected into. 
The problem is that jedis connections are crashing. 
We have exceptions like: java.net.SocketException: Broken pipe, redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Broken pipe
and long can't be parsed to String.
It's really strange. At first we thought that our system(freebsd) is going wrong, so we were trying to resolve this problem there. But after few hours we found out that jedis is going wrong. With redigo there are no problems(we have also got applications written in go with are connected with these in java).

Please help me!

My pool config: 
        JedisPoolConfig config = new JedisPoolConfig();
        config.setTestOnBorrow(true);
        config.setTestWhileIdle(true);
        config.setTestOnCreate(true);
        config.setMaxIdle(10);
        config.setMinIdle(1);
        config.setMaxWaitMillis(240000);
        config.setMaxTotal(24);

**Comment by marcosnils** [comment]
Hi @best241 are you still having issues with this?

**Comment by best241** [comment]
I updated yesterday and so far there weren't any problems with this, but it may still change...

**Comment by marcosnils** [comment]
@best241 what have you updated?. Jedis version or your code?

**Comment by best241** [comment]
@marcosnils Yes, I have updated jedis version to the newest.

**Comment by marcosnils** [comment]
Amazing. I'm closing the issue for the moment. If you're still experiencing problems please comment so we can re-open
