### ISSUE TITLE
I need performance

### ISSUE THREAD

**Issue by nesalc** [xetorthio/jedis#907]
I am using sorted sets and +500,000 results from zrangebyscore is not uncommon.

The current implementation in Protocol with an ArrayList and adding all these results is just to slow.

Any thoughts about doing this with maybe an iterator or allowing me to specify my own / override the default processMultiBulkReply in Protocol.

I was trying override classes/methods and end up with my own processMultiBulkReply where I would do my own parsing of the value (it a an int, so I do not want Strings/Integer or anything) and call some callback method for each value.

Thanks for your time :-)

**Comment by marcosnils** [comment]
@nesalc which are the numbers you're getting?. Can you confirm that the performance issues that you're seeing are because ArrayList construction and not response parsing?

It'd be great if we could see some code samples and numbers to start evaluating improvements.

Thanks!

**Comment by HeartSaVioR** [comment]
First of all, I also think we need to make sure what exactly is slowing down.
Jedis creates ArrayList with response size, so it doesn't have memory reallocation issue.
I don't know how big is your field in sorted set - helps to determine full response / ArrayList size - so letting us know may help to reproduce.

Btw, providing Iterator could make another issue.
Users can read response partially, and stop iterating with leaving some contents in InputStream.
Jedis will throw Exception or return wrong value on next command's response.

We can read full response and store it to Iterator to parse on demand. 
But we should parse to find end of response, so it doesn't help when performance issue is not due to ArrayList.

**Comment by HeartSaVioR** [comment]
Btw, what version of Jedis do you use?

**Comment by marcosnils** [comment]
Some additional information: 

I've made a very simple test in my computer by populating an ArrayList with 1M elements and it only took 10ms to do it. I guess that unless you need extreme performance it sounds like the array population might not be the issue. 

Just in case here's the code I did to run the test:

```java
List<Integer> list = new ArrayList<Integer>(1000000);
		long start = System.currentTimeMillis();
		for (int i = 0; i < 1000000; i++) {
			list.add(i);
		}
		
		System.out.println("Took: " + (System.currentTimeMillis() - start) + " milliseconds");

	}
```

**Comment by nesalc** [comment]
Okey let me explain how I see it.
First I like Jedis because it it simple, it just works.
Second yes I need performance, building search services with should be able thousands of requests per second, every ms counts.

1) Performance speed
What you guys actually do is add to ArrayList, then build a LinkedHashSet from the list.
Some quick code, which I believe is a better "simulation" than the example above:
```
public class PerfTest {

    @Test
    public void testIt() {
        byte[][] input = buildData();
        for (int i = 0; i < 10; i++) {
            doIt(input);
        }
    }

    private void doIt(byte[][] input) {
        List<byte[]> list = new ArrayList<>(input.length);
        long start = System.currentTimeMillis();
        for (int i = 0; i < input.length; i++) {
            list.add(input[i]);
        }
        LinkedHashSet<byte[]> linkedHashSet = new LinkedHashSet<byte[]>(list);
        int size = 0;
        /*
         for (byte[] linkedHashSet1 : linkedHashSet) {
         ++size;
         }
         */
        Iterator<byte[]> itr = linkedHashSet.iterator();
        while (itr.hasNext()) {
            ++size;
            itr.next();
        }
        System.out.println("Timing: " + (System.currentTimeMillis() - start) + " ms");
        System.out.println("Size " + size);
    }

    private byte[][] buildData() {
        byte[][] data = new byte[1000000][];
        for (int i = 0; i < data.length; i++) {
            data[i] = Integer.toString(i).getBytes();
        }
        return data;
    }
}
```
And the output:
Timing: 1334 ms
Size 1000000
Timing: 115 ms
Size 1000000
Timing: 90 ms
Size 1000000
Timing: 151 ms
Size 1000000
Timing: 94 ms
Size 1000000
Timing: 162 ms
Size 1000000
Timing: 90 ms
Size 1000000
Timing: 210 ms
Size 1000000
Timing: 192 ms
Size 1000000
Timing: 90 ms
Size 1000000

If the LinkedHashSet was skipped it only takes about 5 ms, compared to +90 ms with the LinkedHashSet, so this is the big issue if we only take a look at the speed performance.

2) Performance memory usage
With 1000000 results returned from Redis, we are talking 6-8 MB of data int my case.
The you build a List with each of theses 1 mill results. Maybe 12 bytes in Object overhead per result and the the average of 6 bytes, and the 8 bytes for each object reference in the list internal array. So maybe 12 + 6 + 8 bytes = 26 bytes, 26 * 1 mill = 26 MB's just for the data, not including the List structure, afterwards a LinkedHashSet is build with all the results, so we are talking 30-40 MB for a result of this size.
With this kind of memory usage it will never scale with thousand of requests per second.
If I could iterate the results I could skip 30-40 MB of memory allocation per request.

I hope this explains my "problem".

Claus

**Comment by HeartSaVioR** [comment]
Just focusing to performance, maybe issue is not properly defined at all.
As you stated, performance issue seems to be about manipulating Set, not List.
Then there seems to be no problem at processMultiBulkReply.

With knowing that Redis shouldn't give duplicated elements with zrevrangeByScore, we can skip converting List to Set and return List itself. Would be efficient but not intuitive.
I didn't try it earlier, but couldn't we create new class which extends Jedis and add custom method which skips converting phase?

I understand what you're talking about (both performance and memory consumption), but please note that Jedis is widely used library so Jedis should follow usability more than performance. 
On-demand iterator could be error-prone as I stated.

**Comment by marcosnils** [comment]
@nesalc as @HeartSaVioR said LinkedHashSet is created in `Jedis` class. Extending `Jedis` and changing overriding `zrangebyscore` to avoid the creation of the HashSet still doesn't meet your performance expectations?.

**Comment by nesalc** [comment]
@marcosnils yes that is a solution to speed, thanks.
But I need to figure out if I can live with this huge memory usage or I need to find another path.

**Comment by marcosnils** [comment]
@nesalc I really find amusing the amount of processing you're expecting to save with this modifications. We try to keep Jedis as simple as possible but we're open to get any feedback about different ways to improve it. 

We'll definitely discuss performance optimizations per your recommendations and if we come up with a nice solution we'll let you know so we can get continuous feedback.

**Comment by HeartSaVioR** [comment]
@nesalc Oh, I got the another issue, JedisPool doesn't allow subclass of Jedis. 
I'll find a way to do it.

**Comment by marcosnils** [comment]
@nesalc can you check #977 and see if you consider this issue can be closed?

Thanks!.

**Comment by nesalc** [comment]
@marcosnils That would solve some of the problem.
But I ended up doing a custom implementation, where I can iterate the results and avoid allocating huge amount of data.
Much better solution for what I am doing.
