### ISSUE TITLE
Thread safety explanation in Readme

### ISSUE THREAD

**Issue by kennethjor** [xetorthio/jedis#915]
Not an issue as such. I just experienced issues with the Jedis library in my multi-threaded environment. Eventually I found the notice about the based `Jedis` class not being thread-safe on the wiki. Perhaps it would be worth adding this to the main readme file so any newcomer to the library is immediately made aware that they should be doing connection pooling in a multi-threaded environment.

**Comment by marcosnils** [comment]
@kennethjor totally agree. We're a small team maintaining this library and sometimes we forget that documentation for our users is as important as the code. Contributions are welcome though, so if you feel like supporting other users even by submitting a PR which improves the README we'll be more than grateful. 

Thanks!.

**Comment by marcosnils** [comment]
Fixed in 7196dc6db60a3fccba2dc28a1d2f38cae569a31d
