### ISSUE TITLE
JedisCluster connections won't close on Jersey/JAX-RS servlet.

### ISSUE THREAD

**Issue by DerekOverlock** [xetorthio/jedis#919]
This may not be an issue, rather it could just be my naive ignorance. :)

I am writing a web backend using a Jersey servlet in a Tomcat container. We have a redis cluster set up that this Tomcat is connecting to. We created a utility class (called JedisClient) to read a properties file and create the JedisClusters object with all of our nodes. From there, we just proxy the REDIS commands we need (SET, DEL, GET, etc.) to the JedisCluster object from JedisClient.

I am creating the JedisClient object inside of the request that needs to connect to Redis. My understanding of Jersey is that every new request creates a new instance of the resource controller. So, every new web request results in a new JedisClient (thus, a new JedisCluster). When running stress tests (50-100 concurrent users per Tomcat node), doing a lsof -P for this Tomcat PID shows a LOT (~400+) of TCP connections established with the redis cluster. I've added an explicit JedisClient.close() (that then just calls JedisCluster.close()) to close the connection before the request is over.

Is this appropriate? Is there a better way to close the connection? Is there a way for Tomcat/Jersey/Java GC to handle that automatically?

Thanks for the help! Pardon my naivety :)

**Comment by HeartSaVioR** [comment]
I don't know Jersey but I believe there should be a way to initialize shared JedisCluster instance first, and use it. It's thread-safe.
If Jersey has shutdown hook, you can close JedisCluster then.

**Comment by marcosnils** [comment]
Derek,

You definitely don't need to instantiate JedisCluster on each request. You
only need to instantiate it once and then share the same instance along
requests. You can either do this by injecting it into the jersey controller
with the @Service method or either creating a Singleton class which
retrieves the JedisCluster reference.
