### ISSUE TITLE
Multi-threaded env - Invalidated object not currently part of this pool

### ISSUE THREAD

**Issue by DavidBaddeley** [xetorthio/jedis#921]
Hi!

I am having some problems with using the PoolManager in multi-threaded environment, this is a possible duplicate of https://github.com/xetorthio/jedis/issues/556 but as the poster never responded I thought I would create a new issue.

I am using a RedisManager class to manage Jedis connections, the config values for initialising the pool are pretty standard

public class RedisManager implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
    private static final RedisManager instance = new RedisManager();
    private static JedisPool pool;
    private RedisManager() {}
    public final static RedisManager getInstance() {
        return instance;
    }
    public void connect() {
        // Create and set a JedisPoolConfig
        JedisPoolConfig poolConfig = new JedisPoolConfig();
        // Maximum active connections to Redis instance
        poolConfig.setMaxTotal(20);
        // Tests whether connection is dead when connection
        // retrieval method is called
        poolConfig.setTestOnBorrow(true);
        // Tests whether connection is dead when returning a
        // connection to the pool
        poolConfig.setTestOnReturn(true);
        // Number of connections to Redis that just sit there
        // and do nothing
        poolConfig.setMaxIdle(5);
        // Minimum number of idle connections to Redis
        // These can be seen as always open and ready to serve
        poolConfig.setMinIdle(1);
        // Tests whether connections are dead during idle periods
        poolConfig.setTestWhileIdle(true);
        // Maximum number of connections to test in each idle check
        poolConfig.setNumTestsPerEvictionRun(10);
        // Idle connection checking period
        poolConfig.setTimeBetweenEvictionRunsMillis(60000);
        // Create the jedisPool
        String modeStr = System.getProperty("app.mode");
        String redisHost = "localhost";
        if(modeStr.equals("STAGING")){
        	redisHost = "xxxxxx-xxxxx.ng.0001.euw1.cache.amazonaws.com";
        }else if(modeStr.equals("PRODUCTION")){
        	redisHost = "xxxxxx-xxxx-xxxxx.0znfwm.0001.euw1.cache.amazonaws.com";
        }
        pool = new JedisPool(poolConfig, redisHost, 6379);
    }
    public void release() {
        pool.destroy();
    }
    public Jedis getJedis() {
        return pool.getResource();
    }
    public void returnJedis(Jedis jedis) {
        pool.returnResource(jedis);
    }
    public void returnBrokenJedis(Jedis jedis) {
        pool.returnBrokenResource(jedis);
    }
    
}

Now in my application code, I have a class that performs some long running processing and takes about ~40sec to complete (I have removed all the application code for brevity):

    public ProcessingRun processSession(ProcessingRun processingRun){
    	
    	log.debug("Starting the processing...ID {0}",processingRun.getProcessingRunId());
    	Jedis jedis = null;
    	
    	try{
    		
    		jedis = rm.getJedis();
			
                //Do some long running processing actions here and update progress using jedis along the way
				
                //Process is finished so return connection
                //Nb. this is where first exception is thrown!
    		rm.returnJedis(jedis);
    		jedis=null;

		return processingRun;
			
    	}catch(Exception e){
    		
    		//Handle jedis exception
    		if(jedis!=null && (e instanceof JedisConnectionException || e instanceof JedisException)){
    			rm.returnBrokenJedis(jedis);
    			jedis = null;
    		}

    	}
		
    }

I am running this code in production but I am finding that sometimes I get the following exception:

08:25:23,604 ERROR [org.jboss.as.ejb3.invocation] (EJB timer-thread - 10) JBAS014134: EJB Invocation failed on component ProcessSessionBean for method public abstract net.processor.entities.ProcessingRun net.processor.actions.processing.session.ProcessSession.processSession(net.processor.entities.ProcessingRun,boolean): javax.ejb.EJBException: redis.clients.jedis.exceptions.JedisException: Could not return the resource to the pool

 and...

Caused by: redis.clients.jedis.exceptions.JedisException: Could not return the resource to the pool
	at redis.clients.util.Pool.returnBrokenResourceObject(Pool.java:85) [jedis-2.6.2.jar:]
	at redis.clients.jedis.JedisPool.returnBrokenResource(JedisPool.java:95) [jedis-2.6.2.jar:]
	at net.processor.redis.RedisManager.returnBrokenJedis(RedisManager.java:65) [Processor-ejb.jar:]
	at net.processor.actions.processing.session.ProcessSessionBean.processSession(ProcessSessionBean.java:400) [Processor-ejb.jar:]
	at sun.reflect.GeneratedMethodAccessor755.invoke(Unknown Source) [:1.6.0_34]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.6.0_34]
	at java.lang.reflect.Method.invoke(Method.java:622) [rt.jar:1.6.0_34]

and...

Caused by: java.lang.IllegalStateException: Invalidated object not currently part of this pool
	at org.apache.commons.pool2.impl.GenericObjectPool.invalidateObject(GenericObjectPool.java:620) [commons-pool2-2.0.jar:2.0]
	at redis.clients.util.Pool.returnBrokenResourceObject(Pool.java:83) [jedis-2.6.2.jar:]
	... 162 more

The line 400 in processSession method is the 'rm.returnJedis(jedis);' line at the end of the try block

Am I handling connections correctly? Can anyone spot an issue with my code, from what I have read in other issues I am sure it looks ok

**Comment by marcosnils** [comment]
@DavidBaddeley I'm wondering where and how the `connect` method get's called. The only thing that comes into my mind is that eventually the pool reference get's lost and you're trying to return a Jedis instance to a pool that doesn't belong. 

One thing you can try to do is check the pool instance address when you ask for the resource and then print it again when you're calling returnBrokenResource. That way you're sure that the reference is never lost. 

Another fast thing you can do is just call `jedis.close();` which will automatically return the resource to the pool. You need to change your code something like this:

```java
public ProcessingRun processSession(ProcessingRun processingRun){

    log.debug("Starting the processing...ID {0}",processingRun.getProcessingRunId());
    Jedis jedis = null;

    try{

     jedis = rm.getJedis();

    return processingRun;

    } finally {
       jedis.close();
    }
}
```

Give it a try and let me know if it helps!.

**Comment by DavidBaddeley** [comment]
@marcosnils On further inspection of my code I found that connect() was being called elsewhere which was causing the problem...schoolboy error! Thanks for getting back to me on this, oh and for the jedis.close() tip!
