### ISSUE TITLE
eval reslut can not  is byte[]

### ISSUE THREAD

**Issue by moqi2011** [xetorthio/jedis#923]
I put a binary file to redis ,like:
```java
byte[] file=readFile("xxxx.exe");
jedis.set("key".getBytes(),file);
```
Get the file use lua,like:
```java
obj=jedis.eval("return redis.call('get','key')"); 
```
But the result is string ;

Read the source code at [redis.clients.jedis.Jedis]:
```java
  private Object evalResult(Object result) {
    if (result instanceof byte[]) return SafeEncoder.encode((byte[]) result);

    if (result instanceof List<?>) {
      List<?> list = (List<?>) result;
      List<Object> listResult = new ArrayList<Object>(list.size());
      for (Object bin : list) {
        listResult.add(evalResult(bin));
      }

      return listResult;
    }

    return result;
  }
```
I replace: 
```java
if (result instanceof byte[]) return SafeEncoder.encode((byte[]) result);
````
as:
```java
if (result instanceof byte[]) return result;
```
test:
```java
byte[] file=readFile("xxxx.exe");
jedis.set("key".getBytes(),file);
byte[] result=(byte[])jedis.eval("return redis.call('get','key')");
Arrays.equals(file,result);
```
result is true
 
Sorry i english is poor.

Thanks!

**Comment by HeartSaVioR** [comment]
@moqi2011 
Jedis doesn't know what result should be treated to binary. Jedis determines binary/string by method signature. Binary version of methods use binary parameters.
You should call BinaryJedis.eval(byte[] script) to receive result by byte[].
Don't worry, Jedis extends BinaryJedis. :)

In other word, byte[] result = jedis.eval(SafeEncoder.encode("return redis.call('get', 'key')"))); works like charm so you don't need to modify Jedis code.

Just friendly reminder, please check my answer really works and close this issue if it works. :)

**Comment by moqi2011** [comment]
@HeartSaVioR 
thanks!
