### ISSUE TITLE
Jedis bitop is not working

### ISSUE THREAD

**Issue by harikrishna553** [xetorthio/jedis#925]
Hello, 
   I am using jedis "2.6.2", bitop method is not giving me proper result.
import redis.clients.jedis.Jedis;
import redis.clients.jedis.BitOP;

public class JedisStringBitOp {
  public static void main(String args[]) {
    Jedis jedis = new Jedis("localhost");

    String srcKey1 = "foobar";
    String srcKey2 = "abcdef";

    String destAndKey = "default";

    jedis.bitop(BitOP.AND, destAndKey, srcKey1, srcKey2);

    System.out.println("destAndKey is " + destAndKey);
  }
}

Output looks like below.
destAndKey is default

**Comment by HeartSaVioR** [comment]
You missed to call jedis.get(destAndKey) to get the result.
