### ISSUE TITLE
Use commons-pool2 

### ISSUE THREAD

**Issue by lboue** [xetorthio/jedis#929]
Hello,

Jedis still depends on commons-pool2 version 2.0. 2.3 was released a year age (24/Feb/14) with many fixes. Could you upgrade it in your pom file ?

Released	2.3	24/Feb/14	30/Dec/14	Feature and fix release
Released	2.2	12/Dec/13	23/Feb/14	Feature and fix release
Released	2.1		12/Dec/13	Bug fixes and new features

		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-pool2</artifactId>
			<version>2.0</version>
			<type>jar</type>
			<scope>compile</scope>
		</dependency>

Cf https://issues.apache.org/jira/browse/POOL/fixforversion/12326282/?selectedTab=com.atlassian.jira.jira-projects-plugin:version-summary-panel

Regards,
Ludovic

**Comment by lboue** [comment]
Also I don't know where dit it comes from but I have the following errors when I stop Tomcat Server. This seems related to commons-pool.
INFOS: A valid shutdown command was received via the shutdown port. Stopping the Server instance.
mars 26, 2015 9:30:53 AM org.apache.coyote.AbstractProtocol pause
INFOS: Pausing ProtocolHandler ["http-bio-8181"]
mars 26, 2015 9:30:53 AM org.apache.catalina.core.StandardService stopInternal
INFOS: Arrêt du service Catalina
mars 26, 2015 9:30:54 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
GRAVE: The web application [/myapp-ws] appears to have started a thread named [commons-pool-EvictionTimer] but has failed to stop it. This is very likely to create a memory leak.
mars 26, 2015 9:30:54 AM org.springframework.web.context.support.XmlWebApplicationContext doClose
INFOS: Closing Root WebApplicationContext: startup date [Tue Mar 17 11:27:13 CET 2015]; root of context hierarchy
mars 26, 2015 9:30:54 AM org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean destroy
INFOS: Closing JPA EntityManagerFactory for persistence unit 'afone-myapp-persist'
mars 26, 2015 9:30:54 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
GRAVE: The web application [/myapp-jobs] appears to have started a thread named [commons-pool-EvictionTimer] but has failed to stop it. This is very likely to create a memory leak.
mars 26, 2015 9:30:54 AM org.apache.coyote.AbstractProtocol stop
INFOS: Stopping ProtocolHandler ["http-bio-8181"]
mars 26, 2015 9:30:54 AM org.apache.coyote.AbstractProtocol destroy
INFOS: Destroying ProtocolHandler ["http-bio-8181"]

**Comment by marcosnils** [comment]
@lboue for the commons pool update I've already submit PR #930 which upgrades it. As soon as some other contributor checks it out we'll merge. Regarding tomcat shutdown I guess that's a commons-pool problem, you should submit an issue in their project to see what they tell you about it.

**Comment by lboue** [comment]
Thanks. I will submit the issue to commons-pool JIRA.
