### ISSUE TITLE
Fix wiki about JedisPool returnResource/returnResource

### ISSUE THREAD

**Issue by nykolaslima** [xetorthio/jedis#935]
We've deprecated `returnResource` and `returnResource` in favor of `Jedis.close()` but in our latest stable versions(2.6 and 2.7) we still need to use it.

We should upgrade the wiki, explaining that users must keep using `returnResource` and `returnResource` in the stable releases.

**Comment by HeartSaVioR** [comment]
It's already valid that we can use Jedis.close() instead of JedisPool.returnResource() / returnBrokenResource(). Relevant PR is #563 and it's released at 2.5.0.

**Comment by nykolaslima** [comment]
Thank you guys, my bad.
