### ISSUE TITLE
Pool needs to be closed when it is no longer used - Failed to stop thread named [commons-pool-EvictionTimer]

### ISSUE THREAD

**Issue by lboue** [xetorthio/jedis#936]
Hello,

I tried with v2.7.0 release but I still have the same issue when I stop my tomcat application that uses the Jedis library. This is linked to the thread commons-pool-EvictionTimer. I think a thread is not destoyed.  So I open a case on commons-pool JIRA (https://issues.apache.org/jira/browse/POOL-291). That's what they respond:
```
The Pool needs to be closed when it is no longer used. You can use a ServletContextListener to do this. If you created the Pool, you need to close it. If a 3rd party library created the Pool then it needs to close it and it should provide you with an appropriate method to call to do so.
```
This seems to be related to https://github.com/xetorthio/jedis/issues/855. Can we add a ServletContextListener to cleanly destroy this poll on shutdown?

Here is the error I got:
```
INFOS: A valid shutdown command was received via the shutdown port. Stopping the Server instance.
mars 26, 2015 9:30:53 AM org.apache.coyote.AbstractProtocol pause
INFOS: Pausing ProtocolHandler ["http-bio-8181"]
mars 26, 2015 9:30:53 AM org.apache.catalina.core.StandardService stopInternal
INFOS: Arrêt du service Catalina
mars 26, 2015 9:30:54 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
GRAVE: The web application [/myapp-ws] appears to have started a thread named [commons-pool-EvictionTimer] but has failed to stop it. This is very likely to create a memory leak.
mars 26, 2015 9:30:54 AM org.springframework.web.context.support.XmlWebApplicationContext doClose
INFOS: Closing Root WebApplicationContext: startup date [Tue Mar 17 11:27:13 CET 2015]; root of context hierarchy
mars 26, 2015 9:30:54 AM org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean destroy
INFOS: Closing JPA EntityManagerFactory for persistence unit 'afone-myapp-persist'
mars 26, 2015 9:30:54 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
GRAVE: The web application [/myapp-jobs] appears to have started a thread named [commons-pool-EvictionTimer] but has failed to stop it. This is very likely to create a memory leak.
mars 26, 2015 9:30:54 AM org.apache.coyote.AbstractProtocol stop
INFOS: Stopping ProtocolHandler ["http-bio-8181"]
mars 26, 2015 9:30:54 AM org.apache.coyote.AbstractProtocol destroy
INFOS: Destroying ProtocolHandler ["http-bio-8181"]
```

Regards,

**Comment by HeartSaVioR** [comment]
You can close Pool by calling Jedis*Pool.close().
Jedis cannot determine when pool is fully idle, and though it can determine, it shouldn't destroy pool automatically. Pool should be always ready to serve.

**Comment by marcosnils** [comment]
@lboue as described by @xetorthio and the guys from commons-pool you need to create a (ServletContextListener)[http://docs.oracle.com/javaee/5/api/javax/servlet/ServletContextListener.html] and implement the `contextDestroyed` method. In that method you should get the reference to your `JedisPool` and call the `close` method.

**Comment by Maznna** [comment]
I facing same problem. I try to fix it some way.
`
    // in spring config 
    @Bean(name = "jedisConnectionFactory", destroyMethod = "destory")
    public JedisConnectionFactory jedisConnectionFactory() throws IOException {
...
`
and 
`
    // in ServletContext.contextDestoryed()
    if (jedisConnectionFactory != null) {
    try {
        log.info("Try to destroy jedis");
            jedisConnectionFactory.destroy();
        } catch (Exception e) {
            log.warn("Failed to destory jedisConnectionFactory. e:{}", e);
        }
    }
    ...
`
but I cannot fix it. 
Is there any other way?
[http://stackoverflow.com/questions/42199768/when-shut-down-tomcat-i-met-commons-pool-evictiontimer-but-has-failed-to-stop](url)
