### ISSUE TITLE
JedisPoolConfig default Configuration for minEvictableIdleTimeMillis

### ISSUE THREAD

**Issue by srini156** [xetorthio/jedis#937]
JedisPoolConfig sets the default value for `minEvictableIdleTimeMillis` as 60 seconds.
```java
 public JedisPoolConfig() {
    // defaults to make your life with connection pool easier :)
  ...
    setMinEvictableIdleTimeMillis(60000);
  }
```
While, `BaseObjectPoolConfig` (org.apache.commons.pool2.impl.BaseObjectPoolConfig) sets this value as 30 minutes.
```java
public static final long DEFAULT_MIN_EVICTABLE_IDLE_TIME_MILLIS =
            1000L * 60L * 30L;
```

The issue I faced is that for low traffic applications (where I make call to Redis every 5 minutes, the idle connection was being returned back to the pool after 60 seconds, and hence, when the new call comes, the pool doesn't have a Jedis connection and has to create a new connection every single time, thereby, rendering the `JedisPool` useless.

I reverted back the `minEvictableIdleTimeMillis` to about 20 minutes (instead of 30 minutes) and life has been easier.

*Suggestion*: Either update the default configurable value in `JedisPoolConfig` or make a note of all configurable parameters in github to allow users to tune their JedisPoolConfig correctly.

**Comment by marcosnils** [comment]
Wiki updated here: https://github.com/xetorthio/jedis/wiki/FAQ#jedispool-blocks-after-getting-8-connections

Thx for the feedback and apologize for the delay!.
