### ISSUE TITLE
Jedis.ttl + cannot be cast to java.lang.Long

### ISSUE THREAD

**Issue by nykolaslima** [xetorthio/jedis#942]
I'm accessing my Redis server through a slow network and I got this error when calling `jedis.ttl(key)`;

```
java.lang.ClassCastException: [B cannot be cast to java.lang.Long
    at redis.clients.jedis.Connection.getIntegerReply(Connection.java:207)
    at redis.clients.jedis.Jedis.ttl(Jedis.java:287)
```

Maybe Redis answered a bad response and we couldn't deal with it.

**Comment by HeartSaVioR** [comment]
Indeed. It was not broken response since we built a response with byte[], but maybe not Integer reply.

**Comment by nykolaslima** [comment]
But it still looks as an issue, right?

**Comment by HeartSaVioR** [comment]
Yes, it is. I'm curious how we can solve this issue. 
Does throwing JedisException (maybe JedisConnectionException cause it's already mixed up?) instead of ClassCastException make sense?

**Comment by nykolaslima** [comment]
I still didn't understand what causes this behaviour. The problem is that we could read some piece of response but not the entire response? This shouldn't throw some IO exception?

**Comment by HeartSaVioR** [comment]
Since it doesn't have issue parsing result by REDIS protocol, it may receive other response which is not ERR. Seems like connection or Redis is mixed up.

**Comment by HeartSaVioR** [comment]
Maybe sharing your code is better for finding if you don't mind. :)

**Comment by nykolaslima** [comment]
Actually there is nothing different in my code. I'm just calling the `Jedis.ttl` method and it had thrown this exception.

This only happened once, but I think it could be a caused by a slow network connection.
