### ISSUE TITLE
Redis Cluster: Exception in thread "main" redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool

### ISSUE THREAD

**Issue by Pratap6** [xetorthio/jedis#944]
Hi,

I have created redis cluster with default scripts from latest stable redis 3.0.0 release and cluster is created successfully.
$redis-3.0.0/utils/create-cluster# ./create-cluster start
Starting 30001(M)
Starting 30002(M)
Starting 30003(M)
Starting 30004(S)
Starting 30005(S)
Starting 30006(S)
$redis-3.0.0/utils/create-cluster# ./create-cluster create

And I'm implemented a small java main method class to test the redis cluster using Jedis 7.0 API,
Snippet:

public class RedisCTest {

    public static void main(String[] args) {

        Set<HostAndPort> jedisClusterNodes = new HashSet<HostAndPort>();
        //Jedis Cluster will attempt to discover cluster nodes automatically
        jedisClusterNodes.add(new HostAndPort("host", 30001));
        jedisClusterNodes.add(new HostAndPort("host", 30002));
        jedisClusterNodes.add(new HostAndPort("host", 30003));
        JedisCluster jc = new JedisCluster(jedisClusterNodes);
        System.out.println("Cluster Size...." + jc.getClusterNodes().size());
        jc.set("foo1", "bar1");
        jc.set("foo2", "bar2");
        jc.set("foo3", "bar3");
        jc.set("foo4", "bar4");

    }
}
First time it is working fine and keys are stored into redis , when I run this program multiple time's, I'm getting below exception:

Console Output:
---------------------
Cluster Size....9
Exception in thread "main" redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:50)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:86)
	at redis.clients.jedis.JedisClusterConnectionHandler.renewSlotCache(JedisClusterConnectionHandler.java:72)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:75)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:67)
	at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:29)
	at redis.clients.jedis.JedisCluster.set(JedisCluster.java:70)
	at redisclustertest.RedisCTest.main(RedisCTest.java:35)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused: connect
	at redis.clients.jedis.Connection.connect(Connection.java:154)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:83)
	at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1643)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:85)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:819)	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:819)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:429)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
	at redis.clients.util.Pool.getResource(Pool.java:48)
	... 7 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at redis.clients.jedis.Connection.connect(Connection.java:148)
	... 14 more
Java Result: 1

Thanks!

**Comment by marcosnils** [comment]
@Pratap6 for what I see in the logs seems like your cluster becomes unavailable for some time and Jedis tries to reconnect without succeeding. Can you try running a `cluster info` command after the failure to see the status of the cluster?

Thanks.

**Comment by Pratap6** [comment]
thanks @marcosnils for quick reply.

This is the status of cluster my cluster,

 $redis-cli -c -p 30001
 $127.0.0.1:30001> cluster info
cluster_state:ok
cluster_slots_assigned:16384
cluster_slots_ok:16384
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:6
cluster_size:3
cluster_current_epoch:6
cluster_my_epoch:1
cluster_stats_messages_sent:65942
cluster_stats_messages_received:65939

**Comment by marcosnils** [comment]
@Pratap6 can you try removing the slaves and trying again?. I've just made a test without the slave nodes and I ran your code 1000 times and I didn't get any exception.

**Comment by marcosnils** [comment]
tip of the day: You don't need to specify all the master hosts when you create JedisCluster. As long as your cluster is configured correctly by specifying only one master host JedisCluster would do the discovery automatically

**Comment by Pratap6** [comment]
@marcosnils , I have removed my slave nodes with below commands and tested again same problem

root@ub08:/usr/share/Redis-Cluster/redis-3.0.0/utils/create-cluster# ps -aux|grep redis
root      1049  0.3  0.0  36824  7628 ?        Ssl  15:53   0:22 ../../src/redis-server *:30001 [cluster]                                                               
root      1053  0.3  0.0  36824  7624 ?        Ssl  15:53   0:22 ../../src/redis-server *:30002 [cluster]                                                               
root      1060  0.3  0.0  36824  7628 ?        Ssl  15:53   0:23 ../../src/redis-server *:30003 [cluster]                                                               
root      1064  0.3  0.0  36824  7640 ?        Ssl  15:53   0:22 ../../src/redis-server *:30004 [cluster]                                                               
root      1069  0.3  0.0  36824  7636 ?        Ssl  15:53   0:23 ../../src/redis-server *:30005 [cluster]                                                               
root      1073  0.3  0.0  36824  7636 ?        Ssl  15:53   0:22 ../../src/redis-server *:30006 [cluster]                                                               
root@ub08:/usr/share/Redis-Cluster/redis-3.0.0/utils/create-cluster# kill -9 1064 1069 1073
root@ub08:/usr/share/Redis-Cluster/redis-3.0.0/utils/create-cluster# ps -aux|grep redis
root      1049  0.3  0.0  36824  7640 ?        Ssl  15:53   0:22 ../../src/redis-server *:30001 [cluster]                                                               
root      1053  0.3  0.0  36824  7636 ?        Ssl  15:53   0:22 ../../src/redis-server *:30002 [cluster]                                                               
root      1060  0.3  0.0  36824  7640 ?        Ssl  15:53   0:23 ../../src/redis-server *:30003 [cluster]

**Comment by marcosnils** [comment]
@Pratap6 can you paste the redis.conf file you're using for your master nodes?

thx!.

**Comment by HeartSaVioR** [comment]
@Pratap6 
AFAIK, Redis Cluster's failover and replication works as same as traditional Redis master-slave. 
It's one-by-one so you shouldn't expect failover / replication behavior like Hadoop, HBase, and so on.
(Please correct me if I'm wrong!)

And although you're passing only one master to JedisCluster, JedisCluster will find out all nodes on Cluster at initializing.

**Comment by HeartSaVioR** [comment]
Before using Redis Cluster you should read http://redis.io/topics/cluster-spec carefully to learn power and limitation.
Since some parts of spec are changing, I should read it, too. :)

**Comment by HeartSaVioR** [comment]
Regarding to spec, Redis Cluster can failover to other master's slave if current master is down and no slave follows it. Maybe huge things are changed.

**Comment by Pratap6** [comment]
@marcosnils ,I just run the default create-cluster script in latest stable redis 3.0.0 release and passed various commands to create-cluster shell script: 
1) To Run 6 redis instances: $redis-3.0.0/utils/create-cluster# ./create-cluster start
2) To create redis cluster with 6 nodes: $redis-3.0.0/utils/create-cluster# ./create-cluster create
3)To Stop redis cluster: $redis-3.0.0/utils/create-cluster# ./create-cluster stop

Here manually I haven't run and change any redis.conf file. All are happening inside create-cluste shell script. 

small snippet inside default cluster script: $redis-3.0.0/utils/create-cluster# vi create-cluster

#!/bin/bash
# Settings
PORT=30000
TIMEOUT=2000
NODES=6
REPLICAS=1

# You may want to put the above config parameters into config.sh in order to
# override the defaults without modifying this script.

if [ -a config.sh ]
then
    source "config.sh"
fi

# Computed vars
ENDPORT=$((PORT+NODES))

if [ "$1" == "start" ]
then
    while [ $((PORT < ENDPORT)) != "0" ]; do
        PORT=$((PORT+1))
        echo "Starting $PORT"
        ../../src/redis-server --port $PORT --cluster-enabled yes --cluster-config-file nodes-${PORT}.conf --cluster-node-timeout $TIMEOUT --appendonly yes --appendfilename appendonly-${PORT}.aof --dbfilename dump-${PORT}.rdb --logfile ${PORT}.log --daemonize yes
    done
    exit 0
fi

if [ "$1" == "create" ]
then
    HOSTS=""
    while [ $((PORT < ENDPORT)) != "0" ]; do
        PORT=$((PORT+1))
        HOSTS="$HOSTS 127.0.0.1:$PORT"
    done
    ../../src/redis-trib.rb create --replicas $REPLICAS $HOSTS
    exit 0
fi

if [ "$1" == "stop" ]
then
    while [ $((PORT < ENDPORT)) != "0" ]; do
        PORT=$((PORT+1))
        echo "Stopping $PORT"
        ../../src/redis-cli -p $PORT shutdown nosave
    done
    exit 0
fi

Thanks!

**Comment by Pratap6** [comment]
@marcosnils , I have created redis-cluster with manual setup also and still same issue.(redis cluster ports are 8000,8001,8002,8003,8004,8005 )

I have not modified any thing inside redis.conf file,below are the changes made

redis8000.conf
--------------------
pidfile /var/run/redis8000.pid
logfile "/var/log/redis/redis8000.log"
dir /var/lib/redis8000
port 8005
cluster-enabled yes
cluster-config-file nodes8005.conf
cluster-node-timeout 5000
appendonly yes

redis8001.conf
-------------------
pidfile /var/run/redis8001.pid
logfile "/var/log/redis/redis8001.log"
dir /var/lib/redis8001
port 8001
cluster-enabled yes
cluster-config-file nodes8001.conf
cluster-node-timeout 5000
appendonly yes

redis8002.conf
--------------------
pidfile /var/run/redis8002.pid
logfile "/var/log/redis/redis8002.log"
dir /var/lib/redis8002
port 8002
cluster-enabled yes
cluster-config-file nodes8002.conf
cluster-node-timeout 5000
appendonly yes

Thanks!

**Comment by marcosnils** [comment]
@Pratap6 I've created the cluster using the create-cluster scripts as you did but I still can't reproduce the error. I've recorded my steps so you can can check if there's something that I'm missing or something that you can change to make your code work.

Check out where:  https://asciinema.org/a/18613


Here's the test class I used to run the example:

```java


import java.util.HashSet;
import java.util.Set;

import redis.clients.jedis.HostAndPort;
import redis.clients.jedis.JedisCluster;

public class MainTest {
	
	public static void main(String[] args) {
		for (int i = 0; i < 1000; i++) {
			fruta();
		}
	    

	}

	private static void fruta() {
		Set<HostAndPort> jedisClusterNodes = new HashSet<HostAndPort>();
	    //Jedis Cluster will attempt to discover cluster nodes automatically
	    jedisClusterNodes.add(new HostAndPort("127.0.0.1", 30001));
	    JedisCluster jc = new JedisCluster(jedisClusterNodes);
	    System.out.println("Cluster Size...." + jc.getClusterNodes().size());
	    jc.set("foo1", "bar1");
	    jc.set("foo2", "bar2");
	    jc.set("foo3", "bar3");
	    jc.set("foo4", "bar4");
	}

}
```

**Comment by Pratap6** [comment]
@marcosnils : Thanks for your help.

We were trying remote connectivity from client to Redis Cluster. We executed client code from local machine as per your recording and could able get connections without any errors.

It seems something issue with remote connectivity. Could you please suggest me if any changes are needed in redis conf file and other files for remote connectivity.

Thanks!

**Comment by Pratap6** [comment]
@marcosnils : Thanks for your support, we greatly appreciate your help!

we have successfully done remote connectivity from client to Redis Cluster. by replacing Bind IP(127.0.0.1) in redis.conf file with machine IP.

@HeartSaVioR : Thanks for your support, we greatly appreciate your help!

**Comment by marcosnils** [comment]
@Pratap6 your welcome. Can you please close the issue if you consider it fixed?

Thanks!.

**Comment by Pratap6** [comment]
@marcosnils : Ok sure

**Comment by jeromeheng** [comment]
@Pratap6    
THIS IS YOUR ANSWER ： we have successfully done remote connectivity from client to Redis Cluster. by replacing Bind IP(127.0.0.1) in redis.conf file with machine IP.

how to replace to bind ip ?
I should add to this machine ip or add other ip in this cluster

**Comment by sazzad16** [comment]
The issuer considered this fixed.

[Pratap6](https://github.com/xetorthio/jedis/issues/944#issuecomment-92317710)
> we have successfully done remote connectivity from client to Redis Cluster. by replacing Bind IP(127.0.0.1) in redis.conf file with machine IP.

[marcosnils](https://github.com/xetorthio/jedis/issues/944#issuecomment-92319278)
> Can you please close the issue if you consider it fixed?

[Pratap6](https://github.com/xetorthio/jedis/issues/944#issuecomment-92320942)
> Ok sure

Removing tag.
