### ISSUE TITLE
will JedisClusterInfoCache.java cache READONLY slaves slots  ?

### ISSUE THREAD

**Issue by carlvine500** [xetorthio/jedis#953]

**Comment by zhiying8710** [comment]
@carlvine500 no, it will not.
in JedisClusterInfoCache.java, line 43 and 44:

<code>
ClusterNodeInformation clusterNodeInfo = nodeInfoParser.parse(nodeInfo, new HostAndPort(jedis.getClient().getHost(), jedis.getClient().getPort()));</code>

in <code>nodeInfoParser.parse</code> will parse command <code>cluster nodes</code> result, for example:

<code>
e499ce8577471779d43eb699197c693d9a20de65 192.168.2.78:6381 master - 0 1429684688063 2 connected 5461-10922
517388f1d7f1edcaad07598035a4fad6a369a610 192.168.2.78:6382 slave e499ce8577471779d43eb699197c693d9a20de65 0 1429684687042 5 connected
a73fb4f53cc132efec6be0f7681c7ad39d5dfbdf 192.168.2.78:6379 myself,master - 0 0 1 connected 0-5460
da6b53b8386ebf7cdbdd426a9376f7370faed507 192.168.2.78:6380 slave a73fb4f53cc132efec6be0f7681c7ad39d5dfbdf 0 1429684688575 4 connected
b3903cd4a1fd0af78ac7e12bc6ac615b440494c0 192.168.2.78:6383 master - 0 1429684688063 3 connected 10923-16383
bcab0414b31948fccf3c7bc813aadd0830242c3f 192.168.2.78:6384 slave b3903cd4a1fd0af78ac7e12bc6ac615b440494c0 0 1429684686533 6 connected
</code>

u can see, in <code>e499ce8577471779d43eb699197c693d9a20de65 192.168.2.78:6381 master - 0 1429684688063 2 connected 5461-10922</code>, 5461-10922 are the slots on this instance, and this instance is a master, and in <code>517388f1d7f1edcaad07598035a4fad6a369a610 192.168.2.78:6382 slave</code>, this instance is a slave, and no slots info.

so JedisClusterInfoCache  will not cahce slaves slots.

**Comment by carlvine500** [comment]
will jedis support READONLY slaves in the future ?

**Comment by zhiying8710** [comment]
@carlvine500 in redis cluster, u can't read data from slave, if u do this thing, <code>MOVED</code> error occurred.

**Comment by HeartSaVioR** [comment]
With READONLY you can read data from slave, but AFAIK Redis Cluster doesn't treat slave down so I don't want to handle slave.
Please correct me if I'm wrong!

**Comment by carlvine500** [comment]
thands @HeartSaVioR . May antirez will support it . We will monitor slave , and skip reading from it after down.
