### ISSUE TITLE
JedisCluster.zscore throws a NPE when the member isn't present in the sorted set

### ISSUE THREAD

**Issue by asterp** [xetorthio/jedis#958]
Hi, 
While testing the zscore command with jedis cluster I noticed that if a member whose zscore I am looking up in a sorted key doesn't exist it throws an exception. On the redis cli, it just returns (nil) in this case.

**Comment by marcosnils** [comment]
@asterp can you please provide a test case to reproduce the problem?

I've just tested the following code against master and 2.7 and it returns null as expected: 

```java
  @Test
  public void testzscore() {
	  Set<HostAndPort> jedisClusterNode = new HashSet<HostAndPort>();
	  jedisClusterNode.add(new HostAndPort("127.0.0.1", 7379));
	  JedisCluster jc = new JedisCluster(jedisClusterNode);
	  jc.zadd("test",1, "test");
	  Double score = jc.zscore("test", "notexist");
	  System.out.println(score);
  }
```

**Comment by asterp** [comment]
To reproduce it using your sample code, don't add the score using first jc.zadd before doing the jc.zscore 
et<HostAndPort> jedisClusterNode = new HashSet<HostAndPort>();
      jedisClusterNode.add(new HostAndPort("127.0.0.1", 7379));
      JedisCluster jc = new JedisCluster(jedisClusterNode);
      Double score = jc.zscore("test", "notexist");
      System.out.println(score);

**Comment by HeartSaVioR** [comment]
@asterp Could you describe your Jedis version and Redis version?

**Comment by marcosnils** [comment]
@asterp I've changed my test case per your recommendations and it still works as expected. As @HeartSaVioR said, which version are you running it with?

**Comment by marcosnils** [comment]
@asterp any updates about this issue?

**Comment by asterp** [comment]
I was able to reproduce it:

The code I have is simply runs the following command (in its most simplified version) 
Before execution I did the following:

127.0.0.1:6379> zcard to_be_expired
(integer) 0

jedisCluster.zscore("to_be_expired", "1234");

This throws a NPE .. 

Redis version I'm running is 3.0.0 
Jedis version Jedis-2.6.2

**Comment by asterp** [comment]
Both to_be_expired and "1234" don't exist

**Comment by HeartSaVioR** [comment]
I don't reproduce this issue from current master and Jedis 2.6.2.

Could you verify my test met your situation?
```
  @Test
  public void testZScoreToNotExistKeyWithJedisCluster() throws IOException {
    Set<HostAndPort> jedisClusterNode = new HashSet<HostAndPort>();
    jedisClusterNode.add(new HostAndPort("127.0.0.1", 7379));
    final JedisCluster jc = new JedisCluster(jedisClusterNode);
    try {
      jc.del("to_be_expired");
      assertEquals((Long) 0L, jc.zcard("to_be_expired"));
      assertEquals(null, jc.zscore("to_be_expired", "1234"));
    } finally {
      jc.close();
    }
  }
```

Btw, I didn't test it with Redis 3.0.0 official release. Jedis master branch is relying on current unstable branch of Redis.

**Comment by HeartSaVioR** [comment]
I also can't reproduce your issue from Redis 3.0.0 official.
Maybe you need to provide additional informations, stack trace, more detailed code, cluster configurations, etc.

**Comment by asterp** [comment]
Sure, I am using a single node in cluster setup. I've put all the hashslots on the same node.

final Set<HostAndPort> jedisClusterNodes = new HashSet<HostAndPort>();
jedisClusterNodes.add("127.0.0.1", 6379);  
GenericObjectPoolConfig poolConfig = new GenericObjectPoolConfig();
        // Number of total connections in our pool
        poolConfig.setMaxTotal(10);
        // Number of connections to Redis that just sit there and do nothing
        poolConfig.setMaxIdle(5);

        //Jedis Cluster will attempt to discover cluster nodes automatically
        JedisCluster jc = new JedisCluster(jedisClusterNodes, poolConfig);

jc.zscore("to_be_expired", "1234");

**Comment by asterp** [comment]
Actually it works fine. I'm sorry I realized it was my mistake. But you guys are terrific trying to help me debug. Thanks :)

**Comment by sazzad16** [comment]
It is not an issue.

[asterp](https://github.com/xetorthio/jedis/issues/958#issuecomment-96457868)
> Actually it works fine. I'm sorry I realized it was my mistake. But you guys are terrific trying to help me debug. Thanks :)

Removing tag.
