### ISSUE TITLE
Build is failing in travis

### ISSUE THREAD

**Issue by marcosnils** [xetorthio/jedis#962]
This is because seems like travis upgraded their maven version to 3.3.x which doesn't work with java 1.6. I've already sent them an email to see if it's possible to specify an alternative mvn version. I'll update this issue whenever I get back their answer.

**Comment by marcosnils** [comment]
Travis also acks it. Let's wait for a resolution
https://github.com/travis-ci/travis-ci/issues/3778

**Comment by HeartSaVioR** [comment]
Great! Let's wait. :)

**Comment by HeartSaVioR** [comment]
Resolved already.
