### ISSUE TITLE
IOUtils.closeQuietly is too specific in catching exceptions

### ISSUE THREAD

**Issue by allanwax** [xetorthio/jedis#964]
Only catching `IOException` doesn't handle the strange cases.  It should probably be `Exception`

**Comment by sazzad16** [comment]
@allanwax IOUtils.closeQuietly takes only Socket as parameter. Implementation of Socket (if it matters, Closeable too) states that it might throw IOException. So, I don't see any wrong in catching only IOException. Also I haven't seen any issue which was traced back to this point.

@HeartSaVioR @marcosnils WDYT?

**Comment by marcosnils** [comment]
@sazzad16 I agree with you. @allanwax any other thoughts about this?. Can we close?

**Comment by allanwax** [comment]
@marcosnils I like to program defensively.  I have always encountered strange exceptions that rarely occur.  I do not see the harm in in using a broader catch to cover the stuff that might happen deep down in the bowels of the code.  This is my opinion and my style of course.

**Comment by sazzad16** [comment]
@allanwax Closing for now!
