### ISSUE TITLE
Is there any chance for jedis to support compress on the fly, like some memcache client ?

### ISSUE THREAD

**Issue by tangfl** [xetorthio/jedis#969]
I remember once I saw a memcache client which support compress value on the fly when value size exceed a MAX_VALUE_SIZE, but unfortunately I can not find it on github now.

What I wonder is that, is there anyone else want the feature in jedis too ? if I got a pull request, is there any chance to be merged in master?

For the monment, I will choose [QuickLZ](http://www.quicklz.com/QuickLZ.java) for it only relays one java  file

**Comment by marcosnils** [comment]
Thanks for arising the issue. Please let's continue the discussion in the mailing list: 
https://groups.google.com/forum/#!topic/jedis_redis/2xJMUNcrPNo
