### ISSUE TITLE
How to select db when init the pool~

### ISSUE THREAD

**Issue by yheart** [xetorthio/jedis#97]
Hi,when I wanted to use Jedis like this: 
JedisPool pool = new JedisPool(new Config(), "localhost");
Jedis jedis = pool.getResource();
....
pool.returnResource(jedis);

I found that if I want to use a db with index like 1 or 2 or 3 etc,I should use jedis.select(index) to tell jedis myself,so when I got a jedis from the pool , I should use jedis.select(index) everytime to ensure the jedis I got had been told which db selected.
so now,I use jedis like this:
public class JedisImpl implements RedisClient{
    JedisPool pool = null;
    public void init()
    {
       pool = new JedisPool(new Config(), "localhost");
    }
    public String get(String key)
    {
     Jedis jedis = pool.getResource();
     jedis.select(2);
     return jedis.get(key);
     pool.returnResource(jedis);
    }
}

is there anyway to config the JedisPool with a default db index which I want.so that the jedis object from this pool had know which db index to use.
I want to use jedis like this:
public class JedisImpl implements RedisClient{
    JedisPool pool = null;
    public void init()
    {
       pool = new JedisPool(new Config(), "localhost");
       do something to tell the pool use db index 2,so that the jedis I got from this pool would with the default db index 2.
    }
    public String get(String key)
    {
     Jedis jedis = pool.getResource();
     //jedis.select(2); Don't need to tell jedis which db index to use but use the default I had configed on the pool object;
     return jedis.get(key);
     pool.returnResource(jedis);
    }
}

Thank you very much!

**Comment by angrilove** [comment]
I had this problem.
