### ISSUE TITLE
Question regarding "nil"

### ISSUE THREAD

**Issue by JensRantil** [xetorthio/jedis#976]
I am using `Jedis#lindex([]byte)`. Its JavaDoc states that it might return 'nil'. Does that mean need to compare it against `new String("nil").toBytes(CharSets.LATIN1)` to check for existence? Or is it some other way? How about adding a constant to compare against and refer to that in the JavaDoc?

**Comment by marcosnils** [comment]
@JensRantil `null` java type if returned. The doc references Redis API mainly, I guess it's something we need to change. 

Here you have an example: 
https://github.com/xetorthio/jedis/blob/master/src/test/java/redis/clients/jedis/tests/commands/ListCommandsTest.java#L234

Let us know if you have further questions.

**Comment by JensRantil** [comment]
Thanks @marcosnils. Yes, the JavaDoc definitely need to clarify this. Especially the `@return` part of the JavaDocs. I'll leave this issue open until that's done (unless there's a better issue for it)

**Comment by marcosnils** [comment]
@JensRantil there are some javadoc issues open already. I'll close this one as we have the others

**Comment by JensRantil** [comment]
:+1:

**Comment by JensRantil** [comment]
Hi again @marcosnils, sorry for being a pain - could you refer to an issue the would solve this? I think it would be fair to do that for future reference.

**Comment by marcosnils** [comment]
Sure, https://github.com/xetorthio/jedis/issues/978
