### ISSUE TITLE
psubscribe doesn't work when keys include colon

### ISSUE THREAD

**Issue by psydell** [xetorthio/jedis#980]
My goal is to receive key eviction notifications. I'm using keys in the following format: 198:18:key1234 

A Jedis client executing jedis.psubscribe(listener, "__keyspace@0__:198:*"); will never get any key eviction notifications because keys include ":". As soon as I replace ":" with "/" everything starts working.

I verified redis-cli works fine (psubscribe __keyspace@0__:198:*):
1) "pmessage"
2) "__keyspace@0__:198:*"
3) "__keyspace@0__:198:18:key6508"
4) "evicted"

I'm using Redis 2.8.19 and Jedis 2.2.1.

**Comment by marcosnils** [comment]
@psydell here's an example using jedis 2.6.x and 2.7.x that works without a problem:

```java
package redis.clients.jedis;


public class MainTest {
	
	public static void main(String[] args)  {
		final JedisPool pool = new JedisPool();
		
		
		pool.getResource().psubscribe(new JedisPubSub() {
			@Override
			public void onPMessage(String pattern, String channel, String message) {
				System.out.println(pattern);
				System.out.println(channel);
				System.out.println(message);
			}
			
			@Override
			public void onPSubscribe(String pattern, int subscribedChannels) {
				new Thread(new Runnable() {
					
					@Override
					public void run() {
						Jedis j = pool.getResource();
						j.publish("keyspace@0:198:18:key6508", "evicted");
						j.close();
					}
				}).start();
			}
			
		}, "keyspace@0:198:18:*");
	}
}
```

Is there a change you try with a newest Jedis version?

**Comment by psydell** [comment]
@marcosnils thank you for your response. 
I tried to run your sample with jedis 2.7.2 and got the following exception:
Exception in thread "Thread-1" redis.clients.jedis.exceptions.JedisDataException: ERR unknown command 'PUBLISH'
	at redis.clients.jedis.Protocol.processError(Protocol.java:117)
	at redis.clients.jedis.Protocol.process(Protocol.java:142)
	at redis.clients.jedis.Protocol.read(Protocol.java:196)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:288)
	at redis.clients.jedis.Connection.getIntegerReply(Connection.java:213)
	at redis.clients.jedis.Jedis.publish(Jedis.java:2601)
	at redis.clients.jedis.MainTest$1$1.run(MainTest.java:27)
	at java.lang.Thread.run(Thread.java:745)

I tried my test with jedis 2.7.2 - no difference.

Here's more details on my test:

1. Redis is started with this configuration line: "notify-keyspace-events Ke"

2. My test source:

import redis.clients.jedis.Jedis;
import redis.clients.jedis.JedisPool;
import redis.clients.jedis.JedisPubSub;

import java.text.SimpleDateFormat;
import java.util.Date;

public class JedisPubSubTest {
    private final SimpleDateFormat timestampFormat = new SimpleDateFormat("yyyyMMddHHmmss");
    JedisPool jedisPool = new JedisPool("localhost", 1234);

    private Jedis getJedis() {
        Jedis jedis = jedisPool.getResource();
        jedis.auth("password");
        return jedis;
    }

    private void run() {
        Jedis jedis = getJedis();
        jedis.psubscribe(new MyListener(), "__keyspace@0__:198:*");
    }

    public static void main(String args[]) {
        JedisPubSubTest test = new JedisPubSubTest();
        test.run();
    }

    class MyListener extends JedisPubSub {
        @Override
        public void onPMessage(final String pattern, final String channel, final String message) {
            if ("evicted".equals(message)) {
                final String[] tokens = channel.split(":");
                if (tokens.length == 2) {
                    System.out.println("onPMessage(): Evicted key [" + tokens[1] + "] at [" + timestampFormat.format(new Date()) + "]");
                }
            }
        }

        @Override
        public void onMessage(final String channel, final String message) {
        }

        @Override
        public void onSubscribe(final String channel, final int subscribedChannels) {
        }

        @Override
        public void onUnsubscribe(final String channel, final int subscribedChannels) {
        }

        @Override
        public void onPUnsubscribe(final String pattern, final int subscribedChannels) {
        }

        @Override
        public void onPSubscribe(final String pattern, final int subscribedChannels) {
            System.out.println("onPSubscribe(): pattern:=" + pattern + ", subscribedChannels=" + subscribedChannels);
        }
    }
}

The following is printed in system out when this class is run:
onPSubscribe(): pattern:=__keyspace@0__:198:*, subscribedChannels=1

3. A redis-cli is started and registered for eviction events:

127.0.0.1:1234> psubscribe __keyspace@0__:198:*
Reading messages... (press Ctrl-C to quit)
1) "psubscribe"
2) "__keyspace@0__:198:*"
3) (integer) 1


4. After that I'm executing a shell script which does a lot of SETEX in a loop to cause key evictions:
#!/usr/bin/env bash

export REDIS_CLI="redis/2.8.19/bin/redis-cli -p 1234 -a password"
START_INDEX=$1
START=$[$START_INDEX + 1]
FINISH=$[$START + 3000]

for i in `seq $START $FINISH`;
do
    $REDIS_CLI SETEX 198:key$i 200 someStringValue$i
    $REDIS_CLI SETEX 198:18:key$i 200 someStringValue$i
done



Redis-cli client receives eviction events like these:

2) "__keyspace@0__:198:*"
3) "__keyspace@0__:198:18:key3120"
4) "evicted"
1) "pmessage"
2) "__keyspace@0__:198:*"
3) "__keyspace@0__:198:key3700"
4) "evicted"


But the java sample using jedis doesn't receive anything.

As I mentioned before, the test works if I switch ":" with "/" in the java code and the shell script.
My test would print the following:
onPMessage(): Evicted key [198/key6396] at [20150510223622]
onPMessage(): Evicted key [198/18/key6327] at [20150510223622]
onPMessage(): Evicted key [198/key6050] at [20150510223622]
onPMessage(): Evicted key [198/18/key6400] at [20150510223622]

**Comment by marcosnils** [comment]
> Exception in thread "Thread-1" redis.clients.jedis.exceptions.JedisDataException: ERR unknown command 'PUBLISH'

@psydell are you sure you're using redis 2.8.19 or that your redis instance is listening in the default 6379 port?. The error above indicates that redis doesn't know about the publish command.

I've just tried the same code i've pasted before with redis 2.8.19 and it works fine so I'd recommend you investigate what might be happening on your sidce. 

I'll try your code later with the eviction samples and let you know my results.

**Comment by psydell** [comment]
I forgot I had a bunch of commands (including PUBLISH) renamed for security reasons.  Your sample does work, but it's not exactly matching my use case. Could the problem be in different clients/pools involved? I'll wait for you to run my test. Thank you.

**Comment by marcosnils** [comment]
@psydell cool. Then it's not a problem with the pattern. It's about subscribing to the key eviction notifications.  I'll check your code later tonight and provide some feedback

**Comment by marcosnils** [comment]
@psydell just tried your code and script and I'm getting eviction notifications. One thing I've noticed though is that the `if` condition regarding the token size doesn't match any results: 

This is the message format I'm getting through the `onPMessage` method:

```
message  = evicted
channel >> __keyspace@0__:198:18:key7917
pattern >> __keyspace@0__:198:*
message >> evicted
channel >> __keyspace@0__:198:key8362
message >> __keyspace@0__:198:*
...
...
and so on
```

As you can see the `split(":")` on the channel length is never less than 3....

**Comment by psydell** [comment]
Thank you, Marcos, you're correct, everything works as designed.
My bad. Sorry I wasted your time.

**Comment by marcosnils** [comment]
@psydell np. I'll close the issue
