### ISSUE TITLE
Can't figure out why I am getting a redis.clients.jedis.exceptions.JedisConnectionException: no reachable node in cluster

### ISSUE THREAD

**Issue by asterp** [xetorthio/jedis#984]
I am experimenting with Redis cluster and I wrote a script to create a single master instance hosted by a single host. And I intermittently get the exception above. My Jedis pool config is as below: 

final GenericObjectPoolConfig poolConfig = new GenericObjectPoolConfig();
        poolConfig.setMaxTotal(10);
        poolConfig.setMaxIdle(5);
       JedisCluster cluster = new JedisCluster(jedisClusterNodes, poolConfig);

**Comment by marcosnils** [comment]
@asterp have you asigned the slots correctly to your cluster and you have a minimum of 3 masters?

Can you run a `cluster nodes` and `cluster status` command in all your masters to check the cluster status?

thx!.

**Comment by marcosnils** [comment]
BTW: Redis source comes with a `create-cluster` utility which helps a lot in cluster creation. You can check it out here https://github.com/antirez/redis/blob/unstable/utils/create-cluster/create-cluster

**Comment by asterp** [comment]
I am aware of the redis-trib script but it requires a minimum of 3 masters to be setup. Since I'm experimenting I wrote this script so all hash slots would go to the same master.  Here's the output of CLUSTER INFO command 
127.0.0.1:6379> CLUSTER INFO
cluster_state:ok
cluster_slots_assigned:16384
cluster_slots_ok:16384
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:1
cluster_size:1
cluster_current_epoch:0
cluster_my_epoch:0
cluster_stats_messages_sent:0
cluster_stats_messages_received:0

**Comment by asterp** [comment]
127.0.0.1:6379> CLUSTER NODES
4dfa93fe38d35988c2fcad87868e919d33204f73 :6379 myself,master - 0 0 0 connected 0-16383

**Comment by asterp** [comment]
The bizarre thing is it intermittently fails. If I tried to do a get from my code using jedis cluster client the first time it would fail. But if I tried to re-execute the same request again it succeeds. Almost seems like the connection is being closed ?

**Comment by marcosnils** [comment]
@asterp the intermittent failures seems pretty weird. I'd recommend investigating a little bit more in your side (redis logs /  cluster state during the test) and if problem persist then try to send us more info so we can replicate the problem. 

I've just tried a quick test with a single cluster node and setting/getting 1M keys and I didn't get any errors during the process.

**Comment by asterp** [comment]
Is there a recommended pool config I should use ?

**Comment by marcosnils** [comment]
@asterp you shouldn't experience problems with default. Either way for my tests I've tried with your configuration and I didn't get any errors.

**Comment by asterp** [comment]
I was using a port which closes connection intermittently on the firewall so I changed it and that resolved the issue
