### ISSUE TITLE
How to cache Java Ojbect ? 

### ISSUE THREAD

**Issue by dpdev3** [xetorthio/jedis#986]
How to cache Java Object ?

**Comment by marcosnils** [comment]
@dpdev3 you can do this in several ways. If you're looking for cross compatibility you could transform the java object to `json` and then storing as string in Redis. You could also opt to use a binary serialization protocol such as `capnproto` / `protocolbuffers` / `flatbuffers` or which ever you like the most.

If you're just using java can need to serialzie your object to a byte[] (http://stackoverflow.com/questions/2836646/java-serializable-object-to-byte-array) and then use the Jedis `set(byte[]. byte[])` method. You'll have to do the inverse mechanism (de-serializing) when retrieving the object again.

**Comment by xetorthio** [comment]
Or you can use github.com/xetorthio/johm
It is outdated, but maybe if you like it you can help to make that project
better
