### ISSUE TITLE
Bring cluster-revised branch to 2.8

### ISSUE THREAD

**Issue by marcosnils** [xetorthio/jedis#987]
As Jedis 3.0 still has some features which we haven't decide how they're going to be implemented (I.E async) we need to downmerge #671 as it contains many features and improvements that users need as today

**Comment by christophstrobl** [comment]
Any update on this issue? Would be really helpful to have this back ported.

**Comment by olivergierke** [comment]
Guys, we really need to move on this one. Spring Data Redis is supposed to ship cluster support with the upcoming release train which we have a release candidate scheduled for by next week.

In our last call I was under the impression you were planning to get 2.8 out in time for this but now this ticket has been stuck for 2 month :(. Mind that we need some time on our end to implement the functionality, too. Please get in touch.

**Comment by HeartSaVioR** [comment]
@christophstrobl @olivergierke 
Backporting cluster-revised branch to 2.8 with backward compatible way is ready for review - #1107.

Btw, it means that when we move to Jedis 3.0, we don't mind backward compatible and we already did it.
(2.x branches and master are already diverged.)
Is it OK for SDR?

**Comment by marcosnils** [comment]
Closed by #1107
