### ISSUE TITLE
Support sending commands to a dedicated cluster node.

### ISSUE THREAD

**Issue by marcosnils** [xetorthio/jedis#989]
Some users requested the ability to send commands to a specific node in `JedisCluster`. This can be achieved at this moment by using the `getClusterNodes` method and then dispatching the needed command to the specific node. 

So I'm wondering how we can improve this so sending commands to a cluster node is intuitive and easy to use. I believe that if we implement #988 in a cool way then we can use the new `getClusterNodes` function to actually run commands against the desired node.

**Comment by zts1993** [comment]
i wrote a NodesHelper may be can help
`
package com.wangyin.rediscluster.experimental;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;

/**
 * R2m Client component
 * Created by Timothy Zhang on 16-4-7.
 */
public abstract class NodesHelper<T> {

    private ExecutorService service;

    private Map<String, T> resMap;
    private Map<String, JedisPool> nodes;

    public NodesHelper(Map<String, JedisPool> nodes) {
        this.nodes = nodes;
        this.service = Executors.newFixedThreadPool(nodes.size());
        this.resMap = new ConcurrentHashMap<String, T>(nodes.size());
    }

    public NodesHelper(JedisClusterConnectionHandler connectionHandler) {
        this.nodes = setNodes(connectionHandler);
        this.service = Executors.newFixedThreadPool(nodes.size());
        this.resMap = new ConcurrentHashMap<String, T>(nodes.size());
    }


    public abstract Map<String, JedisPool> setNodes(JedisClusterConnectionHandler connectionHandler);

    public abstract T handle(Jedis jedis);

    public abstract void handleException(String Hnp, Exception e);


    public Map<String, T> run(long timeout) throws InterruptedException {
        for (JedisPool tpool : nodes.values()) {

            final String hnp = tpool.getHostAndPort().toString();

            final JedisPool pool = tpool;

            Thread t = new Thread(new Runnable() {
                @Override
                public void run() {

                    Jedis client = null;
                    try {
                        client = pool.getResource();

                        T res = handle(client);
                        resMap.put(hnp, res);

                    } catch (Exception e) {

                        handleException(hnp, e);

                    } finally {
                        if (client != null) {
                            client.close();
                        }
                    }

                }

            });

            service.execute(t);
        }

        service.shutdown();
        service.awaitTermination(timeout, TimeUnit.SECONDS);


        return resMap;
    }

    public Map<String, T> run() throws InterruptedException {
        return run(Long.MAX_VALUE);
    }

}

`
using setNodes to specify nodes which running commands 
this is an example of run commands on all cluster nodes
`
 Map<String, String> res = new NodesHelper<String>(connectionHandler) {

            @Override
            public Map<String, JedisPool> setNodes(JedisClusterConnectionHandler connectionHandler) {
                return connectionHandler.getNodes();
            }

            @Override
            public String handle(Jedis jedis) {
                return jedis.flushAll();
            }

            @Override
            public void handleException(String Hnp, Exception e) {
                System.out.println(Hnp + " got Exception : " + e.getMessage());
            }

        }.run();
`
to running on single nodes just override setNodes

**Comment by marcosnils** [comment]
@zts1993 thx!.

**Comment by sazzad16** [comment]
IMHO, we shouldn't include this one, specially when there are _easy_ workarounds available.

@marcosnils @HeartSaVioR WDYT?

**Comment by marcosnils** [comment]
Let's keep this open and see if more users are requesting it and proposing new design ideas. Doesn't seem to be needed ATM.

**Comment by sazzad16** [comment]
@marcosnils Closing this as dupe of #764. Please reopen if you disagree.
