### ISSUE TITLE
redis cluster get/set cost too much time

### ISSUE THREAD

**Issue by ZhangYiJunNathan** [xetorthio/jedis#991]
i have build redis cluster using redis 3.0. I use jedis-jedis-2.6.2 as the client. Then I test the get/set using jedis cluster. See below:
       Set<HostAndPort> jedisClusterNodes = getClusterInfo(serverInfo);
        // Jedis Cluster will attempt to discover cluster nodes automatically
        StopWatch sw = new StopWatch();
        sw.start();
        JedisCluster jc = new JedisCluster(jedisClusterNodes, 1000, 1000);
        sw.stop();
        System.out.println("time cost:"+sw.getTime());
       
        sw.reset();
        sw.start();
        jc.set("foo", "bar");
        sw.stop();
        System.out.println("time1 cost:"+sw.getTime());
        
        sw.reset();
        sw.start();
        String value = jc.get("foo");
        sw.stop();
        System.out.println("time2 cost:"+sw.getTime());
        System.out.println(value);

but the get/set operation cost many seconds, and the time changes every time. Result see below:
time cost:141
time1 cost:9051
time2 cost:12095
bar
Can anyone guide me on this?

**Comment by xetorthio** [comment]
Nodes are in the local network?

**Comment by HeartSaVioR** [comment]
Hello @ZhangYiJunNathan 
Do you use Jedis 2.6.2? Then its timeout has no effect since we fix it at 2.6.3.

I recommend you to try it with 2.7.2, and lower maxRedirections value (default is 5).

**Comment by ZhangYiJunNathan** [comment]
@xetorthio , yes, all nodes in local network

**Comment by ZhangYiJunNathan** [comment]
@HeartSaVioR , thank you so much for your advice. I will try that.

**Comment by ZhangYiJunNathan** [comment]
Hello, all,
I downloaded the latest jedis-2.7.2 and complie the file to jar. Then i test it again. Seems much better:
time cost:103
time1 cost:75
time2 cost:12
bar
But there are some errors appeared ramdomly(10 times tested. 2 success, 8 failure). See below:
time cost:119
Exception in thread "main" redis.clients.jedis.exceptions.JedisDataException: ERR unknown command 'CLUSTER'
	at redis.clients.jedis.Protocol.processError(Protocol.java:117)
	at redis.clients.jedis.Protocol.process(Protocol.java:142)
	at redis.clients.jedis.Protocol.read(Protocol.java:196)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:288)
	at redis.clients.jedis.Connection.getRawObjectMultiBulkReply(Connection.java:233)
	at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:239)
	at redis.clients.jedis.Jedis.clusterSlots(Jedis.java:3273)
	at redis.clients.jedis.JedisClusterInfoCache.discoverClusterSlots(JedisClusterInfoCache.java:61)
	at redis.clients.jedis.JedisClusterConnectionHandler.renewSlotCache(JedisClusterConnectionHandler.java:73)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:75)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:67)
	at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:29)
	at redis.clients.jedis.JedisCluster.set(JedisCluster.java:70)
	at Test.test(Test.java:55)
	at Test.main(Test.java:74)

**Comment by marcosnils** [comment]
@ZhangYiJunNathan can you please connect to one of your cluster master nodes and run the following comand? `cluster slots`. 

Seems like jedis is complaining that it can't issue the `cluster slots` command against your cluster.

**Comment by ZhangYiJunNathan** [comment]
@marcosnils . See below:
[root@nagios ~]# redis-cli -c -p 6380
127.0.0.1:6380> cluster slots
1) 1) (integer) 0
   2) (integer) 5460
   3) 1) "127.0.0.1"
      2) (integer) 6382
   4) 1) "127.0.0.1"
      2) (integer) 6379
2) 1) (integer) 10923
   2) (integer) 16383
   3) 1) "127.0.0.1"
      2) (integer) 6384
   4) 1) "127.0.0.1"
      2) (integer) 6381
3) 1) (integer) 5461
   2) (integer) 10922
   3) 1) "127.0.0.1"
      2) (integer) 6380
   4) 1) "127.0.0.1"
      2) (integer) 6383

**Comment by HeartSaVioR** [comment]
@ZhangYiJunNathan Could you please connect all of your cluster master nodes and run ```cluster slots```?

**Comment by ZhangYiJunNathan** [comment]
Hello, @HeartSaVioR :
[root@nagios ~]# redis-cli -p 6380 cluster nodes
489ec4b8efe02535f617ba87d5e5318e9bc8c0f4 127.0.0.1:6382 master - 0 1432520367121 11 connected 0-5460
d9df498bc5e87fe6a5f51d628e5254cc83dbc3a2 127.0.0.1:6383 slave ca4f3acadf994ac4dbb4d19a507850f57442e9cb 0 1432520367122 5 connected
fde46a874ec1191632265baead79c5b6255c111e 127.0.0.1:6384 master - 0 1432520367122 10 connected 10923-16383
ca4f3acadf994ac4dbb4d19a507850f57442e9cb 127.0.0.1:6380 myself,master - 0 0 2 connected 5461-10922
810cd3eab4126e9ea23831a78481725d4f15f8df 127.0.0.1:6381 slave fde46a874ec1191632265baead79c5b6255c111e 0 1432520367122 10 connected
6b3aa4c398bbc853e45f56aaaa74242a5c363b7d 127.0.0.1:6379 slave 489ec4b8efe02535f617ba87d5e5318e9bc8c0f4 0 1432520367122 11 connected
[root@nagios ~]# redis-cli -p 6384 cluster nodes
6b3aa4c398bbc853e45f56aaaa74242a5c363b7d 127.0.0.1:6379 slave 489ec4b8efe02535f617ba87d5e5318e9bc8c0f4 0 1432520381870 11 connected
d9df498bc5e87fe6a5f51d628e5254cc83dbc3a2 127.0.0.1:6383 slave ca4f3acadf994ac4dbb4d19a507850f57442e9cb 0 1432520381870 5 connected
fde46a874ec1191632265baead79c5b6255c111e 127.0.0.1:6384 myself,master - 0 0 10 connected 10923-16383
489ec4b8efe02535f617ba87d5e5318e9bc8c0f4 127.0.0.1:6382 master - 0 1432520381870 11 connected 0-5460
ca4f3acadf994ac4dbb4d19a507850f57442e9cb 127.0.0.1:6380 master - 0 1432520381870 2 connected 5461-10922
810cd3eab4126e9ea23831a78481725d4f15f8df 127.0.0.1:6381 slave fde46a874ec1191632265baead79c5b6255c111e 0 1432520381870 10 connected
[root@nagios ~]# redis-cli -p 6382 cluster nodes
fde46a874ec1191632265baead79c5b6255c111e 127.0.0.1:6384 master - 0 1432520388594 10 connected 10923-16383
810cd3eab4126e9ea23831a78481725d4f15f8df 127.0.0.1:6381 slave fde46a874ec1191632265baead79c5b6255c111e 0 1432520388593 10 connected
ca4f3acadf994ac4dbb4d19a507850f57442e9cb 127.0.0.1:6380 master - 0 1432520388593 2 connected 5461-10922
6b3aa4c398bbc853e45f56aaaa74242a5c363b7d 127.0.0.1:6379 slave 489ec4b8efe02535f617ba87d5e5318e9bc8c0f4 0 1432520388593 11 connected
489ec4b8efe02535f617ba87d5e5318e9bc8c0f4 127.0.0.1:6382 myself,master - 0 0 11 connected 0-5460
d9df498bc5e87fe6a5f51d628e5254cc83dbc3a2 127.0.0.1:6383 slave ca4f3acadf994ac4dbb4d19a507850f57442e9cb 0 1432520388593 5 connected
[root@nagios ~]#

**Comment by marcosnils** [comment]
@ZhangYiJunNathan the command @HeartSaVioR was asking is `cluster slots` not `cluster nodes`

**Comment by ZhangYiJunNathan** [comment]
Sorry, my bad:
[root@nagios ~]# redis-cli -p 6380 cluster slots
1) 1) (integer) 0
   2) (integer) 5460
   3) 1) "127.0.0.1"
      2) (integer) 6382
   4) 1) "127.0.0.1"
      2) (integer) 6379
2) 1) (integer) 10923
   2) (integer) 16383
   3) 1) "127.0.0.1"
      2) (integer) 6384
   4) 1) "127.0.0.1"
      2) (integer) 6381
3) 1) (integer) 5461
   2) (integer) 10922
   3) 1) "127.0.0.1"
      2) (integer) 6380
   4) 1) "127.0.0.1"
      2) (integer) 6383


[root@nagios ~]# redis-cli -p 6382 cluster slots
1) 1) (integer) 10923
   2) (integer) 16383
   3) 1) "127.0.0.1"
      2) (integer) 6384
   4) 1) "127.0.0.1"
      2) (integer) 6381
2) 1) (integer) 5461
   2) (integer) 10922
   3) 1) "127.0.0.1"
      2) (integer) 6380
   4) 1) "127.0.0.1"
      2) (integer) 6383
3) 1) (integer) 0
   2) (integer) 5460
   3) 1) "127.0.0.1"
      2) (integer) 6382
   4) 1) "127.0.0.1"
      2) (integer) 6379


[root@nagios ~]# redis-cli -p 6384 cluster slots
1) 1) (integer) 10923
   2) (integer) 16383
   3) 1) "127.0.0.1"
      2) (integer) 6384
   4) 1) "127.0.0.1"
      2) (integer) 6381
2) 1) (integer) 0
   2) (integer) 5460
   3) 1) "127.0.0.1"
      2) (integer) 6382
   4) 1) "127.0.0.1"
      2) (integer) 6379
3) 1) (integer) 5461
   2) (integer) 10922
   3) 1) "127.0.0.1"
      2) (integer) 6380
   4) 1) "127.0.0.1"
      2) (integer) 6383
[root@nagios ~]#

**Comment by HeartSaVioR** [comment]
@ZhangYiJunNathan 
Hey, sorry for responding too late. It seems like 6379 and 6381, 6383 is missed.

**Comment by ZhangYiJunNathan** [comment]
@HeartSaVioR 
Great thks for your advice.
I build a new redis cluster environment follow the "Redis cluster tutorial" by step. I test it using the redis command and it worked well.
 [root@localhost 7000]# redis-cli -c -p 7000
127.0.0.1:7000> cluster info
cluster_state:ok
cluster_slots_assigned:16384
cluster_slots_ok:16384
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:6
cluster_size:3
cluster_current_epoch:7
cluster_my_epoch:7
cluster_stats_messages_sent:69216

But when i use the jediscluter 2.7.2 to do some simple tests. Tested many times and it never succeed. Could please give me any guidelines?
public class Test {
    public void test() {
        Set<HostAndPort> set = new HashSet<HostAndPort>();
        set.add(new HostAndPort("172.18.85.109", 7000));
        StopWatch sw = new StopWatch();
        sw.start();
        JedisCluster jc = new JedisCluster(set);
        sw.stop();
        System.out.println("time cost:"+sw.getTime());
        
        jc.set("foo", "bar");
        String value = jc.get("foo");
        System.out.println("value is :"+value);
    }
    public static void main(String[] args) {
        Test t = new Test();
        //t.test();
        t.test();
    }
}

time cost:139
Exception in thread "main" redis.clients.jedis.exceptions.JedisClusterMaxRedirectionsException: Too many Cluster redirections?
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:34)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:67)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:83)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:67)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:83)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:67)
	at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:29)
	at redis.clients.jedis.JedisCluster.set(JedisCluster.java:70)
	at Test.test(Test.java:26)
	at Test.main(Test.java:35)

**Comment by ZhangYiJunNathan** [comment]
[root@localhost 7000]# redis-cli -c -p 7000
127.0.0.1:7000> set foo bar
-> Redirected to slot [12182] located at 127.0.0.1:7002
OK
127.0.0.1:7002> get foo
"bar"
127.0.0.1:7002>

**Comment by ZhangYiJunNathan** [comment]
[root@localhost 7000]# redis-cli -c -p 7000
127.0.0.1:7000> cluster nodes
79e0f53696b35c98875cbfed961ae32fa023e764 127.0.0.1:7001 master - 0 1435842772062 2 connected 5461-10922
a3ac001c8da81417a5a4050a4e55a9224a8e7298 127.0.0.1:7004 slave 79e0f53696b35c98875cbfed961ae32fa023e764 0 1435842772564 5 connected
6b0e950ca54a13dd7f237eb21b2bc65890559a6b 127.0.0.1:7002 master - 0 1435842771561 3 connected 10923-16383
f484bdf27b4ddcf81d864a2daf5518d2f2ee59b1 127.0.0.1:7003 master - 0 1435842770559 7 connected 0-5460
334659cc874e127e36bd225dff2c6509763ed487 127.0.0.1:7000 myself,slave f484bdf27b4ddcf81d864a2daf5518d2f2ee59b1 0 0 1 connected
bd1f4944aef1f3165ba5d3db380bef7b4c54706c 127.0.0.1:7005 slave 6b0e950ca54a13dd7f237eb21b2bc65890559a6b 0 1435842772564 6 connected

**Comment by marcosnils** [comment]
@ZhangYiJunNathan you need to configure your cluster nodes `bind address` correctly. You're getting redirections because your running the Java code in your machine and your cluster nodes are in a different computer. 

If you check your `cluster nodes` command you can see that all the nodes say `127.0.0.1`. You need to change your bind address so they say `172.18.85.109`

**Comment by ZhangYiJunNathan** [comment]
@marcosnils. Thank you so much !
Another question. For old realeases, we use ShardedJedisPool as  connection pool for redis. So how can i use JedisCluster for connection pool ?   Could you pls give me an example?

**Comment by ZhangYiJunNathan** [comment]
@HeartSaVioR
Does the latest JedisCluter support pub/sub? I didn't find that after searching the source code of JedisCluster.class

**Comment by HeartSaVioR** [comment]
@ZhangYiJunNathan 
Please leave questions to Google Mailing group so many users can see your question and answer, too.
https://groups.google.com/forum/?fromgroups#!forum/jedis_redis

Please refer https://github.com/xetorthio/jedis/blob/master/CONTRIBUTING.md for more details.

**Comment by ZhangYiJunNathan** [comment]
@HeartSaVioR
No lucky, we cannot acess anything with goole in china. Blcoked by the gov.

**Comment by HeartSaVioR** [comment]
@ZhangYiJunNathan That's too bad. I'll think another approach and let you know.

**Comment by xiaolongyuan** [comment]
@HeartSaVioR 
He is flirting with you, the programmer is the basic quality of China over the GFW.
I'm sorry, but it's a robot translation.
You can try to translate into english.
他在调戏你，中国的程序员基本素质是翻墙。

![image](https://cloud.githubusercontent.com/assets/3142363/8539574/e5d3ca66-24af-11e5-861b-359b727e0604.png)

**Comment by HeartSaVioR** [comment]
@xiaolongyuan 
Is it accessible without VPN? Actually I'm searching about GFW from Google, and Quora said http://www.quora.com/How-can-I-use-Google-in-China.
(It could be some kind of outdated information, so let me know it is wrong.)

I also think that googling is "must have" programmer tool so it couldn't be blocked, at least programmers.

@ZhangYiJunNathan Note that I'll close your further issues if it doesn't meet out CONTRIBUTING.md.

**Comment by HeartSaVioR** [comment]
@xiaolongyuan AFAIK, at least programmers in China can access whole services of Google. Do I understand right?

**Comment by xiaolongyuan** [comment]
@HeartSaVioR Right.
