### ISSUE TITLE
Exception in thread "main" redis.clients.jedis.exceptions.JedisConnectionException: no reachable node in cluster

### ISSUE THREAD

**Issue by jeromeheng** [xetorthio/jedis#995]
A exception happen when I successed to  create a redis cluster
=======================================================
this is my code : 
public class Cluster {
	private static JedisCluster jc = null;
	public static void main(String[] args) {
		jc = CreateCluster();
		jc.set("foo", "bar");
		String value = jc.get("foo");
		System.out.println(value);
	}
	private static JedisCluster CreateCluster() {
		Set\<HostAndPort\> jedisnodes = new HashSet\<HostAndPort\>();
		jedisnodes.add(new HostAndPort("10.1.80.191",7379));
		jedisnodes.add(new HostAndPort("10.1.80.191",7380));
		jedisnodes.add(new HostAndPort("10.1.80.192",7379));
		jedisnodes.add(new HostAndPort("10.1.80.192",7380));
		jedisnodes.add(new HostAndPort("10.1.80.193",7379));
		jedisnodes.add(new HostAndPort("10.1.80.193",7380));
		return new JedisCluster(jedisnodes);
	}
}
==============================================================

Exception in thread "main" redis.clients.jedis.exceptions.JedisConnectionException: no reachable node in cluster
	at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnection(JedisSlotBasedConnectionHandler.java:48)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:50)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:67)
	at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:29)
	at redis.clients.jedis.JedisCluster.set(JedisCluster.java:70)
	at com.kugou.rediscluster.Cluster.main(Cluster.java:13)

But in command line , it's right 
eg : 
[hadoop@hd21 redis-3.0.1]$ redis-cli -c -h 10.1.80.192 -p 7379
10.1.80.192:7379> set foo bar
-> Redirected to slot [12182] located at 10.1.80.191:7379
OK
10.1.80.191:7379>

How to explan this problem ? please ....

**Comment by jeromeheng** [comment]
I use to redis 3.0.1 and jedis 2.7.2

**Comment by marcosnils** [comment]
@jeromeheng check out https://github.com/xetorthio/jedis/issues/944

**Comment by HeartSaVioR** [comment]
@jeromeheng 
1.Does it occur all the time, or randomly?
2. Where does your code run? Is it hd21? If it is not, please try same redis-cli operation to the node.

**Comment by jeromeheng** [comment]
@HeartSaVioR 
it occur all the time, and my code is running the remote machine.
it likes that the redis-cli don't find the remote nodes 

but when I  use  : 		System.out.println(jc.getClusterNodes().size()); 
    that can print the result

**Comment by jeromeheng** [comment]
@HeartSaVioR 
thank for your suggestion!
when i run the programmer in redis-cluster node , it success。
why it is happened ?  what should i do ? 
whether or not, I need to change my redis.conf and  how to do this ?

**Comment by HeartSaVioR** [comment]
@jeromeheng Please share your cluster configuration, especially how to configure cluster via redis-trib.

**Comment by jeromeheng** [comment]
@HeartSaVioR 

port 7379
daemonize yes
cluster-enabled yes
cluster-config-file nodes-7379.conf
cluster-node-timeout 5000
appendonly no
bind 10.1.80.191

another params are default

**Comment by jeromeheng** [comment]
@HeartSaVioR  
10.1.80.191 is one of reids-cluster address 
and I visit this cluster from remote machine that is the redis-cli

**Comment by jeromeheng** [comment]
@marcosnils  @HeartSaVioR   
thanks for your support , I have found the answer ^_^ ！

**Comment by HeartSaVioR** [comment]
@jeromeheng Sorry to not followed up, and great to resolve your issue.
What's the reason?

**Comment by jeromeheng** [comment]
it seems like #944 , I change the bind-ip .

**Comment by jeromeheng** [comment]
@HeartSaVioR 
it seems like #944 , I change the bind-ip .

**Comment by HeartSaVioR** [comment]
@jeromeheng Great! I'm closing this issue. Have a good day!

**Comment by WENPIN1** [comment]
The real problem is that JedisCluster method close() will close the whole JedisCluster  connection instead of return the connection to the cluster pool.

**Comment by jongsuny** [comment]
I have the same problem.
My solution is set timeout as higher value,like 600.
or just set as 0.// keep alive connection.
This should be fixed by jedis client,though,I think.

**Comment by marcosnils** [comment]
> This should be fixed by jedis client,though,I think.

what specifically?

**Comment by marcosnils** [comment]
> The real problem is that JedisCluster method close() will close the whole JedisCluster connection instead of return the connection to the cluster pool.

JedisCluster doesn't work as Jedis or JedisPool because it handles a pool a connection internally. Basically you shouldn't call `close` unless you just want to gracefully close all connections to youre redis instances.

**Comment by jongsuny** [comment]
`@Override
  public Jedis getConnection() {
    // In antirez's redis-rb-cluster implementation,
    // getRandomConnection always return valid connection (able to
    // ping-pong)
    // or exception if all connections are invalid

    List<JedisPool> pools = getShuffledNodesPool();

    for (JedisPool pool : pools) {
      Jedis jedis = null;
      try {
        jedis = pool.getResource();

        if (jedis == null) {
          continue;
        }

        String result = jedis.ping();

        if (result.equalsIgnoreCase("pong")) return jedis;

        jedis.close();
      } catch (JedisException ex) {
        if (jedis != null) {
          jedis.close();
        }
      }
    }

    throw new JedisConnectionException("no reachable node in cluster");
  }`
This code,from JedisSlotBasedConnectionHandler
when timeout is 5secs,in 10 secs no operation to redis server,
when user execute "get" command,all connections were gone,after for loop,no connection is available.
finally, throw no reahable node in cluster.
My solution is,set timeout as big value to make sure connection can alive before each operations.
