### ISSUE TITLE
JedisCluster should  add a method : set(final String key, final String value, final String nxxx) {

### ISSUE THREAD

**Issue by zhangms** [xetorthio/jedis#999]
public String set(final String key, final String value, final String nxxx) {
      return new JedisClusterCommand<String>(connectionHandler, maxRedirections) {
          @Override
          public String execute(Jedis connection) {
              return connection.set(key, value, nxxx);
          }
      }.run(key);
  }

**Comment by marcosnils** [comment]
closed by #1004
